dnnsoftware/Dnn.Platform

- DNN Platform/Library/Entities/Portals/PortalController.cs
- Website/DesktopModules/Admin/Portals/SiteSettings.ascx.cs
- Website/DesktopModules/Admin/Portals/Template.ascx.cs
See https://dnntracker.atlassian.net/browse/DNN-6258 for more details.
Please note: I've changed GetPortalSettingsDictionaryCallback to make the keys in the PortalSettingsDictionary case insensitive which reflects the way the StoredProcedure [UpdatePortalSetting] works (this procedure updates the settings even if the key does not match case sensitive).
I would also suggest to introduce some constants instead of using the strings to prevent typos.
> DNN-6258: Fixed "Enable Pop-Ups" settings on page Admin/Site-Settings

- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Components/LiveClient.cs
Updated urls used for live oauth service to be consistent with current Microsoft documentation for OAuth v2 authorization.
> DNN-6464 Upgrade to 7.4.0 - Windows Live Auth Hangs 

- DNN Platform/Library/Entities/Tabs/TabController.cs
It's not obvious how to use GetTab() method in the case we don't know portalId, but only tabId (may happen in some cross-portal scenario), without looking on GetPortalId() source.
> (doc) Clarify use of portalId param

- Website/development.config
- Website/release.config
Microsoft no longer recommends using trust levels to enforce security boundaries since it has been shown to not be effective.
> DNN-6450 Change default trust level to Full Trust

- Website/admin/Skins/Meta.ascx.cs
The Meta skin object has an `HttpEquiv` property, but it should also support `Http-Equiv`, since may skinners will see it work for `Name` and `Content` and assume that it works with `http-equiv`.
In a skin file, with the `meta` tag registered:
<%@ Register TagPrefix="dnn" TagName="META" Src="~/admin/Skins/Meta.ascx" %>
the following skin object reference should work:
<dnn:Meta http-equiv="X-UA-Compatible" content="IE=edge" InsertFirst="true" runat="server"/>
See [DNN-6415](https://dnntracker.atlassian.net/browse/DNN-6415)
> DNN-6415 Added support for Http-Equiv on Meta skin object

- DNN Platform/Library/Common/Lists/ListEntryInfo.cs
#128 and #148 added localization to list values, by looking up a resource file with the same name as the list (plus a prefix). However, if the list name contains characters that are invalid for a file, an exception is thrown (see the stack trace on https://github.com/EngageSoftware/Engage-Employment/issues/6).
See [DNN-6323](https://dnntracker.atlassian.net/browse/DNN-6323)
> DNN-6323 Clean list name before using as resource file name

- DNN Platform/Library/Entities/Portals/PortalSettings.cs
- DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
- Website/Default.aspx.cs
- Website/DesktopModules/Admin/Portals/App_LocalResources/SiteSettings.ascx.resx
- Website/DesktopModules/Admin/Portals/SiteSettings.ascx.cs
- Website/DesktopModules/Admin/Portals/sitesettings.ascx
removed enable module effect related code as it hasn't applied for a few versions now (the two edit states shared the same opacity)
> DNN-5881 Enable Module Effect? feature does not work.

- Website/DesktopModules/Admin/Security/App_LocalResources/EditRoles.ascx.resx
- Website/DesktopModules/Admin/Security/editroles.ascx
Amended code to allow support for brackets (parenthesis) i.e. "(" and ")" in role names -this was already supported at the API level and brackets are used in the translator role names generated by content localization, so this just allows support at the UI level for brackets.
> DNN-5776 SI: Security Role Names - Invalid Characters

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
use network path reference (AKA protocol less url - http://tools.ietf.org/html/rfc3986#section-4.2) in image indicator to ensure that this works in ssl-offload scenarios.
> DNN-4941 ssl-offload issue with platform update image

- DNN Platform/Library/Entities/Portals/PortalController.cs
- DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
- DNN Platform/Library/Services/Cache/CachingProvider.cs
- DNN Platform/Library/UI/Skins/Skin.cs
- Website/admin/Skins/Language.ascx.cs
Since PortalCacheKey now has a culture variation, each culture, including neutral one would have its own portalsettings dictionary. 
When site settings are loaded both dictionaries would be used, depending on the current culture and setting type (culture dependent or not). When setting gets update we need to ensure both cachekeys are cleared (when clear cache is set to true) because we don't know if setting is culture specific or not.
> DNN-6170 Switching Language does not clear portalsettings cache

- DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
When SSL-enforced is enabled, and the page is secure, it will now do a http 301 redirect when using advanced url's (basic already does a 301 redirect)
> DNN-6609 HTTPS 301 redirect

- DNN Platform/Modules/Journal/FileUploadController.cs
updated journal upload code to handle the case where a filename is legal but would cause a double escape sequence as a URI.
> DNN-5917 SI: File upload special characters

- DNN Platform/Library/Security/Permissions/Controls/PermissionsGrid.cs
fixed issues where "all users" role was using an invalid portalid and caused exception's when building permissions grids.
> DNN-6601 Page / Module / Folder Settings unavailable, if Portal 0 is missing

- Website/DesktopModules/Admin/Portals/Signup.ascx.cs
This commit modifies how the Create New Site logic checks for the existence of the chosen portal alias.  This allows subdomains "p1.domain.com" to be created when "www.domain.com" already exists.  The original logic did not allow this.
> DNN-6690 EVOQCONTENT: Parent site cannot be created with an error

- DNN Platform/Library/Entities/Tabs/TabController.cs
- Website/DesktopModules/Admin/Portals/portal.template.xsd
Added taburls to the portal template (export /import).
PortalAlias usage and Id are not exported, but set to default (tab serialization used for both templates and pages export/import so I set default values to avoid issues with portalid reference during portal creation):
objTabUrl.PortalAliasId = Null.NullInteger;
objTabUrl.PortalAliasUsage = PortalAliasUsageType.Default;
Other values are exported/imported as is.
Tested using DNN Platform site with localized content and tabUrls set on multiple pages.
> DNN-5904 Exporting a site with content doesn't save URL information

- DNN Platform/Library/Entities/Users/UserController.cs
Resolved "directory is not empty" exception in case if parent or root folder have items added bypassing file manager.
Added sync on parent and root folder before attempt to delete. 
This won't delete synced items on the parent or root level - only inside the userfolder, but will resolve "Directory is not empty".
> DNN-3787 user folders are not deleted when user is deleted

- DNN Platform/Library/Services/FileSystem/FileManager.cs
This pull request fixes the problem, that files > 2GB are not downloadable using the with LinkClick.aspx. 
Please note: The problem, that the file size are negative for large files (due too integer overflow) is not fixed in the pull request. This requires changing the API (see @cathalconnolly comments here https://dnntracker.atlassian.net/browse/DNN-5206)
> DNN-5206: DotNetNuke.Services.FileSystemFileManager.WriteFileToHttpContext(): Do not send negative "Content-Length" header

- .gitignore
Needed for people working with Ghostdoc for auto code documentation
> DNN-6672: Do not include GhostDoc solution files in commits

- DNN Platform/DotNetNuke.Web.Razor/RazorModuleBase.cs
The `RazorModuleBase` class (used by the Razor Host module) calls `Server.HtmlDecode` on the output from the `RazorEngine`. This is probably to combat Razor's default HTML encoding, but also means that anyone using the Razor Host module will not get the normal behavior of Razor, and will not be able to easily output HTML encoded content.
I think it is important for the behavior of the Razor Host module to match Razor itself, however this will be a breaking change for existing Razor Host scripts that need the extra HTML decoding.
See [DNN-6324](https://dnntracker.atlassian.net/browse/DNN-6324)
> DNN-6324 Don't HTML decode the Razor engine's output

- DNN Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs
Updated OAuthClientBase to support the optional parameter "resource" of the OAuth V2 standard, as this field is required to support the Microsoft Azure Active Directory OAuth implementation.
Also added UrlEncode logic to the APISecret, as apparently secret keys generated by Azure are not url friendly. 
Tested implementation on dev box and an Azure site for LiveConnect, Google, Facebook and Azure Active Directory.
> DNN-6265 Update OAuthClientBase to support optional parameters

- DNN Platform/Modules/DDRMenu/MenuBase.cs
- DNN Platform/Modules/DDRMenu/TemplateEngine/TokenTemplateProcessor.cs
The token template processor would only check for true/false values (0, 1). Added a super ugly check if they're not 0 or 1 and also not an empty string. It seems to solve the issue with checking for icons or any other string node via the ddr token text template.
> Dnn-3522: If-tokens in DDRmenu templates fail

- DNN Platform/Library/Security/PortalSecurity.cs
- DNN Platform/Modules/MemberDirectory/Services/MemberDirectoryController.cs
See: https://dnntracker.atlassian.net/browse/DNN-6096
- Instead of changing the available SortFields, we'll use "UserId" as SortField if the TabModuleSetting SortField was CreatedOnDate. This is because the GetUsersBasicSearch and GetUsersAdvancedSearch do not allow sorting on CreatedOnDate. Sorting on UserId however has the same effect as sorting on CreatedOnDate.
- Also invalid T-SQL statements are filtered from the inputstring.
> Dnn 6096: Member Directory SortBy error

- Website/Providers/DataProviders/SqlDataProvider/07.04.01.SqlDataProvider
[DNN-6659](https://dnntracker.atlassian.net/browse/DNN-6659)
>The JavaScript Library table's `Version` column can only hold 10 characters, but versions can be longer than that. Installing [JS libraries for Kendo UI](https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/kendo-ui-core_2014.3.1424) demonstrates the problem. The version number 2014.3.1424 is 11 characters, so a link is generated to `/Resources/libraries/kendo.core/2014_03_142/kendo.core.min.js` (notice the missing `4` at the end of the version part of the URL).
> DNN-6659 Allow long JS library version numbers

- DNN Platform/Library/UI/Modules/ModuleHost.cs
- Website/admin/Skins/JavaScriptLibraryInclude.ascx
[DNN-6661](https://dnntracker.atlassian.net/browse/DNN-6661)
>When a module is cached, the {{JavaScriptLibraryInclude}} control doesn't cause script libraries to be requested.
> DNN-6661 Restore JS library registrations from cached modules

- DNN Platform/Library/Data/DataUtil.cs
See [DNN-6730](https://dnntracker.atlassian.net/browse/DNN-6730)
>When calling `DataProvider.Instance().ExecuteReader` (or any other `Execute*` method), you should be able to pass `SqlParameter` objects to include the parameter name with the value. This makes the calling code not have to be dependent on the order of parameters in the stored procedure.
>
>I'm fairly certain that this worked before PetaPoco was introduced, but it now ignores the parameter names.
> DNN-6730 use parameters names in generated SQL when calling stored procedure

- DNN Platform/Library/UI/Modules/Html5/Html5HostControl.cs
- Website/DesktopModules/Admin/Extensions/Editors/EditModuleControl.ascx.cs
This pull request adds support for javascript files and css files in HTML5 (SPA) modules that are named following a standard convention.  e.g. if the html file is test.html, the js file should be called test.js and the css file should be called test.css.
> DNN-6655 HTML Module Conventions

- DNN Platform/Components/ClientDependency/Source/CssFileUrlFormatter.cs
Fix for the CDF striping out the data: attribute from CSS embed images. Images can actually render now.
> DNN-6660 ClientDependancy breaks dataUris in css

- DNN Platform/Website/Templates/Blank Website.template
- DNN Platform/Website/Templates/Default Website.template
- Website/Providers/DataProviders/SqlDataProvider/07.04.01.SqlDataProvider
Sets the default priority for 404 pages to 0 so they are not included in the sitemaps.
Also fixes current 404 and 500 to priority 0.
> DNN-6636 Sitemap : Shows 404 Page in the Sitemap

- DNN Platform/Library/Collections/EnumerableExtensions.cs
PetaPoco is mostly used together with strong typed Info-classes. Thats nice and working well but sometimes we need a more flexible way to retrieve data. Think of a simple module where the user enters an arbitrary select statement to any table of the database (yes, I wont do that! Its just for explanation!). With PetaPoco this could be done with ExecuteQuery<dynamic> and the result is of type IEnumerable<dynamic>. This is nice and working "out of the box". But you can not databind this IEnumerable<dynamic> to a datagrid : even if the data is retrieved correctly, nothing is shown in the grid. So I implemented an extension method for IEnumerable<dynamic> named "ToDataTable"
> DNN-5455 Extension method for binding PetaPoco dynamic result set 

- Website/admin/Menus/ModuleActions/ModuleActions.js
The module order was calculated wrong. The `up` action moved the module two positions up. The `down` action did not move the module at all.
Applying this fix worked for me, although I do not understand why the index is multiplied with 2.
> DNN-6564 - Fixed wrong module order after using "down" and "up" actions

- DNN Platform/Library/Services/Log/SiteLog/SiteLogController.cs
See https://dnntracker.atlassian.net/browse/DNN-6769 for more details.
> DNN-6769: Fixed cache setting "None" enables Site Log feature if Site Log was disabled by setting "Site Log Buffer" to 0

- DNN Platform/Library/Services/Vendors/BannerController.cs
- DNN Platform/Library/UI/Navigation.cs
- DNN Platform/Library/UI/Skins/SkinThumbNailControl.cs
- Website/DesktopModules/Admin/Extensions/InstalledExtensions.ascx.cs
- Website/DesktopModules/Admin/Extensions/MoreExtensions.ascx
- Website/DesktopModules/Admin/HostSettings/hostsettings.ascx
- Website/DesktopModules/Admin/Skins/EditSkins.ascx.cs
- Website/Resources/FeedBrowser/scripts/feedbrowser.js
- Website/Resources/FeedBrowser/scripts/templates.js
- Website/admin/ControlPanel/RibbonBar.ascx
- Website/controls/help.ascx
This will replace all occurrences of target="_new" with target="_blank" to get better standards compatibility.
http://www.w3.org/html/wg/drafts/html/master/single-page.html#browsing-context-names describes browsing context names. According to it, "_new" isn't valid browsing context name nor keyword.
In case when we need to open links in a specific window, target="new" or any other valid browsing context name (window name) should be used.
> DNN-6845: Multiple uses of non-standard target="_new"

- DNN Platform/Library/Entities/Urls/AdvancedFriendlyUrlProvider.cs
- DNN Platform/Library/Entities/Urls/BasicFriendlyUrlProvider.cs
This is a follow up pull request for tickets https://dnntracker.atlassian.net/browse/DNN-6364 and https://dnntracker.atlassian.net/browse/DNN-6366.
This pull request should fix the problems mentioned by Ben Zhong in the Jira comments https://dnntracker.atlassian.net/browse/DNN-6364?focusedCommentId=74812&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-74812 and https://dnntracker.atlassian.net/browse/DNN-6366?focusedCommentId=74813&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-74813
> Updated AdvancedFriendlyUrlProvider and BasicFriendlyUrlProvider to consider SSL URL setting when creating https://-links to secure pages

- DNN Platform/Library/Services/FileSystem/FileLinkClickController.cs
- DNN Platform/Library/Services/FileSystem/IFileLincClickController.cs
See https://dnntracker.atlassian.net/browse/DNN-6849 for more details.
Please note: I'm not sure whether to use -1 as return value for an invalid fileticket  parameter is best practice in DNN. IMHO using int? and returning null is a better option, but this would be a breaking change.
> DNN-6849: Fixed IFileLinkClickController.GetFileIdFromLinkClick if fileticket parameter has wrong format

- Website/DesktopModules/Admin/Portals/SiteSettings.ascx.cs
- Website/DesktopModules/Admin/Portals/sitesettings.ascx
Following properties were updated and use dnn:label control:
Registration Settings
Registration_UseProfanityFilter
Registration_UseAuthProviders
Registration_UseEmailAsUserName
Registration_RequireUniqueDisplayName
Registration_RandomPassword
Registration_RequireConfirmPassword
Security Settings
Security_RequireValidProfile
Security_CaptchaRegister
Login Settings
Security_CaptchaLogin
Security_RequireValidProfileAtLogin
Security_CaptchaRetrivePassword
Security_CaptchaChangePassword
Profile Settings
Profile_DisplayVisibility
> DNN-6677 Label: Setting "ControlName" does not work

- Website/DesktopModules/Admin/Portals/App_LocalResources/Signup.ascx.resx
- Website/DesktopModules/Admin/Portals/Signup.ascx.cs
To prevent exception I added verification of host email address - if it is empty email won't be sent with empty address and following message would be displayed:
There was an error sending confirmation emails - There is no email address set on Site and/or Host level. However, the website was created. Click Here To Access the new site
> DNN-5981 SendEmail from address cannot be empty.

- DNN Platform/Library/Services/Scheduling/DNNScheduler.cs
- DNN Platform/Library/Services/Scheduling/SchedulingProvider.cs
- Website/DesktopModules/Admin/Scheduler/EditSchedule.ascx.cs
Task would be executed on Update if:
it was enabled
start time was changed
frequency or retry time lapse was changed
if other settings were changes - task would be updated without execution.
I also made a change in the public override void UpdateSchedule(ScheduleItem scheduleItem) to use SchedulingController.UpdateSchedule(...) that takes scheduleItem.ScheduleStartDate as a last param.
This was necessary as Schedule Start Date/Time was set always to Now.
> DNN-6876 SI: Scheduled Task Update vs Run Now

- Website/Install/InstallWizard.aspx
added dnn.jquery.extensions.js to the InstallWizard as the error occurs because .removeCssProperties() is defined in that script and it was not loaded on the page.
Tested one the DNN_Platform_7.4.2.63 + changes in InstallWizard.aspx
in IE11, Chrome and FF
> DNN-6967 Hovering over Password Strength Meter does not activate Tooltip

- DNN Platform/Tests/DotNetNuke.Tests.Utilities/Fakes/FakeCachingProvider.cs
This does not require any Jira as it's part of the unit tests utility class. Fixing this will help some of the tests in Content
> FakeCachingProvider - Fix null reference exception when key is not present in the dictionary.

- Website/Resources/Shared/scripts/dnn.jquery.js
A previous pull request updated DNN to use jQuery 1.11 - this version removes the deprecated position option that was being used in dnnConfirm dialogs,
This change removes the use of the deprecated option and reverts to the default which is the required behavior.
> DNN-7008 Update code to avoid use of deprecated jQuery UI proprety

- DNN Platform/Library/Entities/Portals/PortalSettings.cs
Added documentation to avoid confusion about users related properties being related to portal administrator as they are not.
> (DOC) - Documented the user related signatures

- DNN Platform/Library/Collections/CollectionExtensions.cs
Added defensive code in the `GetValueOrDefault` to catch exception when string value is invalid and can't be converted
> DNN-6554 PortalSettings not getting parsed correctly

- DNN Platform/Library/Entities/Urls/TabIndexController.cs
Added logoff to the TabDictionary.
Logoff and Login would redirect correctly when appended to the alias root.
For example:
evoq.dnndev.me/en-us/Login
evoq.dnndev.me/en-us/Logoff
If Logoff or Login is appended to the existing page:
evoq.dnndev.me/en-us/MyTest/Login
evoq.dnndev.me/en-us//MyTest/Logoff
it won't work as we can't be adding all possible combinations to the TabDictionary.
In this situations ctl=Login or ctl=Logoff would work:
evoq.dnndev.me/en-us/MyTest?ctl=Login
evoq.dnndev.me/en-us//MyTest?ctl=Logoff
or
evoq.dnndev.me/en-us/MyTest/ctl/Login
evoq.dnndev.me/en-us//MyTest/ctl/Logoff
> DNN-5471 SI: Logoff.aspx 404

- Website/DesktopModules/Admin/Portals/Signup.ascx.cs
[DNN-7080](https://dnntracker.atlassian.net/browse/DNN-7080)
>When an exception occurs during portal creation, the module catches but does not log the error, meaning that there are no records anywhere of what caused the error (except for showing the user the error's message, but when it's "Object reference not set to an instance of an object," that's not much help).
>The caught exception should be logged so that follow-up investigation into unexpected errors can be done.
> DNN-7080 Log exception during portal creation

- DNN Platform/Library/Entities/Portals/PortalAliasController.cs
[DNN-7091](https://dnntracker.atlassian.net/browse/DNN-7091)
`_dataProvider` field may be initialized before `DataProvider` is ready, instead of
using the field, call `DataProvider.Instance()` directly (as the rest of the code
in `PortalAliasController` is doing already)
> DNN-7091 Fix race condition in PortalAliasController

- DNN Platform/Library/Entities/Users/UserController.cs
Delete of unauthorized superusers fails because GetUnAuthorizedUsers(portalId) can't return unauthorized superusers.
SuperUser accounts are not assigned to any portal and do not store Authorized value in the vw_Users (as Authorized value is joined from UserPortals table that has no records for super users).
To resolve this, method selection should be based on the portalId value.
> DNN-6924 SuperUsers - Deleting Unauthorized SuperUser accounts fails

- Website/DesktopModules/Admin/Portals/SiteSettings.ascx.cs
as the request always redirect by profile definitions. for code impact in future, only rebind portal when response haven't call redirect, also config active tab to avoid error in this situation.
> DNN-5979: as the request always redirect by profile definitions.

- DNN Platform/DotNetNuke.Web/InternalServices/ItemListServiceController.cs
Hidden Pages are not security relevant - they are just not included in the menu. There can be tons of reasons for that. This change is strongly requested from my power users.
> DNN-6796 Cannot add existing module from hidden page as non-admin user.

- Website/Providers/DataProviders/SqlDataProvider/07.04.02.SqlDataProvider
The incorrect use of the {databaseOwner} resulted in no values being returned from a query in the SPROC.  This caused searches to return no results.
> DNN-7178: Fix broken SqlDataProvider script 

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
This third attempt to fix this requires a slight modification to how packages are uninstalled in Upgrade.  The previous private method UnInstall's based on the package name - but this value is not globally unique.  It is only unique within a specific package type.  I have therefore modified the UnInstall method to take a packagetype parameter - updated all uses of that method and used the correct package type in uninstalling the Dark Knoght Mobile skin and container.
> DNN-5288: only uninstall package when the skin/container folder does not exist

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
Added the hideadminborder module setting for any module added to an Admin page in Upgrade.
> DNN-7223 DCC Manager shows Admin Only notification

- Website/DotNetNuke.Website.csproj
- Website/packages.config
This is due to a version mismatch for two Web API assemblies.  The original WAP conversion used the old .NET 4.5 version of these assemblies, rather than using the Nuget 5.1 version.  This PR resolves that.
> DNN-7259 Upgrade - Platform 7.4.1 to 8.0.0 web.config is broken site will not load

- Website/App_GlobalResources/List_Country.resx
provide empty "stub" file to ensure that translators are aware a file needs translated and tools pick it up - en-us translations still come from countrylistbox so resx has no entries.
> DNN-7103 Ensure that translators provide valid countrylist resx files

- Website/Portals/_default/Blank Website.template.de-DE.resx
- Website/Portals/_default/Blank Website.template.es-ES.resx
- Website/Portals/_default/Blank Website.template.fr-FR.resx
- Website/Portals/_default/Blank Website.template.it-IT.resx
- Website/Portals/_default/Blank Website.template.nl-NL.resx
- Website/Portals/_default/Default Website.template.de-DE.resx
- Website/Portals/_default/Default Website.template.es-ES.resx
- Website/Portals/_default/Default Website.template.fr-FR.resx
- Website/Portals/_default/Default Website.template.it-IT.resx
- Website/Portals/_default/Default Website.template.nl-NL.resx
At present language specific templates are added manually to the templates folder - this means that updates are difficult and the process is error-prone. The decision was made to add the language specific templates to the portals/_default folder and at language pack creation time we will delete the unneeded templates
> DNN-7104 update platform to support an edition specific list of template

- Website/DesktopModules/Admin/Languages/LanguagePackWriter.ascx.cs
Added code to export library/connector packagetypes as long as they have a foldername defined (so we know where to search to include resx files)
> DNN-7105 Fix language pack create function so all extension types are exported

- DNN Platform/Library/Services/Search/Internals/SearchHelperImpl.cs
- DNN Platform/Library/Services/Search/SearchEngine.cs
- DNN Platform/Library/Services/Search/SearchEngineScheduler.cs
If REINDEX button clicked while the scheduler is running, the fix makes sure it doesn't affect the currently running indexing cutoff date.
This pull request must accompany the previous request for bug/DNN-7238.
> DNN-7242: fixes that make sure re-index button clicks work as expected.

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/contentTypes.js
Call getDataTypes  in both init (for add Field) and load (for edit Field) functions of ContentFieldViewModel object.
> DNN-7261 DCC - Host cannot edit an existing Content Field within a Content Type

- DNN Platform/Library/Services/Mobile/RedirectionController.cs
DNN by default has a definition for the MobileRedirect httpmodule which runs for all .net requests (except for install/upgrade requests).
As part of it's logic it checks to see if a redirect rule exists and if so checks if it applies to the page (and a few other pieces of validation). Before this check loop the clientcapabilities are read from 51degrees even though they may not later be checked against (e.g. if the current page does not have a redirect rule). This has been refactored to ensure the capabilities are only loaded if needed
> DNN-7362 Improve MobileRedirectModule performance by doing ClientCapability checks only when needed

- Website/development.config
- Website/release.config
The DDRMenuNavigationProvider should be the default provider and the only provider installed in a standard DNN installation.
> DNN-7432 Remove references to DNNMenuNavigationProvider

- Website/DesktopModules/Admin/Analytics/GoogleAnalyticsSettings.ascx
- Website/DesktopModules/Admin/Analytics/GoogleAnalyticsSettings.ascx.designer.cs
Removed the "required" validator attached to the trackingId field of the
google analytics settings controller. This should allow users to remove
Google Analytics from their website if they so wish.
https://dnntracker.atlassian.net/browse/DNN-3547
> It should be possible to remove Google Analytics

- DNN Platform/Library/Entities/Host/Host.cs
- Website/Default.aspx.cs
- Website/DesktopModules/Admin/HostSettings/App_LocalResources/HostSettings.ascx.resx
- Website/DesktopModules/Admin/HostSettings/HostSettings.ascx.cs
- Website/DesktopModules/Admin/HostSettings/HostSettings.ascx.designer.cs
- Website/DesktopModules/Admin/HostSettings/hostsettings.ascx
- Website/Install/DotNetNuke.install.config.resources
Public pages can now emit a admin set HTTP Cache Control. 
Settings available in the host area.
> DNN-5387: Improve cacheability for unauthenticated (public) pages.

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
Updated the sortable binding to use the Move icon as a handle for the sorting
> DNN-7424 DCC Admin - Sorting the fields should use the "Move" handle

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
Using the scroll, scrollSensitive options to enable scrolling of the window.  Also use containment setting to restrict drag and drop to within table.
> DNN-7425 DCC Admin - Allow window to scroll when sorting fields

- DNN Platform/Library/Services/ClientCapability/ClientCapability.cs
- DNN Platform/Library/Services/ClientCapability/IClientCapability.cs
- DNN Platform/Library/Services/Mobile/RedirectionController.cs
- DNN Platform/Providers/ClientCapabilityProviders/Provider.FiftyOneClientCapabilityProvider/FiftyOneClientCapability.cs
in commit https://github.com/dnnsoftware/Dnn.Platform/commit/deea18c2d3bfae9c4c34dd292b327513e3b3313d it drop the use of Capabilities property(not fill it so it will always empty) as its not memory efficient.
for the purpose to read client capabilities value, i add a new property accessor in this pull request, and obsolete the collections one.
> DNN-7500: add property accessor to get client capabilities values.

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
The CodeMirror update changed the way the HtmlEmbedded mode works and it now requires an additional JavaScript file get loaded.  There is still a rendering bug which will be handled in a separate issue.
> DNN-7581 Add missing multiplex JavaScript reference

- DNN Platform/Library/Common/Globals.cs
When a DNN website has an application domain recycle a check is made to see if an incremental file exists to see if an incremental upgrade may occur (i.e. where the DNN version has not changed but an xx.xx.xx.xx.sqldataprovider exists)
At present this check has a few short-circuits to ensure it doesn't affect performance after app domain recycle. For instance if the dotnetnuke.dll assembly version is less than 7.4.2 then an incremental check is not done as incremental updates did not exist in that version.
A second check occurs to see if more than 1 incremental exists - this is based on the assumption that a release that will support incremental updates will have at least one xx.xx.xx.xx.sqldataprovider initially so that the "increment" column in the "version" table is populated. If more …
> DNN-7598 Allow releases without an initial incremental file to support incremental upgrades

- Website/DesktopModules/Admin/HostSettings/App_LocalResources/HostSettings.ascx.resx
- Website/DesktopModules/Admin/HostSettings/HostSettings.ascx.cs
- Website/DesktopModules/Admin/HostSettings/HostSettings.ascx.designer.cs
- Website/DesktopModules/Admin/HostSettings/hostsettings.ascx
This item will show a warning message is oauth server support is enabled at the host settings level but the oauth server library is not installed.
> DNN-7637 Add warning text to host settings that flags if oauth extension is not installed

- Website/DesktopModules/Admin/Portals/SiteSettings.ascx.cs
- Website/DesktopModules/Admin/Portals/SiteSettings.ascx.designer.cs
- Website/DesktopModules/Admin/Portals/sitesettings.ascx
also add's a warning message if the oauth server library is not installed.
Note: this needs to be done after #857 as it shares the same resource key
> DNN-7393 support for enable/disable oauth at portal level

- DNN Platform/Library/Framework/PageBase.cs
- Website/Default.aspx.cs
This moved the JS registration from PageBase into Default.aspx, I'm not sure if
anything needs to be added to support the use of JavaScript Libraries in pages
other than Default.aspx that inherit from PageBase
> DNN-7701 Register JS libraries later in page lifecycle

- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnHtmlHelper.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnHtmlHelperOfT.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnUrlHelper.cs
[DNN-7744](https://dnntracker.atlassian.net/browse/DNN-7744)
>The `DnnWebViewPage<TModel>` base class that MVC views and DCC templates use overrides the standard MVC helpers, `Html` and `Url`. There are some methods and properties available through those helpers in MVC that are not accessible in DNN's versions.
>
>For example, using `@Html.Raw(Dnn.ViewData.Model.Content.Fields["ProposalTitle"].Value)` in a DCC template gives an error that "`DotNetNuke.Web.Mvc.Helpers.DnnHtmlHelper<dynamic>` does not contain a definition for `Raw`"
> DNN-7744 Add missing members to DnnHtmlHelper and DnnUrlHelper

- DNN Platform/Library/Collections/CollectionExtensions.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Collections/CollectionExtensionTests.cs
[DNN-7742](https://dnntracker.atlassian.net/browse/DNN-7742)
>When saving a content item in the DCC Viewer module, if there is a string data field with a comma in the value, there is an error thrown.  This does not affect Rich Text or Markdown, because they are handled differently.  It would also, theoretically, affect Integer or Float fields if a comma was in the value (e.g. as a decimal or thousands separator).
>
>The culprit is the `GetValueOrDefault` call in `ViewerController.ProcessFields`, which uses `ToLookup`, which splits values on commas (in `ParseValues`).
>
>For example, but the DCC Viewer module on the page, select _Employee_ as the content type, and save.  Reload the page, then select _Edit Content_ from the action menu.  Enter content with a comma into one of the text …
> DNN-7742 exception editing dynamic content item

- DNN Platform/Library/Services/Localization/ILocalizationProvider.cs
- DNN Platform/Library/Services/Localization/LocalizationProvider.cs
Takes the original system resx file, loads all variations over it and returns that as a dictionary for further use.
> DNN-7740: Retrieve a compiled resx file as a dictionary

- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Entities/Modules/ICustomTokenProvider.cs
- DNN Platform/Library/UI/Modules/Html5/Html5ModuleTokenReplace.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Components/BusinessController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Components/FontPropertyAccess.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Dnn.Modules.DynamicContentManager.csproj
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/dnn_DCCManager.dnn
This change adds the ability to use custom Tokens in your SPA modules.  A new Interface was created which adds a GetTokens method.  If you implement this interface in the BusinessControllerClass, then the HTML5TokenReplace class will call the GetTokens methods and add your tokens to the list that is processed as part of your HTML views.
This change also adds a sample implementation to the Dynamic Content Type Manager which implements an [Icon] token that takes the name of an icon defined in the [DNN Icons project](http://dnncommunity.github.io/dnnicons/) and outputs the full class implementation for a given icon.  For example the token [Icon:home] will output "dnni dnni-home".  This abstracts away any web font implementations so that if we choose to change the dnni prefix, we only have …
> DNN-7550 Add ability to create custom tokens in SPA modules

- DNN Platform/Library/Services/Tokens/BaseTokenReplace.cs
When creating a SPA module some valid angularjs code is removed from the
HTML page due to the code in the Html5HostControl. This isn't just an
angularJS issue, it is just javascript. So this issue could effect
others with SPA modules.
These are two examples of valid angularJS code.
var sbApp = angular.module('sbApp', []);
...
$scope.orders = [];
However when the html module is rendered to the browser the empty [] is removed and the code looks like this.
var sbApp = angular.module('sbApp', );
...
$scope.orders = ;
This creates a JS error and stops the module from working. The issue that DNN have used the square brackets to allow token replacement to add modulecontext information, resource string etc.
However the RegEx statement and code in the DNN …
> DNN bug 7811

- DNN Platform/Library/UI/Modules/Html5/ModuleActionsPropertyAccess.cs
When creating SPA modules you might want to leverage the module action menu without necessarily being forced to do a popup dialog.  This change will allow you to set a script which is called when the module action menu item is selected.  If this option is used then the ControlKey is ignored and instead the Script is used to generate a JavaScript link for the menu.  Both the ControlKey and Script options use the underlying Url option in the ModuleAction.  If your script does not include a "javascript:" prefix, then it will automatically be added.
> DNN-7627 Add ability to set script for module actions.

- DNN Platform/DotNetNuke.Web/Api/Internal/DnnContextMessageHandler.cs
fix to bug 7857,  before this would always return true regardless of the
portalId.
The method GetTab will work out the correct portalId to locate the tab
if the tabId doesn't existing in the portal. Therefore we need to test
to see if the returned TabInfo object has the portalId as the expected
value.
If this pull request is accepted then its import to apply pull request #952 since without this additional pull then anyone with a child portal won't be able to call the webAPI. This is due to the code needing an additional fix to correct the fact that portalId is wrong when called via a child portal.
> Fix Bug7857 - WebAPI TabIsInPortal always returns true

- Website/DesktopModules/Admin/Scheduler/App_LocalResources/EditSchedule.ascx.resx
- Website/DesktopModules/Admin/Scheduler/EditSchedule.ascx.cs
- Website/DesktopModules/Admin/Scheduler/EditSchedule.ascx.designer.cs
- Website/DesktopModules/Admin/Scheduler/editschedule.ascx
This is a follow-up pull request to https://github.com/dnnsoftware/Dnn.Platform/pull/725 and https://github.com/dnnsoftware/Dnn.Platform/pull/726. I think the "retry time lapse" property should be optional and not mandatory.
> DNN-7408 & DNN-7409: Make RetryTimeLapse optional

- DNN Platform/DotNetNuke.Web/Api/Internal/DnnContextMessageHandler.cs
The fix in the DNN Platform\DotNetNuke.Web\Api\Internal\DnnContextMessageHandler.cs TabIsInPortal method did in DNN-7857 does not handling properly host pages. Unfortunately there is no way in the DnnContextMessageHandler to know if a web method request is done in the context of an host tab. The portal id is based on the alias so this will always set a valid portal Id.
I have fixed extended the logic added in DNN-7857 returning true in the method if the tab is an Host tab. The private method has been renamed from *TabIsInPortal *to *TabIsInPortalOrHost*
> DNN-7941 - DAM module on Host File Management page shows error

- DNN Platform/Library/Entities/Modules/Settings/ParameterAttributeBase.cs
- DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
Initialize a property  instead, and don't  set it if the setting is null.
[ModuleSetting(Prefix = "Foo_")]
public DateTime Bar { get; set; } = DateTime.Now;
> DefaultValue not needed. 

- DNN Platform/Website/Install/InstallWizard.aspx
- Website/Install/UpgradeWizard.aspx
The install and upgrade wizards had hard links to the old default.css location.  The files were updated to use the new location for default.css.
> DNN-8022 Fix default.css reference in installwizard

- DNN Platform/Library/Security/Roles/DNNRoleProvider.cs
When a role is created or updated, it's name and description should be trimmed for white spaces.
> SOCIAL-4266 and DNN-7900 : When a role is created or updated

- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnUrlHelper.cs
DNN-8093 Fixed the bug for missing controller name in case of Action(actionName) overload.
Now the system will pick the current controller name in case it is not provided.
> DNN-8093 Fixed the bug for missing controller name

- DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
If the settings don't yet have a value, this throws an exception.  The intention was to throw only when the type or the attribute wasn't defined, but that wasn't what the implementation did.  I'm just going to leave the TODO comment for now to indicate that we should consider handling the possibility of other attributes somehow.
> DNN-8091 fix exception when settings not set

- DNN Platform/DotNetNuke.Web/Api/HMACAuthenticationAttribute.cs
- DNN Platform/Library/Common/Utilities/DataCache.cs
I reviewed the “DnnModuleAuthorizeAttribute” and had to made few changes (refactoring, optimization, and logging). From my previous experience, working with any security scheme without any logging is a nightmare. Therefore, I added some logging at TRACE level to allow developers to see why their calls fail when these happen.
Also, I change the time-stamp timeout to be 5 minutes instead of not 5 seconds because the server time could have more time drift than the 5 seconds. From a security perspective, this is not an issue as we have the NONCE caching to take care of this. Moreover, I set the key to be “APPID + NONCE”. This is extremely necessary to allow any service to server more than one user at the same time if NONCE was repeated by different clients (the clients may reset the NONCE …
> DNN-6719: HMAC attribute enhancements (refactoring, optimization, logging)

- DNN Platform/Components/ClientDependency/Source/Controls/ClientDependencyInclude.cs
Reverts dnnsoftware/Dnn.Platform#1185
Code reverted and issue closed as it will impact modules which register scripts via CDF and are cached. For these modules the scripts are re-registered from cached version of the module by finding the CDF version from cached content.
> Revert "DNN-8050 The comments will be injected when debug is enabled"

- DNN Platform/Library/Services/GeneratedImage/StartTransform/UserProfilePicTransform.cs
Basically the error occurs because of closed memory stream linked with the image.
As workaround provided by the Microsoft a copy image method has been introduced to resolve the issue.
Reference link: https://support.microsoft.com/en-us/kb/814675
> DNN-8207 Fixed the GDI exception.

- DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
- DNN Platform/Dnn.AuthServices.Jwt/Library.build
Note: Auth_System module types need to abide by some contracts which the JWT does not need; therefore it is moved under providers.
> DNN-8247: Moved JWT module under providers to fix settings page

- DNN Platform/Library/UI/Skins/Pane.cs
Ensuring that containerSrc is taken from the tab if it is still empty in the code flow.
(Preventive measure).
> DNN-8012 Ensuring that containerSrc is taken from the tab

- DNN Platform/Modules/CoreMessaging/Scripts/CoreMessaging.js
Added logic to pass in thread count when marking as read/unread. If read, count is 0, and unread, count is 1.
> DNN-7311 - Core Messaging: Mark as Unread/Read

- DNN Platform/DotNetNuke.Web/InternalServices/SearchServiceController.cs
Old evaluation is == (which does not make sense).
More should only be true if the search result count is more than the page size.
> DNN-8289 - Updated "more" valuation for search results.

- DNN Platform/DotNetNuke.Web/UI/WebControls/DnnUrlControl.cs
The first time the Page option is selected, the url is not set so we have to check it
> DNN-8303 - RGR - Page Settings > Advanced Settings - Change does not persist + error in log file

- DNN Platform/Library/Services/GeneratedImage/DnnImageHandler.cs
- DNN Platform/Library/Services/GeneratedImage/ImageHandlerInternal.cs
- DNN Platform/Library/Services/GeneratedImage/StartTransform/ImageFileTransform.cs
- DNN Platform/Library/Services/GeneratedImage/StartTransform/SecureFileTransform.cs
- DNN Platform/Library/Services/GeneratedImage/StartTransform/UserProfilePicTransform.cs
I revisited all the place where a bitmap is created from a file path and changed the new Bitmap(filepath) to Image.FromStream. The previous method locks the file until the image is disponsed (see https://msdn.microsoft.com/en-us/library/0cbhe98f(v=vs.110).aspx). As part of this issue I have also add image.disponse() when found possible to ask the Garbage Collector to release memory as soon as possible.
> DNN-8176 - DNNImagehandler does not close handle to source image

- DNN Platform/HttpModules/Services/ServicesModule.cs
The Set-Cookie was being removed from headers as per JIRA DNN-8204 but it affected the functionality of persona bar add page
where a new page was going entering into edit mode automatically.
> DNN-8325 Removed the code to remove Set-Cookie header

- DNN Platform/Library/Services/FileSystem/Providers/DatabaseFolderProvider.cs
the position of the stream is only used when the steam is seekable
> DNN-8273 - DAM - file move failed from Amazon S3 to Database folder type

- DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
- DNN Platform/DotNetNuke.Web.Mvc/Framework/ModuleDelegatingViewEngine.cs
- DNN Platform/DotNetNuke.Web.Mvc/Framework/ViewEngineCollectionExt.cs
- DNN Platform/DotNetNuke.Web.Mvc/MvcHostControl.cs
The issue was happening due to MVC cache key. Since MVC is designed to work on single site architecture and does not expect multiple modules and views folders.
The cache key has been modified to include the namespace in it so that each module is treated differently.
Also the call render module has been moved from onload to oninit because in onload case the if the page has different modules and then the view locations are overwritten to the last module at the time of onload. So all the other modules are not found and throws exception
> DNN-8348 Fixed the issue by removing MVC cache and using own cache key

- DNN Platform/Library/Framework/JavaScriptLibraries/JavaScript.cs
[DNN-8381](https://dnntracker.atlassian.net/browse/DNN-8381)
>DNN should support JS library packages without their own script, but which just pull in dependencies.  This mostly works already, but causes a `script` tag to be included for the empty library, causing a 404 request.
>
>### Steps to Reproduce
>1. Download all packages from https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/jQuery.cycle_2.1.5 which have a numeric prefix
>2. Copy those packages to the `\Install\JavaScriptLibrary` folder of your DNN website
>3. Hit the `/Install/Install.aspx?mode=installresources` URL of your DNN website
>4. Ensure script combination is turned off
>5. Install attached module which requests the `jQuery.cycle2` JS library
>
>### Expected Results
>* All dependent libraries …
> Don't try to request empty JS library file DNN-8381

- DNN Platform/Library/Services/Authentication/OAuth/OAuthConfigBase.cs
[DNN-8383](https://dnntracker.atlassian.net/browse/DNN-8383)
>DNN installations with many sites sometimes want to share the API secret & key between those sites, instead of having to redefine them for each site.
> Allow sharing OAuth service config across sites DNN-8383

- DNN Platform/DotNetNuke.Web/Api/AuthorizeAttributeBase.cs
Reverts dnnsoftware/Dnn.Platform#1314
This will cause the WebAPI to throw Unauthorized error even if there is AllowAnonymous attribute present at the controller level. (See JIRA SOCIAL-4458)
This issue will need different solution.
> Revert "DNN-4864: when class have AllowAnonymous attribute, then need check the action doesn't contains any authorize attribute."

- Website/DesktopModules/Admin/Extensions/App_LocalResources/UsageDetails.ascx.resx
- Website/DesktopModules/Admin/Extensions/UsageDetails.ascx.cs
[DNN-8559](https://dnntracker.atlassian.net/browse/DNN-8559)
>There are a couple of small changes that the Usage Details report in the extensions module could make to make its user experience smoother.
[DNN-8560](https://dnntracker.atlassian.net/browse/DNN-8560) (sub-task)
>The module generates URLs using the first portal alias for the site, instead of the primary alias. Also, it generates the URL as `/Default.aspx?tabId=123` instead of generating the canonical URL for the page.
[DNN-8561](https://dnntracker.atlassian.net/browse/DNN-8561) (sub-task)
>When accessing the usage details of a module from _Host -> Extensions_, it requires you to pick the portal/site, even if your installation only contains one site. It should default to the current site.
> DNN-8559 enhance UX for Usage Details report in Extensions module

- DNN Platform/Modules/CoreMessaging/View.ascx
Fixed username encoding so now can contains apostrophe without errors on messaging tab. Also applied same fix in portal name variable.
> DNN-8532 - Messaging Fails for users with an Apostrophe in their name

- Website/DesktopModules/Admin/SearchResults/SearchResults.ascx
- Website/DesktopModules/Admin/SearchResults/SearchResults.ascx.cs
The `SearchResult.ascx` page is susceptible to XSS when the search string has single-quotes (breaks JSON at page bottom). This patch fixes the issues the right way; using `HtmlAttributeEncode` when emitting user-supplied values (when echoing back the `SearchTerm` or `TagsQuery` values in the input fields) and `JavaScriptStringEncode` when emitting the `SeachTerm` in the `dnn.searchResult.queryOptions` script.
This also simplifies the code behind to null-coalesce the query parameters and not do the encoding on the input values (instead encoding them on the rendering out, as it should be)
> Properly handle SearchResult XSS issues.

- DNN Platform/DotNetNuke.WebUtility/ClientAPI.vb
- DNN Platform/Library/Services/Localization/Localization.cs
The current implementations are woefully incomplete and can cause breakages and
security risks
This is an alternate implementation of #1488, thanks to @IDisposable for taking on the initial work for fixing this!  I'm suggesting this implementation so that :one: other users of the `GetSafeJSString` methods are protected, not just usages within DNN, :two: to simplify the change and not have to touch as many core files, and :three: to avoid having to distinguish between the two overloads of `Localization.GetSafeJSString`.
[DNN-8664](https://dnntracker.atlassian.net/browse/DNN-8664)
>Through testing and correction of an XSS vulnerability found in the SearchResults module, we've discovered that the library routine used to escape strings for inclusion as a javascript variable in a script block …
> DNN-8664 Update GetSafeJSString to use built-in encoder

- DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/viewsource.ascx.cs
The current code did not account for MVC modules having a different
directory structure.  In addition, MVC files are typically not in the root
directory, so the available file list should be generated by recursively
searching the directory tree.
> DNN-8587: Handle develop action menu for MVC modules

- Website/admin/Menus/ModuleActions/ModuleActions.js
DNN-8678: When using a <ul> element in a quick settings view, the jquery
ul selector would apply to all ul elements.  Since showMenu() applied
styles by calling .css(), the menu placement adjustments being performed
would incorrectly be applied to <ul> elements internal to the quick
settings view. This limits the jquery object to the first <ul>.
> Limit menu action ul selector to first ul

- Website/DesktopModules/Admin/HostSettings/App_LocalResources/HostSettings.ascx.resx
This will fix two instances of wrong letter case at the start of sentence in the `HostSettings.ascx.resx` file. Also performed search for similar issues across all other resources files, but none was found.
> [doc] Fix letter case at the start of sentence

- Website/admin/Menus/ModuleActions/ModuleActions.ascx.cs
This prevents a collision with FindControl when deleting the module.
> DNN-8586: Make QuickSettings Control.ID unique

- DNN Platform/Library/Services/FileSystem/FileUrlHelper.cs
See https://dnntracker.atlassian.net/browse/DNN-8629.
The line `var filePath = match.Groups["filePath"].Value;` does not work if the regex is converted to lower case.
> DNN-8629: Fixed System.ArgumentException in IsStandardFileURLFormat

- Build/Tools/NuGet/DotNetNuke.Bundle.nuspec
- Build/Tools/NuGet/DotNetNuke.Core.nuspec
- Build/Tools/NuGet/DotNetNuke.Instrumentation.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Client.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Deprecated.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Mvc.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.nuspec
- Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
- Build/Tools/NuGet/DotNetNuke.nuspec
This PR improves the NuGet packages by using consistent terminology and naming, and expanding descriptive text.  
It also uses dependencies between packages instead of duplicating files in each package (though I believe this can be improved on more than is in place via this PR).
Finally, the new DotNetNuke.Bundle package is renamed to just DotNetNuke, to indicate its place as the standard "meta" package.
Any feedback is welcome!  Thanks!
> Nuspec cleanup

- DNN Platform/Library/Services/ImprovementsProgram/BeaconService.cs
This change is to include the version and product edition to the Beacon Service calls
> DNN-9268: Add Version and Edition to Beacon Service Data

- Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
This NuGet package was removed, because it was including all of the source.  This explicitly ignores all files (before, since this only had dependencies and no files, NuGet automatically added all files)
This reverts ff1258b829250728b8c0cc8f59c993da030983a1 (which was a breaking change, since it removed a previously-public website)
This is related to #1592
> NOJIRA: Add back DotNetNuke.WebApi NuGet package

- Website/App_GlobalResources/SharedResources.resx
Users may not be enabling popups for their portal so the last part is not always accurate.
> DNN-9312 Optimize registration message for non popup

- DNN Platform/DotNetNuke.Web/InternalServices/ItemListServiceController.cs
[DNN-9835](https://dnntracker.atlassian.net/browse/DNN-9835)
>If you have a page which redirects (i.e. its type is _Tab_ or _URL_), but it also has children, that page does not show up in the page picker for selecting an existing module, which means that its children cannot be selected, either (though the children are available by searching).
>
>As an example:
>
> -   _Advocacy_ (redirect to `/Advocacy/Overview`)
>     -  _Overview_
>     - _Details_
>
>None of these three pages would show, and modules on _Overview_ would not be available to be copied to _Details_ (or anywhere else).
>
>This manifests itself in a couple of different ways. The `DnnPortalPageDropDownList` is a control available to 3rd party developers to use, and it uses the web service …
> DNN-9835 URL pages incorrectly excluded from Add Existing Module picker

- DNN Platform/Library/Services/Installer/Dependencies/ManagedPackageDependency.cs
- DNN Platform/Library/Services/Installer/Dependencies/PackageDependency.cs
- DNN Platform/Library/Services/Installer/Installers/LanguageInstaller.cs
- DNN Platform/Library/Services/Installer/Installers/PackageInstaller.cs
- DNN Platform/Library/Services/Installer/LegacyUtil.cs
- DNN Platform/Library/Services/Installer/Packages/PackageController.cs
- DNN Platform/Library/Services/Installer/Util.cs
- DNN Platform/Library/Services/Localization/LocaleController.cs
- DNN Platform/Library/Services/Upgrade/Upgrade.cs
- Website/DesktopModules/Admin/EditExtension/EditExtension.ascx.cs
[DNN-8941](https://dnntracker.atlassian.net/browse/DNN-8941)
> When a package has a dependency on another package, that dependency is currently case sensitive. Likewise, when installing a package, the search for duplicate packages (to determine if this is an upgrade, repair, etc.) is case sensitive. This behavior should not be case sensitive.
> # Scenario
> 
> The attached package [knockout-postbox_0.5.2_mismatch-dependency.zip](https://dnntracker.atlassian.net/secure/attachment/40755/knockout-postbox_0.5.2_mismatch-dependency.zip) has a dependency on "knockout," whereas the package that comes with DNN has the name "Knockout" with a capital _K_
> 
> ```
> <dependencies>
>   <dependency type="managedPackage" version="2.0.0">knockout</dependency>
> </dependencies>
> ```
> ## Steps to …
> DNN-8941 Package names should be case insensitive

- DNN Platform/Modules/Journal/ServicesController.cs
Fixes DNN-10071 issue by adding check for null.
When _relativePath_ paramter was null, it was throwing an exception.
> Fixes DNN-10071

- Website/App_GlobalResources/SharedResources.resx
This with fix unclosing P tag in the FileUpload.UnzipFileSuccessPromptBody.Text resource string.
> DNN-10273 Unclosed P tag in the resource string

- Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
When using Email address as username:
Login blocked after several failed login attempts. So the user is locked out for some minutes, but the problem is we did not receive a proper message indicating the locked out state, we see an error instead!
> bug fix: lockout user throws error

- DNN Platform/Components/ClientDependency/Source/CompositeFiles/CompositeDependencyHandler.cs
- DNN Platform/Components/ClientDependency/Source/Config/ClientDependencySettings.cs
- DNN Platform/Components/ClientDependency/Source/HtmlAttributesStringParser.cs
This brings the change from #1854 up to date with the [1.9.3 release](https://github.com/Shazwazza/ClientDependency/releases/tag/v1.9.3) from a couple of days ago.
This includes a couple of changes from 1.9.2 to 1.9.3, importantly
Shazwazza/ClientDependency#108, which fixes a bug when adding multiple HTML
attributes to a script tag
> DNN-9408 Upgrade ClientDependency.Core to 1.9.3

- DNN Platform/Library/Data/DataProvider.cs
- DNN Platform/Library/Entities/Host/Host.cs
- DNN Platform/Library/Entities/Users/Membership/MembershipPasswordController.cs
- DNN Platform/Library/Entities/Users/Membership/MembershipPasswordSettings.cs
- Website/Providers/DataProviders/SqlDataProvider/09.02.00.SqlDataProvider
[DNN-9759](https://dnntracker.atlassian.net/browse/DNN-9759)
>As part of a security audit, it came up that we couldn't set a minimum timeframe for which to retain passwords. So, while we can say that you can't reuse your last six (for example) passwords, there's nothing to stop you from changing you password six times in a row and reusing your original password.
>
>I'd like to propose adding a new setting with the minimum number of days to retain passwords (our client's requirements are six months, but I would plan to default to zero, for backwards compatibility, unless y'all think there should be a default).
> Password history should have minimum timeframe for password retention (DNN-9759)

- DNN Platform/Library/Entities/Host/Host.cs
- DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Portals/TestFiles/DefaultValues.csv
Changed `MaxIdleTime` from `0` to `100000` (100 seconds). This is the [default in .NET Framework](https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.maxservicepointidletime(v=vs.110).aspx). The old default of 0 may cause .NET to reuses a closed socket/connection and fail with error "Unable to write data to the transport connection: An established connection was aborted by the software in your host machine." This is because most SMPT-Servers close an open SMTP-connection after 5 minutes.
Also changed `ConnectionLimit` from `1` to `2`. This is the [default in .NET Framework](https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.defaultconnectionlimit(v=vs.110).aspx). Note: The [default in .NET Framework depends whether a loopback address is used or …
> (DNN-8129) Adjust default setting for SMTP client for idletime and connectionlimit

- DNN Platform/Library/Services/Installer/Installers/ConfigInstaller.cs
- DNN Platform/Library/Services/Installer/XmlMerge.cs
- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/MergeFiles/NoChangeOnOverwriteMerge.xml
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/MergeFiles/NoChangeOnOverwriteTarget.xml
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/MergeFiles/ShouldChangeOnOverwriteMerge.xml
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/MergeFiles/ShouldChangeOnOverwriteTarget.xml
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/XmlMergeTests.cs
[DNN-8604](https://dnntracker.atlassian.net/browse/DNN-8604)
> It is common for packages to include a [config component](http://www.dnnsoftware.com/wiki/manifest-config-component) in their manifest if they require any adjustments to the `web.config` file.  On initial install, this change will be made correctly.  However, this component will also run on upgrades (ensuring that the config is correctly in place), and the vast majority of the time, won't do anything, since it was done on install.  The problem is that the config component still updates the `web.config` file, even if no changes are being made, which causes the website to be restarted unnecessarily.
> 
> I've attached a modified version of the Xcillion theme package which adds support for the `woff` and `woff2` font file …
> DNN-8604 Avoid touching files when XmlMerge doesn't change anything

- DNN Platform/Library/Services/Journal/JournalControllerImpl.cs
Fixing a case where a disposed memory stream was passed as an argument to another method.
> DNN-10389: fixing a potential platform crash issue.

- CONTRIBUTING.md
The hyperlink to the CLA document on DNNSoftware.com is broken due to spaces in the Word.doc file name. I've added in %20 where appropriate.
> Fixing CLA Hyperlink

- DNN Platform/DotNetNuke.Web.Mvc/Framework/Controllers/DnnController.cs
- DNN Platform/DotNetNuke.Web.Mvc/Framework/Controllers/IDnnController.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnUrlHelper.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/Fakes/FakeDnnController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/Framework/Controllers/DnnControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/Helpers/DnnUrlHelperTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/MockHelper.cs
Added support in the `DnnController` for `DnnUrlHelper`. 
* I added the `DnnUrlHelper` inside of the `IDnnController` and `DnnController`. Since the ASP.NET MVC object isn't really useful in DNN Routing I created our `DNNUrlHelper` as a new property which hides the base Url implementation. In the `DnnController` 
* The `DnnController` now overrides the ASP.NET MVC `Controller` method `Initialize(RequestContext requestContext)` and sets our `DnnUrlHelper`. This is the **exact** same way that the `Controller` works from ASP.NET MVC. This method will get called on every request and be able to appropriately set the `DnnUrlHelper`
**Our code**
```c#
protected override void Initialize(RequestContext requestContext)
{
base.Initialize(requestContext);
Url = new DnnUrlHelper(requestContext, this); …
```
> DNN-10462: Added support for DnnUrlHelper in DnnController for MVC

- DNN Platform/Modules/DnnExportImport/Providers/DataProviders/SqlDataProvider/09.02.00.SqlDataProvider
Original definition for this stored procedure can be found [here](https://github.com/dnnsoftware/Dnn.Platform/blob/0659a27424fe90a4805e709ba71d303e747b81eb/DNN%20Platform/Modules/DnnExportImport/Providers/DataProviders/SqlDataProvider/09.01.00.SqlDataProvider#L1999)
> DNN-10143: Fix ambiguous column reference

- DNN Platform/Library/Entities/EventManager.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FileManagerTests.cs
Logging in `FileManager` has been breaking unit tests recently.
1. I've made the logger call in `EventManager` more resilient to nulls and lil bit less repetitive
1. there was still one more test failing so I actually mocked the event log controller
> task/DNN-10662 fix breaking test on Team City

- Website/App_GlobalResources/SharedResources.resx
- Website/admin/Menus/ModuleActions/ModuleActions.ascx
- Website/admin/Menus/ModuleActions/ModuleActions.ascx.cs
- Website/admin/Menus/ModuleActions/ModuleActions.css
- Website/admin/Menus/ModuleActions/ModuleActions.js
This is an alternative implementation of #1256.
[DNN-8355](https://dnntracker.atlassian.net/browse/DNN-8355)
> Like with the "Shared Module" indicator in module actions for cross-site sharing withing a portal group, site administrators need to know if the module they're going to edit is shared by other pages on the same site.
> ### Steps to Reproduce
> 1. Add a module to a page
> 2. Create a new page
> 3. Select _Add Existing Module_ from the _Modules_ menu
> 4. Choose the page from step 1
> 5. Ensure _Make a Copy_ is unchecked
> 6. Choose the module from step 1 and add it to a pane
> ### Expected Results
> - There is an indication that the module is shared with the other page
> ### Actual Results
> - There is no indication
> DNN-8355: Show "Shared Module" indicator for cross-page module sharing

- CONTRIBUTING.md
Updated contribution guide to use GitHub Issues instead of JIRA issues
#2044
> Updated contributing guide for GitHub issues

- .gitmodules
Fixes a git clone error using git@github.com instead of https://github.com
closes #2051
> Fixes git clone error due to ClientDependency submodule

- DNN Platform/DotNetNuke.Web.Mvc/Framework/ActionResults/DnnRedirecttoRouteResult.cs
- DNN Platform/DotNetNuke.Web.Mvc/Framework/Controllers/DnnController.cs
Adds RedirectToAction support in the DnnController to support the additional API. This is a small change but will have a big impact on our MVC API. We updated the DnnController to override the virtual RedirectToAction to properly use our `DnnRedirectToRouteResult` object. All the non-virtual methods rely on this. 
AspNetWebStack Controller class
https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Web.Mvc/Controller.cs
Lines: 478-517
Looking at the Microsoft Controller implementation referenced above the all the non-virtual RedirectToAction rely on the virtual one that we now override in this change.
We also update the `DnnRedirectToRouteResult` to handle the correct Url Mapping. Consider you have 2 DNN MVC Modules on the same page, routing is handled the same way it currently …
> Adds support for RedirectToAction from a DnnController

- DNN Platform/Library/Services/Search/Internals/Constants.cs
- DNN Platform/Library/Services/Search/Internals/LuceneControllerImpl.cs
> DNN-21973: retry the search when there have exception throw during search process.

- DNN Platform/Tests/App.config
Fixes Issue #2234
Had to add a config section in the App.Config to explicitly tell the framework where to get the Data Provider named System.Data.SqlServerCe.4.0
> Add system.data to web.config file for VSTS unit tests to pass.

- DNN Platform/Website/Templates/Blank Website.template
- DNN Platform/Website/Templates/Default Website.template
- Website/DesktopModules/Admin/Security/Profile.ascx
Closes #2146 
Switched the country and region fields so that the country is first. This field populated the region dropdown so it needs to be filled first in order to see a dropdown of the regions available in that country. Without this, the entered region disappears when the user selects a country after the region.
Implemented a workaround to prevent browsers to display their suggestions above the Dnn built-in ones. Due to a bug in chrome autocomplete="off" does not work, to really make sure that the browser does not try to autocomplete, we need a random value in the autocomplete parameter so that the browser had no fields to suggest in memory.
- make sure to use chrome latest release, and in the browser settings make sure you have a couple of form fill records with addresses.
Before …
> Fixed issue where the browser covered the region and country dropdowns

- DNN Platform/Library/Services/Installer/Installers/CleanupInstaller.cs
- DNN Platform/Library/Services/Installer/Util.cs
- Website/App_GlobalResources/SharedResources.resx
Instead of showing an install as having an error, failing to clean up a file/folder should show a warning as it is not fatal to the installation of an extension.
Fix #2206
> Improve user feedback for cleanup node in installer

- Website/Resources/Shared/scripts/dnn.dragDrop.js
Fixes #2276
In dnn.DragDrop.js I changed the regular expression that's used to get the moduleId from a class attribute.
It used to work in cases like this:
`class="DnnModule DnnModule-OpenContent DnnModule-4084"`.
but would fail in cases like this:
`class="DnnModule DnnModule-40FingersWebshopSearch DnnModule-3767"`
With the fix, the latter also works.
This is the same solution @iJungleboy proposed in a previous Jira ticket mentioned in the issue. I tried and tested the solution on DNN 8.0.4, 9.2.1, 9.2.2RC.
> Fixed: dragdrop fails for modules with friendlyname starting with number

- DNN Platform/Library/Entities/Tabs/ITabController.cs
- DNN Platform/Library/Entities/Tabs/TabCollection.cs
- DNN Platform/Library/Entities/Tabs/TabController.cs
- DNN Platform/Library/Entities/Tabs/TabWorkflowTracker.cs
> DNN-22612: update the tab info in cache object instead of clear whole cache during workflow process.

- DNN Platform/Components/Newtonsoft/DotNetNuke.Newtonsoft.Json.dnn
- DNN Platform/Website/Install/Config/BindingRedirect.config
- DNN Platform/Website/Install/Config/RemoveBindingRedirect.config
Fixes #2121 
The Config component in the manifest of Newtonsoft.Json package is not needed. The binding redirect is ensured by the AssemblyInstaller through the [AddOrUpdateBindingRedirect()](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/Installer/Installers/AssemblyInstaller.cs#L194) method call inside the InstallFile() method.
This also broke the DNN upgrade from a version prior to 9.2.0 when the web.config contained additional `<codebase>` assembly bindings before the one with the `<bindingRedirect>`.
Moreover besides that, it also updated the web.config with the binding redirect twice, in both scenarios (clean install and DNN upgrade).
> Fix Newtonsoft.Json package install during DNN Upgrade.

- DNN Platform/DotNetNuke.Web/InternalServices/ControlBarController.cs
- DNN Platform/Library/Entities/Host/Host.cs
- DNN Platform/Library/Entities/Portals/PortalSettings.cs
- DNN Platform/Library/UI/Modules/ModuleInstanceContext.cs
This is a continuation of #1272, after rebasing and fixing conflicts
[DNN-8374](https://dnntracker.atlassian.net/browse/DNN-8374)
> We've made some customizations for a client which we think would be a good fit for inclusion in the core. There's a "Lock Site" action added to the control bar, which allows a super-user to turn off modifications to the site (probably for entering some sort of maintenance mode). For our client, the "good enough" way this is implemented is to disable the module actions whenever the site is locked (in addition, custom modules are able to access the locked status via a property on `PortalSettings` and do any additional changes, if desired).
> DNN-8374 adding locking functionality to the instance and individual sites

- DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
- DNN Platform/Library/Security/Membership/MembershipProvider.cs
- DNN Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs
- DNN Platform/Library/Services/Authentication/UserAuthenticatedEventArgs.cs
- Website/DesktopModules/Admin/Authentication/Login.ascx.cs
This is a continuation of #1346 (after rebasing and fixing conflicts)
[DNN-8450](https://dnntracker.atlassian.net/browse/DNN-8450)
> The fix for [DNN-4133](https://dnntracker.atlassian.net/browse/DNN-4133) was to add a prefix for the service to the beginning of the username. This broke our custom OAuth provider and I believe that we should have the ability to override whether we want to prefix the service to the Username in OAuth providers. In addition to allowing that overriding, this also implements the option to automatically associate logins to existing users, based on email.
> Testing of this API change will require a custom OAuth provider implementation which sets the new `PrefixServiceToUserName` and `AutoMatchExistingUsers` properties in that provider's implementation of …
> DNN-8450 Allow override of prefixing the service name for OAuth providers

- Website/DesktopModules/Admin/Authentication/Login.ascx.cs
Fixes #2267 
Issue is reported in 9.2.1, but also occurs in 9.2.2 RC.
Added` .TrimEnd('/')` to the following line, because a portalalias for a specific culture will not have a trailing /, while a returnurl will. Thus the `.Equals` did fail and the redirect to the configured tab did not occur.
`                var isDefaultPage = redirectURL == "/"
|| (alias.Contains("/") && redirectURL.TrimEnd('/').Equals(alias.Substring(alias.IndexOf("/", comparison)), comparison));
`
The issue was easily reproducible from the issue description.
> Fixed issue Redirect After Login failed for culture specific portalalias

- Website/Providers/DataProviders/SqlDataProvider/09.03.00.SqlDataProvider
Fixes performance issues experienced with `CoreMessaging_GetMessageConversations` procedure. The where clause for filtering paging could take 5+ minutes to properly return the result set due to the way the query was written. Added additional CTE to not have to calculate the row count range inside of the where clause.
Fixes issue with `Journal_ListForGroup` procedure where the page size is set, but the result set is less any deleted journal entries, so the page size is almost always greater, and thus you can never "get more" via the get more button. Proc change allows for Row_number to work properly depending on if you want deleted posts or not.
> Performance fix for CoreMessaging_GetMessageConversations and Journal_ListForGroup  Procedure

- Build/Tools/NuGet/DotNetNuke.Bundle.nuspec
- Build/Tools/NuGet/DotNetNuke.Core.nuspec
- Build/Tools/NuGet/DotNetNuke.Instrumentation.nuspec
- Build/Tools/NuGet/DotNetNuke.Providers.FolderProviders.nuspec
- Build/Tools/NuGet/DotNetNuke.SiteExportImport.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Client.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Deprecated.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Mvc.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.nuspec
- Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
- build.cake
This adds a new task `CreateNugetPackages`, which gathers up all the nuspec files from `Build/Tools/NuGet` and generates the nuget package. I had to update the version numbers with the `$version$` replacement-token feature of nupack.
> CI: Add Cake Task to generate our Nuget Packages

- DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
Fix issue #2133
1. renewal token must be validate before renewing access token.
2. making error messages clear
> renewal token must be validate before renewing access token.

- build.cake
#2270 changed the `buildNumber` variable to `GetBuildNumber()`, and #2323 was merged which was submitted and merged using the original variable.
> CI: Fixing broken builds due to change in build number variable

- DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
Fixes #2343
After max invalid attempts reached user still Unlock in Admin UI, though membership table showing Locked out true.
> DNN23855_Clear user cache onlogin failure

- Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
Fixes #2367 
If EnableEmailasUsername is set, then verify user obtained by GetbyEmail must not be null.
> Checking for option of EnableEmailasUsername before validating user

- DNN Platform/Library/Entities/Users/Profile/ProfilePropertyAccess.cs
`CheckAccessLevel` method has to be accessible to the rest libraries that refers to DotNetNuke.dll. 
I need it to check whether one user has a proper access to see some profile properties of other user. In particular, changes will be done in evoq social component.
fixes #2366
> Social Profile: visibility of user profile properties

- gitversion.yml
I propose that version are always prerelease, unless built from a tagged commit.
| branch/tag | version |
| -- | -- |
| `development` | `9.3.0-alpha.123` |
| `release/9.4.0` | `9.3.0-beta.12` |
| `v9.3.0` (tag) | `9.3.0` |
> Tweak version calculation

- DNN Platform/Modules/MemberDirectory/module.css
- Website/Resources/Shared/scripts/jquery/jquery-ui.js
fixes #2391
When searching member directory users, once autocomplete popup opened, application is adding the text next to the main form.
1. Create multiple dnn users
2. Create a new page
3. Add Member Directory module to a newly created page, click on publish
4. Start typing user name in a search box
5. Observe the text "..results are available, use up and down key" which is added at the bottom of the page
Text which is added is a part of [Live Region](https://www.oreilly.com/library/view/javascript-cookbook/9781449390211/ch14s09.html). It is used to voice additional info by screen readers. 
Live Region is marked with `.ui-helper-hidden-accessible` style, but it is not defined on a module level css. Similarly to other modules, we should hide helper text `display:none;`
> Member Directory Search: adding unused text to page

- DNN Platform/Library/Entities/Portals/PortalController.cs
This PR is addition to [PR 2297](https://github.com/dnnsoftware/Dnn.Platform/pull/2297)
On portal creation, when exception occurred, application removes folder that is already in use with other portal.
1. Create a DNN Site for future Portal ID by modifying home directory [PortalID] token, e.g. if current portal ID is 0 then create a portal with [PortalID] = 2. So, home directory path should be like: Portals/2
2. Create a site without modifying [PortalID]. So, home directory path should be like: Portals/[PortalID].
We get an exception and error message "Portal Folder Portal/2 is already Used".
3. Check folder Portals/2 created in step 1. It is fully removed.
When [PortalID] folder token is not defined explicitly, system assigns portal id automatically (portal id created in db). We have got …
> Portal deletion removes home folder linked to other portal

- .gitignore
- Build/cake/version.cake
- build.cake
Currently NuGet packages receive the version which is used for the Platform itself, like `9.3.0`.
This PR changes cake scripts so that the number will match the full build number such as `9.3.0-alpha024` or `9.3.0-RC1`. 
This way those packages will be nicely deployable to MyGet/NuGet, where each version has to be unique
> use full sermver for nuget packages

- Website/admin/Menus/ModuleActions/ModuleActions.ascx
- Website/admin/Menus/ModuleActions/ModuleActions.ascx.cs
- Website/admin/Menus/ModuleActions/ModuleActions.css
- Website/admin/Menus/ModuleActions/ModuleActions.js
- Website/admin/Menus/ModuleActions/ModuleActions.less
fixes [2353](https://github.com/dnnsoftware/Dnn.Platform/issues/2353)
Similar indicator is already shown for the shared modules. It is placed vertically in a right corner. To stay with the same design, module label is added in a same way. 
I'm open to discuss more ideas.
Short DEMO: [mp4](https://drive.google.com/file/d/1C2EFMusxS2npDRwDpN0qfoFsKir4NpEZ/view)
> Show Module Labels

- Website/admin/Menus/ModuleActions/ModuleActions.js
This is a quick fix for a typo I did in a previous [PR 2354](https://github.com/dnnsoftware/Dnn.Platform/pull/2354)
Due to wrong variable name there is an error occurred. `moduleTitle` should be used instead of `menuTitle`.
> Show Module Labels (Typo)

- Build/cake/version.cake
An apparent bug on VSTS causes issues accessing builds with duplicate numbers which happen when we have multiple triggers for the same commit (such as trigger by merging, manually, or by AdminExperience)
This PR changes the build number by appending the incremented build id from VSTS to the gitversion number.
> Unique build numbers on VSTS

- DNN Platform/Library/Services/ModuleCache/FileProvider.cs
- DNN Platform/Library/Services/OutputCache/Providers/FileProvider.cs
There is a site failure due to following exception:
`DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.UnauthorizedAccessException: Access to the path 'D:\home\site\wwwroot\Portals\0-System\Cache\Pages\55_8137927E7998C915DC56554B051AC3B3FFB9F67A8301079DD8BB1C1DC407D9F3.attrib.resources' is denied.`
Folder permission is a most often reason. 
In this PR I'm adding try/catch blocks to all places in which we perform handling of cached files. For some methods I didn't find exception handling in the calling/parent code.
To prevent site crashing we expect more logs to be captured for the further investigation.
> Locked cache file caused site load failure

- Website/DesktopModules/AuthenticationServices/DNN/Login.ascx
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2487
Login form action buttons (login, cancel, register, reset password) gets disabled every time user clicks on a particular action link. This behavior is expected and needed to avoid double click to raise same request multiple times.
When post back request completed the state of the buttons is not restored. In this PR it is fixed so all action links are enabled at the end of every post back request.
> Account Login Module: Login Button Disabled

- tools/Modules/packages.config
Adding [Cake.LongPath.Module](https://github.com/cake-contrib/Cake.LongPath.Module) to support long paths during CI build
> CI: Added Cake.LongPath.Module

- DNN Platform/Website/Templates/Blank Website.template
- DNN Platform/Website/Templates/Default Website.template
Fixes #2360 
Changed "Blank website.template" and "Default website.template" to have Biography profile property as Multi line text in stead of Richt Text.
ProfileController.AddDefaultDefinitions already had Multi Line Text for Biography, so no change needed there.
Portal installs with both template and checked the type of the Biography fields in a user's profile.
> Fixes issue 2360. Biography as Multi line text by default

- DNN Platform/Modules/HtmlEditorManager/module.css
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2500
`HTML Editor Management` module has its own css where some basic styles are defined, i.e. background color, borders, padding's and etc.. I found default text color is missing here, so it inherits the color from the skin. 
Since we have background defined, we should care about text color on that background. 
See result:
> HTML Editor Management Module: some labels are in white color

- DNN Platform/Tests/DotNetNuke.Tests.Core/Collections/LockStrategyTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Collections/ReaderWriterLockStrategyTests.cs
This pull request fixes unit tests broken by #2423.
There is the following hierarchy:
```
LockStrategyTests
|
+--> ExclusiveLockStrategyTests
|
+--> ReaderWriterLockStrategyTests
```
The `ReaderWriterLockStrategy` class no longer throws exception when user attemps to acquire the lock recursively, so unit tests in `ReaderWriterLockStrategyTests` no longer have the `ExpectedException` attribute.
Tests in `ExclusiveLockStrategyTests` remain unchanged.
> Fixed broken LockStrategy unit tests

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
When the platform is uninstalling extensions, it doesn't log when and what extensions were uninstalled as part of the upgrade process.
Hopefully this will help troubleshoot similar issues like #2552
> Log name of package when uninstalling extensions

- DNN Platform/Library/Common/Globals.cs
> get language from transferred parameter.

- DNN Platform/Modules/DDRMenu/DotNetNuke.Modules.DDRMenu.csproj
- DNN Platform/Modules/DDRMenu/TemplateEngine/RazorTemplateProcessor.cs
Closes: #2637 
The DDRMenu depends on `DotNetNuke.Web.Razor` which will be marked as deprecated in 9.x and removed in 11.0. As the platform moves forward we need to give developers and vendors ample time to migrate from the RazorEngine to [Microsoft's Razor 3](https://docs.microsoft.com/en-us/aspnet/web-pages/overview/getting-started/program-asp-net-web-pages-in-visual-studio) Implementation.
This PR adds an additional render support for `System.Web.WebPages.WebPage` which falls back to the RazorEngine if it isn't implemented.
Consider the following DDRMenu Razor Template
```
@using DotNetNuke.Web.DDRMenu;
@using System.Dynamic;
@inherits DotNetNuke.Web.Razor.DotNetNukeWebPage<dynamic>
... omitted code
```
This snippet currently works, and works with the proposed changeset. Developers …
> DDRMenu: Add Support for Web Pages (Razor 3) Renderer

- Website/Default.aspx
Currently it is not possible to make async calls during a page lifecycle event like On_Load.  Adding Async="true" allows extension controls to utilize async await for handling asynchronous calls.
> The default.aspx should support Async

- DNN Platform/DotNetNuke.Web.Razor/DotNetNukeWebPage.cs
- DNN Platform/DotNetNuke.Web.Razor/Helpers/DnnHelper.cs
- DNN Platform/DotNetNuke.Web.Razor/Helpers/HtmlHelper.cs
- DNN Platform/DotNetNuke.Web.Razor/Helpers/UrlHelper.cs
- DNN Platform/DotNetNuke.Web.Razor/RazorEngine.cs
- DNN Platform/DotNetNuke.Web.Razor/RazorHostControl.cs
- DNN Platform/DotNetNuke.Web.Razor/RazorModuleBase.cs
- DNN Platform/DotNetNuke.Web.Razor/RazorModuleControlFactory.cs
- DNN Platform/Modules/RazorHost/AddScript.ascx.cs
- DNN Platform/Modules/RazorHost/CreateModule.ascx.cs
- DNN Platform/Modules/RazorHost/EditScript.ascx.cs
- DNN Platform/Modules/RazorHost/RazorHost.ascx.cs
- DNN Platform/Modules/RazorHost/RazorHostSettingsExtensions.cs
- DNN Platform/Modules/RazorHost/Settings.ascx.cs
Closes: #2613 
Marks all **public** and **protected** APIs in 
* `DotNetNuke.Web.Razor`
* `DotNetNuke.Modules.RazorHost`
```
[Obsolete("Deprecated in 9.3.1, will be removed in 11.0.0, use Razor Pages instead")]
```
As we build out Razor Pages modules we will update the messages where applicable to point to what they should be using instead.
> Deprecate Razor Modules for DNN 11.0

- DNN Platform/JavaScript Libraries/Selectize/dnn.combobox.js
- DNN Platform/Library/Services/Search/Controllers/UserResultController.cs
- Website/DesktopModules/Admin/SearchResults/App_LocalResources/ResultsSettings.ascx.resx
- Website/DesktopModules/Admin/SearchResults/ResultsSettings.ascx
- Website/DesktopModules/Admin/SearchResults/ResultsSettings.ascx.cs
- Website/DesktopModules/Admin/SearchResults/ResultsSettings.ascx.designer.cs
> Add setting to display search result for users in specific roles

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
- Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Data.SqlDataProvider
The default 30 second timeout of the SQL data provider is often not enough during install and generates timeout errors.
This is now happening to me when using the **/Install/Install.aspx** page to refresh test environments. I can't say this has happened to me using the wizard though.
Here's what I see in the DotNetNuke.Data.log.resources file:
```
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
...
Add 6 rows to dbo.[ContentTypes]
Add 146 rows to dbo.[EventLogTypes]
Add 3 rows to dbo.[FolderMappings]
Add 1 row to dbo.[IPFilter]
Add 35 rows to dbo.[Journal_Types]
Add 1 row to dbo.[Languages]
Add 5126 rows to dbo.[Lists] ---> System.ComponentModel.Win32Exception …
```
> Increased data provider timeout during install

- DNN Platform/Connectors/Azure/Components/AzureConnector.cs
- DNN Platform/Connectors/Azure/Components/Constants.cs
- DNN Platform/Providers/FolderProviders/AzureFolderProvider/App_LocalResources/Settings.ascx.resx
- DNN Platform/Providers/FolderProviders/AzureFolderProvider/AzureFolderProvider.cs
- DNN Platform/Providers/FolderProviders/AzureFolderProvider/Constants.cs
- DNN Platform/Providers/FolderProviders/AzureFolderProvider/Settings.ascx
- DNN Platform/Providers/FolderProviders/AzureFolderProvider/Settings.ascx.cs
- DNN Platform/Providers/FolderProviders/AzureFolderProvider/Settings.ascx.designer.cs
- DNN Platform/Providers/FolderProviders/DotNetNuke.Providers.FolderProviders.csproj
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2697
After some investigation we found it loads Azure content using very small batches of data in a loop. On every Azure folder click, system synchronizes content and makes huge amount of iterations to upload all files. See:
https://github.com/dnnsoftware/Dnn.Platform/blob/99686770464291109629a62c8d0611dbe5b2ec0a/DNN%20Platform/Providers/FolderProviders/AzureFolderProvider/AzureFolderProvider.cs#L159
To improve performance, I added `SyncBatchSize` setting which is now available on UI. It is possible to configure size of batches to load from Azure in one call. Customer can make it configured to their needs, smaller values means we will need more round trips to fetch all files, large numbers will potentially lead to timeouts in case …
> Digital Assets: Azure folders are slow to open

- DNN Platform/Library/Common/Initialize.cs
Removed the lookups for prior versions of .NET Framework that are no longer possible for the operation of DNN Platform after the upgrade to 4.7.2 as a platform requirement in 9.4.0
Renamed private static methods to properly indicate their dependence on a specific .NET Framework type.
Added support for the identification of .NET Framework version 4.8 display.  Additionally left a note for the reference list for future updates.
Fixes #2710
> Correction of .NET Framework Version Determination

- DNN Platform/Providers/FolderProviders/AzureFolderProvider/AzureFolderProvider.cs
- DNN Platform/Providers/FolderProviders/Components/BaseRemoteStorageProvider.cs
Fixes a bug in ea26f8356df3efeb874653e9b7b3b92813c158de.
When the **Sync Batch Size** parameter is left blank, it's saved as an empty string instead of a null string. And empty strings throw an error when cast to integer.
1. Login as Host
2. Open Persona Bar > Manage > Global/Site Assets
3. Add New Folder Type > Set up Azure Folder Provider (**leave Sync Batch Size blank**)
4. Add New folder with Azure Folder type
5. Synchronize the folder and subfolders
Following error occurs:
> Fixed bug in Azure folders

- DNN Platform/Modules/DDRMenu/Localisation/Apollo.cs
- DNN Platform/Modules/DDRMenu/Localisation/Ealo.cs
DDR Menu included localization support for two third-party solutions; EALO and Apollo.  Both of these products are no longer supported and the respective implementations DO NOT work in 9.x DNN.
Given that neither solution works, these methods have been flagged for special removal in version 10.0 to be completed alongside all other breaking changes.
Fixes #2724
> Addition of Obsolete Attribute to DDR Localisation Implementations

- Build/Cake/create-database.cake
- Build/cake/unit-tests.cake
- Build/cake/version.cake
- build.cake
- devfactory.yml
- gitversion.yml
This pull request should change the build labels for pull requests to -pr from -PullRequest, release* to -rc, and other branch as -unstable.
> update version labels for various build types / branch names

- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/UserRequest/IPAddressFamily.cs
- DNN Platform/Library/Services/UserRequest/IUserRequestIPAddressController.cs
- DNN Platform/Library/Services/UserRequest/UserRequestIPAddressController.cs
- Website/DesktopModules/Admin/Authentication/Login.ascx.cs
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2691
In this RP I extended existing mechanism to read IP address from request. Default IP remains IPv4, nothing is changed in terms of application functionality and public API's. Only thing is now it is possible to extract IPv6 from request. I used it just for the admin logs purposes when user is logging in. So administrators can now check logs and determine IPv6 addresses. 
See how does it look:
> IP is missing in the logs when user request comes with IPv6 

- DNN Platform/Website/Install/Cleanup/09.04.00.txt
- DNN_Platform.sln
Closes #2740 
Issues #2716  and #2729 accounted for new installations (delete old licenses and then update them to today's reality), but that did not cover the upgrade scenario, this PR solves that and deletes the old license files upon upgrade.
> Removes old license files upon upgrade

- Website/DesktopModules/Admin/Security/EditUser.ascx
- Website/DesktopModules/Admin/Security/EditUser.ascx.cs
If Data Consent is enabled a user must be offered the same deletion choice as when they consent. So this PR covers the scenario when a user has already consented but wishes to delete their account.
> Unregister user to use same logic as in Data Consent

- Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Data.SqlDataProvider
Closes #2743 
This PR splits the creation of rows in the Lists table into 500 item batches intead of a single bath with more than 5000 lines. This is to prevent a timeout issue during installation on some environments.
> Splits the Lists table population in 500 items batches

- DNN Platform/Library/Data/SqlDataProvider.cs
`GetAzureCompactScript` doesn't appear to be required any longer for azure compatibility and it adds quite a bit of overhead to every single sql query run through the Platform. This PR removes the check and removal of the following strings. 
`WITH\\s*\\([\\s\\S]*?((PAD_INDEX|ALLOW_ROW_LOCKS|ALLOW_PAGE_LOCKS)\\s*=\\s*(ON|OFF))+[\\s\\S]*?\\)`
`(TEXTIMAGE_)*ON\\s*\\[\\s*PRIMARY\\s*\\]`
> Remove GetAzureCompactScript from SqlDataProvider

- DNN Platform/Library/Services/Installer/Installers/ResourceFileInstaller.cs
- DNN Platform/Library/Services/Installer/Util.cs
Adjustments to the installer process to resolve issues with Resource File Installation impacting users on Azure (Fixes #2766).
A few highlights on the changes included
* Cleanup of resource management when writing files inside of the zip loop
* Adjustment of retry logic, making two changes
*  Adjustment of the retry to attempt for 3.5 seconds, rather than only 1 second for a better opportunity to process the file
*  Changing the file share process to allow others to read/write the file.  Rather than just write
This should allow real-time items to read the file, even if we are writing to it.  Which should resolve the lock issues.
> Correction of File Access Issues

- Build/Tools/NuGet/DotNetNuke.Providers.FolderProviders.nuspec
- Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
Fixes: #2684 
Added icon URL and project URL for the following nuspec files that were missing:
* DotNetNuke.Providers.FolderProviders
* DotNetNuke.WebApi
> Fixed nuspec to include Icon & Project URL

- DNN Platform/Library/Services/Installer/Util.cs
This is an additional fix for #2766 
Upon further testing, thanks to @meetmandeep, it has been determined that the locking behavior was actually introduced by the codes prior attempts to delete the file, and then immediately write it.  This is due to the file structures used in azure.
Given that the code that copies files in other locations are using overwrite options, which are safe, and supported, I removed the "Delete" call from the method.  This has been tested already in Azure and has reliability resolved the issues.
> Additional Installer Fix for Azure

- Website/Install/Config/09.04.00.config
fixes: #2788 
Adds upgrade script to update the targetFramework elements in the web.config to be .NET 4.7.2. This is needed to properly upgrade websites to 9.4 as .NET 4.7.2 is introduced in the new version
> Added DNN Upgrade script for 9.4: .NET 4.7.2

- DNN Platform/DotNetNuke.ModulePipeline/ModuleControlPipeline.cs
- DNN Platform/DotNetNuke.Web.Mvc/MvcModuleControlFactory.cs
- DNN Platform/DotNetNuke.Web.Razor/RazorModuleControlFactory.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/UI/Modules/BaseModuleControlFactory.cs
- DNN Platform/Library/UI/Modules/Html5/Html5ModuleControlFactory.cs
- DNN Platform/Library/UI/Modules/IModuleControlFactory.cs
- DNN Platform/Library/UI/Modules/ReflectedModuleControlFactory.cs
- DNN Platform/Library/UI/Modules/WebFormsModuleControlFactory.cs
Fixes: #2780 
Removed MVC specific code from the shared ModuleControlPipeline. Added extension point using inheritance in the `BaseModuleControlFactory` which is inherited in each specific module pattern. This creates a special extension to have module specific code.
CC: @bdukes
> Removed MVC Specific Code from ModuleControlPipeline

- DNN Platform/Connectors/GoogleAnalytics/App_LocalResources/SharedResources.resx
- DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
- DNN Platform/Connectors/GoogleAnalytics/Scripts/connector.js
- DNN Platform/Connectors/GoogleAnalytics/connector.htm
- DNN Platform/Library/Services/Analytics/GoogleAnalyticsEngine.cs
This PR fixes #2782 and also implements `AnonymizeIp` and `TrackUserID` settings in Google Analytics.
> Google Analytics: TrackAdmin, AnonymizeIp, and TrackUserID Support

- DNN Platform/Connectors/GoogleAnalytics/App_LocalResources/SharedResources.resx
- DNN Platform/Connectors/GoogleAnalytics/Connector.css
- DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
- DNN Platform/Connectors/GoogleAnalytics/Scripts/connector.js
- DNN Platform/Connectors/GoogleAnalytics/connector.htm
- DNN Platform/Library/Services/Analytics/GoogleAnalyticsEngine.cs
When the `DataConsentActive` property is true, we will always set the google analytics configuration for `anonymizeIp` to `true`. Then in the admin ui, we disable the checkbox and display a notice that this setting is automatically enforced when data consent is enabled.
> Google Analytics: Toggle Anonymize IP when DataConsent is Enabled

- DNN Platform/Library/Common/Globals.cs
- DNN Platform/Library/Entities/Modules/ModuleSettingsBase.cs
- DNN Platform/Library/Entities/Modules/PortalModuleBase.cs
- DNN Platform/Library/Properties/AssemblyInfo.cs
- DNN Platform/Library/Services/Authentication/AuthenticationConfigBase.cs
- DNN Platform/Library/Services/Authentication/AuthenticationLogoffBase.cs
Fixes: #2794 
Marks the `Globals.Common.DependencyProvider` as internal and only accessible within the Core Libraries of DNN. Web Forms modules now contain a protected instance of the `DependencyProvider` which gives Web Forms developers access to the Service Locator since Dependency Injection does not work with the Web Forms Modules.
This will couple the Service Locator with the lifetime of the Web Forms module and prevent developers from abusing the Service Locator.
```C#
public partial class MyView : PortalModuleBase
{
protected IMessageService MessageService { get; }
public MyView()
{
MessageService = DependencyProvider.GetService<IMessageService>();
}        
}
```
```C#
public partial class MySettings : PortalModuleBase
{
protected IMessageService MessageService { get; }
public …
```
> Marked DependencyProvider as Internal

- DNN Platform/HttpModules/Users Online/UsersOnlineModule.cs
- DNN Platform/Library/Data/DataProvider.cs
- DNN Platform/Library/Entities/Host/Host.cs
- DNN Platform/Library/Entities/Users/Membership/UserMembership.cs
- DNN Platform/Library/Entities/Users/UserController.cs
- DNN Platform/Library/Entities/Users/Users Online/AnonymousUserInfo.cs
- DNN Platform/Library/Entities/Users/Users Online/BaseUserInfo.cs
- DNN Platform/Library/Entities/Users/Users Online/OnlineUserInfo.cs
- DNN Platform/Library/Entities/Users/Users Online/PurgeUsersOnline.cs
- DNN Platform/Library/Entities/Users/Users Online/UserOnlineController.cs
- DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
- DNN Platform/Library/Security/Membership/MembershipProvider.cs
- DNN Platform/Tests/App.config
Back in DNN 8.x, or earlier, the UsersOnline HttpModule was removed from the default installations of DNN.  The configuration settings and actual source code for this feature were left inside the platform, however, they have not been tested or supported.
As such, the methods supporting this are legacy and no-longer properly managed.  To follow the published deprecation standards, since no prior notice was given.  I've flagged all implementation methods for the UserOnline feature for removal in v11.0.0.  
The DNN Community initiative, which has the supplemental UsersOnline module, could easily extract this code and install as an extension, which would be the preferred long-term solution as it.
One additional change was included, to update the configuration file on a UnitTest project to …
> Addition of [Obsolete] Attribute to Users Online

- DNN Platform/DotNetNuke.ModulePipeline/DotNetNuke.ModulePipeline.csproj
Fixes: #2806
Fixes the build process to force copy the correct NET472 assembly of `DotNetNuke.ModulePipeline`. 
This project is our first multi-targeting library for both net472 and netstandard2.0 which will help us migrate to .NET Core. The project will not register any `System.Web` objects if it is build against netstandard 2.0 (see snippet below). Since it was copying the netstandard2.0 library it was not properly registering the `IModuleControlFactory`
DI Registration Code
```C#
public void ConfigureServices(IServiceCollection services)
{
// MULTI-TARGETTING PIPELINE
// -------------------------
// This file multi-targets .NET Framework and .NET Standard,
// which is needed as DNN migrates to .NET Core. The 'NET472'
// pre-processor directives are to fully support Legacy DNN.
// As …
```
> Fixes Build Process for DotNetNuke.ModulePipeline to Copy Correct NET472 Assembly

- DNN Platform/Library/Common/Globals.cs
- Website/Default.aspx
After discussion in TAG meeting May 21st: this rolls back Async and a change made on Nov 8 2018 to the way NavigateUrl gets the locale for a tab/page.
> Fix for #2809 and #2760 and #2778

- Website/DesktopModules/Admin/Authentication/Login.ascx.cs
Issue #2749 documents a loss of display of the authentication provider when using a non-standard DNN Provider when the DNN Provider is not included.
It appears that Pull Request #1897 moved the location whereby the login control is displayed, this changed the behavior that resulted in any custom providers not displaying unless the DNN.
This PR reverts that portion of this change.  Long-term, this might not be the best solution, but this should restore functionality for users in the time being.
For those on 9.3, 9.3.1, or 9.3.2 a temporary workaround would be to remove the `Visible="false"` from line 13 of /DesktopModules/Admin/Authentication/login.ascx
> Fix for Custom Authentication Providers

- README.md
We switched pipelines with v9.4.0, and this just updates the badge to the correct url so show successful build status on the homepage of the project.
> Updating DevOps badge URL

- DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
Fixes #2823
I also combined both if statements into a single statement, as I didn't see the need to check schema != null twice.
> check if terms fields exist before reading from datareader

- SECURITY.md
This is just a copy of the content from https://www.dnnsoftware.com/community/security/security-center.  We may want to look at adjusting the security process to make use of GitHub's new functionality.
The template for the security policy also has a section about supported versions, but I wanted to start with what's there, and then we can add.  Here's a rough sketch of some content we might want to consider:
>
>## Supported Versions
>
>Only the latest release of DNN Platform receives security patches.  We do make an effort to provide workarounds or backports of patches when possible.
>The last release of DNN Platform 10.x is intended to be marked as a Long Term Support (LTS) version, which will receive official patch support while ongoing work continues on later versions.
>
>| Version …
> Add GitHub security policy

- DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/Templates/Web/Module - HTML/template.ascx
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2853
Issue caused due to wrong path to the View.html file. Module is created dynamically from templates and is saved to the `DesktopModules\_OWNER_\_MODULE_` folder, where _owner_ and _module_ are names provided by the user when creating module.  
See demo of the fix: [DEMO](https://drive.google.com/file/d/1Yk1w-y4h-Oh95AW9RcCmmjRb0CUpSqvw/view?usp=sharing)
> View.html file is not rendered via Module Creator update

- DNN Platform/Library/Common/Globals.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/FileSystem/Exceptions/InvalidFilenameException.cs
- DNN Platform/Library/Services/FileSystem/FileManager.cs
- Website/App_GlobalResources/Exceptions.resx
We should be checking all filenames for illegal characters. This is now done right after a check of illegal extension.
> Filename illegal characters check

- DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
- DNN Platform/Connectors/GoogleAnalytics/Scripts/connector.js
Right or wrong the connectors infrastructure only supports passing strings as config values. Knockout has a strange behaviour where it treats any string as true and empty strings as false. However we get back from the connector UI either "true" or "false" for some reason. This PR handles this difference of behaviour when sending and receiving the settings for boolean values.
I have tested that it saves "false" or "true" in the database and that this PR restores the module UI problem, however I am not sure then where those database values are used, so testing that could be nice :)
It also adds a confirmation on save since that part was missing compared to the Azure Connector.
> Fixes an issue with the boolean values in the Google Analytics Connector

- DNN Platform/Library/Services/Mail/Mail.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Mail/MailTests.cs
Fixes #2899
Set AlternativeView.Encoding with bodyEncoding
- This is to ensure AlternativeView encoding is always consistent with bodyEncoding and not relying on the body text
- Extract the code to AddAlternateView method to allow UTs
Notes: UT covered existing behavior even not part of the changes. Minor fix to the existing test method (ConvertToText_removes_styles_including_css_defs) 
Confirmation Video - https://drive.google.com/file/d/1tiz3ce6gJtVrD4ZclsRX-Z3PDaryFbSr/view
> Missing encoding in email alternate view

- DNN Platform/JavaScript Libraries/Knockout/Knockout.dnn
- DNN Platform/JavaScript Libraries/KnockoutMapping/KnockoutMapping.dnn
- DNN Platform/JavaScript Libraries/Selectize/Selectize.dnn
- DNN Platform/JavaScript Libraries/jQuery/jQuery.dnn
- DNN Platform/JavaScript Libraries/jQueryMigrate/jQueryMigrate.dnn
- DNN Platform/JavaScript Libraries/jQueryUI/jQueryUI.dnn
Redo of previously submitted PR #2912  that got messed up.
Closes #2904 
Removes a duplication of license files already in the Licenses folder but also put there by the installer.
> Removes duplication of license files for javascript libraries

- DNN Platform/Library/Common/Globals.cs
When ensuring a file name is valid should also ensure we're getting the regex options right.
> Ensure proper regex matching

- Build/Cake/unit-tests.cake
When running tests, the following error occurs:
>VSTest: Could not locate executable.
https://github.com/cake-build/cake/issues/1522#issuecomment-341612194 indicates that there's an issue using VS 2019, and presents a workaround to find the correct path
> Fix error running unit tests

- DNN Platform/Library/Entities/Tabs/TabController.cs
Partially Fixes #2919 (There are total 2 PRs; for the other PR, you can check: https://github.com/dnnsoftware/Dnn.AdminExperience/pull/1099 ).
A new overload which accepts an additional parameter named as "includeDeletedChildren" is added. (retargeted to "9.4.x" branch, you can reach the previous PR which was targeted to "development" branch from here: https://github.com/dnnsoftware/Dnn.Platform/pull/2920 )
Demo: https://drive.google.com/open?id=1yg6OuVuLMbwCbBlFHXDqQa8Abd3WPIn_
Note: This PR should be merged BEFORE https://github.com/dnnsoftware/Dnn.AdminExperience/pull/1099
> DNN-31366 - Deleted page can still be selected as parent page

- Build/Cake/unit-tests.cake
- DNN Platform/Library/Entities/Tabs/TabController.cs
The referenced changes have already been approved. Since this is a release management task we are self approving the merge without any reviews.
> Update development with fixes from v9.4.0-rc

- DNN Platform/DotNetNuke.DependencyInjection/Extensions/TypeExtensions.cs
Closes #2952 
Previously if one type in an assembly was failing, all the types of that assembly where ignored by the startup code. This PRs fixes this and returns all the other types to prevent odd behaviours.
> Allows loading dependencies during startup even if one fails

- gitversion.yml
Updating GitVersion to properly set up the build for 9.4.1 versioning.
Per the published policies, this is in support of continuous development and will be self merged.
> Updated to Version Properly for 9.4.1

- DNN Platform/DotNetNuke.Web.Razor/DotNetNukeWebPage.cs
Fixes: #2997 
The DDRMenu supports multiple types of rendering engines. The razor engine which uses `.cshtml` files leverages the DNN Razor3 Module Platform. When we implemented Dependency Injection for 9.4.0 this was added to every module platform including the Razor3 Module Pattern (which is used by DDRMenu Razor).
When running a page that uses DNN 9.4.0 the Razor Menu would completely disappear, which is documented in #2997. This was discovered when installing the default theme for nvQuickTheme.
Copied screenshot from #2997 for convenience
In DNN 9.4.0 we updated the constructor of any Razor3 module's `DotNetNukeWebPage<T>` to resolve the model if it is included in the IoC DependencyProvider. This provides simple DependencyInjection for this deprecated module pattern. 
**As part of …
> Fixes DDRMenu Razor Bug with Dependency Injection

- DNN Platform/Library/Services/FileSystem/Providers/StandardFolderProvider.cs
> DNN-32726: avoid null reference exception when call to Globals.LinkClick method.

- DNN Platform/Modules/DigitalAssets/ClientScripts/dnn.DigitalAssets.js
Fixes #2958 
For loop should start at the second element since the first element (root) is already expanded and handled before. This is a retargeted PR, you can reach the original PR from https://github.com/dnnsoftware/Dnn.Platform/pull/2959
Demo: https://drive.google.com/open?id=199i4weckQqh4odCwyU8KThuQoflIZ7kP
> DNN-30542 - Asset Manager activity wheel constantly spins

- DNN Platform/Library/Services/Exceptions/ExceptionInfo.cs
Fixes #2972
After change applied:
> Add missing HTML encoding to ExceptionInfo

- DNN Platform/Library/Services/Installer/XmlMerge.cs
- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/MergeFiles/ShouldPreserveEmptyNamespaceOnSaveMerge.xml
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/MergeFiles/ShouldPreserveEmptyNamespaceOnSaveTarget.xml
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/XmlMergeTests.cs
- DNN Platform/Website/Install/Config/08.00.00.22.config
- DNN Platform/Website/Install/Config/08.00.00.30.config
The background for this issue is documented in #2971.  This PR fixes a bug that can be introduced when using `collision="save"` with an incorrectly created XML Merge file.  This can result in an element with a namespace being replaced by an element that has the namespace reset (e.g. `<dependentAssembly xmlns="">`), resulting in that element being ignored.
> Fix potential XML namespace bug

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
Upon upgrading, this PR will find invalid binding redirects (i.e. `<dependentAssembly xmlns="">`), and remove them from the `web.config` (since they weren't doing anything anyway).  If a valid `dependentAssembly` element also exists, then that's all that's done, but if it doesn't, and new `dependentAssembly` is added with a binding redirect for the version in the `bin` folder.
I'm still in process of testing this, but thought I'd push it as a PR in case someone wants to pick it up and run with it this weekend.
Not sure if we want to try to get this in 9.4.0 or hold for 9.4.1, but this'll need adjustments if we hold it.
Fixes #2971.
> Fix invalid binding redirects when upgrading to DNN 9.4.0

- Build/Tools/NuGet/DotNetNuke.Core.nuspec
With the introduction of Dependency Injection with the DNN 9.4.0 release, a reference to the DependencyInjection package should be added
> Correction to DotNetNuke.Core NuGet Package

- DNN Platform/Library/Framework/JavaScriptLibraries/IJavaScriptLibraryController.cs
- DNN Platform/Library/Framework/JavaScriptLibraries/JavaScript.cs
- DNN Platform/Library/Framework/JavaScriptLibraries/JavaScriptLibraryController.cs
This exception is occurring on sites upgraded to DNN 9.4.0 when opening module settings, because the `DnnComboBox` class in use on module settings loads the _Selectize_ library, which will now have two versions installed.
Fixes #2993
> Fix exception loading JS library

- DNN Platform/Library/Services/Upgrade/Internals/Steps/IISVerificationStep.cs
- Website/Install/App_LocalResources/Installwizard.aspx.de-DE.resx
- Website/Install/App_LocalResources/Installwizard.aspx.es-ES.resx
- Website/Install/App_LocalResources/Installwizard.aspx.fr-FR.resx
- Website/Install/App_LocalResources/Installwizard.aspx.it-IT.resx
- Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
- Website/Install/App_LocalResources/Installwizard.aspx.resx
- Website/Install/UpgradeWizard.aspx.cs
Closes #2990 
Adds a check in the existing IIS configuration step to make sure that .Net Framework 4.7.2 at least is installed. This is the first step for both installs and upgrades so that the upgrade does not continue if that condition is not met and users can just re-fire the upgrade after doing windows updates without needing to restore and all that...
> Warns before install/upgrade about needing .Net Framework 4.7.2

- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Users.Web/src/_exportables/package.json
- Dnn.AdminExperience/yarn.lock
fs is a core package, and the version on the npm registry is just an
empty package; this was almost certainly added accidentally
Fixes #3091
> Remove reference to empty fs npm package

- DNN Platform/Library/Entities/Content/Taxonomy/Term.cs
Fixes #2955 
If "System.Net.WebUtility.HtmlDecode" returns the same value as the input, it will cause an infinite loop because of the while loop. There are no needs for a while loop here since it's enough for "System.Net.WebUtility.HtmlDecode" to work only once.
Demo: https://drive.google.com/open?id=1nG5P1_drh8Ncx-AvwNcSDI1MANxAz9Ve
Note: This is a retargeted PR, the original one was #2956
> Infinite loop occurs in vocabularies

- DNN Platform/DotNetNuke.Web/InternalServices/NewUserNotificationServiceController.cs
- DNN Platform/Library/UI/Skins/Skin.cs
- Website/App_GlobalResources/SharedResources.resx
- Website/Resources/Shared/scripts/dnn.jquery.js
new PR on behalf of #1999 to set target to 9.4.x branch
> DNN-7818: add send verification mail link in unverified message.

- DNN Platform/Website/Templates/Blank Website.template
The blank template provides now permissions for the default portal folders `[root]`, `Users` and `Templates`. Fixes [Fnl#64](https://github.com/DNNCommunity/DNN.FormAndList/issues/64)
> Permissions for default folders

- DNN_Platform.sln
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.csproj
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Module.build
- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/Module.build
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Module.build
Closes #3166 
This fixes some missing commits from the merge of the persona bar into this repository and restores ability to build a working site.
For people reviewing this, please try the following before approving.
1. `git clone -b fix-merge-build https://github.com/valadas/Dnn.Platform`
2. open powershell as admin and run `./Build.ps1`
Let it build then verify the following
** Status should be clean **
`git status` should show nothing to commit (providing there was no build errors that stopped the build midway in which case, you should run `git reset --hard` and try again fixing what caused the error.
** You should have 4 zips in the Artifacts folder **
Try a clean install.
Try an upgrade.
Verify the Persona Bar works and gets 9.4.2 version
Verify the Edit Bar works
> Fixes errors with previous build scripts following PB merge

- .github/BUILD.md
- .github/ISSUE_TEMPLATE/bug-report.md
- DNN Platform/Website/Templates/Blank Website.template
Updates the issue templates as per the release of 9.4.1
Updates the build instructions as per the merge of Admin Experience into this repository.
> Updates issue templates and build docs

- DNN Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs
Fixes: #2687 
Adjusts OAuthClientBase implementation to prevent thread abortion code. This allows the OAuthClientBase to properly return the status code to the caller and adds additional extension points to custom Auth Providers.
I checked the history on this change and it dates prior to the migration to git so I can't find the reason why we were aborting the thread. This was discussed awhile back in #2687 and we agreed this change would be a good thing to do for the Auth Provider
> Remove Thread Cancellation from OAuthClientBase Implementation

- Website/DesktopModules/Admin/SearchResults/dnn.searchResult.js
Fixes #3184 
Code change was the removal of showing the message when no search operation was a actually performed. Previously the code showed the message and stopped further processing. As of now it just does not show the message if no search is performed and also does no further processing.
[Demo Video](https://drive.google.com/file/d/1pxE-Cx1u_K3-zduZdqgIwo-KeyF1Vj8f/view?usp=sharing)
Created after **closing #3185** which was approved but closed because it was opened against "develop" branch and not "release/9.4.x".
> Do not show "No Search results" message when no search is performed.

- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Servers.Web/src/components/Tabs/tabs.less
> Make white-space visible in log viewer

- Website/controls/user.ascx
Email address is at the bottom below password.  when you have to enter in the captcha code you have to scroll up to get to enter password again.  would be nice not to have to re-enter passwords as this is an issue as well but at least the email address is below the username field with this pull request if accepted.
NOTE:  I wish I could move "Display Name"  below User Name but this is where the bio registration fields go so no way to really move this easily.
If you have Email as Username set the email address is at the bottom making a user enter passwords first and I can't find any other website that does this.  However email address under Username is more industry standard I believe for a registration form.
> Move email above username field.

- DNN Platform/Library/Services/Sitemap/SitemapBuilder.cs
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2819
See demo: [DEMO](https://drive.google.com/file/d/1ewxm5j7-fvbOeey1CZpac9A3xcMrFBgY/view?usp=sharing)
To validate generated sitemap, there is a bunch of validators available. Validation requires sitemap.xml to be available on public. To pass xml from local environment to public, I generated sitemap locally and mock xml response using [mocky.io](https://www.mocky.io/). Passing public URL to the validator does the trick. No issues detected.
Please be noted, adding `xhtml:link` tags makes xml broken to be displayed in browser, however, document parses correctly in a sitemap validators and looks as per official google documentation, see [Sitemap](https://support.google.com/webmasters/answer/189077) chapter.
> Sitemap.aspx does not produce alternate links in multilingual website

- DNN Platform/Library/Entities/Modules/DesktopModuleInfo.cs
- DNN Platform/Library/Services/Installer/Installers/ModuleInstaller.cs
Please refer to Issue #2885 
Also PR #2886 2886 is the same as this, but was originally made against a 9.3.2 branch causing a minor conflict. This PR has been closed in favor of this one.
A very simple change to the DesktopModule installation logic allowing multiple DesktopModules in a single Package.
> Closes Issue#2885: Allow multiple DesktopModules in a single package

- DNN Platform/Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2621
I didn't find any reason why we replace username in database on login event. There is a well-working mechanism to get user object by email, so then we use it's username property to authenticate it.
See demo: [demo](https://drive.google.com/file/d/1PMVgt31AbgT83WX8iKFopL_OUYjgTZyg/view?usp=sharing)
This is a clone of https://github.com/dnnsoftware/Dnn.Platform/pull/2622. The difference is that this PR is targeted to development branch.
> Username is changed to email address in the user profile

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
- DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
- DNN Platform/Modules/HTML/dnn_HTML.dnn
Two issues are being addressed in this PR:
1. When installing the installer skips the Install/Library folder. No packages in there are currently being installed when first installing DNN.
2. The HTML and DA modules have a dependency on the Web.Deprecated package. The current type of "Package" means they don't actually get checked during install and will therefore not get sorted after that dependency has been installed. Changing this to "ManagedPackage" solves the issue and DNN correctly installs them towards the end.
> Fix to installer and the dependencies of the HTML and DA modules

- DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
When installing an assembly type component, the code automatically creates the assembly bindings, the previous manifest did it also manually in a config merge component which under some situations caused upgrades to hang at this step.
One one to reproduce is to install clean Dnn 9.4.1 and upgrade to 9.4.2. This removes the extra config merge and resolves the upgrade issue.
> Fixes an upgrade issue that affects 9.4.1 => 9.4.2 upgrades

- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpAdminController.cs
Fixes
https://github.com/dnnsoftware/Dnn.Platform/issues/3168
https://www.dnnsoftware.com/forums/threadid/86505/scope/posts/change-portal-administrator-email-address
I may get shot down here but it is worth a try.   Thanks for the dnndocs.com it helped me find some things I was looking for. I found a typo there I will submit a fix for as well.
Please help me if I went wrong here it just didnt make sense the way it was written when setting the To and From addresses nothing referenced the portal administrator email.  And the send to address it feels to me like it should be going to whoever is logged in testing it so they can see it works.
I also am not sure if this actually uses the email being set in Host SMTP Settings.  For testing the emails this is where it needs set so any changes to …
> Fixes #3168 Test Sending Email Issues

- DNN Platform/Modules/DigitalAssets/ClientScripts/dnn.DigitalAssets.js
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/3250
Summary: 
There is a dnnCheckbox control that needs to be updated according to the selected items. If no one item is selected, we should remove `dnnCheckbox` class, otherwise , if all items selected, add this class. 
Confirmation video: [DEMO](https://drive.google.com/file/d/1qXSI2pNX0mQNrlT2j6B5wX9Oaf7TXTUO/view?usp=sharing)
> DNN-29110 Site Assets > Select All is not working

- DNN Platform/Website/DesktopModules/AuthenticationServices/DNN/Login.ascx
Moves Remember Login above Login and Cancel buttons on the login form.
Fixes issue #2471 and part 4 in #3255
moved UI for setting the Remember Login checkbox above Login Cancel buttons
> Moves Remember Login above Login Button:  referenced in issue #2471 #3255

- DNN Platform/Library/Data/DataProvider.cs
- DNN Platform/Library/Services/Search/Entities/SearchDocumentToDelete.cs
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/3259
Summary:
I added `ToJsonString()` explicitly to the base class to avoid inconsistency between base and a child `ToString()` implementations. Newly created method will be invoked when writing JSON to database regardless of a data type that comes to API. 
I also left previous implementations as it is since they are shared and may be used in other places.
> Search scheduler is failing when trying to delete removed objects

- DNN Platform/Library/Services/FileSystem/FolderManager.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FolderManagerTests.cs
Fixes #3248 
I added the recursive delete option for the nested folders too.
Demo: https://drive.google.com/open?id=1lMUHbr2-tcj8vVMXPZvhucO0eMuvqEQI
> DNN-32474 - Not able to delete custom roles if their associated social group folder isn't empty

- DNN Platform/Library/Entities/Users/Profile/UserProfile.cs
Moved country above region to help resolve any issues from trying to set the region prior to setting the country might be concerned.
https://github.com/dnnsoftware/Dnn.Platform/issues/2140 I can reference this issue but I will not say it will fix it.  But it makes more sense to have it show up here in this file so I propose the change.
> Move Country Above Region in UserProfile.cs

- Build/Cake/thirdparty.cake
Small fix to scripts. The main CI logic goes through UpdateDnnManifests. The local dev stuff should not do this. Only if specifically requested by developer.
> Ensure UpdateDnnManifests doesn't run for building dev site

- DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
Closes #3318 
Supersedes #3319 
The TrackingId should be uppercase to work with Google Analytics.
> Google Analytics TrackingID is stored in lowercase #3318

- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Containers/PersonaBarContainer.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Dnn.PersonaBar.Library.csproj
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Startup.cs
Fixes #3328 
This makes `PersonaBarContainer.Instance` property use DI to build the returned object instead of simply newing up a `PersonaBarContainer` instance.
This allows third-party apps to register PB container derived classes with DI and override the default PB container.
> Registered IPersonaBarContainer with DI

- .github/APPROVERS.md
- README.md
Ensure it is clear and transparent how this works
> Document approval process and group

- Build/Cake/nuget.cake
Fixes #3330
Relaxes the GetFiles filter so that it also includes **Dnn.PersonaBar.Library.nuspec** file.
> Relaxed nuget.cake wildcard to include all packages in folder

- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/Components/Pages/PagesControllerImpl.cs
Fixes #3358 
Code change was to add additional check of ScopeId with the current PortalID during the determination of vocabulary for which the tags are being added. Previously since this check was missing it used to pickup any first Vocabulary of type PageTags irrespective of the portal it is being created in. This caused tags to be assigned to vocabulary in wrong portal.
[Demo Video](https://drive.google.com/file/d/1SAy0V680VadfYP-ga3ixk50OzmIgNBdV/view?usp=sharing)
> Create PageTags in correct vocabulary scope

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.04.04.SqlDataProvider
Adds the required 09.04.04.SqlDataProvider file to allow upgrades to 9.4.4 to work. This is a release management task and we are self-approving it for that reason.
> Adds sqldataprovider for 9.4.4 upgrades

- DNN Platform/Library/Entities/Urls/UrlRewriterUtils.cs
This is a rebase of #3340 onto `release/9.4.x` for @engineering87
Closes #3339
>  Add safe access to UrlReferrer in Log404

- DNN Platform/Library/Entities/Portals/PortalSettings.cs
Currently when setting the TimeZone property on the PortalSettings object it will persist to the database and clears the cache. This is obviously not a good idea. The front end already sets the TimeZone when an admin changes the value in the site settings personabar module.
> Make sure TimeZone doesn't store to database just by setting the prop

- DNN Platform/Website/Resources/Shared/stylesheets/dnndefault/7.0.0/default.css
- DNN Platform/Website/Resources/Shared/stylesheets/dnndefault/8.0.0/default.css
#3387
allows a form message to use 100% of the area it is presented in.
will now look like 
if accepted as a solution.
> dnnFormMessage 100% width fix

- DNN Platform/Library/Entities/Portals/PortalAliasExtensions.cs
- DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
Fixes #3395
Fixes #3017 
Fixes #2841 
This pull request fixes wrong redirections that occur on Canonical and None URL mappings.
I have tested this as much as I could. I created following spreadsheet to track my tests and make sure this change does not introduce new regressions:
https://docs.google.com/spreadsheets/d/1c9DyWfLAG5qrAnPDZsvAg5VBJkSRWBciWtPxHARxWUA/edit?usp=sharing
Above spreadsheet contains:
Tab | Description
-- | --
DNN943 | A set of test URLs along with the expected and the actual responses when executed on DNN 9.4.3. Red colors on the right show cases where the response is not correct, as per my understanding. In such cases the Severity column shows 1 (minor issue) or 3 (big issue).
Patched | Same set of test URLs but with responses after applying this fix. Green colors in …
> Fixed Canonical and None mapping redirects

- DNN Platform/Library/UI/UserControls/User.cs
- DNN Platform/Website/DesktopModules/Admin/Security/Register.ascx.cs
#3371 #3372
Moves Email above Username in User.ascx.cs to match order of Users.aspx
Moves Registration Email Field above Username on the Registration Form.
> Moves Email + Display Name on Registration Form & Email in User.ascx file above Username/Password on 

- Build/Tools/NuGet/Dnn.PersonaBar.Library.nuspec
- Build/Tools/NuGet/DotNetNuke.Abstractions.nuspec
- Build/Tools/NuGet/DotNetNuke.Bundle.nuspec
- Build/Tools/NuGet/DotNetNuke.Core.nuspec
- Build/Tools/NuGet/DotNetNuke.DependencyInjection.nuspec
- Build/Tools/NuGet/DotNetNuke.Instrumentation.nuspec
- Build/Tools/NuGet/DotNetNuke.Providers.FolderProviders.nuspec
- Build/Tools/NuGet/DotNetNuke.SiteExportImport.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Client.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Deprecated.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Mvc.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.nuspec
- Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
Fixes #3411 by removing the <iconUrl> node from all NuGet specifications to match documentation
> Fixed NuGet package specification

- .github/BUILD.md
> Revised build documentation

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/App.jsx
- Dnn.AdminExperience/ClientSide/Pages.Web/src/utils.js
Fixes #1116
Summary
When the script got loaded the first time, a wrong page id was getting sent in the XHR request which caused this issue (there were multiple page requests being sent and the order of responses for that requests play an important role in this bug's intermittent occurrence).
Demo: https://drive.google.com/open?id=1RvwR04B8iPrDdqrMAInCK3N0kN1cWMe2
Note: This is the copy of the PR in https://github.com/dnnsoftware/Dnn.AdminExperience/pull/1117
> DNN-29164 - Open page settings can't display data for correct page

- DNN Platform/Modules/Journal/module.css
To resolve Issue #2225 plus issue #2981 
Dedicated to enhance the Journal Module Styles for the Journal UI.
- This PR Expands Journal Editor and Comment Areas to use 100% Width of Site Theme Module Container Width.
- This PR Adds Visibility Setting to Save Space for for Closing Items Replacing Display Setting for Journal Close Items as Needed to Keep Text from Shifting When Hovering Mouse Pointer Over a Journal Item.
- This PR Adds Word Break Feature in the Journal  and Link Author, Titles, Description and Comment Areas.
- This PR Adds Inline-Flex to Author Links
- This PR adjusts author image area margin allowing more screen use.
- This PR Removes Border and Padding from Author Images.
- This PR Removes borders from Journal Link Images.
- This PR Adds Responsive Effect to Journal Link …
> Journal Links + Comments Word-Break and Resizing

- DNN Platform/Library/Entities/Modules/ModuleController.cs
Fix the 'UpdateModuleSetting' method in ModuleController refactoring the update module conditions.
Issue https://github.com/dnnsoftware/Dnn.Platform/issues/2868
Modified the update conditions, removed the 'settingExist' variable and check directly the settings value.
> Fix UpdateModuleSetting in ModuleController

- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FolderManagerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/Constants.cs
Adds FolderManager unit tests that cover #3392.
> Added FolderManager unit tests

- Build/Cake/ci.cake
- Build/Cake/compiling.cake
- Build/Cake/packaging.cake
- Build/Cake/version.cake
* Removes the hardcoded tools version 2017 which prevented building if you only have Visual Studio 2019 and never had 2017
* Automates the generation of the xx.xx.xx.sqlDataProvider file to prevent and upgrade loop if we forget to create that file.
Closes #3296
> Automates generation of .sqlDataProvider file

- Dnn.AdminExperience/ClientSide/Seo.Web/src/components/sitemapSettings/providerRow/index.jsx
- Dnn.AdminExperience/ClientSide/Seo.Web/src/components/sitemapSettings/providerRow/style.less
Fixes #3425
Fix enabled-icon to display properly
Increase the width to 46px = 16px (height size) + 30 px (padding left
and right)
Fix to display priority as None if override priority is false
Confirmation video - https://drive.google.com/open?id=1G4jDqp_pM3CZrMqgaNWM42hUDctygqNr
Notes: This PR is migrated from https://github.com/dnnsoftware/Dnn.AdminExperience/pull/1066
> DNN-26060 fix sitemap settings display develop

- DNN Platform/Library/Services/Localization/Localization.cs
Fixes #3444
When adding new languages, I'm adding following fallback logic to select the base URL for the new aliases:
1) pick first culture-neutral, primary alias
2) pick first culture-neutral, non-primary alias
3) just pick the first one (the strategy before this change)
> Fixed alias of added language

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Connectors/scripts/Connectors.js
Fixes #3448 
Since the other connector names are in single word (except Amazon S3), this situation is specific to the connector names with multiple words because it was resetting the displayName property by the name property which can be different from the displayName (like "Azure" and "Azure Storage") so that it's bound to the correct property now.
Demo: https://drive.google.com/file/d/1ArAiSShbeg6cd5chSysR2RPxLYrX3kvy/view
> DNN-35360 - Azure Storage connector changes its name on disconnect

- DNN Platform/DotNetNuke.Web/Api/StandardTabAndModuleInfoProvider.cs
Current logic ignores module's status when finding it
> Fix module find logic in module attribute

- DNN Platform/DotNetNuke.Web.Mvc/MvcHostControl.cs
> Get the module id from query string correctly when redirect mixed case option enabled.

- Build/Cake/version.cake
When specifying a version in settings.local.json the build was not successful due to a missing buildNumber in the Cake scripts.
> Fix to custom version building

- Build/Cake/version.cake
- build.cake
The version used will be parsed from the solutioninfo.cs. This is done using a new method in the CakeUtils library.
> Ability to entirely switch off the versioning mechanism.

- Build/Cake/ci.cake
- Build/Cake/compiling.cake
- Build/Cake/database.cake
- Build/Cake/devsite.cake
- Build/Cake/packaging.cake
- Build/Cake/settings.cake
- Build/Cake/version.cake
- build.cake
This PR will make the default cake build avoid:
1. Creating NuGet packages
2. Tweak the checksum of default.aspx
The advantage is that this avoids unnecessary work and avoids potential mishaps for people building locally. You can still call the CI build using the target BuildAll.
> Separate out CI from local package build

- gitversion.yml
Right now gitVersion will default to 9.4.5 because we bump the last digit (patch) since the last tagged release (9.4.4) on the develop branch. Since we know the next version we will release is 9.5.0, if we need to have sql scripts in that release, they will be 9.5.0 versioned and will not run during install or upgrade since everything else would be versioned 9.4.5. 
This PR sets next-version to 9.5.0 for that reason.
What this means is that CI will default to 9.5.0 for the develop branch until we actually release and tag 9.5.0, after that time it will go back to it's normal behaviour of bumping the patch number as it does now. This affectes only CI and if the local settings for version is set to "auto".
> Ensures we can use 09.05.00.SqlDataProvider scripts

- DNN Platform/Website/DotNetNuke.Website.csproj
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.05.00.SqlDataProvider
Fixes #3367
Excludes Console and Module Creator from `SetCorePackageVersions` stored procedure.
> Fixed Console and Module Creator installation

- DNN Platform/Library/Entities/Portals/PortalSettings.cs
- DNN Platform/Library/Services/FileSystem/Providers/StandardFolderProvider.cs
This is a duplicate of @roman-yagodin's #3528 which was merged into `development` instead of `develop`.
Closes #2850
(cherry picked from commit 143b1879cccc222e3a1b39f676d4676b4598ee7a)
> Don't expose file last modifed date/time via cachebusted URLs

- DNN Platform/DotNetNuke.Web.Mvc/DnnMvcDependencyResolver.cs
- DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
- DNN Platform/DotNetNuke.Web.Mvc/Extensions/StartupExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Startup.cs
- DNN Platform/DotNetNuke.Web/Api/Extensions/StartupExtensions.cs
- DNN Platform/DotNetNuke.Web/Api/Internal/DnnDependencyResolver.cs
- DNN Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs
- DNN Platform/DotNetNuke.Web/Common/LazyServiceProvider.cs
- DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
- DNN Platform/DotNetNuke.Web/Startup.cs
- DNN Platform/HttpModules/DependencyInjection/ServiceRequestScopeModule.cs
- DNN Platform/HttpModules/DotNetNuke.HttpModules.csproj
- DNN Platform/HttpModules/packages.config
- DNN Platform/Library/Common/Extensions/HttpContextDependencyInjectionExtensions.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/DependencyInjection/IScopeAccessor.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/Internals/DnnDependencyResolverTests.cs
Fixes #3513 
* Added a HttpModule (ServiceRequestScopeModule) that handles DI's request scope lifetime.
* This enables scoped service resolutions for WebForms, MVC and WebApi.
* It also stores the created scope inside the HttpContext.Items for easy access. This can be useful for vendors to access the request scope.
* Setup the ServiceRequestScopeModule as part of the Application_Start initialization.
* Register the WebApi controllers in the DI container.
Used example from https://github.com/dotnet/aspnetcore/issues/3172 as inspiration.
TODOs: 
* Properly include the `ServiceRequestScopeModule` HttpModule through the web.config, get rid of `PreApplicationStartMethod` assembly attribute in `ServiceRequestScopeModule` and the `Microsoft.Web.Infrastructure` package. The module should be the …
> Fixed MVC dependency injection.

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeviewInteractor.jsx
Fix bug #3532 
- Update store method was repeating called for each tree view node with the same parameters.
- Optimize call to this update store method once per process as parameters remains constant.
**Measurements**
Action | Baseline (ms) | Baseline avg. | Improve (ms) | Improve avg. | Improvement
-- | -- | -- | -- | -- | --
Expand node | 59,358 | 59,227.80 | 6,032 | 5,685.60 | 10.42 X
-- | 59,573 | | 5,512 | | 
-- | 61,184 | | 5,631 | | 
-- | 58,579 | | 5,775 | | 
-- | 57,445 | | 5,478 | | 
Collapse node | 55,476 | 53,868.40 | 825 | 754.20 | 71.42 X
-- | 52,227 | | 695 | | 
-- | 54,076 | | 716 | | 
-- | 54,947 | | 794 | | 
-- | 52,616 | | 741 | |
> Performance improvement PersonaBar pages treeview on Expand/Collapse

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeviewInteractor.jsx
Fix bug #3534 
- UpdateStore method was repeating called for each tree view node with the same parameters.
- Optimize call to this update store method once per process as parameters remains constant.
**Measurements**
Action | Baseline (ms) | Baseline avg. | Improve (ms) | Improve avg. | Improvement
-- | -- | -- | -- | -- | --
on selection change | 54,622 | 53,314.60 | 456 | 349.00 | 152.76
-- | 53,091 | | 334
-- | 52,230 | | 309
-- | 54,076 | | 307
-- | 52,554 | | 339
> Performance improvement PersonaBar tree view node selection change

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.05.00.SqlDataProvider
thanks to @eugene-sea for bringing up and testing this issue.
> fix performance #3539

- Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/reducers/pagination.js
This PR improves Site Management (#3085) for setups with a lot of portals (>>50). 
Change is trivial as it just increases  the pagesize from 10 to 100. The  request will take now aout 100ms instead of about 30ms, which is still reasonable.
This should **not** close the linked issue. But it impoves the handling until a PR with pagination like in Eventlog is provided.  
Smaller setups with just a few portals will see a longer list.
> Increase pagesize for site management

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeview.jsx
- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/styles.less
Fixes #3090.
1. No longer truncates the page name. This means screen readers should be able to read the entire page name.
1. Handles the text-overflow using CSS.
1. Adds the page name to the `title` attribute of the list item. Most desktop browsers will show this when hovering over the page name.
1. Tightens up the spacing a little, so slightly longer page titles fit. I'm pretty sure there's more we can do here, but I think this is a decent start.
I've tested in latest Chrome, Edge (Chromium) and Firefox. Could do with testing in a wider variety of browsers.
> Persona bar: Show page title on hover, show more of long page titles

- .gitignore
Closes #3571
.gitignore was ignoring all files in 'src' folders, this was probably not noticed since it only affects new files and most PRs that came in since this change did not have new files.
> Updates .gitignore to include files in 'src' folders

- DNN Platform/DotNetNuke.Web.Mvc/Extensions/StartupExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Startup.cs
- DNN Platform/DotNetNuke.Web/Api/Extensions/StartupExtensions.cs
Fixes #3543 
This is a quick fix for the assigned issue.
This will allow vendors to add/replace controller registrations with their own.
The DefaultControllerFactory is also added to the ServiceCollection using the `TryAddSingleton` for the same reasons.
Fix AddWebApiControllers typo for AddMvcControllers.
> DI: Register MVC/WebApi Controllers using TryAddScoped.

- DNN Platform/Website/DesktopModules/Admin/Security/Register.ascx.cs
Fixes  #3157
Change is minor - if no displayname can be set directly, is must not be checked if it is valid.
> Fix for DisplayUserName

- DNN Platform/Modules/DnnExportImport/Components/Services/VocabularyService.cs
Fixes #3567
The terms import process was identifying hierarchical vocabularies by checking on the `ParentTermId` property of the `TaxonomyTerm` items. This is not correct because the root element of a hierarchical vocabulary doesn't have a parent element and yet it's a hierarchical item. So the root element was being imported as a simple term which affected the rest of the hierarchy.
> Fixed hierarchical terms import

- DNN Platform/Library/Entities/Portals/PortalController.cs
- DNN Platform/Website/DesktopModules/Admin/Portals/portal.template.xsd
Fix missing parsing of AllowUserUICulture and EnableBrowserLanguage settings from portal templates
> Fix missing parsing of AllowUserUICulture and EnableBrowserLanguage settings from portal templates #3558

- Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
- Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
- Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
- Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
- Dnn.AdminExperience/ClientSide/Pages.Web/package.json
- Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
- Dnn.AdminExperience/ClientSide/Roles.Web/package.json
- Dnn.AdminExperience/ClientSide/Security.Web/package.json
- Dnn.AdminExperience/ClientSide/Seo.Web/package.json
- Dnn.AdminExperience/ClientSide/Servers.Web/package.json
- Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
- Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
- Dnn.AdminExperience/ClientSide/Sites.Web/package.json
- Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
- Dnn.AdminExperience/ClientSide/Themes.Web/package.json
- Dnn.AdminExperience/ClientSide/Users.Web/package.json
- Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
- package.json
This was overlooked in the last Lerna/Yarn overhaul. The user must be able to target a local dev site with the Lerna build. It is currently missing as it only runs in production mode.
> Add debug build to lerna

- .github/ISSUE_TEMPLATE/bug-report.md
trivial adjustment without Issue.
I removed "Alpha build" from 9.5.0, added 9.5.1
I left 9.4.4 for the moment. We won't benefit from reports stating wrong number.
> Adjust version numbers

- DNN Platform/Library/Entities/Modules/ModuleController.cs
Fixes #3583 
The proposed solution ensures content is only decoded and sent to `IPortable.ImportModule` implementation of the bussiness controller. 
The rest of the `GetModuleContent` method schedules the non-decoded html content of the module for the next app start so that the static method `EventMessageProcessor.ImportModule` will decode it and import the module
> Fix bug #3583 for double Html decoding when using custom portal templates

- DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/InternalSearchControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/SearchControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/SearchHelperTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Mobile/RedirectionControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Urls/TestUtil.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/JwtAuthMessageHandlerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/StandardTabAndModuleInfoProviderTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/SearchServiceControllerTests.cs
- DNN Platform/Website/Install/DotNetNuke.install.config.resources
- Dnn.AdminExperience/ClientSide/Prompt.Web/src/__tests__/prompt/ui.test.js
According to descriptions in the blog, I have changed default mail change.me to changeme.invalid due to security issues.
https://medium.com/@SajjadPourali/do-not-use-internet-valid-domain-names-as-default-users-email-e-g-host-change-me-309213dffb8a
> change change.me to changeme.invalid

- DNN Platform/Library/Common/Utilities/NetworkUtils.cs
- DNN Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs
> get the real client ip address.

- build.cake
Closes #3613
As part of the build process we do a backup commit when the build starts
then we revert 1 commit up to bring back the files at excatly the point
they where before the build. This works nice when there are any files
to commit but not when there is nothing to commit.
This PR resolves that by adding the --allow-empty flag to the backup
commit.
> Fixes an issue with backup/restore in build

- Build/Cake/devsite.cake
- DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider.csproj
- DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/Properties/AssemblyInfo.cs
- DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
- Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
- package.json
This PR addresses these issues:
1. The new SimpleWebCachingProvider project wasn't pulling in the solutioninfo for versioning
2. The cake ResetDevSite task wasn't adjusting the version on items according to the settings
3. Add the missing watch task to the root package json
> Fixes to build process

- DNN Platform/Website/Resources/Shared/scripts/jquery/jquery.fileupload.js
Fixes #3630
The updated `jquery.fileupload.js` file changed the way it references the widget factory from this:
```javascript
if (typeof define === 'function' && define.amd) {
// Register as an anonymous AMD module:
define([
'jquery',
'jquery.ui.widget'
], factory);
} else ...
```
to this:
```javascript
if (typeof define === 'function' && define.amd) {
// Register as an anonymous AMD module:
define([
'jquery',
'jquery-ui/ui/widget'
], factory);
} else ...
```
and since this standalone `jquery-ui/ui/widget.js` file doesn't exist, it returns a 404, causing dependent modules to fail. The needed widget factory is actually included in the `jquery-ui.min.js` file.
After reverting this path, the module loads fine again:
> Fixed widget.js 404 error

- Build/Cake/database.cake
- Build/Cake/sql/create-db.sql
> Fix errors setting up dev site

- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Repository/PersonaBarRepository.cs
Note: This is the duplicate PR of https://github.com/dnnsoftware/Dnn.AdminExperience/pull/1126 . I do it again now since it wasn't merged here after Dnn.AdminExperience is migrated here.
Fixes https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1125
Summary
The problem lies in "Dnn.PersonaBar.Library.Repository.PersonaBarRepository.GetMenuItem(string identifier)" method which is called from "Evoq.PersonaBar.UI.Controllers.EvoqPersonaBarContainer.Initialize(UserControl personaBarControl)". GetMenuItem method doesn't exist in the StackTrace because JIT (Just-In-Time) Compiler does Inline Code Optimizations for release builds which basically means that some methods (especially like the ones that are only a few lines) get inlined into the previous method chain for performance reasons. …
> DNN-30135 - Issue when loading the Persona Bar: Not Thread Safe

- DNN Platform/Library/Services/Social/Messaging/MessagingController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Messaging/MessagingControllerTests.cs
> check message attachment's permission.

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/RoleGroupFilter/style.less
Replacing text-indent css property with margin-left, to insure wrapping text will all start at the same left position.
[Issue #3651](https://github.com/dnnsoftware/Dnn.Platform/issues/3651)
I've replaced the text-indent property in /Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/RoleGroupFilter/style.less to utilize the margin-left property to insure wrapping text will all start at the same left position.
I am unable to compile and test the code locally, but all in-browser tests on a production environment show this to be a successful modification.
When editing the file, I noticed two additional css modifiers (.text-with-page-icon, and .no-icon) that utilize the text-indent property. These appear to be conditional based on line 298 in …
> Fixes #3651 — UI/UX Dropdown page picker within Personabar 

- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ContentEditor.js
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ModuleDialog.js
Closes #2289
Changed dnnModuleDialog setModuleId function so that it saves the property _callFromExistingModule to cookie. In contentEditorManager, it's then possible to load that property back from cookie and use it to call apply function of dnnModuleDialog so that existing modules are not relocated.
Add a new page to an existing web site. Then add an existing module to that page and make sure to link it to original (no copy). Finally, add a new module to the page and put it in another pane (not the one where you put the existing module). Once the page as reloaded, all modules should remain in their pane. Without the fix, all the modules a relocated to the pane where you put the last module.
> Fixed the issue that caused all modules to be relocated to same pane

- DNN Platform/DotNetNuke.Web/InternalServices/FileUploadController.cs
- DNN Platform/DotNetNuke.Web/UI/WebControls/DnnFileUploadOptions.cs
- DNN Platform/Library/Common/Utilities/ValidationUtils.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/Personalization/PersonalizationController.cs
- DNN Platform/Website/Resources/Shared/components/FileUpload/dnn.FileUpload.js
> validate file upload request.

- DNN Platform/Website/admin/Modules/Modulesettings.ascx.cs
Fixes #3656
After installation, some modules have no entries in `TabModuleSettings` or `ModuleSettings`. This is the case for instance of the "CONNECT and PARTICIPATE" module in the home page. In such cases, a default value is calculated in `DNN Platform\Website\admin\Modules\Modulesettings.ascx.cs`.
The default value of "Allow Indexing" setting is `True`, as calculated at line 116 (`BindData` method):
```
chkAllowIndex.Checked = Settings["AllowIndex"] == null || Settings["AllowIndex"] != null && bool.Parse(Settings["AllowIndex"].ToString());
```
but at line 558 (`OnUpdateClick` method) the expression is different and generates a `False` default value:
```
var allowIndex = Settings.ContainsKey("AllowIndex") && Convert.ToBoolean(Settings["AllowIndex"]);
```
This bug then affects the …
> Fixed "Allow Indexing" module setting

- DNN Platform/Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
- DNN Platform/Website/DotNetNuke.Website.csproj
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.00.SqlDataProvider
This fixes issues #3658 and #3660 by 
1. allowing a superuser to also be returned from the GetSingleUserByEmail SPROC even though they might not ba a member of the portal.
2. Ensuring we user EffectivePortalId when looking up a user by email in the login logic
> Allow (super)users to log in to portals that have email as username

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.00.SqlDataProvider
Like the title says. Small addendum to previous PR #3664
> Improve portal groups logging migration script to log by default

- Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/siteAliasSettings/siteAliases/index.jsx
Fixes #3667
The `loadData()` method was being called in the wrong component events. I'm now calling `loadData()` in `componentDidMount()` and then in `componentDidUpdate()` only if selected website has changed.
> Fixed portal alias update on website change

- gitversion.yml
This updates gitversion.yml so that CI builds version 9.6.0
as we decided this would be the next version.
This is a release management task and we are self-approving
it for that reason
> Updates version to 9.6.0

- DNN Platform/Website/Install/Config/09.06.00.config
This PR disables additional Telerik features that are not used by DNN Platform.
This is a potential breaking change for anyone with third-party modules that are using Telerik functionality, however, it is NOT a breaking change for a base DNN Platform installation.
> Adjusted Telerik Bindings

- DNN Platform/Website/Install/Config/09.06.00.config
This PR fixes an incomplete push from #3671 disables additional Telerik features that are not used by DNN Platform.
This is a potential breaking change for anyone with third-party modules that are using Telerik functionality, however, it is NOT a breaking change for a base DNN Platform installation.
> Fixes #3671

- Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/Components/ExportPortal/index.jsx
- Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/Components/ExportPortal/style.less
- Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/Components/ListView/index.jsx
- Dnn.AdminExperience/ClientSide/Sites.Web/src/components/App.jsx
- Dnn.AdminExperience/ClientSide/Sites.Web/src/components/PortalList/index.jsx
Since the introduction of the PersonaBar we have lost the ability to export a portal template. This PR brings back a button on the site list that will take the user to a page from where the portal template can be created.
> Bring back Export Portal Template

- DNN Platform/Website/admin/Modules/Export.ascx.cs
When trying to export a module, we write a file to disk. If this fails the error the user sees is non-descript. This PR allows the error message to bubble up to the end user.
> Provide better feedback in export

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
- DNN Platform/Website/Install/DotNetNuke.install.config.resources
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.00.SqlDataProvider
- DNN Platform/Website/admin/Modules/Export.ascx.cs
- DNN Platform/Website/admin/Modules/Import.ascx.cs
Change the extension used for export/import of modules
> Fix for import/export

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/DatePicker/index.jsx
Fixes #3619
To be honest, I can't really explain the internals of why this code change fixes this issue. What I know is that the way modules are exported/imported evolved and now it's mandatory to specify the default object for modules like this one, which is essentially a directory on disk.
This fixes both the Users panel and the Roles panel.
> Fixed user role icons not showing

- DNN Platform/Website/admin/Modules/App_LocalResources/ModuleSettings.ascx.resx
Corrects some typos and errors in module settings localization files
This was submitted without an issue due to the obvious nature of these small changes.
> Corrects typos and errors in module settings resx

- DNN Platform/Website/admin/Modules/Export.ascx.cs
Fixes #3720
The validation message appears only if the folder dropdown's selected item is null, but this never happens because the "< None Specified >" item is selected by default, which has a value of `-1`. So I changed this to check whether the actual folder returned by the folder provider is null. This works for the "None Specified" item too.
> Fixed content export validation

- DNN Platform/Library/Common/Utilities/ValidationUtils.cs
- DNN Platform/Library/Services/FileSystem/FileManager.cs
- DNN Platform/Library/Services/FileSystem/IFileManager.cs
- DNN Platform/Modules/ResourceManager/App_LocalResources/ResourceManager.resx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/.eslintskipwords.js
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/actions/addAssetPanelActions.js
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FileDetails.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderDetails.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/FolderPicker.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/Item.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/DropZoneContainer.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/globals/api.js
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/services/itemsService.js
- DNN Platform/Modules/ResourceManager/View.ascx
- DNN Platform/Modules/ResourceManager/View.ascx.cs
This fixes this module which wouldn't work on a recent DNN version due to changes we made to the API. It also adds a client-side check to prevent non-suspecting users from uploading a file they're not allowed to.
> Fix resource manager to use the revised upload file handler in the core

- DNN Platform/Website/Resources/Shared/scripts/dnn.searchBox.js
Closes #3712
Due to jQuery 3.5.0 not supporting shortcuts to closing html tags in templates:
ie: `<div class="something" />` is no longer supported and needs to be rewritten as `<div class="something></div>`
This PR fixes those instances used in the jQuery code for the search results.
> Fixed an issue with search results page rendering

- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/releaseNotes.txt
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/releaseNotes.txt
Fixes #3739
I changed the text "DotNetNuke Professional Edition" to "DNN Platform"
> Change "Dotnetnuke Professional" to "DNN Platform" in 2 releasenotes.txt files

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/workflows/updateVersions.yml
- Build/Cake/unversionedManifests.txt
- Build/Cake/version.cake
Upon creation of a release/x.x.x branch, updates the following:
- Updates all versions in Dnn manifests
- Updates AssemblyInfo
- Adds RC to issue template
- Updates versions in package.json files
This can only be tested upon creation of a release
branch so we need to merge this before release/9.6.1 in order to test it.
Example usage in a copy of this repository:
Action: https://github.com/valadas/Dnn.Platform.Copy/runs/654270580?check_suite_focus=true
PR generated: https://github.com/valadas/Dnn.Platform.Copy/pull/20
> Adds action to automated versioning on RC

- .github/workflows/image-actions.yml
Our images-action workflow was referencing the master branch of the actions repositories.
The recommendation for github actions is to reference tags and not branches because branches can change at any time and be unstable. This might be the reason why we got many PRs that included a ton of images minification in different PRs.
This PR locks us on the latest version without subjecting us to "nightly builds"
> Locks versions of image-actions

- .github/workflows/updateVersions.yml
An issue was found where the action would run on any branch.
By mistake the filter was on just one of the steps
instead of the whole action.
This PR fixes that and applies the filter to the whole action.
This is a release management task and we are self-approving it for that reason
> Limit rc action to run only on release branches

- Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/editLanguagePanel/resourceEditor/fullEditor.jsx
Closes #3754
There was a breaking change with I believe raw-loader or file-loader
or svg-loader or some such, we already had 2 other similar PRs for
this same issue in other areas.
After that dependency update, I think in 9.5.0,
we now need to add `.default` at the end of svg imports.
This fixes the same issue in the language resources editor.
I did a search to find if we missed this in other spots and did not find
any other instance.
Also, as discussed in Slack, we would like to get this in 9.6.1-rc2 since we have so many contributors right now working on localization and this is a very small front-end only change.
> Restores icons in language editor

- DNN Platform/Website/App_GlobalResources/Exceptions.resx
Fixes some errors in exceptions localization
> Fixes some errors in exceptions localization

- DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/ModuleSettingsTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/NullableSettingsTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/TabModuleSettingsTests.cs
> Fix to settings saving in MVC modules

- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/Search/IndexingProviderBase.cs
- DNN Platform/Library/Services/Search/ModuleIndexer.cs
- DNN Platform/Library/Services/Search/SearchEngine.cs
- DNN Platform/Library/Services/Search/TabIndexer.cs
- DNN Platform/Library/Services/Search/UserIndexer.cs
Closes #3776
Please read the issue during review. This is what comes to mind, but if there are better ideas, I am open to them :)
Basically my idea is to deprecate the whole base class, created a new copy of it which has the recommended method enforced and the deprecated method optional. That way 3rd parties will be able to change class now and be ready BEFORE the required method is removed.
> Improves deprecation of search indexes

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PersonaBarPageHeader/index.jsx
- Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/App.jsx
Fixes #3690
Extend PersonaBarPageHeader component titleCharLimit yo better suit localized versions, 50 seems to be better here than component default 20.
> Fix weird shorting in site settings PB heading

- DNN Platform/Library/Services/Search/IndexingProviderBase.cs
Closes #3805
This is a followup on PR #3777
For context the deprecated class had the deprecated method required and the recommended one not required. PR #3777 deprecated the whole class for easier migration and reversed the required vs the non-required methods so developers can implement the new way without hacks or build warnings.
In that PR, a mistake was made on the deprecated method where we default to return null, but that caused a null reference exception on old modules. This PR replaces that return for an empty collection, which solves the same goal without an exception.
> Fixes a null reference exception with ISearchable

- DNN Platform/Library/Entities/Portals/PortalSettings.cs
- DNN Platform/Library/Services/Localization/LocalizationProvider.cs
An earlier "fix" for urls in emails added a blanket replace on each and every resource being retrieved. This is not just incorrect (as it also affects resources that should not be touched), it is also a performance hit.
This PR rolls back the fix and adds a "scheme" token to the portal settings. The [portal:scheme] token will resolve to either "https" or "http" depending on SSLEnabled for the portal. It is not used in any email in the framework currently, but if someone needs this in a template, it can be used.
Note that using the scheme token looks at the entire portal, so won't be a solution for those with mixed http/https situations. The [portal:fullurl] uses the current page's SSL setting, but obviously depends on context and so was never meant for emails.
> Fix random replacement of http with https in resources (issue #3599)

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpHostController.cs
Fixes #3813 
For Reference: logic was added here but only administrators got the fix... so this would be in addition to the following PR https://github.com/dnnsoftware/Dnn.Platform/pull/3237
In the above referenced PR the logic was created to send emails to the user using host or portal while logged in as administrator.
A second controller is used for host accounts which also needed the same logic to allow testing different portals SMTP settings while logged in as a host similar to how you can while logged in as an administrator currently.  
The same logic needs added to the host users SMTP test method that is being used for administrator SMTP tests as it is still utilizing the previous logic for the Send From and To variables that get set.
This PR puts the same administrator SMTP test …
> Use newer logic to send Host SMTP test emails

- DNN Platform/Website/Portals/_default/Blank Website.template.en-US.resx
- DNN Platform/Website/Portals/_default/Default Website.template.en-US.resx
Replaces `DNN Corp` in copyright for **Blank Website** and **Default Website** templates with `My Website` to make this more generic and user friendly.
Resolves #3715
> Replace DNN Corp copyright in Blank Website and Default Website templates with generic copyright

- .editorconfig
- stylecop.json
First follow-up to #3802 
I've added the default configuration inside `stylecop.json`, I'm going to propose some changes from the defaults as PR review comments, and we can try to come to a consensus.  There is also the option of [using a `ruleset` file to turn some rules off altogether](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#sharing-configuration-among-solutions).
I've also added an `.editorconfig` file, which is a mixture of the [`.editorconfig` file from StyleCop](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/.editorconfig) and the [`.editorconfig` files from `dotnet-format`](https://github.com/dotnet/format/blob/master/.editorconfig), with StyleCop "winning" where they conflict.  Some of the notable …
> StyleCop configuration

- DNN Platform/Library/Services/FileSystem/Providers/StandardFolderProvider.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/StandardFolderProviderTests.cs
Fixes #3838
Calling the `EncryptParameter(string, string)` overload instead of the `EncryptParameter(string)` overload because the latter invokes `PortalController.Instance.GetCurrentPortalSettings()` which is known to produce a `NullReferenceException` in the context of a Scheduler task.
> Fixed NullReferenceException when StandardFolderProvider is used in a Search provider task

- DNN Platform/Library/Entities/Portals/PortalController.cs
- DNN Platform/Website/DesktopModules/Admin/Portals/portal.template.xsd
- DNN Platform/Website/DotNetNuke.Website.csproj
The new portal templates include items in portal settings that were not yet included in the import. Items to do with Cookie Consent and Data Consent. This PR adds them to the schema that is used to verify a template and the code that imports the template.
> Fix portal template import

- DNN Platform/Library/Services/Social/Messaging/Scheduler/CoreMessagingScheduler.cs
The messaging dispatch scheduled task gathers and sends emails to users. However, it relies on GetString from localization without passing portalSettings. This means that portal overrides of the resx file (GlobalResources) are ignored. This PR fixes that.
> Fix to email template retrieval for messaging

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/AssetsPanelContainer.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/DropZoneContainer.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
- DNN Platform/Modules/ResourceManager/ResourceManager.dnn
- yarn.lock
This PR fixes the new resource manager to allow file uploads again
> Further fixes to RM

- DNN Platform/DotNetNuke.Web/InternalServices/FileUploadController.cs
- DNN Platform/DotNetNuke.Web/UI/WebControls/DnnFileUploadOptions.cs
> Update file upload validation

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/FileUpload/Browse/index.jsx
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/FileUpload/index.jsx
- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageDetails/PageDetails.jsx
- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageDetails/PageIcons/PageIcons.jsx
- Dnn.AdminExperience/ClientSide/Pages.Web/src/services/pageService.js
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
- Resolves about 200 Stylecop warnings
- Fixes an issue where filetypes where detected wrong from mimeTypes (for instance "application/svg+xml" was loogink for files named *.svg+xml" it now properly looks for *.svg files instead).
- Made the validationCode required in the FileUpload common component since it does not work without that prop.
- Fixes #3863 in a similar fashion as in #3769 but for the page icons.
> Fixed an issue where it was impossible to upload any icons in page settings.

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
Fixes #3866 in the same way as in #3865 and #3769
The validation code is also needed when creating a new page, not only when editing an existing page.
> Fixes an issue that prevented creating new pages

- DNN Platform/Library/Services/GeneratedImage/ImageHandlerInternal.cs
Fixes #3872
This error occurs when the image was already generated by `DnnImageHandler` in a previous request and now it's cached in the `~\App_Data\_imagecache` folder.
A quick workaround is to  switch server cache off, in the web config:
```xml
<configuration>
...
<appSettings>
<add key="DnnImageHandler" value="enableclientcache=False;enableservercache=False" />
...
```
but then of course all images are re-generated everytime.
As explained [here](https://stackoverflow.com/a/20080696) and [here](https://forums.asp.net/post/3970586.aspx), the problem is that the `System.Web.HttpResponseWrapper.TransmitFile(string)` method, followed by `Response.End()` produces the exception mentioned in #3872.
This sequence can be seen in code, in following lines: …
> Fixes exception when DnnImageHandler returns a cached response

- DNN Platform/HttpModules/Membership/MembershipModule.cs
JWT auth sets the thread identity to a "GenericIdentity". The membership module, when checking for having to log off a user, assumes the thread identity is a FormsIdentity. When the exception gets thrown the user is logged out. Hence all JWT traffic is broken. This checks for the type before casting it.
> Fix to membership module due to cast error when using JWT auth

- DNN Platform/Library/Services/Sitemap/CoreSitemapProvider.cs
Fixes #3896 
Non-indexed tabs should not be included in the sitemap. This effectively tells the crawler two different statements.  
The only change needed is to validate that the tab is supposed to be index prior to exporting it to the sitemap.
> Tabs that are not Indexed shouldn't be in the SiteMap

- DNN Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/Tokens/BaseCustomTokenReplace.cs
- DNN Platform/Library/Services/Tokens/BaseTokenReplace.cs
- DNN Platform/Library/Services/Tokens/CoreTokenProvider.cs
- DNN Platform/Library/Services/Tokens/TokenContext.cs
- DNN Platform/Library/Services/Tokens/TokenProvider.cs
- DNN Platform/Library/Services/Tokens/TokenReplace.cs
- DNN Platform/Tests/App.config
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Tokens/TokenReplaceTests.cs
- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
#3819. 
The token replacement code is very exposed through public and protected members. My implementation leaves all of those in place to avoid breaking existing functionality. Therefore, all the core tokenization code still lives in the BaseCustomTokenReplace, BaseTokenReplace and TokenReplace classes. 
If the provider is different than the CoreTokenProvider, it calls that provider instead. The CoreTokenProvider also has a simple implementation that calls the TokenReplace class. This is in case someone decides to use the provider instead of calling TokenReplace directly.
The changes I did also consolidate all parameters related to tokenization into a single TokenContext class that can be easily passed around.
Tested on DNN 9.6.1 with some simple scenarios and everything seems to work as …
> Implement a Token Provider interface

- DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnHelper.cs
I find myself including helper methods in all of my projects to do this. We have a control in web forms, but we don't have anything equivalent for MVC modules. This PR addresses that.
> Include CSS and JS CDF methods in the Dnn helper for Razor

- DNN Platform/Library/Services/FileSystem/FileManager.cs
- DNN Platform/Library/Services/FileSystem/IFileManager.cs
That prevented the buid from running
> Fixes 2 wrong merged conflicts resolutions

- DNN Platform/Library/Common/Utilities/Null.cs
- DNN Platform/Library/Entities/Tabs/TabInfo.cs
- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageDetails/PageDetailsFooter/PageDetailsFooter.jsx
- Dnn.AdminExperience/ClientSide/Pages.Web/src/services/pageService.js
Fixes #3918
This is both a back-end issue and a front-end issue.
Initially, when start/end datetime is null, and the user picks a datetime in the date picker, the front-end sends the datetimes correctly as UTC, and the back-end API saves the datetimes correctly in the database as UTC.
Later, during browser refresh, the `GetPageDetails` API is called, which fails to specify the `DateTimeKind` as UTC when filling the DTO from the database, and therefore the datetimes are serialized back as local datetimes, which produces the offset in the front-end.
At this point, if the user changes the datetime back to the original value, this time the date picker returns a `String` instead of a javascript `Date` object, and the TZ info is lost there, and the API then receives a local datetime. This sort …
> Enable Scheduling - Add TZ to page StartDate and EndDate

- DNN Platform/Library/Entities/Tabs/TabChangeTracker.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Tabs/TabChangeTrackerTests.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ModuleService.js
Fixes #3911
Fix summary: A differentiable exception is thrown now so that the message of the exception can be shown if the exception data includes "IsModuleDoesNotBelongToPage" bool; the exception type is not changed to not cause any regressions (some places might depend on that specific exception type). There is also another PR made (on an Engage repo) which checks the thrown exception in [SettingsController.cs](https://github.com/trilogy-group/Dnn.Evoq.Module.StructuredContent/blob/1bf07ddd58829befd455ae2d81806181e086bfd3/src/StructuredContent.Visualizer/Services/SettingsController.cs)
Demo: https://drive.google.com/file/d/10QAWw7IES9l3lY_nc-88r0LVsOGWx-ut/view?usp=sharing
> Visualizer not able to change settings in shared pages

- DNN Platform/Library/Common/Globals.cs
Fixes #3926
`Globals.Status` is only calculated once, but if it's an `Error`, we should try again.
> Retry determining Globals.Status if it was Error

- Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/siteLanguageSelector/index.jsx
Fixes #3922 
onSitechange(event) will invoke getCultureList method only if portalId is changed and prevent otherwise.
> Prevented unnecessary call to getCultureList method on website change

- DNN Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs
- DNN Platform/DotNetNuke.Web/DependencyInjectionInitialize.cs
- DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
- DNN Platform/DotNetNuke.Web/Prompt/ListServices.cs
- DNN Platform/DotNetNuke.Web/Startup.cs
- DNN Platform/Website/App_GlobalResources/Prompt.resx
This PR relies upon #3920.  
Fixes #3931.
> Add List-Services command to Prompt

- DNN Platform/Library/Entities/Tabs/TabInfo.cs
- DNN Platform/Library/Services/Search/TabIndexer.cs
- DNN Platform/Library/Services/Sitemap/CoreSitemapProvider.cs
Updated usage in TabIndexer.cs
Used same logic for check in CoreSitemapProvider.cs
Fixes #3901
Closes #3902 
Used same logic from TabIndexer by abstracting to a property on TabInfo and used in both TabIndexer.cs and CoreSitemapProvider.cs
> Abstracted AllowIndex logic into TabInfo property

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
The returned object was not scoped on a page object which caused the frontend to no read the proper object in GetPageDetails return.
Additionally stylecop fixes that were already done got missed by the conflict resolution.
new line 104 is the actual fix and everything else you see are missed stylecop fixes.
> Fixes a wrong merge conflict resolution that broke the pages module.

- DNN Platform/Website/DesktopModules/Admin/Security/EditUser.ascx.cs
All details of this change are shared via private email.
> Reset invalidation link on email change

- DNN Platform/Library/Services/FileSystem/FolderManager.cs
- DNN Platform/Modules/ResourceManager/Components/SearchController.cs
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/less/components.less
Add better wildcard search support
- Style correction for `Item Name` sort dropdown
- Corrected wildcard regex logic for SearchFiles
> Add better wildcard file search support

- DNN Platform/Library/Services/FileSystem/FolderManager.cs
This PR optimizes `WildcardToRegex()` to remove unnecessary start/end wildcard characters per comments on #3962.  Thanks to @bdukes for the RegEx tip!
Also, since `Replace(oldValue, newValue)` just returns the current instance unchanged if the `oldValue` is not found, I thought we could further optimize by removing the check for `*` or `?` in the search term.
> Optimize WildcardToRegex for file search

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/EditUrl.jsx
Fixes #3953 
Site alias is set to default only on create pages and not on edit pages.
Demo: https://drive.google.com/file/d/1q6RzNpwihqZ3QqIrbFx5adTAszMkPrg9/view?usp=sharing
> Issue-3953 - Default site alias comes as pre-selected on SEO URL edit page

- Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/FiltersBar/index.jsx
- Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/RoleEditor/RoleGroupEditor/index.jsx
Fixes #3949
The Edit and Delete icons next to the selected role group are components that are rendered within the dropdown, so the dropdown was intercepting all the bubbling clicks, and thus expanding.
This change adds the necessary `stopPropagation()` calls on the bubbling events so that the dropdown doesn't expand at the wrong times.
> Prevent Role Groups dropdown expand on delete

- DNN Platform/Modules/DnnExportImport/Components/Common/CompressionUtil.cs
Fixes #3964
DNN creates the export zip files in App_Data\ExportImport folder, but it does not add all necessary files at once. It closes and re-opens the zip file many times to add additional files. So DFS detects that the zip file is no longer locked and it starts replication. But then DNN attempts to open it again to add more files, and fails. All of this is noticeable only on large sites.
Typically, replication takes just a few seconds, so I used the `RetryableAction` to add a simple retrial mechanism to `CompressionUtil.OpenCreate(string)` to prevent such files from being skipped during export.
I'm targetting the `release/9.7.0` branch because `develop` is currently missing some important commits.
1) if decision is to approve and include this fix in 9.7.0, then this PR can be merged …
> Added retry to CompressionUtil.OpenCreate to prevent failures during site export

- .github/mergeable.yml
This PR adds a check to mergeable for the `Status: On Hold` label.
> Update mergeable to check for Status: On Hold label

- .editorconfig
> Standardize on CR/LF line endings

- gitversion.yml
Sets the maximum GitVersion lookup date to january 1st 2020 thus speeding up GitVersion calculations a lot. This means GitVersion will only look at commits from this year instead of well all the project history to find tags and read commit messages, etc.
> Improves GitVersion speed

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
Fixes #3979 
The popup message is changed from "Settings has been updated." to "Configuration has been updated." to avoid plural confusion with Settings vs Setting
> Popup message content changed to avoid plural confusion

- DNN Platform/Library/Services/Tokens/TokenReplace.cs
https://github.com/dnnsoftware/Dnn.Platform/issues/4003
TokenReplace was modified in a recent code change, which broke a functionality where the Module-provider didn't work any more - see #4003. 
There is a funny mechanism in the `TokenReplace` which caused wrong values to be used. The code starts like this:
```
/// <summary>
/// Gets or sets /sets the current ModuleID to be used for 'User:' token replacement.
/// </summary>
/// <value>ModuleID (Integer).</value>
public int ModuleId {
get => TokenContext.Module?.ModuleID ?? Null.NullInteger;
set => TokenContext.Module = GetModule(value);
}
```
Then in the GetModule this happens
```
private ModuleInfo GetModule(int moduleId)
{
if (moduleId == TokenContext.Module?.ModuleID)
return TokenContext.Module;
if (moduleId <= 0)
return null;
var tab …
```
> Fixes #4003 bug in TokenReplace getting Module by Id

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Attributes/RegistrationFieldsAttribute.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Constants.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/UpdateRegistrationSettingsRequest.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
DNN-41046: disallowed custom form without DisplayName and lacking a DisplayNameFormat
Fixes #3971 
Custom Registration Form without DisplayName field on it and lacking Display Name Format is no longer allowed and considered as incorrect configuration.
> Prevents creation of custom registration form without DisplayName and no DisplayNameFormat

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/FolderSelector.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/Folders.jsx
Somewhere in god knows which update of which dependency, the way to import svgs using raw-loaders changed and we have to add .default to the import. This PR solves that in the resource-manager module.
> Fixes 2 wrong svg imports in resource-manager

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderDetails.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/Permissions.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/AssetsPanelContainer.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/DropZoneContainer.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/globals/dnnSf.js
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/webpack.config.js
The frontend build of the new resource-manager had multiple warnings which this PR resolves (whitespace and unused vars or method parameters).
> Fixes frontend build warnigns in resource-manager

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/webpack.config.js
SVG files where present in the scripts folder on every build, those files should use raw-loader as the rest of our projects.
> Removes svg from resource-manager build

- DNN Platform/Library/Entities/Users/IUserController.cs
- DNN Platform/Library/Entities/Users/UserController.cs
- Fixed an issue with user management in portal groups
- Fixed many of the build warnings, there are a couple left about IPortalSettings vs PortalSettings which I did not fix because I think the correct solution would involve modifying other components so they can take IPortalSettings instead of PortalSettings and well, lack of time on that...
> Fixed an issue with user management in portal groups

- Dnn.AdminExperience/ClientSide/Vocabularies.Web/src/components/VocabularyList/RightPane/index.jsx
Fixes #4047
Several problems in this `findInChildren` function.
1) The `forEach` loop cannot be broken, so the `return` statement at line 19 was not actually exiting the function.
2) The initial value of `parentTerm` was an empty object, so if the item was not found, an empty object was being returned by the function. However, empty objects evaluate to `true`, not to `false`.
3) Since this is a recursive function, and because of 2), line 21 was deciding to continue instead of deciding to stop. This was causing the `parentTerm` variable to get incorrectly overwritten in following cycles.
I replaced this buggy function with a more clear implementation that immediately breaks the loop if the item is found, or returns `null` otherwise.
> Fixed bug with hierarchical vocabularies

- DNN Platform/DotNetNuke.Abstractions/Application/IHostSettingsService.cs
- DNN Platform/Library/Entities/Controllers/HostController.cs
- DNN Platform/Library/Obsolete/HostController.cs
Fixes: #4051 
Updated `Dictionary<>` references in the `IHostSettingsService` to use `IDictionary<>`
> Updated IHostSettingsService to use IDictionary instead of Dictionary

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/GridCell/index.jsx
- Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
- Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/HeaderRow/index.jsx
- Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/HeaderRow/style.less
- Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/index.jsx
- Dnn.AdminExperience/ClientSide/Users.Web/src/components/Body/index.jsx
This PR allows the user to click on the three column headers to sort by them (DisplayName, Email and Joined Date). Clicking again will invert the sort order.
> Implement clickable column headers on the users table

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeMenu.jsx
- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeview.jsx
- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/styles.less
Fixes #3960 
Pencil icon moved to the right ... menu. Only visible in Evoq and for unpublished pages.
Evoq rendering:
DNN Platform rendering:
> pencil icon moved to the right ... menu

- .github/BUILD.md
I have been chasing an issue for more time than I want to admit.
Ends up that after changing DNN_Platform.local.build you need to restart visual studio for it to take effect.
Thought it would be a good idea to document it for the next poor guy fighting this issue 😄
> Updates debug build documentation to indicate restarting visual studio

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/actions/folderPanelActions.js
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/TopBarContainer.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/services/itemsService.js
- DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/Dropdown/index.jsx
Wire up `Sync This Folder` and `Sync This Folder & Subfolders`.  It was tested by setting `EnableAutoSync = N` in `HostSettings` table.  Works like a charm.
> Wire up sync this folder and recursive

- DNN Platform/DotNetNuke.Abstractions/Application/IApplicationInfo.cs
- DNN Platform/DotNetNuke.Abstractions/Application/IApplicationStatusInfo.cs
- DNN Platform/DotNetNuke.Abstractions/Application/IDnnContext.cs
- DNN Platform/DotNetNuke.Abstractions/Application/IHostSettingsService.cs
- DNN Platform/DotNetNuke.Abstractions/Application/ReleaseMode.cs
- DNN Platform/DotNetNuke.Abstractions/Application/UpgradeStatus.cs
- DNN Platform/DotNetNuke.Abstractions/DotNetNuke.Abstractions.csproj
- DNN Platform/DotNetNuke.Abstractions/INavigationManager.cs
- DNN Platform/DotNetNuke.Abstractions/Portals/IPortalAliasInfo.cs
- DNN Platform/DotNetNuke.Abstractions/Portals/IPortalAliasService.cs
- DNN Platform/DotNetNuke.Abstractions/Portals/IPortalInfo.cs
- DNN Platform/DotNetNuke.Abstractions/Portals/IPortalSettings.cs
- DNN Platform/DotNetNuke.Abstractions/Prompt/ICommand.cs
- DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandHelp.cs
- DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandOption.cs
- DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandRepository.cs
- DNN Platform/DotNetNuke.Abstractions/Prompt/IConsoleCommand.cs
- DNN Platform/DotNetNuke.Abstractions/Prompt/IConsoleResultModel.cs
- DNN Platform/DotNetNuke.Abstractions/Prompt/IPagingInfo.cs
- DNN Platform/DotNetNuke.Abstractions/Settings/IConfigurationSetting.cs
- DNN Platform/DotNetNuke.Abstractions/Urls/BrowserTypes.cs
- DNN Platform/DotNetNuke.Abstractions/Users/IUserInfo.cs
- DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
- DNN Platform/DotNetNuke.DependencyInjection/Extensions/TypeExtensions.cs
- DNN Platform/DotNetNuke.DependencyInjection/IDnnStartup.cs
Fixes #4040 
This PR updates `DotNetNuke.Abstractions` and `DotNetNuke.DependencyInjection` to treat all build warnings as errors. This will help ensure a high level of code quality in these new projects.
> Treat Build Warnings as Errors for Abstractions & DependencyInjection Projects

- DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
- DNN Platform/Website/Install/Config/09.07.02.config
- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
Fixes #4044 
Allows ability to set mobile view cookie name.
I have been having issues with VS + Github so may need new setup to get that part right... please double check things for me if you can test the cookies are able to be set properly when this fix is applied.  0 build errors... but still something can go wrong for someone potentially please be sure this fix is acceptable.  I ended up just copying my changes into the GitHub browser... please again double check this will work please test for me if you can find time as I know it is something that needs tested.
Thank you everyone for help @bdukes deserves some credit here for the help thank again.
I was also thinking of changing out the comments which I had added you can edit as you please for any changes you desire.
And also in the …
> Ability to set mobile view cookie name in root web.config

- DNN Platform/Library/Common/ServiceScopeContainer.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Entities/Modules/PortalModuleBase.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/Internals/ServiceContainerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
Fixes #4046
Currently every PortalModule create its own service scope. This PR changes this behaviour by using the request scope when possible.
If a PortalModule is created outside ASP.Net (or the HttpContext was not available) it'll still create a new scope.
I've placed the unit test in the same directory as `DnnDependencyResolverTests` since I was not sure where to place it. If this is incorrect, place a comment and I'll move it 😄.
> Use request scope in PortalModuleBase

- Dnn.AdminExperience/ClientSide/TaskScheduler.Web/src/components/scheduler/schedulerEditor/index.jsx
- Dnn.AdminExperience/ClientSide/TaskScheduler.Web/src/utils/index.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/TaskScheduler/TaskSchedulerController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/TaskSchedulerController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.TaskScheduler/App_LocalResources/TaskScheduler.resx
Fixes #2961
This PR is a re-creation of dnnsoftware/Dnn.AdminExperience#1139 because it was lost during the merge of the Dnn.AdminExperience repo and didn't make it into Dnn.Platform.
Here's a live [demo](https://drive.google.com/file/d/1ejWztejmaB0j0KECZKXJM6074O7g9PWd/view).
> Warns admins about running search indexer on wrong server

- DNN Platform/Website/DesktopModules/Admin/SearchResults/module.css
These are very minimal changes to make the SearchResults page look more appealing, these are things that I seem to be repeating when creating a DNN installation and I'm sure that many other do too.
This PR is is a suggestion and there is no issues with it not being done, just thought I'd try and be helpful...
Please let me know if this will have a negative impact on the system.
Regards
Kieran
> Search Results UI Alignment changes

- DNN Platform/Library/Entities/Controllers/IHostController.cs
The deprecation warnings on `IHostController` recommend using a new interface, but that interface's name changed during the course of the PR, so it's now referencing a type that doesn't exist.
> Fix deprecation message referencing wrong type

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/Checkbox/style.less
Resolves #3912 
This PR resolves an annoying quirk where the `Accept License` checkbox jumps when checked (Extensions > Install Extensions).
> Resolve styling issue for checked Accept License checkbox in Extension installer

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/ScrollBar/styles.less
Closes #4107
This scopes the `container` styles inside the `area` class for the Scrollbars common component. It looks like this component is only used once in all our modules in the Pages module for the list of pages scroll area. I have done some testing and it looks all like before.
Before:
After:
> Fixed an issue where the React common components would interfere with container css class

- DNN Platform/Library/Services/Installer/Util.cs
- DNN Platform/Website/App_GlobalResources/SharedResources.resx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Constants.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/ExtensionsController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Extensions/App_LocalResources/Extensions.resx
Fixes #4114 
Upon further review, since version 8.0.0 it has been impossible to install, or uninstall Dashboard components.  However, there were lingering references.  Given this, I have opted in this PR to remove the references rather than simply flagging as there wasn't anything easily flaggable.  I can adjust if needed.
> Removal of references to the Dashboard Project Type

- .github/PULL_REQUEST_PROCESS.md
- .github/RELEASE_SCHEDULE.md
- .github/VERSIONING_POLICY.md
- NOTICE.md
This PR is a clean up of various bits of documentation included in the repositories.
* The listing of approvers
* Usage of the "on-hold" tag and Draft PR's
* Updated versioning policy
> DNN Platform Documentation Fixes
