dnnsoftware/Dnn.Platform

- Website/DesktopModules/Admin/Portals/SiteSettings.ascx.cs
See [DNN-6495](https://dnntracker.atlassian.net/browse/DNN-6495)
> DNN-6495 Display Friendly Name in Available Modules list

- Website/DesktopModules/Admin/Skins/EditSkins.ascx.cs
See [DNN-6417](https://dnntracker.atlassian.net/browse/DNN-6417)
> DNN-6417 Allow skin and container images to be png

- DNN Platform/HttpModules/Analytics/Config/AnalyticsEngineConfiguration.cs
- DNN Platform/HttpModules/MobileRedirect/MobileRedirectModule.cs
- DNN Platform/Library/Application/Application.cs
- DNN Platform/Library/Common/Utilities/Calendar.cs
- DNN Platform/Library/Common/Utilities/Config.cs
- DNN Platform/Library/Common/Utilities/HtmlUtils.cs
- DNN Platform/Library/Common/Utilities/NetworkUtils.cs
- DNN Platform/Library/Common/Utilities/UrlUtils.cs
- DNN Platform/Library/Framework/BaseHttpHandler.cs
- Website/Default.aspx.cs
Optimizations across the platform focused on improving the management of strings.  Use of StringBuilder, the proper instantiation of strings, as well as avoiding unnecessary allocations.
> Dnn 6560 string performance

- DNN Platform/DotNetNuke.Web/InternalServices/ModuleServiceController.cs
Added new web method to allow deleting tab modules.
Note: it has been introduced for integration testing purpuses.
> DNN-6557 - added web method to delete a tab module.

- SolutionInfo.cs
- Website/Default.aspx.cs
amended host copyright text and solutioninfo.cs date.
> DNN-6561 update solution files to reflect 2015

- Website/admin/Security/PasswordReset.ascx.cs
added code to validate user status and if necessary redirect them to login to force them to update their profile
> DNN-4213 SI: Profile field screen not appearing after New User resets password

- DNN Platform/Library/Entities/Urls/FriendlyUrlSettings.cs
See https://dnntracker.atlassian.net/browse/DNN-6282
> DNN-6282: Fixed URLRewriter to work with VS2013 browser link feature

- DNN Platform/Modules/HTML/App_LocalResources/Workflow.ascx.resx
Just a small typo - I don't think it deserve DNN JIRA ticket.
> Fixing typo in the resource file

- DNN Platform/Library/UI/Skins/Controls/LanguageTokenReplace.cs
This replaces the pull request https://github.com/dnnsoftware/Dnn.Platform/pull/251.
Please see https://dnntracker.atlassian.net/browse/DNN-6310 for more details.
> DNN-6310: Fixed DotNetNuke.UI.Skins.ControlsLanguageTokenReplace.NewUrl() to not remove query string parameters (except returnurl)

- DNN Platform/Modules/UrlManagement/App_LocalResources/SharedResources.resx
It is a simple and dirty job, but somebody has to do it :-)
> Missing Resource Keys - Site Settings

- Website/DesktopModules/Admin/Languages/App_LocalResources/LanguageEnabler.ascx.resx
in the help text. SImple change, but somebody has to do it. 
Good excercise for working with GitHub as well
> DNN-6404 There should be more meaningful word 

- DNN Platform/Modules/CoreMessaging/App_LocalResources/View.ascx.resx
Simple correction, but someone has to do it!
> DNN-5518 Communications field level help is inconsistent: textual correction

- Website/DesktopModules/Admin/HostSettings/hostsettings.ascx
See https://dnntracker.atlassian.net/browse/DNN-6625 for more details.
> DNN-6625: Fixed label association on page "Host > Host Settings"

- Website/DesktopModules/Admin/RecycleBin/recyclebin.ascx
See https://dnntracker.atlassian.net/browse/DNN-5849
> DNN-5849: Fixed canceling in "restore page confirm dialog"

- Website/Install/InstallWizard.aspx
See https://dnntracker.atlassian.net/browse/DNN-6284
> DNN-6284: Installation Wizard: Optimized number of requests to Install/installstatlog.resources.txt

- DNN Platform/Library/Framework/CDefault.cs
- DNN Platform/Library/Framework/PageBase.cs
- Website/Default.aspx.cs
See https://dnntracker.atlassian.net/browse/DNN-6285
> DNN-6285: Some string (performance) optimizations in DefaultPage (and base classes)

- DNN Platform/Library/Entities/Tabs/TabInfo.cs
optimization in TabInfo.CheckIfDoctypeConfigExists to avoid loading the doctype XML file from disk on each page load
> DNN-6287: Optimization for checking if doctype config exists

- DNN Platform/Library/Framework/PageBase.cs
See https://dnntracker.atlassian.net/browse/DNN-6289
> DNN-DNN-6289: Performance improvements in DotNetNuke.Framework.PageBase.ProcessControl()

- Website/DesktopModules/Admin/Extensions/PackageWriter.ascx.cs
Hi Guys,
I'm not sure if this requires further extension, but it certainly does ignore all git related things in the manifest build step.
Jira ticket for ref: [DNN-6297](https://dnntracker.atlassian.net/browse/DNN-6297)
> Ignore .git directory and .git* files in manifes build step

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
- DNN Platform/Website/Install/Config/Net45.config
added net45.config file to update web.config to .net 4.5
> DNN-6699 Upgrade DNN to .Net 4.5

- DNN Platform/HttpModules/UrlRewrite/BasicUrlRewriter.cs
See https://dnntracker.atlassian.net/browse/DNN-6278 for more details.
> DNN-6278: Fixed endless redirect loop in BasicUrlRewriter.RewriteUrl() if PortalAliasMapping=Redirect and no primary portal alias is defined

- Website/DesktopModules/Admin/Extensions/Install.ascx.cs
See https://dnntracker.atlassian.net/browse/DNN-6619 for more details.
> DNN-6619: Extension install wizard: Show proper validation error if corrupt zip file was uploaded

- Website/DesktopModules/Admin/Languages/App_LocalResources/LanguageEnabler.ascx.resx
- Website/DesktopModules/Admin/Languages/LanguageEnabler.ascx.cs
Updated Local Resource for Language Enabler.
Added check on urlFormat value in web.config. If using advanced, checkbox is disabled.
> DNN-6622- Hide Enable Language Parameter in URLs if using AUM.

- DNN Platform/Library/Entities/Urls/AdvancedFriendlyUrlProvider.cs
See https://dnntracker.atlassian.net/browse/DNN-6364 for more details
> DNN-6364: Improve AdvancedFriendlyUrlProvider.FriendlyUrl(...) to create https://-links to secure pages if SSL is enabled

- DNN Platform/Library/Entities/Urls/BasicFriendlyUrlProvider.cs
See https://dnntracker.atlassian.net/browse/DNN-6366 for more details.
> DNN-6366: Improve BasicFriendlyUrlProvider.FriendlyUrl(...) to create https://-links to secure pages if SSL is enabled

- Website/Default.aspx.cs
Enabled refresh metatag to be rendered only when in VIEW-mode.
> DNN-5834 - SI: Page Refresh Interval - Page does not refresh

- DNN Platform/Library/Entities/Portals/PortalSettings.cs
- DNN Platform/Library/Services/FileSystem/Providers/StandardFolderProvider.cs
- Website/DesktopModules/Admin/Portals/App_LocalResources/SiteSettings.ascx.resx
- Website/DesktopModules/Admin/Portals/SiteSettings.ascx.cs
- Website/DesktopModules/Admin/Portals/sitesettings.ascx
- Website/admin/Skins/Logo.ascx.cs
DNN-6562 - Add cache buster to uris for images and other resources accessed from the browser via a FileUrl
> DNN-6562 Browsercaching

- Website/DesktopModules/Admin/Tabs/Tabs.ascx.cs
See https://dnntracker.atlassian.net/browse/DNN-4679 for more details.
Please note: Beside the bug fix, this pull requests also includes some refactoreings.
The bugfix is changing
ShowPermissions(!tab.IsSuperTab && TabPermissionController.CanAdminPage());
to
ShowPermissions(!tab.IsSuperTab && TabPermissionController.CanAdminPage(tab));
in line 930 / 933.
> DNN-4679: Fixed displaying of permission section in page management module

- Website/Resources/Shared/scripts/dnn.jquery.js
Please see https://dnntracker.atlassian.net/browse/DNN-6600 for more details.
> DNN-6600: Fixed escape characters in DNN styled confirm dialogs

- DNN Platform/Modules/DigitalAssets/ClientScripts/dnn.DigitalAssets.js
See https://dnntracker.atlassian.net/browse/DNN-6107 and https://dnntracker.atlassian.net/browse/DNN-5857 for more details.
> DNN-6107: Fix URL in DAM "Get URL" popup

- DNN Platform/Library/Framework/JavaScriptLibraries/JavaScript.cs
- DNN Platform/Library/Services/Installer/Packages/PackageInfo.cs
[DNN-6662](https://dnntracker.atlassian.net/browse/DNN-6662)
>When requesting a JavaScript Library to be included on the page, its direct dependencies are also included on the page. However, any dependencies of those direct dependencies are not included.
> DNN-6662 Load full hierarchy of JS library dependencies

- DNN Platform/Website/Templates/Blank Website.template
- DNN Platform/Website/Templates/Default Website.template
Set the AllowIndex to false for 404 pages
> DNN-6636: Sitemap : Shows 404 Page in the Sitemap

- Website/DesktopModules/Admin/Languages/module.css
This is an alternative (and maybe better solution) for this pull request: https://github.com/dnnsoftware/Dnn.Platform/pull/257
> DNN-23079: Fixed DnnLanguageComboBox width in FF using module.css

- DNN Platform/Library/Security/PortalSecurity.cs
See [DNN-6493](https://dnntracker.atlassian.net/browse/DNN-6493)
> DNN-6493 Don't treat profanity filter values as regex

- DNN Platform/Library/Services/Mail/Mail.cs
Added From and Sender to the mail. Both use combination of email + displayname
> DNN-5373 SI: Email "From:" formatting

- Build_Install_Package.bat
- Build_Upgrade_Package.bat
- DNN Platform/Library/Entities/Portals/PortalAliasExtensions.cs
Reverts dnnsoftware/Dnn.Platform#266
> Revert "DNN-6163 - additional fix. "

- DNN Platform/Library/Entities/Tabs/TabController.cs
Added QueryString to the DeserializeTabUrls
> DNN-5904 Exporting a site with content doesn't save URL information

- DNN Platform/DotNetNuke.Web/Api/HMACAuthenticationAttribute.cs
- DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
- Website/admin/Skins/UserAndLogin.ascx.cs
add a HMAC Authentication Attribute
> DNN-6719 Create HMAC Authentication Attribute

- Website/DesktopModules/Admin/Languages/App_LocalResources/LanguageEnabler.ascx.resx
- Website/DesktopModules/Admin/Languages/LanguageEnabler.ascx.cs
Reverts dnnsoftware/Dnn.Platform#328
> Revert "DNN-6622- Hide Enable Language Parameter in URLs if using AUM."

- DNN Platform/Library/Services/Upgrade/Internals/InstallControllerImpl.cs
- DNN Platform/Library/Services/Upgrade/Internals/Steps/SynchConnectionStringStep.cs
Reverts dnnsoftware/Dnn.Platform#370
> Revert "DNN-6134 Compatibility with LocalDB"

- Website/Providers/DataProviders/SqlDataProvider/08.00.00.SqlDataProvider
Fixed up some issues in the sqldataprovider - appears to be other code related issues that need resolution
> DNN-6892 Errors in 08.00.00.SqlDataProvider file causing DNN8 installer to fail

- DNN Platform/Library/Services/Installer/Installers/AssemblyInstaller.cs
- DNN Platform/Library/Services/Installer/Util.cs
- DNN Platform/Website/Install/Config/BindingRedirect.config
- DNN Platform/Website/Install/Config/RemoveBindingRedirect.config
- Website/App_GlobalResources/SharedResources.resx
See [DNN-6797](https://dnntracker.atlassian.net/browse/DNN-6797) and http://www.dnnsoftware.com/voice/automatically-add-binding-redirect-when-installing-strong-named-assembly
> DNN-6797 Add binding redirect when installing strong-named assembly

- DNN Platform/HttpModules/Membership/MembershipModule.cs
Fixed issue where some of WebAPI requests was not authenticated, when IIS was working in "Windows Authentication" mode.
More info: https://dnntracker.atlassian.net/browse/DNN-6673
> DNN-6673: fixed issue

- DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
detected another issue when Fixing DNN-6743
> Fix DNN-6841 and DNN-6743

- DNN Platform/Library/Entities/Portals/PortalController.cs
- DNN Platform/Library/Services/Cache/CachingProvider.cs
this needs to be reverted as the fix should have been done in the 8.0.0 branch
> Revert "DNN-3000: add enable/disable cache expiration api."

- DNN Platform/Modules/DigitalAssets/ClientScripts/dnn.DigitalAssets.js
See https://dnntracker.atlassian.net/browse/DNN-6868
> DNN-6868: Fix action button visibility in DAM module

- DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
> Fix a typo in last PR

- DNN Platform/Providers/HtmlEditorProviders/RadEditorProvider/ProviderConfig.ascx.cs
assign selected value to the rblMode only if role exists on the current portal
> DNN-6840 SI : HTML Editor Manager Copy Configuration Issue

- DNN Platform/Website/Install/Config/07.04.01.config
- Website/development.config
- Website/release.config
This is a performance improvement discovered during load performance testing.
> DNN-6964 Add precondition="manageHandler" to Services module

- Website/Providers/DataProviders/SqlDataProvider/07.04.02.SqlDataProvider
Added missing placeholder for object qualifier
> DNN-6877 SI: Purge Schedule History

- Website/Providers/DataProviders/SqlDataProvider/07.04.02.SqlDataProvider
Notifications have NotificationTypeID, so I used that column to determine if message is a notification.
> DNN-6980 DismissAllNotifications deletes all user messages

- DNN Platform/HttpModules/Membership/MembershipModule.cs
fix for userinfo key duplicate based on the existing PR: https://github.com/dnnsoftware/Dnn.Platform/pull/519
,but with Resharper optimization
Tested on DNN AD enabled site (using latest build):
Auto sign in works correctly;
User gets created correctly on the initial sign in;
Sign out works correctly;
> DNN-6673 SI: WebAPI - Windows Authentication

- DNN Platform/Dnn.DynamicContent/DynamicContentType.cs
- DNN Platform/Dnn.DynamicContent/DynamicContentTypeManager.cs
- DNN Platform/Dnn.DynamicContent/IDynamicContentTypeManager.cs
- DNN Platform/Library/Entities/Portals/PortalController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/App_LocalResources/Manager.resx
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/Manager.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/contentTypes.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/dataTypes.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/util.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/ContentTypeController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/DataTypeController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/ViewModels/ContentTypeViewModel.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/module.css
- Website/Providers/DataProviders/SqlDataProvider/08.00.00.SqlDataProvider
This pull request combines two related features of the new DCC module
> DNN-6929 Add a Content Type and DNN-6930 Edit a Content Type

- Website/Install/Web.config
See https://dnntracker.atlassian.net/browse/DNN-6954
> DNN-6954: Disable caching for install client side resource

- DNN Platform/Library/Entities/Users/UserInfo.cs
See my comments in https://dnntracker.atlassian.net/browse/DNN-6990 for more details.
> DNN-6990: Replaced SharedDictionary with ConcurrentDictionary in UserInfo

- Website/DesktopModules/Admin/Vendors/EditAffiliate.ascx.cs
Please accept pull request that fixes incorrect VendorID passed in as AffiliateID.
> DNN-7053: Incorrect AffiliateID sent in email notification

- Website/admin/Skins/Language.ascx.cs
Jira Bug/DNN-7049 - Language DropDownList show Non Active language to
All Users
> DNN-7049: Language DropDownList show Non Active language to All Users

- DNN Platform/Dnn.DynamicContent/DynamicContentType.cs
- DNN Platform/Dnn.DynamicContent/FieldDefinitionManager.cs
- DNN Platform/Dnn.DynamicContent/IFieldDefinitionManager.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/App_LocalResources/Manager.resx
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/Manager.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/contentTypes.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/dataTypes.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/ContentTypeController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/ViewModels/ContentFieldViewModel.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/module.css
Most of the code to edit a content field was incorporated in the earlier PR #588  for adding a Content Field.  This PR includes some minor fixes as well as the code to delete a Content Field which was missed from an earlier PR #576 .
> DNN-6932 Edit a Content Field for a Content Type

- DNN Platform/Library/Services/Scheduling/DNNScheduler.cs
See https://dnntracker.atlassian.net/browse/DNN-7108
> DNN-7108: Fixed substring check in DotNetNuke.Services.Scheduling.DNNScheduler.CanRunOnThisServer

- DNN Platform/Dnn.DynamicContent/DynamicContentTypeManager.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/App_LocalResources/Manager.resx
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/Manager.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/templates.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Dnn.Modules.DynamicContentManager.csproj
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/TemplateController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/ViewModels/TemplateViewModel.cs
This pull request includes all the code to display a list of templates
> DNN-6938 View and Search Template list

- DNN Platform/Library/Entities/Urls/ExtensionUrlProviderController.cs
- DNN Platform/Library/Services/Installer/Installers/UrlProviderInstaller.cs
Fixed uninstall object reference not found error.
> DNN-3936: Uninstalling package with URL Provider errors

- Website/admin/Security/PasswordReset.ascx
Added an ASP:Panel element. Set the DefaultButton value to cmdChangePassword.
Tested and enter key will submit form.
> DNN-7064 - Reset password form should allow hitting enter key to submit

- DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
fix a few references where the assembly version and hintpath are out of sync
> Dnn 7124 - fix incorrect version references

- DNN Platform/Library/Entities/Content/Workflow/Repositories/WorkflowRepository.cs
- DNN Platform/Library/Entities/Content/Workflow/Repositories/WorkflowStateRepository.cs
- DNN Platform/Library/Entities/Content/Workflow/WorkflowStateManager.cs
https://dnntracker.atlassian.net/browse/DNN-7183
> DNN-7183: Typo in a hardcoded SQL query string in C# code

- DNN Platform/Library/Entities/Users/UserController.cs
- DNN Platform/Library/Entities/Users/UserEventArgs.cs
- DNN Platform/Library/Entities/Users/UserEventHandlers.cs
This is a modified pull request of https://github.com/dnnsoftware/Dnn.Platform/pull/580; see https://dnntracker.atlassian.net/browse/DNN-7098 for more detail.
>  DNN-7098: Added parameter sendNotification to UserController.UpdateUser()

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/Manager.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Components/BusinessController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Dnn.Modules.DynamicContentManager.csproj
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/dnn_DCCManager.dnn
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/packages.config
This minor fix - hides the DCC Manager's language selector when there is only one language.
> DNN-7194 The DCC Manager shows the language selector even when only one language

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Components/BusinessController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Dnn.Modules.DynamicContentManager.csproj
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/dnn_DCCManager.dnn
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/packages.config
Aded IUpgradable support to the Dynamic Content Creator Manager module so it is automatically added to the Admin menu on Install/Upgrade
> DNN-7193 Add Dynamic Content Creator Manager to Admin menu

- Website/DesktopModules/Admin/Scheduler/ViewSchedule.ascx.cs
See https://dnntracker.atlassian.net/browse/DNN-7214
> DNN-7214: Hide next start instead of showing "1/1/0001 12:00:00" if no next start could be calculated

- Website/App_GlobalResources/SharedResources.resx
- Website/admin/Security/PasswordReset.ascx.cs
More accurate reporting of failures when password reset doesn't work
> DNN-7169 Created 2 more helpful error messages when trying to reset the password

- DNN Platform/Dnn.DynamicContent/DataTypeManager.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/contentTypes.js
This pull request should be cherry-picked to the CTP 3 branch when merged.
> DNN-7226 DCC - Cannot add Content Field to a Content Type

- DNN Platform/Library/Common/Globals.cs
- DNN Platform/Library/Data/DataProvider.cs
- DNN Platform/Library/Services/Upgrade/Upgrade.cs
- Website/Providers/DataProviders/SqlDataProvider/08.00.00.01.SqlDataProvider
- Website/Providers/DataProviders/SqlDataProvider/08.00.00.SqlDataProvider
https://dnntracker.atlassian.net/browse/DNN-6919
> Dnn 6919 - Support multiple SqlDataProvider scripts for each release

- DNN Platform/Library/Common/Globals.cs
- DNN Platform/Library/Services/Upgrade/Upgrade.cs
- Website/Install/App_LocalResources/UpgradeWizard.aspx.resx
- Website/Install/UpgradeWizard.aspx.cs
CTP 3 - When installation completes clicking "Next" loads upgradewizard.aspx not default.aspx
> DNN-7246 CTP 3 - When installation completes clicking "Next" loads upgradewizard.aspx not default.aspx

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Components/BusinessController.cs
- DNN Platform/Website/Templates/Blank Website.template
- DNN Platform/Website/Templates/Default Website.template
- DNN Platform/Website/Templates/Default Website.template.en-US.resx
- DNN_DynamicContent.sln
Added DCC Manager page to templates
> DNN-6927 - Create Dynamic Content Administrator Module Shell

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/module.css
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/module.less
Added row highlighting - modified existing row highlighting for data types.
> DNN-7248 Add row highlight on hover to grids

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/templates.js
Only update the filePath property if the Name's new value is Not an empty string.
> DNN-7282 DCC - Saving a portal template file directly after deleting a portal template file

- DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/SearchControllerTests.cs
This should be imported in both branches for completeness of the task.
> DNN-7281 & CONTENT-5195: added/modified unit tests for this issue.

- DNN Platform/Library/Common/Globals.cs
fixed issue where exception was thrown due to httpcontext null exception
> DNN-7269 Installation same error is repeated 6 times into the log files

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/App_LocalResources/Manager.resx
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/templates.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Dnn.Modules.DynamicContentManager.csproj
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/ContentTypeController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/TemplateController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/ViewModels/SnippetViewModel.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/module.css
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/module.less
- Website/Portals/_default/Config/Snippets.config
This also includes the code for DNN-7250 (Add a context menu to insert Razor Helper tags into template )
> DNN-7249 DCC Add a context menu to insert Content Type fields to template 

- DNN Platform/Library/Services/FileSystem/FileManager.cs
Fixed logic in if statement that determined if file could be saved.
> DNN-7260 DCC - Admin is NOT able to save a local Template

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/module.css
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/module.less
While I could no longer reproduce the specific bug I did need to tweak some of the language selector positioning after the UI change.
> DNN-7251 DCC Localization doesn't work for Dynamic Content Type Manager

- Website/DesktopModules/Admin/Extensions/Editors/App_LocalResources/EditModuleDefinition.ascx.resx
This will fix typo in the resource file.
> (doc) Fix typo Chcek => Check

- DNN Platform/Website/Install/Config/08.00.00.01.config
- Website/development.config
- Website/release.config
This change adds a preCondition attribute so the module is only called for managed code.  This change improves performance by allowing IIS to handle all requests for static resources.
> DNN-7383 Update UrlRoutingModule module

- DNN Platform/DotNetNuke.Web.Mvc/Framework/Modules/ModuleApplication.cs
- DNN Platform/DotNetNuke.Web.Mvc/MvcHostControl.cs
- DNN Platform/DotNetNuke.Web.Mvc/Routing/StandardModuleRoutingProvider.cs
Extended convention for MVC Module Control's controlSrc property, to support namespaces.
> DNN-7370 - MVC Add support for Namespaces to MVC Controller detection

- Website/DesktopModules/Admin/Scheduler/EditSchedule.ascx.cs
- Website/DesktopModules/Admin/Scheduler/editschedule.ascx
See https://dnntracker.atlassian.net/browse/DNN-7408
> DNN-7408: Fix validation of txtRetryTimeLapse control

- Website/DesktopModules/Admin/Scheduler/editschedule.ascx
See https://dnntracker.atlassian.net/browse/DNN-7409
> DNN-7409: Added CSS class dnnFormRequired to controls plRetryTimeLapse and plTimeLapse

- Website/Providers/DataProviders/SqlDataProvider/08.00.00.SqlDataProvider
See https://dnntracker.atlassian.net/browse/DNN-7410
Please note: I'm not sure, if 08.00.00.SqlDataProvider is the right place or if its better to create a new 08.00.00.XX.SqlDataProvider file to support "in-place" upgrades?!
> DNN-7410: Fix GetSchedule

- DNN Platform/JavaScript Libraries/jQueryMigrate/jquery-migrate.js
See https://dnntracker.atlassian.net/browse/DNN-7411
> DNN-7411: Run jQuery Migrate in mute mode by default

- DNN Platform/HttpModules/DotNetNuke.HttpModules.csproj
- DNN Platform/HttpModules/UrlRewrite/Config/RewriterConfiguration.cs
- DNN Platform/HttpModules/UrlRewrite/Config/RewriterRule.cs
- DNN Platform/HttpModules/UrlRewrite/Config/RewriterRuleCollection.cs
- DNN Platform/Library/Entities/Urls/RewriteController.cs
Reverts dnnsoftware/Dnn.Platform#735
> Revert "DNN-7153: optimizing siteurl.config rewrite rules handling"

- DNN Platform/Library/Services/Search/IndexingProvider.cs
- DNN Platform/Library/Services/Search/Internals/ISearchHelper.cs
- DNN Platform/Library/Services/Search/Internals/SearchHelperImpl.cs
- DNN Platform/Library/Services/Search/ModuleIndexer.cs
- DNN Platform/Library/Services/Search/SearchEngine.cs
- DNN Platform/Library/Services/Search/SearchEngineScheduler.cs
- DNN Platform/Library/Services/Search/TabIndexer.cs
- DNN Platform/Library/Services/Search/UserIndexer.cs
I fixed the merge conflict.
This needs to be cherry-picked into release/7.4.2 branch as well.
> DNN-7278: Break search indexing process into batches.

- DNN Platform/Components/ClientDependency/Source/Controls/ClientDependencyLoader.cs
- DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
This change reintroduces the DNN fork into the CDF code as we don't support the Attribute feature of CDF and it affects performance
> DNN-7148 Fix performance of CDF

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/contentTypes.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
Added a helper to fix the cell widths (from Stack Overflow) http://stackoverflow.com/questions/1307705/jquery-ui-sortable-with-table-and-tr-width/1372954#1372954
> DNN-7428 DCC Admin - Field that is being dragged during sorting loses style

- Website/admin/Security/App_LocalResources/PasswordReset.ascx.resx
- Website/admin/Security/PasswordReset.ascx
- Website/admin/Security/PasswordReset.ascx.cs
- Website/admin/Security/PasswordReset.ascx.designer.cs
- Website/admin/Security/SendPassword.ascx
- Website/admin/Security/SendPassword.ascx.cs
- Website/admin/Security/SendPassword.ascx.designer.cs
I have moved the Question/Answer challenge from SendPassword to ResetPassword where it can actually be validated
> DNN-7434 Password answer not verified for password reset with requiresQuestionAndAnswer=True

- DNN Platform/Modules/Dnn.Modules.DynamicContentViewer/App_LocalResources/Settings.resx
- DNN Platform/Modules/Dnn.Modules.DynamicContentViewer/Dnn.Modules.DynamicContentViewer.csproj
- DNN Platform/Modules/Dnn.Modules.DynamicContentViewer/Views/Settings/Index.cshtml
- DNN Platform/Modules/Dnn.Modules.DynamicContentViewer/compilerconfig.json
- DNN Platform/Modules/Dnn.Modules.DynamicContentViewer/module.css
- DNN Platform/Modules/Dnn.Modules.DynamicContentViewer/module.less
- Website/admin/Menus/ModuleActions/ModuleActions.ascx
- Website/admin/Menus/ModuleActions/ModuleActions.css
- Website/admin/Menus/ModuleActions/ModuleActions.js
- Website/admin/Menus/ModuleActions/ModuleActions.less
Also fixed the width of the Quick Settings view.
> DNN-7422 DCC Viewer - Display Info in settings.

- DNN Platform/Library/UI/Modules/Html5/ModuleContextPropertyAccess.cs
I needed access to some of these IDs so I can call services.
> Added a few more properties to the token replace logic

- DNN Platform/Library/UI/Modules/Html5/ModuleContextPropertyAccess.cs
Reverts dnnsoftware/Dnn.Platform#790
> Revert "Added a few more properties to the token replace logic"

- DNN Platform/Admin Modules/Dnn.Modules.Sql/sql.ascx
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/templates.js
- Website/Resources/Shared/scripts/dnn.utility.js
This pull request fixes two minor annoying CodeMirror rendering issues by refreshing the codemirror editor when it becomes visible.
To accomplish that I created an onVisible method in the utility library that uses an interval timer to determine when the element becomes visible.
> DNN-7579 / DNN-7582 Refresh codemirror when it becomes visible.

- DNN Platform/Library/Services/Social/Messaging/Scheduler/CoreMessagingScheduler.cs
Please review my changes and merge them if everything is ok.
> DNN-7020 Fixed bug: notification emails were sent twice to each user.

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Components/BusinessController.cs
- Website/DotNetNuke.Website.csproj
- Website/Portals/_default/Content Templates/ViewHtml.cshtml
- Website/Portals/_default/Content Templates/ViewMarkdown.cshtml
This Pull Request only partially resolves the associated JIRA (adding support for two of the Content Types only).  So please do not "resolve" the JIRA.
> DNN-7593 Create Templates for default content types (HTML and Markdown)

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/templates.js
It looks like a lot of changes but I reformatted the Javascript file as it was using the incorrect {} style.
> DNN-7588 DCC Admin - Context menus submenus not rendering

- DNN Platform/Modules/DigitalAssets/Services/ContentServiceController.cs
Issue with Web API 5.1 passing a Queryable/Enumerable to JSON.NET.  Added ToList call.
> DNN-7602 DAM - Can't sync/refresh files & folders

- DNN Platform/Modules/Dnn.Modules.DynamicContentViewer/ClientScripts/dcc.quickSettings.js
- Website/admin/Menus/ModuleActions/ModuleActions.ascx
- Website/admin/Menus/ModuleActions/ModuleActions.css
- Website/admin/Menus/ModuleActions/ModuleActions.less
Fixed a few other minor issues when displaying and updating quick settings
> DNN-7604 Quick Settings menu stays open

- DNN Platform/Modules/Dnn.Modules.DynamicContentViewer/Models/Settings.cs
The Settings were defaulting to 0 rather than -1.
> DNN-7616 - DCC Viewer - Set correct default values for the Settings object.

- DNN_PlatformNoTests.sln
[DNN-7632](https://dnntracker.atlassian.net/browse/DNN-7632)
>The `NoTests` solution file hasn't been updated to use the _DotNetNuke.Website_ project. I've copied `DNN_Platform.sln` file, and removed the testing projects.
> Sync changes from DNN_Platform.sln to DNN_PlatformNoTests.sln

- DNN Platform/Library/Services/Installer/Installers/ComponentInstallerBase.cs
- DNN Platform/Library/Services/Installer/Installers/ModuleInstaller.cs
- DNN Platform/Library/Services/Installer/Installers/PackageInstaller.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/templates.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Components/BusinessController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/TemplateController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/dnn_DCCManager.dnn
This PR allows module developers to write code that will always execute on any upgrade regardless of the version of the current installed package.
> DNN-7634 IUpgradable - Add support for non-version based upgrades

- Website/DesktopModules/Admin/Tabs/ManageTabs.ascx.cs
Note I have submitted separate PRs for 7.4.2 and 8.0.0 - as the code is not easily cherry-picked
> DNN-7640 Page Hierarchy is NOT preserved when changing languages within a site

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/Manager.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/contentTypes.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/ClientScripts/templates.js
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Manager.html
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/ContentTypeController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/module.css
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/module.less
Updated context menu UI to allow for cascading menus when a field is based on another content type.
> DNN-7589 - Updated UI for Template editor context menu

- DNN Platform/Modules/Dnn.Modules.DynamicContentViewer/Views/Viewer/AutoGeneratedView.cshtml
This bug in the Autogenerated templates happened because of the sequence of added features.
> DNN-7608 Update the Autogenerated view template to account for content types as fields

- DNN Platform/DotNetNuke.Web/Api/Internal/ServicesRoutingManager.cs
- DNN Platform/Library/Common/Internal/ServicesRoutingManager.cs
- DNN Platform/Library/Framework/Reflections/TypeLocator.cs
- DNN Platform/Library/UI/Modules/ModuleInjectionManager.cs
This code was cherry-picked from the speed-base-dnn-7458 branch (which was based on an old 7.4.2 build)
> DNN-7458 Optimized Type scanning

- DNN Platform/Library/Entities/Tabs/TabController.cs
DNN-7591: Seqnum on taburl import is case sensitive
> DNN-7591: Seqnum on taburl import is case sensitive

- Website/Resources/Shared/scripts/dnn.dragDrop.js
See https://dnntracker.atlassian.net/browse/DNN-7635 for more details.
> DNN-7635: Fixed module drag&drop when "Inject Module Hyperlinks" is disabled

- DNN Platform/Modules/DDRMenu/DNNAbstract.cs
- DNN Platform/Modules/DDRMenu/DotNetNuke.Modules.DDRMenu.csproj
- DNN Platform/Modules/DDRMenu/TemplateEngine/TemplateDefinition.cs
[DNN-7657](https://dnntracker.atlassian.net/browse/DNN-7657)
>The DDR Menu allows a menu template to define style sheets and scripts that it loads, but it does all of the loading manually.  Both JS and CSS should be loaded via the client resource manager.  Additionally, it would be nice if the DDR menu supported requesting JS Libraries, in addition to loose scripts.
> DNN-7657 DDR Menu with Client Resource Manager

- DNN Platform/Library/Entities/Modules/ModuleController.cs
Reverts dnnsoftware/Dnn.Platform#846. Since this change force-deletes module's content items upon uninstall, we will revert.
> Revert "DNN-7617 Module deletion leaves orphaned Content Items"

- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnHtmlHelper.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnHtmlHelperOfT.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnUrlHelper.cs
Reverts dnnsoftware/Dnn.Platform#891
> Revert "DNN-7744 Add missing members to DnnHtmlHelper and DnnUrlHelper"

- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Components/BusinessController.cs
- DNN Platform/Modules/Dnn.Modules.DynamicContentManager/Services/DataTypeController.cs
- Host Portal "Content Templates" folder is created if does not exists
- Refactored BusinessController code into smaller private methods
> DNN-7665 - DCC Manager does not display templates

- Website/development.config
- Website/release.config
- added missing Client Dependency http handler and http module into release.config and development.config
> DNN-7756 - CDF enabled CSS doesn't render in site

- Website/DesktopModules/Admin/Security/SecurityRoles.ascx.cs
See https://dnntracker.atlassian.net/browse/DNN-7778
> DNN-7778: Path parameters in role adminisrration are now case insensitive

- Website/DesktopModules/Admin/Extensions/Install.ascx.cs
See https://dnntracker.atlassian.net/browse/DNN-7794
> DNN-7794: Make value of path parameter ptype case insensitive

- DNN Platform/MVC Modules/Dnn.Modules.Html/dnn_HTML.dnn
Corrected typo in iconFile path.  JIRA Bug: DNN-7831
> DNN-7831: Update to dnn_Html.dnn

- Website/Robots.txt
Change default robots.txt to allow client side resources
> DNN-7544: Change default robots.txt

- DNN Platform/Library/Data/DataContext.cs
- DNN Platform/Library/Data/PetaPoco/FluentColumnMap.cs
- DNN Platform/Library/Data/PetaPoco/FluentMapper.cs
- DNN Platform/Library/Data/PetaPoco/FluentMapperExtensions.cs
- DNN Platform/Library/Data/PetaPoco/PetaPocoDataContext.cs
- DNN Platform/Library/Data/RepositoryBase.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Data/RepositoryBaseTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Data/FluentMapperTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Data/PetaPocoDataContextTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Data/PetaPocoIntegrationTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Data/PetaPocoRepositoryTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
This work was under development so I have completed it and submitted as a Pull Request.  I have included extra tests to make sure the existing DAL2 attribute-based mapping still works, as well as tests for the fluent mapping.
> DNN-7221 Fluent Configuration for the DAL2

- Website/DesktopModules/Admin/Portals/App_LocalResources/SiteSettings.ascx.resx
- Website/DesktopModules/Admin/Portals/sitesettings.ascx
DNN-7310 DNN-7309 DNN-7308 Resource file changes done. In SiteSettings.ascx file for SMTP setting ListItems
> DNN-7310 DNN-7309 DNN-7308 Resource file changes done.

- Website/Resources/Search/SearchSkinObjectPreview.css
Reverts dnnsoftware/Dnn.Platform#975
> Revert 872dfd492a20d14f3987e7a9871785fbf88c0b78

- Website/Providers/DataProviders/SqlDataProvider/08.00.00.25.SqlDataProvider
re-submitting PR #764 against the correct branch now
> complete fix for DNN-6758

- Website/Providers/DataProviders/SqlDataProvider/08.00.00.25.SqlDataProvider
> DNN-8006 - Update 08.00.00.25.SqlDataProvider

- DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlPartialExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlRenderPartialExtensions.cs
Added extensions for Partial and RenderPartial. This will allow a developer to use Html.RenderPartial and Html.Partial just like an MVC application.
This will work only if you are rendering Partial view from the View.cshtml file. Returning the PartialView from the controller is still not supported.
> DNN-8030 Added extensions for Partial and RenderPartial.

- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnLabelExtensions.cs
DNN-8075 - Added the overloaded methods.
They will pick the labelText and helpText from Model properties metadata.
> DNN-8075 - Added the overloaded methods.

- DNN Platform/Library/Security/Roles/DNNRoleProvider.cs
- DNN Platform/Library/Security/Roles/RoleController.cs
- Website/DesktopModules/Admin/Security/EditRoles.ascx.cs
DNN-7900 Fixed issues for trailing and leading white spaces in security roles.
> DNN-7900 Fixed issues for trailing and leading white spaces

- DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlDisplayExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlDisplayNameExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlDisplayTextExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlEditorExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlInputExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlLabelExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlNameExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlSelectExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlValidationExtensions.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/HtmlValueExtensions.cs
List of Extensions added:
Html.Display
Html.DisplayForModel
Html.DisplayName(string expression)
Html.DisplayNameForModel
Html.DisplayText
Html.Editor
Html.EditorForModel
Html.Hidden
Html.Password
Html.RadioButton
Html.Label
Html.LabelForModel
Html.Id
Html.IdForModel
Html.Name
Html.NameForModel
Html.DropDownList
Html.EnumDropDownListFor
Html.ListBox
Html.Validate
Html.ValidationMessage
Html.Value
Html.ValueForModel
> DNN-8043 Added most of the missing Html Helper extensions.

- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/Helpers/DnnUrlHelperTests.cs
Modified the integration test to add ControllerContext.RouteData["controller"] and ControllerContext.RouteData["action"] in Moq
Refactored the common code
> Modified the integration test to add route data.

- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnHtmlHelper.cs
- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnUrlHelper.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/Helpers/DnnUrlHelperTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/MockHelper.cs
Added Url.Content and Url.IsLocalUrl.
Added Unit Test for Url.Content and Url.IsLocalUrl
> DNN-8092 : Add missing Url Helpers:

- DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnHtmlHelper.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/Helpers/DnnHtmlHelperTests.cs
Added
Html.GetUnobtrusiveValidationAttributes
Html.EnableClientValidation
Html.EnableUnobtrusiveJavaScript
and unit tests
> DNN-8121 Added client validation methods

- DNN Platform/DotNetNuke.Web.Mvc/Common/AntiForgery.cs
- DNN Platform/DotNetNuke.Web.Mvc/Common/AntiForgeryImpl.cs
- DNN Platform/DotNetNuke.Web.Mvc/Common/IAntiForgery.cs
- DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
- DNN Platform/DotNetNuke.Web.Mvc/Framework/ActionFilters/ValidateAntiForgeryTokenAttribute.cs
Allow service framework request also
Code comment added as per Ash's request.
The request params changes
> DNN-8134 : Added custom ValidateAntiForgeryToken for validation

- Website/Resources/Shared/stylesheets/dnndefault/8.0.0/default.css
> DNN-8158 - Removed padding and margin from fieldset.

- DNN Platform/Admin Modules/Dnn.Modules.Tabs/ManageTabs.ascx.cs
- DNN Platform/DotNetNuke.Web.Deprecated/UI/WebControls/DnnDateTimePicker.cs
Extended the DnnDateTimePicker maxdate value to allow DateTime.MaxValue
>  Extended the DnnDateTimePicker maxdate value to allow DateTime.MaxValue

- DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
improved the management of boolean values when they were stored as 0 or 1
> DNN-8181 - HTML Module - Workflow & Module Settings Bug (Seen in Upgrades)

- Website/DesktopModules/AuthenticationServices/DNN/Login.ascx
Start the code block with <%# instead of <%= so that the CLR won't complain.
> DNN-7731: Fixed the code blocks issue in login.ascx

- DNN Platform/Components/ClientDependency/Source/Controls/ClientDependencyInclude.cs
either from web.config or from host settings.
> DNN-8050 The comments will be injected when debug is enabled

- Build/BuildScripts/Module.build
- Build/BuildScripts/Package.targets
- Website/Portals/_default/Content Templates/GettingStarted.cshtml
- Website/Portals/_default/Content Templates/ViewHtml.cshtml
- Website/Portals/_default/Content Templates/ViewMarkdown.cshtml
since it was required only by DCC and DCC is not a part of the present release
> DNN-7675 ContentTemplates has been removed

- Website/DesktopModules/Admin/Portals/Template.ascx.cs
The export template process was not considering the StorageLocation=Secured into consideration.
> DNN-8266 Fixed the export template.

- DNN Platform/Library/Common/Initialize.cs
Stop the processing of application initialization while install is in progress
> DNN-8299 Stop the processing of application initialization 

- DNN Platform/Library/Services/Installer/Blocker/InstallBlocker.cs
Parallel programming with ash.
> DNN-8299 Changes for lockfile deletion rights.

- Website/admin/Tabs/Export.ascx.cs
the template folder is now retrieved directly and then the permission is checked
> DNN-8297 - RGR - Exception thrown when page is exported as RU with proper permission to edit page (this is fine for Host)

- DNN Platform/Library/Services/GeneratedImage/DnnImageHandler.cs
Increase the default requests count to 500.
> DNN-8335 Make default ipcheck = false(Code review with ash)

- DNN Platform/Library/Services/FileSystem/FileManager.cs
the old title is used in the new file one
> DNN-8351 - (EVOQCONTENT) SI: When uploading and overwriting existing files, make sure Titles are not removed

- DNN Platform/Modules/DigitalAssets/Components/Controllers/DigitalAssetsController.cs
Remove Add to avoid possible errors in currency scenario.
> DNN-7595 - First time load File Management get unavailable errors.

- DNN Platform/Modules/DigitalAssets/Services/ContentServiceController.cs
- DNN Platform/Modules/Journal/NotificationServicesController.cs
> CONTENT-5782: fixing anti-forgery related issues

- DNN Platform/Library/Services/GeneratedImage/ImageTransform.cs
- DNN Platform/Library/Services/GeneratedImage/StartTransform/ImageFileTransform.cs
- DNN Platform/Library/Services/GeneratedImage/StartTransform/SecureFileTransform.cs
- DNN Platform/Library/Services/GeneratedImage/StartTransform/UserProfilePicTransform.cs
Moved copyimage method into ImageTransform abstract class as a virtual method.
Added usage of CopyImage where ever it was required.
> DNN-8360 Used copy image method at all required calls

- DNN Platform/Library/Services/GeneratedImage/DnnImageHandler.cs
- DNN Platform/Library/Services/GeneratedImage/ImageTransform.cs
Changes done to get correct content type in all cases and create correct image.
> DNN-8346 Fixed the transparency.

- Website/Providers/DataProviders/SqlDataProvider/08.00.00.29.SqlDataProvider
Use ISO date format for comparisons
> DNN-8377: Installation fails on non-English databases

- DNN Platform/Library/Common/Utilities/Config.cs
The issue was happening because AddFcnMode was saving the web.config whenever it was called.
Modified the AddFcnMode to update the web.config only if the FcnMode needs a change and not to update it every time.
Also modified the logic to get the current FCN mode. This would save one read call to web.config.
> DNN-8397 Fixed the AddFcnMode logic.

- DNN Platform/Modules/Groups/Create.ascx
It doesn't matter if the button doesn't get-reactivated because the web form posts back and re-renders the button if its invalid.
> DNN-7454 - added logic to disable button on form submit.

- DNN Platform/Library/Services/Authentication/OAuth/OAuthConfigBase.cs
Reverts dnnsoftware/Dnn.Platform#1282
> Revert "Allow sharing OAuth service config across sites DNN-8383"

- DNN Platform/Library/Services/Localization/Localization.cs
- DNN Platform/Tests/DotNetNuke.Tests.Urls/FriendlyUrlTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Urls/UrlRewriteTests.cs
Added new overloads and fixed the failing tests.
> DNN-6547: fixing unit and integration tests

- DNN Platform/DotNetNuke.Web.Client/ClientResourceManager.cs
> DNN-7213: empty and obsolete UpdateVersion method.

- DNN Platform/Library/Common/Utilities/Config.cs
- DNN Platform/Library/Common/Utilities/RetryableAction.cs
Fix for logged errors during app start.
> CONTENT-5390: fix for web.config touch error during application restart.

- DNN Platform/Library/Services/Social/Notifications/NotificationsController.cs
so that we don't hit database for empty object calls. This will also solve the issue of repeated notifications due to cache returned object.
> DNN-8464 Made changes to save the blank object in cache

- Website/DesktopModules/Admin/Extensions/scripts/Gallery.js
Refactored code and added extra fail safes for category properties.
> DNN-8465 - Added wrapper to ensure category data exists.

- DNN Platform/DotNetNuke.Web/InternalServices/ItemListServiceController.cs
- DNN Platform/DotNetNuke.Web/UI/WebControls/DnnPageDropDownList.cs
- Website/DesktopModules/Admin/Portals/sitesettings.ascx
This is a follow-up pull request for https://github.com/dnnsoftware/Dnn.Platform/pull/666.
> DNN-7287: Enable selecting child-pages of disabled pages as 404 Error Page or 500 Error Page (follow up for pull request #666)

- DNN Platform/Library/Common/Utilities/DataCache.cs
- DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
- DNN Platform/Library/Services/Social/Messaging/Internal/InternalMessagingControllerImpl.cs
- DNN Platform/Library/Services/Social/Notifications/NotificationsController.cs
Reducing SQL queries by utilizing caching to enhance performance. The changes here reduce the queries to database by about 5 to 8 calls.
> Performance DNN-8198

- DNN Platform/Library/Data/DataProvider.cs
- DNN Platform/Library/Data/PetaPoco/PetaPocoHelper.cs
- DNN Platform/Library/Data/SqlDataProvider.cs
- DNN Platform/Tests/DotNetNuke.Tests.Data/Fakes/FakeDataProvider.cs
Support for bulk-insertion of DataTable object (with multiple rows) into the database.
> DNN-8565: added support for bulk-insertion of DataTable object

- DNN Platform/Admin Modules/Dnn.Modules.Tabs/Tabs.ascx.cs
Changes to the Tabs module to respect consistent permissions for "Add Page" actions.
> DNN-8558 Tab Module Permissions Fix

- DNN Platform/Library/Services/FileSystem/FileManager.cs
We check if there is a metadata property present for orientation. If present then we apply the rotation and remove the property
> DNN-8588 Rotate the images on upload if required

- DNN Platform/Library/Data/DataProvider.cs
- DNN Platform/Library/Entities/Controllers/HostController.cs
- DNN Platform/Library/Entities/Modules/ModuleController.cs
- DNN Platform/Library/Entities/Tabs/TabController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Host/HostControllerTest.cs
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Framework/Controllers/ModuleController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Framework/Controllers/TabController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Integration/Tests/Jwt/JwtAuthTest.cs
- Website/Providers/DataProviders/SqlDataProvider/08.01.00.01.SqlDataProvider
Adjust SettingValue column size for HostSettings, PortalSettings and RoleSettings and use same procedure construct for all settings tables.
> DNN-8659 Change HostSettings and PortalSettings SettingValue column size

- Website/DesktopModules/Admin/Security/module.css
See https://dnntracker.atlassian.net/browse/DNN-8568
> DNN-8568 update module.css

- Build/Tools/NuGet/DotNetNuke.Bundle.nuspec
- Build/Tools/NuGet/DotNetNuke.Core.nuspec
- Build/Tools/NuGet/DotNetNuke.Instrumentation.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Client.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Deprecated.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.Mvc.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.nuspec
- Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
> Add license URL to NuGet packages

- Website/Providers/DataProviders/SqlDataProvider/09.00.01.SqlDataProvider
> DNN-9133: Added missing objectQualifier

- DNN Platform/Library/Data/DataProvider.cs
- DNN Platform/Library/Data/SqlDataProvider.cs
- DNN Platform/Tests/DotNetNuke.Tests.Data/Fakes/FakeDataProvider.cs
I used this timeout in the PurgeScheduleHistory task because it is timing out in systems with large number of history records.
> DNN-9047: added new SQL execution methods with timeout parameter.

- DNN Platform/Components/ClientDependency/Source/ClientDependency.Core.csproj
- DNN Platform/Components/ClientDependency/Source/ClientDependency.csproj
- DNN Platform/Controls/CountryListBox/CountryListBox.csproj
- DNN Platform/Controls/SolpartMenu/CountryListBox/CountryListBox.csproj
- DNN Platform/DotNetNuke.Web.Deprecated/DotNetNuke.Web.Deprecated.csproj
- DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
- DNN Platform/DotNetNuke.WebUtility/DotNetNuke.WebUtility.vbproj
- DNN Platform/HttpModules/DotNetNuke.HttpModules.csproj
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Modules/Taxonomy/DotNetNuke.Modules.Taxonomy.csproj
- DNN Platform/Syndication/DotNetNuke.Syndication.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Taxonomy/DotNetNuke.Tests.Taxonomy.csproj
- DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
Note: left two projects without change since they are done in DNN-8892 which has its own change.
> DNN-8895: removing any .NET 3.5 reference in the solution.

- Website/Install/App_LocalResources/Installwizard.aspx.resx
"email address", not "emaila ddress"
> Fix Email.Help value

- Website/DesktopModules/Admin/SearchResults/dnn.searchResult.js
Recalculate the input field and close icon's CSS attributes when the window has been resized.
> DNN 9348 Recalculate Search Results page's input box on window resize

- DNN Platform/Skins/Xcillion/Skin/skin.css
This is a copy of XCESS-NL/xcillion#4 (a slightly improved version of XCESS-NL/xcillion#2)
> DNN-9317 Use HTTPS for Xcillion font requests

- Website/DesktopModules/Admin/Security/module.css
Media query and additional CSS to help better render the data table on small devices.
> DNN-9321 Optimize Edit Profile Page's Manage Services Table

- DNN Platform/DotNetNuke.Web/InternalServices/NewUserNotificationServiceController.cs
- DNN Platform/Library/Services/Mail/Mail.cs
- DNN Platform/Library/Services/Mail/MessageType.cs
- Website/App_GlobalResources/GlobalResources.resx
Added template for sending email on un-authorize
> DNN-9369: Send email on approval.

- DNN Platform/Modules/DnnExportImport/Components/Providers/DataProvider.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
- DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
- DNN Platform/Modules/DnnExportImport/Providers/DataProviders/SqlDataProvider/09.01.01.SqlDataProvider
- DNN Platform/Modules/DnnExportImport/Providers/DataProviders/SqlDataProvider/Uninstall.SqlDataProvider
- DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
Fix restore and delete of modules on target.
> CONTENT-8174: Add soure Unique Id for tab module while import.

- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
- DNN Platform/Modules/DnnExportImport/Providers/DataProviders/SqlDataProvider/09.01.01.SqlDataProvider
Export only modules which currently exists on a published page.
Do not export a page which has never been published yet.
Export only published part of the page
> CONTENT-8178: Fix export inconsistency error.

- DNN Platform/Library/Services/Installer/Installers/AssemblyInstaller.cs
see also initial conversation on original pull-request https://github.com/dnnsoftware/Dnn.Platform/pull/1381
> fixing dnn-8479

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
fixes jira issue https://dnntracker.atlassian.net/browse/DNN-8992
> fix issue with missing file-sort on linux-based NAS - close DNN-8992

- DNN Platform/Modules/DnnExportImport/Components/Providers/DataProvider.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/AssetsExportService.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/WorkflowsExportService.cs
- DNN Platform/Modules/DnnExportImport/Providers/DataProviders/SqlDataProvider/09.01.01.SqlDataProvider
Fix no tab modules if state is not null and no version history(Old websites)
> CONTENT-8384: Fix duplicate permissions issue.

- DNN Platform/Modules/DnnExportImport/Components/Providers/DataProvider.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
- DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
- DNN Platform/Modules/DnnExportImport/Providers/DataProviders/SqlDataProvider/09.02.00.SqlDataProvider
- DNN Platform/Modules/DnnExportImport/Providers/DataProviders/SqlDataProvider/Uninstall.SqlDataProvider
- DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
Try to assign the source UniqueId to the target module.
> CONTENT-8184: Try to assign the source UniqueId to the target page.

- DNN Platform/Library/Entities/IPFilter/IPFilterController.cs
- Website/App_GlobalResources/Exceptions.resx
Added a check to validate the IP address and subnet mask which throws ArgumentException if either of them are not in correct format.
> DNN-10166 add IP Filter validation

- Website/DesktopModules/Admin/Authentication/Login.ascx.cs
- Website/DesktopModules/Admin/Security/Membership.ascx.cs
Fix to ensure update password (as initiated by an admin) is not subject to a time out like reset password is.
> DNN-8725 Fix to update password issue

- DNN Platform/DotNetNuke.Web/InternalServices/ProfileServiceController.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/Registration/IRegistrationProfileController.cs
- DNN Platform/Library/Services/Registration/RegistrationProfileController.cs
- Remove from DotNetNuke.Web to Library project as that to be used in validation for CONTENT-7615
- Put in Registration folder under Library.Sesrvices need feedback on this
> DNN-10299:  SECURITY: Admin Security settings issues

- DNN Platform/Library/Services/Mail/Mail.cs
https://dnntracker.atlassian.net/browse/DNN-9020
New PR, as updating #1575 was not possible
> DNN 9020: Only override sender if SmtpAuth is Enabled

- DNN_Platform.sln.DotSettings
I wanted to get started creating some shared settings, so folks can avoid simple mistakes that ReSharper might insert (or not correct).
To start, this only has a setting to avoid adding nested namespaces.  I'm sure there are more settings that can be added to this.
Does this need a JIRA if it's only affecting developer experience?
> Add ReSharper settings

- Website/Resources/Shared/components/ComposeMessage/ComposeMessage.css
Minor css adjustment to the user icon images as seen when searching from the compose message pop up.
> DNN-9379 Compose message user icon image css 

- DNN Platform/Library/Services/Tokens/BaseTokenReplace.cs
> DNN-10160: Curly braces are not allowed within the caption of the object

- Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
Reverts dnnsoftware/Dnn.Platform#1611
This was merged by mistake into branch release/8.04 by mistake.
> Revert "bug fix: lockout user throws error"

- DNN Platform/Library/Services/Social/Messaging/Frequency.cs
Do not mark enums with FlagsAttribute in the Platform code.
See MSDN Documentation here http://msdn.microsoft.com/en-us/library/ms182335.aspx
> DNN-10390: fixing warning CA2217

- README.md
I added a few relevant links and removed the references to the forge.
> Updating links, Removing Forge

- DNN Platform/Library/Services/Localization/LocalizationProvider.cs
- changes make in LocalizationProvider
> DNN-10289:Message/Email Tokens Don't Reflect SSL

- DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
- Unlock the lock out user first before resetting the password.
> DNN-10510: Cannot Request Password Reset Link

- Website/Resources/Shared/stylesheets/dnndefault/7.0.0/default.css
- Website/Resources/Shared/stylesheets/dnndefault/8.0.0/default.css
- this CSS3 checked on all browser. this rule take care of possible word wrap  break point
> DNN-9220: No wrap in HTML Editor

- DNN Platform/Library/Services/Log/EventLog/ExceptionLogController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Membership/MembershipProviderTests.cs
Also fixed a unit test that causes such a behavior.
> DNN-10550: fix for endless exceptions loop to prevent stack overflow.

- Website/Providers/DataProviders/SqlDataProvider/08.00.00.30.SqlDataProvider
- Website/Providers/DataProviders/SqlDataProvider/08.00.00.SqlDataProvider
make 08.00.00.sqldataprovider and 08.00.00.30.sqldataprovider rerunnable
> DNN-10595: DNN 8.0.0 Upgrade scripts not rerunnable

- DNN Platform/Library/Security/PortalSecurity.cs
The bug is reported under EVOQ board as issue CONTENT-8624
> DNN-8014: fixing a bug that appeared after last change to this issue.

- Website/admin/Security/SendPassword.ascx
- Website/admin/Security/SendPassword.ascx.cs
- Website/admin/Security/SendPassword.ascx.designer.cs
- Converting the cancel/close button to hyperlink to stop postback plus response.redirect
> DNN-10568: Password Reset - Clicking on Cancel button throw 503 Error

- Website/DesktopModules/Admin/Authentication/Login.ascx.cs
- Stopping redirect if not authenticated in same request lifecycle
> DNN-8552: Account Login Module Redirect Issue

- Build/Tools/NuGet/DotNetNuke.Bundle.nuspec
- DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
- DNN Platform/Modules/MemberDirectory/packages.config
- DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
- README.md
Also, fixing the bundle packaging and unifying all Newtonsoft.Json package references.
> DNN-10693: adding Appveyor build status.

- DNN Platform/Skins/Xcillion/Skin/koi.json
This is an info-file for https://connect-koi.net, which lets Koi automatically pick up what CSS-framework is being used - in this case Bootstrap 3
> koi.json broadcasting that it's using bootstrap 3

- DNN Platform/Modules/DDRMenu/MenuBase.cs
- DNN Platform/Modules/DDRMenu/MenuNode.cs
- Simplify the matching logic for filtering nodes
- Add new method to remove the nested or child node by recursion
> DNN-17683:  SI: DDR Menu: Exclude Nodes

- Website/DesktopModules/Admin/Authentication/Login.ascx.cs
- Check for url referrer for "login" url
> DNN-19925: SI: Redirect after login setting not working for login page

- DNN Platform/Library/Services/Localization/LocalizationProvider.cs
See issue 2055 on Github for details
> Fix path to resource file construction. Fixes #2055

- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Reverts dnnsoftware/Dnn.Platform#2030
> Revert "DNN-18210 SI: ImportExport issue for child pages"

- DNN Platform/Library/Common/Globals.cs
- DNN Platform/Library/Entities/Users/IUserController.cs
- DNN Platform/Library/Entities/Users/UserController.cs
- DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
- Website/DesktopModules/Admin/Security/Register.ascx.cs
- Pull string to static field to be used in other project as well
> DNN-20316: Cannot create new user with email address as username

- DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
> DNN-18612: validate unique display name only in current portal.

- .github/ISSUE_TEMPLATE.md
I figure that it's enough to have one section for browser / OS.
> Added browser section to issue template

- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
> DNN-20914: save module permissions into database.

- DNN Platform/DotNetNuke.Web/InternalServices/FileUploadController.cs
fixes #2135 
- Possible regression due to #2035 
- Pull back the deleted code
- Check if folder object null, then go for portal base folder
> Fix bug #DNN-21129

- Build/Symbols/DotNetNuke_Symbols.dnn
- DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
- DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/dnn_ModuleCreator.dnn
- DNN Platform/Connectors/Azure/AzureConnector.dnn
- DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
- DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
- DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
- DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
- DNN Platform/Modules/DDRMenu/DDRMenu.dnn
- DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
- DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
- DNN Platform/Modules/Groups/SocialGroups.dnn
- DNN Platform/Modules/HTML/dnn_HTML.dnn
- DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
- DNN Platform/Modules/Journal/Journal.dnn
- DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
- DNN Platform/Modules/RazorHost/Manifest.dnn
- DNN Platform/Modules/RazorHost/RazorHost.dnn
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
- DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
- DNN Platform/Providers/FolderProviders/FolderProviders.dnn
- SolutionInfo.cs
- Website/DotNetNuke.Website.csproj
- Website/Providers/DataProviders/SqlDataProvider/09.02.02.SqlDataProvider
Fixes DNN-21505
- Need to make changes for versions 
-  *.dnn files 
-  solutioninfo.cs 
-  add 09.02.20.sqlprovider
> DNN-21505: Upgrade page is displayed after install Evoq Engage 9.2.2.7-2

- DNN Platform/Library/Services/Search/Controllers/ModuleResultController.cs
> DNN-22200: avoid insert duplicate key in race condition.

- Website/Install/App_LocalResources/Installwizard.aspx.es-ES.resx
- Website/Install/App_LocalResources/UpgradeWizard.aspx.es-ES.resx
Added missing translations and some mistakes corrected.
> Installation resource files reviewed

- Build/BuildScripts/CreateCommunityPackages.build
- build.cake
This pull request enables the CreateSymbols step and fixes the issues when running CreateSource.
> CI: Enable the CreateSymbols and CreateSource build tasks.

- Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
- put null check if user not approve or unauthorrized
fixes #2211
> DNN-22144: Email as username breaks login/Unauthorized message

- Build/BuildScripts/PublishArtifacts.ps1
This is mainly for testing right now.
> CI: Added Powershell script for publishing artifacts

- DNN Platform/Library/Services/Search/Internals/Constants.cs
- DNN Platform/Library/Services/Search/Internals/LuceneControllerImpl.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/LuceneControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/SearchControllerTests.cs
> DNN-21973: retry the search when there have exception throw during search process.

- DNN Platform/Library/Services/Search/Internals/LuceneControllerImpl.cs
> DNN-22201: release write lock as well.

- DNN Platform/Library/Entities/Users/UserController.cs
Fix [#50](https://github.com/dnnsoftware/Dnn.AdminExperience/issues/50)
> Use master portalID set by GetEffectivePortalId to which user is belong

- CONTRIBUTING.md
Closes #2261 
Adds the youtube video playlist in the contributing.md
> Added video playlist in contributing.md

- DNN Platform/Library/Entities/Portals/PortalController.cs
- Website/App_GlobalResources/SharedResources.resx
> Bugfix: avoid creation of portals using an existing home folder.

- DNN Platform/Library/Services/Authentication/AuthenticationController.cs
- DNN Platform/Library/Services/Authentication/OAuth/OAuthConfigBase.cs
- DNN Platform/Modules/CoreMessaging/Subscriptions.ascx.cs
- Website/App_GlobalResources/SharedResources.resx
- Website/DesktopModules/Admin/Authentication/Login.ascx.cs
- Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
- Website/admin/Skins/Login.ascx.cs
- Website/admin/Skins/User.ascx.cs
- Website/admin/Skins/UserAndLogin.ascx.cs
Pull request for https://dnntracker.atlassian.net/browse/DNN-8448
> Dnn-8448: Support host-level OAuth authentication provider configuration

- .github/PULL_REQUEST_PROCESS.md
Documentation change to the Pull Request process.  Added policy regarding stale pull requests.
> Updated Pull Request Documentation

- DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
Fixes #2343 
Clear user cache after Updates for Approval or LockedOut on found user
> Clear user cache after Updates for Approval or LockedOut

- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Fixes #2176
Removed useless code generating a null reference exception while performing a full import.
Actually no functional changes will be introduced. Just avoid a Null Reference exception generated by a piece of that did nothing.
> Fixes #DNN-8338 SI: Full Exports Do Not Update Existing HTML Pro Modules

- DNN Platform/Library/Entities/Tabs/TabController.cs
> copy terms into localized pages

- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Fixes #2280 
Implement parent tab case by URL
> Implement Parent by Url

- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FolderManagerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/SearchServiceControllerTests.cs
> DNN-25706: fix broken unit tests.

- Build/cake/version.cake
Adds a call to GitVersion which will update build number with its output
> have gitversion update VSTS build number

- DNN Platform/Library/Data/SqlDataProvider.cs
> DNN-25771: set default database connection provider to compactible for upgrade process.

- DNN Platform/Library/Application/Application.cs
- DNN Platform/Library/Application/AssemblyStatusAttribute.cs
- DNN Platform/Library/Collections/CollectionExtensions.cs
- DNN Platform/Library/Collections/EnumerableExtensions.cs
- DNN Platform/Library/Collections/PagedList.cs
- DNN Platform/Library/Collections/PagedSelector.cs
- DNN Platform/Library/Collections/PagingExtensions.cs
This adds/updates XML documentation on many methods and classes of the DotnetNuke.Application and DotNetNuke.Collections namespaces.
I have not added any XML documentation on the following because I am no expert in that field (Locking and Shared collections). If anyone knows how to document that, either help me out here or on slack or by submitting an additional pull request, etc.
> DOCS: API docs on Application and Collections

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
> DNN-26075: sort the files list to alphabetically order.

- DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
Fixes #2410 
Checking lockout when login try failed.
> After Invalid attempt checking lockout from MemberShip Api

- DNN Platform/Connectors/GoogleAnalytics/Connector.css
- DNN Platform/Connectors/GoogleAnalytics/Scripts/connector.js
- DNN Platform/Connectors/GoogleAnalytics/connector.htm
Fixes #2378 
This is a continuation of Issue #2129 and Pull Request #2288. That fix included unsynced files and therefore the merged code did not preform properly.
This PR syncs the connector code to the latest version.
I've reinstalled the generated install package on a fresh install and the connector worked as expected without the errors defined in issue #2378.
Follow test steps located on PR #2288.
Same as found on PR #2288
> Merge unsynced file updates that are required for the GA connector.

- DNN Platform/Library/Common/Utilities/UrlUtils.cs
Fixes #2399 
Checking Offloading header for popups when opening
> - checking SSLOffloading header set by environment

- Build/Symbols/DotNetNuke_Symbols.dnn
- DNN Platform/Components/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/releaseNotes.txt
- DNN Platform/Modules/DDRMenu/DDRMenu.dnn
- DNN Platform/Modules/DigitalAssets/ReleaseNotes.txt
- DNN Platform/Modules/DnnExportImport/ReleaseNotes.txt
Close #2263 
change reference to  support@dotnetnuke.com into support@dnnsoftware.com
> Close #2263: change support@dotnetnuke.com to support@dnnsoftware.com

- DNN Platform/Library/UI/Navigation.cs
> DNN-26206: find dnn node from dictionary to improve performance.

- DNN Platform/Modules/DnnExportImport/Components/Controllers/EntitiesController.cs
- DNN Platform/Modules/DnnExportImport/Components/Interfaces/IEntitiesController.cs
- DNN Platform/Modules/DnnExportImport/Components/Providers/DataProvider.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
- DNN Platform/Modules/DnnExportImport/Providers/DataProviders/SqlDataProvider/09.03.00.SqlDataProvider
> do not export modules which already deleted from page.

- Website/Default.aspx.cs
Fixes #2416 
Replace http with https when SSL is setup
> - Replacing http to https if SSL is setup

- DNN Platform/Library/Common/Globals.cs
- DNN Platform/Library/Entities/Users/UserController.cs
- Website/Providers/DataProviders/SqlDataProvider/09.03.00.SqlDataProvider
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2474
> Unable to create a user using domain\username format

- Website/DotNetNuke.Website.csproj
- Website/Providers/DataProviders/SqlDataProvider/09.03.00.02.SqlDataProvider
Fixes #2498 
- Commented out the lastlockedoutdate in aspnet_Membership_UnlockUser stored procedure
> - Commented out the lastlockedoutdate in storeprocedure

- DNN Platform/Library/Entities/Tabs/TabCollection.cs
> refresh cache by keep the data position.

- DNN Platform/Library/Services/Exceptions/ExceptionExtensions.cs
This is a fix for https://github.com/dnnsoftware/Dnn.Platform/issues/2507
> Change algorithm to SHA1CryptoServiceProvider

- Website/DesktopModules/Admin/Security/Register.ascx.cs
> DNN-27566: end the response after redirect.

- DNN Platform/Library/Collections/ReaderWriterLockStrategy.cs
fixes [issue 2185](https://github.com/dnnsoftware/Dnn.Platform/issues/2185)
> Recursive read lock acquisitions not allowed

- DNN Platform/Skins/Xcillion/Skin/skin.css
Fixes #2553 
Add Css for languages elements
> All languages enabled 

- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2294
There is a problem when importing pages. On import, system overwrites `DefaultLanguageGuid` tab property on the target site. It uses `UniqueId` of default locale page of original portal and set it to the child site. It creates inconsistent data and we can observe following situation:
Due to above system is unable to define other translated tabs that are linked to the default page, so lang icons are not visible for the portal pages (portal 1 in our particular case). 
This is how system should link pages:
> After export with Content Localization site language flags disappears from pages

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
- DNN Platform/Skins/Xcillion/Skin/skin.css
The referenced changes have already been approved. Since this is a release management task we are self approving the merge without any reviews.
> Update development branch with fixes from 9.3.0-rc2

- .nuget/NuGet.Config
- DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
- DNN Platform/Modules/DigitalAssets/DotNetNuke.Modules.DigitalAssets.csproj
- DNN Platform/Modules/Groups/DotNetNuke.Modules.Groups.csproj
- DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj
- DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
- DNN Platform/Modules/Journal/DotNetNuke.Modules.Journal.csproj
- DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/DotNetNuke.Authentication.Facebook.csproj
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/DotNetNuke.Authentication.Google.csproj
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/DotNetNuke.Authentication.LiveConnect.csproj
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/DotNetNuke.Authentication.Twitter.csproj
- DNN Platform/Providers/HtmlEditorProviders/RadEditorProvider/DotNetNuke.RadEditorProvider.csproj
- DNN Platform/Skins/Xcillion/DotNetNuke.Skins.Xcillion.csproj
- DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
- DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
- DNN_Platform.sln
Fixes #2561
In addition to fixing above issue, I'm also setting active Nuget package source to "All".
> Fixed parallel build

- DNN Platform/Library/Services/Installer/Installers/AssemblyInstaller.cs
> Add error handling in AssemblyInstaller

- DNN Platform/Library/Framework/JavaScriptLibraries/JavaScript.cs
> Supply name and version for JS library requests

- DNN Platform/Library/Services/Journal/JournalControllerImpl.cs
> get journal include deleted items when try to do hard delete.

- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
> keep exported tab modules in order.

- Website/Resources/Shared/scripts/TreeView/dnn.DynamicTreeView.js
Fixes #2594 
Checking for includeDisabled
> - Unable to add module from Disable page

- DNN Platform/Library/Common/Utilities/FileSystemUtils.cs
> call to overload method to avoid the issue.

- DNN Platform/Library/Services/Upgrade/Internals/InstallConfiguration/InstallConfig.cs
- DNN Platform/Library/Services/Upgrade/Internals/InstallControllerImpl.cs
- DNN Platform/Website/Install/InstallWizard.aspx
- DNN Platform/Website/Install/InstallWizard.aspx.cs
- DNN Platform/Website/Install/InstallWizard.aspx.designer.cs
- Website/Install/App_LocalResources/Installwizard.aspx.de-DE.resx
- Website/Install/App_LocalResources/Installwizard.aspx.es-ES.resx
- Website/Install/App_LocalResources/Installwizard.aspx.fr-FR.resx
- Website/Install/App_LocalResources/Installwizard.aspx.it-IT.resx
- Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
- Website/Install/App_LocalResources/Installwizard.aspx.resx
- Website/Install/DotNetNuke.install.config.resources
- Website/Install/Install.css
- Website/Install/UpgradeWizard.aspx
Remove Object Qualifier and Banners from Installation Wizard. 
Waiting for CI builds to complete for an initial install test.
Closes #2346 
Closes #2657
Closes #2650
> Remove Object Qualifier and Banners from Installation Wizard 

- DNN Platform/Library/Entities/Tabs/TabController.cs
Fix: https://github.com/dnnsoftware/Dnn.Platform/issues/2568
> Create localized versions of the page on the same position in the menu as original version is

- .github/PULL_REQUEST_PROCESS.md
- .github/VERSIONING_POLICY.md
- CONTRIBUTING.md
Updated to reflect the proper processes that are being followed now and added additional notes regarding contributions to obsolete code.
> Updates to Process Documentation

- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
> DNN-30121: fix export/import bugs.

- DNN Platform/Connectors/Azure/App_LocalResources/SharedResources.resx
- DNN Platform/Connectors/Azure/Components/AzureConnector.cs
- DNN Platform/Connectors/Azure/Scripts/connector.js
> Rename "Azure" to "Azure Storage", and prefix settings with "Storage"

- DNN Platform/Providers/FolderProviders/AzureFolderProvider/AzureFolderProvider.cs
- DNN Platform/Providers/FolderProviders/Components/BaseRemoteStorageProvider.cs
- Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Data.SqlDataProvider
The referenced changes have already been approved. Since this is a release management task we are self approving the merge without any reviews.
> Update development branch with the final fixes from v9.3.2

- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
> check pages culture correctly.

- Website/Resources/Shared/scripts/TreeView/dnn.DynamicTreeView.js
Fixes #2594 
Extends solution implemented in d06a05289d3372dfaf7205956ab01929fbf61ebb to `getChildren` and `search` methods. With this fix, child disabled pages can be selected as well.
> Amended d06a05289d3372dfaf7205956ab01929fbf61ebb

- Website/Providers/DataProviders/SqlDataProvider/10.00.00.SqlDataProvider
- gitversion.yml
This is a devops task since we now have two active branches, increments the version to v10.0.0 on the development branch.
> Bump version to v10.0.0

- .github/ISSUE_TEMPLATE/security-issue.md
See @valadas' comment on #2833
> Remove security issue template

- DNN Platform/Library/Entities/Users/UserRegistrationEmailNotifier.cs
- DNN Platform/Library/Services/Mail/Mail.cs
- DNN Platform/Library/Services/Mail/MessageType.cs
This is a clone of https://github.com/dnnsoftware/Dnn.Platform/pull/2845
Target branch is changed from `development` to `release/9.4.x`
CC: @daguiler , @bdukes , @ohine , @sleupold
> Wrong text in welcome email when users are added manually

- DNN Platform/Library/Entities/Users/UserController.cs
- DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
- DNN Platform/Library/Security/Membership/UserCreateStatus.cs
- Website/App_GlobalResources/SharedResources.resx
- Website/DesktopModules/Admin/Security/Register.ascx.cs
> process the registration data and update to user object.

- .github/PULL_REQUEST_PROCESS.md
Adds information about targeting the correct branch when submitting pull requests
> Added branching explanation to PR documentation

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/help-and-other-questions.md
- .github/ISSUE_TEMPLATE/request-for-comments.md
Adds information about targeting the correct branch when submitting pull requests
> Bug template

- DNN Platform/Library/Services/FileSystem/Providers/StandardFolderProvider.cs
This is a clone of https://github.com/dnnsoftware/Dnn.Platform/pull/2903 re-targeted to 9.4.*
@bdukes @mikesmeltzer @valadas
> CK Editor: Browser - Taking a long time to load [Performance Issue]

- DNN Platform/Library/Common/Utilities/FileSystemUtils.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/FileSystemUtilsTests.cs
clone for https://github.com/dnnsoftware/Dnn.Platform/pull/2945
https://github.com/dnnsoftware/Dnn.Platform/issues/2943
fix for DNN-17149 , DNN-32014
> deleting_themes_from_Extensions_doesnt_remove_it_from_themes_rebased

- Build/Cake/unit-tests.cake
- DNN Platform/DotNetNuke.DependencyInjection/Extensions/TypeExtensions.cs
- DNN Platform/Library/Common/Utilities/FileSystemUtils.cs
- DNN Platform/Library/Entities/Tabs/TabController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/FileSystemUtilsTests.cs
This is a release management PR to update the development branch with recent changes from 9.4.x, because of that we are self approving this PR
> Updating development with recent changes on release/9.4.x

- DNN Platform/Library/Common/Utilities/FileSystemUtils.cs
Fix #2351 again, also find another place which call to the same method, so change that together.
> Issue-2351: call to overload method to avoid the issue.

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/help-and-other-questions.md
- .github/ISSUE_TEMPLATE/request-for-comments.md
This is a release management task and we are self approving it as per our policies
> Updates issues templates as per 9.4.0 being released

- Website/Resources/Shared/components/FileUpload/dnn.FileUpload.js
> enable jquery browser detection.

- DNN Platform/Modules/DnnExportImport/Components/Common/CompressionUtil.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/ThemesExportService.cs
> fix several bugs around export/import area.

- DNN Platform/Modules/DnnExportImport/Components/Services/PortalExportService.cs
> DNN-33314: import portal languages correctly.

- Website/admin/Containers/PrintModule.ascx.cs
The print container action stopped working because it wasn't finding the print action.
> Fix print container action

- DNN Platform/Library/Entities/Portals/PortalSettings.cs
- DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
There are issues deserializing the date in some cultures.
Fixes #3010
> Store DataConsentTermsLastChange in round-trip format

- .github/PULL_REQUEST_PROCESS.md
Fixed typos in the Pull Request Process document.
> (doc) Update pull request process documentation

- .github/stale.yml
Addition of configuration file for StaleBot.  This is an effort to manage the backlog and active issues.  Issues that are closed by this process will be properly labeled for review/reopen if necessary as well.
Added the noteworthy tag as this should be highlighted with the next set of release notes.
> Addition of configuration for StaleBot

- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
'Fixes #3124' 
Tip for writing better page title with SEO in mind.
> Fixes #3124

- DNN Platform/Library/Entities/Modules/ModuleController.cs
this is a clone of https://github.com/dnnsoftware/Dnn.Platform/pull/3132 pointing to `release/9.4.x`
> DNN-32978 Copying pro html module don't modify the permission

- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/serversummary.js
> Documentation action cleanup

- .github/ISSUE_TEMPLATE/bug-report.md
Replace "nightly build" phrase with "non-release build".
Resolves #3172
> Update bug report issue template

- .github/ISSUE_TEMPLATE/help-and-other-questions.md
Replace "nightly build" phrase with "non-release build".
Resolves #3174
> Update "help and other questions" issue template

- .github/ISSUE_TEMPLATE/request-for-comments.md
Replace "nightly build" phrase with "non-release build".
Resolves #3176
> Update "request for comments" issue template

- .github/PULL_REQUEST_TEMPLATE.md
Closes #3181 
Typo correction in PR template
> Fixes typo correction in PR template

- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Pages.Web/src/components/Modules/ModuleEdit/ModuleEdit.jsx
> check the url with case insensitive.

- DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
- DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/LoginData.cs
> JWT Audience

- .github/stale.yml
Resolves #3216
This pull request is being made to improve the language for automated **Stale** bot comments and to add the **pull request submitted** label to the exempt list.
> Improve Stale bot implementation

- DNN Platform/Library/Entities/Portals/PortalController.cs
To fix following issue
https://github.com/dnnsoftware/Dnn.Platform/issues/3233
> Fix Typo "Frind" to "Friendly issue #3233

- DNN Platform/Modules/DigitalAssets/FileProperties.ascx.cs
Small correction on property getter
> Improve querystring parse

- DNN Platform/Library/Data/DataProvider.cs
> Improve input checking of sites

- .github/stale.yml
> Improve Stale bot messaging

- DNN Platform/Library/Common/Globals.cs
- DNN Platform/Library/Services/Url/FriendlyUrl/FriendlyUrlProvider.cs
> Add PortalSettings overloads back

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/help-and-other-questions.md
- .github/ISSUE_TEMPLATE/request-for-comments.md
- .github/ISSUE_TEMPLATE/security-issue.md
Updates issue templates as per 9.4.2 being released.
> Updates issue templates as per 9.4.2 release

- DNN Platform/Website/controls/user.ascx
For issue #3305
This will put email address field above username on the User.ascx form
> Move Email Above Username in User.ascx #3305

- DNN Platform/Modules/Journal/module.css
Issue #2225 
Keeps words from breaking in journal posts.
> Word-Break added to Journal P

- DNN Platform/Website/Portals/_default/Skins/_default/WebControlSkin/Default/GridView.Default.css
- DNN Platform/Website/admin/Modules/Modulesettings.ascx
- DNN Platform/Website/admin/Modules/Modulesettings.ascx.cs
In Module Settings > Added to Pages section, the pager does not work when there is a large number of pages.
Closes #2897
> Fix ModuleSettings > Added to Pages grid, pager wasn't working Issue #2897

- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Sites.Web/src/components/CreatePortal/index.jsx
> Allow only alphanumeric characters to be used when forming url from name

- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Servers.Web/src/components/App.jsx
> Reload page when the code tells you to

- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/Components/Security/Resources/sums.resources
Closes #3324 
Adds checksums for the security analyzer in 9.4.3
> Updates checksums for Dnn 9.4.3

- Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/Components/Security/Resources/sums.resources
Adding missing checksums for the Security Analyzer.
> Added missing checksums

- DNN Platform/Website/Install/DotNetNuke.install.config.resources
#3345
Updates references for DotNetNuke resources and SMTP Testing
> Updates References To DotNetNuke

- DNN Platform/Website/Install/DotNetNuke.install.config.resources
For Issue: https://github.com/dnnsoftware/Dnn.Platform/issues/3345
Updates DotNetNuke CMS References in Host Template
> Updates DotNetNuke References

- DNN Platform/HttpModules/UrlRewrite/BasicUrlRewriter.cs
- DNN Platform/Library/Common/Utilities/UrlUtils.cs
- DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
> ssl offloading need to check the header value as well.

- DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
> do not replace the protocol in query string.

- Website/Install/Config/09.05.00.config
This PR includes a configuration merge script to be used as part of the installation/upgrade process for 9.4.0 to cleanup the installation from old data.
> Added Configuration Merge Script for 9.5.0

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageLocalization/PageLanguage.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/DnnPageDto.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
This is a clone of https://github.com/dnnsoftware/Dnn.AdminExperience/pull/996, which didn't make it to Dnn.Platform repo after the merge.
> Error message while deleting localized version of home page

- DNN Platform/Library/Framework/JavaScriptLibraries/JavaScript.cs
> resolve the cdn path with correct protocol.

- .github/stale.yml
> Update stale bot configuration to accommodate new Issue Management system

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
Add "Status: New" label to all new Bug and Enhancement issues.
Resolves #3432
> Update issue templates to auto apply correct label

- .github/ISSUE_TEMPLATE/config.yml
> Add issue template configuration to redirect users

- DNN Platform/Library/Application/Application.cs
- DNN Platform/Website/Install/Config/09.05.00.config
- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SecurityController.cs
Resolves #3442 by changing the Update Service URL to use the new community provided one.
> Changed Update Service to Community URL for both install & upgrade

- .github/ISSUE_TEMPLATE/bug-report.md
adjust current DNN version number
> adjust DNN version number

- DNN Platform/Library/Common/Utilities/UrlUtils.cs
> DNN-35719: page in redirect mode doesn't work under ssl offloading environment.

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Connectors/Connectors.html
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Connectors/scripts/Connectors.js
Fixes #3450 
Please note that this PR is dependent on #3448 so that it should be merged first. Only change that was introduced as for this PR's scope was changing the binding name in Connectors.html from "name" to the "displayName".
Demo: https://drive.google.com/file/d/1KkwhcKKRY9GPNn_qHThh4ck-gahkQ1Pt/view
> DNN-35706 - Azure Storage connector changes its name when adding multiple connectors

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.TaskScheduler/App_LocalResources/TaskScheduler.resx
> fix typo "FreindlyName" #3484

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
This key was accidentally deleted during earlier work on GDPR compliance.
> Reinstate an old key that was deleted

- DNN Platform/Providers/FolderProviders/AzureFolderProvider/App_LocalResources/Settings.ascx.resx
Fix a minor obvious typo (no issue created)
> fix a Typo in Azurefolder > Settings.ascx.resx

- .github/mergeable.yml
> Enforce milestone assignment to merge a PR

- .github/mergeable.yml
> Enforce 'Type' label assignment to merge a pull request

- .github/mergeable.yml
> Update mergeable.yml to remove fail action

- DNN Platform/Website/Resources/Shared/scripts/jquery/jquery.fileupload.js
- DNN Platform/Website/Resources/Shared/scripts/jquery/jquery.iframe-transport.js
The existing jquery upload component is outdated. This is version 10.7.0 which is the latest version.
Preliminary testing on my dev machine shows no breaking changes.
> Update Blueimp uploader to latest version

- DNN Platform/Library/Entities/Portals/PortalSettings.cs
- DNN Platform/Library/Services/FileSystem/Providers/StandardFolderProvider.cs
> Don't expose file last modifed date/time via cachebusted URLs

- DNN Platform/Library/Common/Utilities/FileSystemExtensions.cs
- DNN Platform/Library/Common/Utilities/FileSystemUtils.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/FileSystem/FileManager.cs
- DNN Platform/Library/Services/Installer/InstallerInfo.cs
- DNN Platform/Library/Services/Installer/Installers/ResourceFileInstaller.cs
- DNN Platform/Library/Services/Installer/Packages/PackageController.cs
- DNN Platform/Library/UI/Skins/SkinController.cs
- Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/reducers/pagination.js
This adds a sanity check on filenames from zipfiles
> Add check on filename in zip files

- DNN Platform/Library/Services/Search/Controllers/ModuleResultController.cs
- DNN Platform/Library/Services/Search/Controllers/TabResultController.cs
Fix #3546
ESW JIRA number: DNN-36584
> don't display the disabled pages in search result.

- .github/workflows/image-actions.yml
This adds a GitHub Actions workflow which optimizes images automatically in pull requests.
Retrying #3253 now that GitHub Actions is enabled for the repo.
> Add PR workflow to optimize images

- .github/workflows/image-actions.yml
See https://github.com/calibreapp/image-actions/blob/08437f2fb2e1548570f2e24cf8c902191c2f5432/README.md#installation for "expected" config
Should fix failure of this check in #3596
> Fix image-actions configuration

- DNN Platform/Library/Common/Utilities/FileSystemExtensions.cs
- DNN Platform/Library/Common/Utilities/FileSystemUtils.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/FileSystem/FileManager.cs
- DNN Platform/Library/Services/Installer/InstallerInfo.cs
- DNN Platform/Library/Services/Installer/Installers/ResourceFileInstaller.cs
- DNN Platform/Library/Services/Installer/Packages/PackageController.cs
- DNN Platform/Library/UI/Skins/SkinController.cs
As part of 9.5.1 RC, there was changes that needs to be merged back into develop for continuity. As per our policy about release management tasks, I will self-approve this PR.
> Merges latest changes from 9.5.1 back into develop

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.05.01.SqlDataProvider
Fix #3604 (missing tokens) in SProc CoreMessaging_GetNextMessagesForDigestDispatch from DNN 9.5.0)
> Fix missing databaseOwner/objectQualifier in CoreMessaging sproc.

- DNN Platform/Website/Portals/_default/admin.css
https://github.com/dnnsoftware/Dnn.Platform/issues/3581
Fixes https://github.com/dnnsoftware/Dnn.Platform/issues/3581
Created this PR to resolve the action button style at the bottom of registration module when added to pages and while logged in as administrator.
> .dnnActions change inline-block to block

- DNN Platform/Website/DesktopModules/Admin/Security/DataConsent.ascx
- DNN Platform/Website/DesktopModules/Admin/Security/DataConsent.ascx.cs
Fixes Issue #3193 
Alternative to PR #3609
> Fix to data consent feature when wrapped in UpdatePanel

- DNN Platform/Website/Resources/Shared/scripts/jquery/jquery.fileupload.js
This is a replay of PR #3631 that was accidentally merged into develop instead of release/9.5.1 but there was request to get this into 9.5.1 which I read after merging the PR.
> Pr3631redo

- DNN Platform/DotNetNuke.Web.Mvc/Extensions/StartupExtensions.cs
Fixes #3634, thanks @DaveMartinSE!
> Fix error when MVC module is on a page multiple times

- DNN Platform/DotNetNuke.Web.Mvc/Extensions/StartupExtensions.cs
- DNN Platform/Website/Resources/Shared/scripts/jquery/jquery.fileupload.js
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Repository/PersonaBarRepository.cs
This is a release management task and we are self approving it for that reason. 
Due to COVID-19 we are postponing the 9.5.1 release due to multiple factors, due to community slowdown regarding testing, ability to install by companies, etc.
> Updates develop with latest changes from release/9.5.1

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.05.01.SqlDataProvider
Fixing a batch size issue in the previous version of this PR
Relates to #3604
> Adds objectQualifier and databaseOwner to messaging sql for upgrades

- DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
- DNN Platform/Tests/App.config
- DNN Platform/Website/Install/Config/05.02.00.config
- DNN Platform/Website/Install/Config/05.02.01.config
- DNN Platform/Website/Install/Config/09.06.00.config
This completes work from a PR #3673 where we adjusted bindings
> Remove items from default web.config

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
Resolves #3694 
Also resolves the same issue with the `enhancement-request` issue template.
> Correct CONTRIBUTING links in issue templates

- DNN Platform/Library/Services/Scheduling/ProcessGroup.cs
- DNN Platform/Library/Startup.cs
Fixes #3602, thanks for the direction @dimarobert!
> Add DI support to scheduler

- DNN Platform/Website/admin/Skins/Toast.ascx.cs
> Add Services Framework call to Toast skin object

- Build/BuildScripts/AEModule.build
- Build/Cake/version.cake
- DNN Platform/Modules/ResourceManager/Module.build
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/webpack.config.js
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/yarn.lock
- DNN Platform/Modules/ResourceManager/ResourceManager.dnn
- DNN Platform/Modules/ResourceManager/View.ascx.cs
Currently the react scripts are not built when running a build. This PR fixes that.
> Ensure yarn runs when module is built

- DNN Platform/Website/DesktopModules/Admin/SearchResults/SearchResults.ascx.cs
This code change was merged into an obsolete branch with PR #3333 and fixes #3332
> Redo PR #3333

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.02.SqlDataProvider
Tested performance configuration to fix #3757 for 9.6.2
> DB Performance Improvement

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/EditUrl.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PageUrlsController.cs
closes issue #3750
Change the default selected site alias so primary alias instead of the first in the list
> Solves issue #3750

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/FileUpload/index.jsx
- Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/basicSettings/index.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
Fixes #3722.
Validation code was supplied in SiteSettingsController.cs so it is available in basicStting react component and we pass it along to FileUploadController.UploadFromLocal API .
> Fix logo/icon upload in site setting for #3722

- .github/ISSUE_TEMPLATE/bug-report.md
> adjust version

- DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.resx
Fixes #3792 
Updated links to more recent DNN Community site, for now just default culture.
@sleupold can you please explain how "DNN improvement program" is outdated, is it new page for this program? or this program is discontinued and this should be removed at all from install wizard?
please advice
> Update outdated links for #3792 - part 1 - for default culture

- Dnn.AdminExperience/ClientSide/Servers.Web/package.json
- Dnn.AdminExperience/ClientSide/Servers.Web/src/actions/logsTab.js
- Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/LogFileRow/index.jsx
- Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/LogFileRow/style.less
- Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/Logs.jsx
- Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/tabs.less
- Dnn.AdminExperience/ClientSide/Servers.Web/src/services/logsTabService.js
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Servers/Log/LogController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Servers/Log/LogFile.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsLogsController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Servers/App_LocalResources/Servers.resx
Fixes #3827 
Use listing similar to Event Log, rather than dropdown
Order by last modified date
Show the size
> Update display of server log files

- DNN Platform/Website/DesktopModules/Admin/ViewProfile/Settings.ascx
- DNN Platform/Website/Resources/Shared/components/ComposeMessage/ComposeMessage.js
> Removed maxlength from ViewProfiles/Settings.ascx

- DNN Platform/Library/Common/Utilities/UrlUtils.cs
> Revert "DNN-35719: page in redirect mode doesn't work under ssl offloading environment"

- DNN Platform/Website/DotNetNuke.Website.csproj
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.02.SqlDataProvider
An error crept in with PR #3797 with casing of objectQualifier and databaseOwner
> Fix casing issues in 9.6.2 data provider script

- DNN Platform/Website/DotNetNuke.Website.csproj
- DNN Platform/Website/Install/InstallWizard.aspx
- DNN Platform/Website/Install/InstallWizard.aspx.cs
- DNN Platform/Website/Install/InstallWizard.aspx.designer.cs
Fixes #3857 
It looks like some change with Stylecop auto-fixes caused issues with this file.
I fixed the issue in one commit then I resolved all Stylecop warnings (for this file, don't get your hopes up too much) on another commit.
> Fixes install wizard

- DNN Platform/DotNetNuke.Web/InternalServices/FileUploadController.cs
- DNN Platform/DotNetNuke.Web/UI/WebControls/DnnFileUploadOptions.cs
- DNN Platform/Modules/ResourceManager/View.ascx.cs
> Update file upload validation - ResourceManager

- DNN Platform/Website/Install/Config/09.06.02.config
#3829 was merged without testing. It did not work on upgrades, this PR fixes it
> Fixes an issue where webp support would not work on upgrades.

- DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
- DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.nl-NL.resx
Close #3868 
Just text corrections in nl-NL.resx files
> nl nl text installwizard & upgradewizard improvements

- Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
- Dnn.AdminExperience/ClientSide/Pages.Web/package.json
- Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
- Dnn.AdminExperience/ClientSide/Seo.Web/package.json
- Dnn.AdminExperience/ClientSide/Servers.Web/package.json
- Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
- Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
- yarn.lock
Switch to `@babel/core` package instead of `babel-core`
Resolves #3087
> Switch to @babel/core package instead of babel-core

- DNN Platform/Website/App_GlobalResources/SharedResources.resx
> Update alert to refer to Admin Logs vs Event Viewer

- DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
- DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.nl-NL.resx
> Small textual nl-NL improvements on DNN962-RC2

- DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
> Improve install page nl-NL  text

- DNN Platform/DotNetNuke.Abstractions/INavigationManager.cs
- DNN Platform/DotNetNuke.Abstractions/Portals/IPortalAliasInfo.cs
- DNN Platform/DotNetNuke.Abstractions/Portals/IPortalSettings.cs
- DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandHelp.cs
- DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandRepository.cs
- DNN Platform/DotNetNuke.Abstractions/Prompt/IConsoleCommand.cs
- DNN Platform/DotNetNuke.Abstractions/Users/IUserInfo.cs
Move using statements inside namespace for DotNetNuke.Abstractions project
> Move using statements inside namespace for DotNetNuke.Abstractions project

- DNN Platform/Library/Entities/Modules/PortalModuleBase.cs
Uses a DI scope to ensure dependencies are disposed correctly.
Fixes #3929
> Ensure DI services are disposed in WebForms

- DNN Platform/Library/Entities/Tabs/TabInfo.cs
This is an improvement to #3903
> Use Ordinal comparison for Boolean check

- DNN Platform/Library/Entities/Tabs/TabInfo.cs
> Deprecate TabInfo.TabPermissionsSpecified

- Dnn.AdminExperience/ClientSide/Seo.Web/src/actions/seo.js
- Dnn.AdminExperience/ClientSide/Seo.Web/src/components/testUrl/index.jsx
- Dnn.AdminExperience/ClientSide/Seo.Web/src/reducers/seoReducer.js
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SeoController.cs
resolves #3947 
Passes admin role id to front end
> Provide administrators role id to the test url page

- DNN Platform/DotNetNuke.Abstractions/README.md
- DNN Platform/DotNetNuke.DependencyInjection/README.md
@ahoefling and I were discussing the goals and guidelines for the DotNetNuke.Abstractions project, so I wrote up some guidelines, hoping that we could discuss and then document the plans for this project, and how it fits into the overall approach and direction of the DNN Platform.
> Add documentation to new .NET Standard projects

- .github/CODE_OF_CONDUCT.md
This pull request adds an official code of conduct file to the repo.  This follows the standard language used by other repos that have adopted the .NET Foundation Code of Conduct.
> Add official code of conduct file

- DNN Platform/Website/ErrorPage.aspx
Fixes #4054 
Changes "DNN Error" to "Application Error" in ErrorPage.aspx
I was not sure exactly what to change this to in order to make it more generic and accepted by the community.  Maintainers more than welcome to make adjustments as needed.
1.  Site Error
2.  Application Error
3.  App Error
4.  Create localization for this along with changing from DNN to one of the above
> Change 'DNN Error' to 'Application Error'

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs
Fixes #4066 
Duplicate check is added for multi-page addition. The validation considers the same-named pages in different hierarchies as well.
Demo: https://drive.google.com/file/d/1lWurDaDGXlM6XBYRwQqWb_plMmnhXiIx/view?usp=sharing
> Issue-4066 - Create multiple pages validation passed with same page name on same hierarchy

- DNN Platform/Website/DotNetNuke.Website.csproj
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.01.SqlDataProvider
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.07.00.SqlDataProvider
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.07.02.SqlDataProvider
Closes #4075
- Adds missing SqlDataProvider files
> Fixed an issue that prevents 9.7.0 to 9.7.1 upgrades

- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ModuleDialog.js
> Fix module dialog adding new module to wrong pane

- Dnn.AdminExperience/ClientSide/Servers.Web/src/components/App.jsx
> Address React invariant violation

- DNN Platform/Website/App_GlobalResources/GlobalResources.resx
> Add portal name to SMTP test email for better identification

- DNN Platform/Website/Install/Config/09.07.03.config
This change was missed from #4121
> Remove beacon setting on upgrade

- DNN Platform/Website/DotNetNuke.Website.csproj
09.07.03.config was updated in #4121 but it was not added into the project. This PR adds it back.
> Adds 09.07.03.config into the project

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/SqlConsole.html
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/css/SqlConsole.css
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/scripts/SqlConsole.js
Resolves #4168 
Please see the linked issue for more details on why this was implemented without package management.  It is a stepping-stone PR to get the editor integrated into a project that does not already have package management set up.
> Swap CodeMirror in SqlConsole for monaco-editor

- Build/BuildScripts/AEModule.build
Resolves #4177 
This has been whacked up for a long time, wasting hours upon hours of time, but I finally had time to track this down and fix it.
> Fix MSBuild issue with Dnn.PersonaBar.Extensions

- DNN Platform/Modules/DDRMenu/DDRMenu.dnn
Closes #3942 by adding the system designation to the DDR Menu
> Updated DDR Menu to be System Package

- .github/RELEASE_SCHEDULE.md
Updated per discussion during the Approvers Discussion to better reflect the process
> Updated Release Schedule Documentation

- DNN Platform/Admin Modules/Dnn.Modules.Console/Components/BusinessController.cs
- DNN Platform/Admin Modules/Dnn.Modules.Console/Components/ConsoleController.cs
- DNN Platform/Admin Modules/Dnn.Modules.Console/Dnn.Modules.Console.csproj
- DNN Platform/Admin Modules/Dnn.Modules.Console/Properties/AssemblyInfo.cs
- DNN Platform/Admin Modules/Dnn.Modules.Console/Settings.ascx.cs
- DNN Platform/Admin Modules/Dnn.Modules.Console/ViewConsole.ascx.cs
- Fixed all stylecop warnings in the Console module project
- Enabled TreatWarningsAsErrors for the project
> Fixed all build warnings in Console module

- DNN Platform/Library/Services/Installer/XmlMerge.cs
> Ensure comments are only inserted when necessary

- DNN Platform/Modules/DnnExportImport/Components/Services/PackagesExportService.cs
> avoid I/O process frequency during export process.

- DNN Platform/HttpModules/Membership/MembershipModule.cs
Fixes #4222 
Current culture can change according to the opened URL (e.g. dnn.../fr-fr, dnn.../ro-ro), therefore, it shouldn't be static. 
Demo: https://drive.google.com/file/d/1uQl8EWtVk_wRZRvrfLKAw-dR4JIIeVpZ/view?usp=sharing
> Issue-4222 - Registration Module system messages use an incorrect language

- DNN Platform/Admin Modules/Dnn.Modules.Console/Components/BusinessController.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddModule.ascx.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/ControlBar.ascx.cs
- DNN Platform/Library/Common/Globals.cs
- DNN Platform/Library/Entities/Portals/PortalSettings.cs
- DNN Platform/Library/Services/Personalization/Personalization.cs
- DNN Platform/Library/UI/Containers/ActionBase.cs
- DNN Platform/Library/UI/Containers/ActionManager.cs
- DNN Platform/Library/UI/ControlPanels/ControlPanelBase.cs
- DNN Platform/Library/UI/Modules/Html5/Html5ModuleTokenReplace.cs
- DNN Platform/Library/UI/Modules/ModuleHost.cs
- DNN Platform/Library/UI/Modules/ModuleInstanceContext.cs
- DNN Platform/Library/UI/Skins/Pane.cs
- DNN Platform/Library/UI/WebControls/ActionLink.cs
- DNN Platform/Modules/HTML/Components/HtmlTextController.cs
- DNN Platform/Modules/HTML/HtmlModule.ascx.cs
- DNN Platform/Website/Default.aspx.cs
- DNN Platform/Website/admin/Containers/PrintModule.ascx.cs
- DNN Platform/Website/admin/Containers/Title.ascx.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PagesControllerImpl.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Controllers/ContentEditorManager.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/AddExistingModuleMenu.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/AddModuleMenu.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/ExitEditModeMenu.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/PageSettingsMenu.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Containers/PersonaBarContainer.cs
Closes #4213
I am open to any feedback on this, I do believe this way would not be a breaking change...
> Moved UserMode from PortalSettings to Personalization class

- DNN Platform/Library/Entities/Portals/PortalInfo.cs
- DNN Platform/Library/Entities/Portals/PortalSettings.cs
- DNN Platform/Library/Entities/Users/Profile/ProfilePropertyAccess.cs
- DNN Platform/Library/Entities/Users/Profile/UserProfile.cs
- DNN Platform/Library/WebControls/WebControlBase.cs
- DNN Platform/Modules/DDRMenu/Localisation/Apollo.cs
- DNN Platform/Modules/DDRMenu/Localisation/Ealo.cs
This moves everything that was marked deprecated in v9.x.x but was slated for removal in v10 to now be removed in v11.
> Moves things deprecated in v9 to be removed in v11 instead of v10

- DNN Platform/Library/Entities/Modules/IActionable.cs
- DNN Platform/Library/Entities/Modules/ModuleSettingsBase.cs
- DNN Platform/Library/UI/Modules/IModuleControl.cs
- DNN Platform/Library/UI/Modules/ISettingsControl.cs
- DNN Platform/Library/UI/Modules/ModuleUserControlBase.cs
- DNN Platform/Modules/RazorHost/AddScript.ascx.cs
- DNN Platform/Modules/RazorHost/CreateModule.ascx.cs
- DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
- DNN Platform/Modules/RazorHost/EditScript.ascx.cs
- DNN Platform/Modules/RazorHost/RazorHost.ascx.cs
- DNN Platform/Modules/RazorHost/RazorHostSettingsExtensions.cs
- DNN Platform/Modules/RazorHost/Settings.ascx.cs
- Resolves all build warnings
- Enables Treat Warnings as Errors on project
> Resolved all build warnings in RazorHost project

- DNN Platform/Admin Modules/Dnn.Modules.Console/Components/BusinessController.cs
- DNN Platform/Connectors/GoogleAnalytics/Constants.cs
- DNN Platform/Connectors/GoogleAnalytics/Dnn.GoogleAnalyticsConnector.csproj
- DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
- Resolved all build warnings in Google Analytics Connector
- Enabled TreatWarningsAsErrors on project
> Resolved all build warnings in Google Analytics Connector

- DNN Platform/Admin Modules/Dnn.Modules.Console/Components/BusinessController.cs
- DNN Platform/Library/UI/Containers/ActionBase.cs
- DNN Platform/Library/UI/Containers/IActionControl.cs
- DNN Platform/Modules/DDRMenu/Actions.cs
- DNN Platform/Modules/DDRMenu/Common/DNNContext.cs
- DNN Platform/Modules/DDRMenu/Common/PathResolver.cs
- DNN Platform/Modules/DDRMenu/Common/Utilities.cs
- DNN Platform/Modules/DDRMenu/Controller.cs
- DNN Platform/Modules/DDRMenu/DDRMenuControl.cs
- DNN Platform/Modules/DDRMenu/DDRMenuNavigationProvider.cs
- DNN Platform/Modules/DDRMenu/DNNAbstract.cs
- DNN Platform/Modules/DDRMenu/INodeManipulator.cs
- DNN Platform/Modules/DDRMenu/Localisation/Apollo.cs
- DNN Platform/Modules/DDRMenu/Localisation/Ealo.cs
- DNN Platform/Modules/DDRMenu/Localisation/Generic.cs
- DNN Platform/Modules/DDRMenu/Localisation/ILocalisation.cs
- DNN Platform/Modules/DDRMenu/Localisation/Localiser.cs
- DNN Platform/Modules/DDRMenu/MenuBase.cs
- DNN Platform/Modules/DDRMenu/MenuNode.cs
- DNN Platform/Modules/DDRMenu/MenuSettings.ascx.cs
- DNN Platform/Modules/DDRMenu/MenuView.ascx.cs
- DNN Platform/Modules/DDRMenu/Settings.cs
- DNN Platform/Modules/DDRMenu/SkinObject.cs
- DNN Platform/Modules/DDRMenu/TemplateEngine/RazorTemplateProcessor.cs
- DNN Platform/Modules/DDRMenu/TemplateEngine/TemplateDefinition.cs
- DNN Platform/Modules/DDRMenu/TemplateEngine/TokenTemplateProcessor.cs
- DNN Platform/Modules/DDRMenu/TemplateEngine/XsltTemplateProcessor.cs
Resolves multiple build warnings on the DDRMenu Project
This is still a work in progress, some of it I want to undo, just submitting the draft to no forget continuing this a bit later this week...
> Resolves some build warnings in DDRMenu Project

- DNN Platform/Library/Common/Controls/Form.cs
- DNN Platform/Library/Common/HttpContextSource.cs
- DNN Platform/Library/Common/Initialize.cs
- DNN Platform/Library/Common/Internal/EventHandlersContainer.cs
- DNN Platform/Library/Common/Internal/IEventHandlersContainer.cs
- DNN Platform/Library/ComponentModel/ComponentBase.cs
- DNN Platform/Library/Entities/EventManager.cs
- DNN Platform/Library/Entities/IEventManager.cs
- DNN Platform/Library/Framework/ServiceLocator.cs
- DNN Platform/Library/Services/Tokens/BaseCustomTokenReplace.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FileManagerTests.cs
I would use some advice on correct replacement in EventManager.cs for the deprecated EventLogController.EventLogType
and
EventLogController.Instance.AddLog call if anyone has some idea on how to refactor that properly. If not, then let's not block this PR for just this and revisit this part later.
> Resolves some more build warnings on library project

- DNN Platform/DotNetNuke.Web/InternalServices/ControlBarController.cs
> check the module permission to add module.

- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
It'll get added by `09.08.00.config`, having it already in there will create a duplicate
Thanks @daguiler for pointing out this issue with #4251!
> Remove Localization HTTP module from config

- DNN Platform/HttpModules/OutputCaching/OutputCacheModule.cs
- DNN Platform/Library/Services/OutputCache/OutputCacheResponseFilter.cs
Fixes #4278 
Prevented caching of the page output if the page is redirected.
> do not cache output if page is redirected

- Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/index.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/SiteSettings/UpdateOtherSettingsRequest.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Adding InjectModuleHyperlink and InlineEditorEnabled to the SiteSettings module
> Add two more settings to the personabar

- DNN Platform/Library/Data/DataProvider.cs
> Remove deprecation for some DataProvider methods

- Dnn.AdminExperience/ClientSide/Extensions.Web/src/components/InstallExtensionModal/FileUpload/index.jsx
Fixes https://github.com/dnnsoftware/Dnn.Platform/issues/4256
Updated error message to display error count only if errorcount is > 0
> Fixes invalid extension error message for 0 errors

- DNN Platform/Library/Data/SqlDataProvider.cs
Fixes issue introduced by #4258, supersedes #4299
> Fix data provider always failing

- azure-pipelines.yml
Trying to adjust included branches for azure pipeline
> Trying to adjust included branches for azure pipeline

- DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Urls/AdvancedUrlRewriterTests.cs
Fixes #4336 
The page was getting redirected to itself due to an encoding mismatch which is fixed now.
Demo: https://drive.google.com/file/d/1NFn9eJZS7rkPwPbND4vhrT92w4qh1o5l/view?usp=sharing
> Issue-4336 - Umlaut characters in URL cause module setting error

- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> Inherit Monaco font (instead of using Roboto)

- DNN Platform/Website/Resources/Shared/scripts/jquery/jquery-vsdoc.js
This doc file was out of date with the actual `jQuery.js` in the same folder.
> Update vsdoc file for jQuery to 3.4.1

- DNN Platform/Library/Entities/Portals/PortalController.cs
- DNN Platform/Website/Portals/_default/Blank Website.template
- DNN Platform/Website/Portals/_default/Default Website.template
Fixes #3959 by adding support for the sitemap properties in the portal template
> Properly configure SiteMap on portal creation

- DNN Platform/Library/Services/GeneratedImage/ImageHandlerInternal.cs
> Don't check user permissions unless there's a user

- .github/ISSUE_TEMPLATE/bug-report.md
This is a release management task, as per our policy, we are are self approving it.
> Updates bug report template as per 9.8.1rc1 release

- DNN Platform/Website/DesktopModules/Admin/Portals/portal.template.xsd
> Add sitemap settings to portal template XSD

- Build/Symbols/license.txt
- DNN Platform/Admin Modules/Dnn.Modules.Console/license.txt
- DNN Platform/Connectors/Azure/license.txt
- DNN Platform/Dnn.AuthServices.Jwt/license.txt
- DNN Platform/DotNetNuke.Web.Deprecated/license.txt
- DNN Platform/DotNetNuke.WebUtility/license.txt
- DNN Platform/DotNetNuke.Website.Deprecated/license.txt
- DNN Platform/Modules/CoreMessaging/license.txt
- DNN Platform/Modules/DDRMenu/License.txt
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/license.txt
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/license.txt
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/license.txt
- DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/License.txt
- DNN Platform/Providers/FolderProviders/license.txt
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Install/license.txt
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/license.txt
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/LICENSE.txt
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/License.txt
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/license.txt
- Dnn.AdminExperience/LICENSE.txt
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/license.txt
Closes #4414 by adjusting all license manifest values to be consistent
> Corrected all license.txt files for module installers to be consistent

- Build/Cake/unit-tests.cs
This PR adds more tests to the unit testing done during CI (via Cake).  #4250 fixed some of these tests but did not enable them.
> Enable more tests

- .github/BUILD.md
Add documentation to build React projects. Upon request :-)
> Improve build documentation

- DNN Platform/Library/Services/Mail/CoreMailProvider.cs
- DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
> Add BCC and CC before sending the email

- Build/Build.csproj
> Upgrade to stable version of Cake

- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/config.js
Fixes #4491.
This change has been working for me for months and I haven't noticed any other regressions, but I'm not sure what other things this might affect.
> Fix PersonaBar loading when within an iframe

- DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
> Address potential email parsing error

- Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
- Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/Components/ListView/index.jsx
- yarn.lock
> Resolve issue with dayjs relativeTime plugin and locale

- Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/helpers.js
> Resolved localized date formats

- .github/ISSUE_TEMPLATE/bug-report.md
Updates bug report as per 9.9.0 release
This is a release management task, as per our policy, we are are self approving it.
> Updates bug report as per 9.9.0 release

- DNN Platform/Modules/HTML/Components/HtmlTextController.cs
> Make sure the content is decoded before being passed to tokenization providers.

- Build/Tasks/packaging.json
> Don't include System.Buffers in bin

- DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
> Fix MailKitMailProvider using incorrect priority

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Helper/TreeViewHelper.cs
> Fix HTML Editor Manager failure to load

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteGroups/App_LocalResources/SiteGroups.resx
Some minor improvements to the wording of the Site Groups module
> Improved wording on Site Groups localization

- DNN Platform/Website/App_GlobalResources/Prompt.resx
Fixes some typos, clarifies some things, uses consistent punctuation, etc.
> Fixed some typos in Prompt localization

- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> Resolve issues with hover and locked styles for new PersonaBar icons

- Build/Tasks/packaging.json
- DNN Platform/Components/Microsoft.AspNetMvc/Microsoft.AspNetMvc.dnn
- DNN Platform/Components/Microsoft.AspNetWebPages/Microsoft.AspNetWebPages.dnn
- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
Updated develop with latest changes from 9.10.0 RC
> Updated develop with latest changes from 9.10.0 RC

- DNN Platform/Website/Install/Config/BindingRedirect.config
- DNN Platform/Website/Install/Config/RemoveBindingRedirect.config
> Make binding redirect XML Merge case sensitive

- DNN Platform/Website/Install/Config/BindingRedirect.config
- DNN Platform/Website/Install/Config/RemoveBindingRedirect.config
Merging regression fixes from v9.10.0 into develop
This is a release management task, as per our policy, we are are self approving it.
> Merging regression fixes from v9.10.0 into develop

- DNN Platform/Website/Default.aspx.cs
> Ensure dnn.js is requested for cookie consent

- .github/workflows/updateVersions.yml
> Fixed an issue with issue template and version update action

- .github/ISSUE_TEMPLATE/bug-report.md
Updates issue template as per current state
> Updates issue template as per current state

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/plugins/dnnpages/lang/fr.js
Fixed an issue that prevented inserting links using the default HTML Editor Provider
Closes #4801
> Fixed an issue that prevented inserting links using the default HTML Editor Provider

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/plugins/dnnpages/lang/fr.js
Corrected a typo in CKEditor for dnnpages plugin in french
> Corrected a typo in CKEditor for dnnpages plugin in french

- DNN Platform/Connectors/Azure/Dnn.AzureConnector.csproj
- DNN Platform/Connectors/Azure/packages.config
> Remove unused RestSharp reference

- Build/Tasks/OtherPackages.cs
- Build/Tasks/PackageMicrosoftGlobbing.cs
- Build/Tasks/packaging.json
- Build/Tasks/thirdparty.json
- DNN Platform/Components/Microsoft.Extensions.FileSystemGlobbing/License.txt
- DNN Platform/Components/Microsoft.Extensions.FileSystemGlobbing/Microsoft.Extensions.FileSystemGlobbing.dnn
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/packages.config
- DNN_Platform.sln
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/app.config
> Created package for Microsoft.Extensions.FileSystemGlobbing

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/packages.config
- DNN Platform/Skins/Xcillion/DotNetNuke.Skins.Xcillion.csproj
- DNN Platform/Skins/Xcillion/packages.config
- Dnn.AdminExperience/EditBar/Dnn.EditBar.Library/Dnn.EditBar.Library.csproj
- Dnn.AdminExperience/EditBar/Dnn.EditBar.Library/packages.config
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/app.config
This bumps the remaining projects that were still refencing the older versions of the library to our currently distributed version.
Closes #3994
> Replaced old Newtonsoft.Json references

- DNN Platform/DotNetNuke.Web.Client/ClientResourceSettings.cs
Added a check to see if HttpContext is available before accessing it
> fix null pointer exception when called from scheduled tasks (fixes #4898)

- DNN Platform/Library/Entities/Urls/AdvancedFriendlyUrlProvider.cs
> Fix #4910: check the page name with case insensitive.

- DNN Platform/Website/Portals/_default/Blank Website.template
- DNN Platform/Website/Portals/_default/Default Website.template
> Updated website templates to make `Activity Feed`, `My Profile`, `Friends`, and `Messages` pages visible to `Registered Users` only by default

- DNN Platform/Website/admin/Security/SendPassword.ascx.cs
Content added to message needs to be encoded to ensure proper display
> HTML encode message input

- DNN Platform/Library/UI/Skins/Skin.cs
Reverts dnnsoftware/Dnn.Platform#4930
> Revert "No module message should be able to contain any scripts"

- Build/Tasks/CreateUpgrade.cs
- DNN Platform/Modules/ResourceManager/Module.build
Change the extension of the install file to zip so it will install by default. 
Resolves #4944
> Ensure Resource Manager installs by default

- .github/BUILD.md
We moved CkEditor in here, so this PR updates our build docs accordingly.
> Corrected external repositories in build.md

- .github/BUILD.md
Looks like Cake took that part out of their new docs but this link still has the info.
> Adjusted link to powershell security docs for cake

- DNN Platform/Website/DotNetNuke.Website.csproj
I saw a warning that these two files were references twice in the `csproj` file, so I removed once of the references (the others are just a couple of lines above).
> Remove duplicate files from csproj

- DNN Platform/Library/Services/Installer/Installers/PackageInstaller.cs
> Show error on package parse

- Build/Build.csproj
This PR upgrades Cake from 2.0.0 to 2.2.0
> Upgrade Cake.Frosting from 2.0.0 to 2.2.0

- package.json
- yarn.lock
> Upgrade Lerna from 3.x to 5.3.0

- .github/workflows/open-merged-pr-to-future-9.11.0.yml
This action is running into an error resolved in repo-sync/pull-request@v2.6.2
> Specify latest version for 9.11 merge action

- DNN Platform/JavaScript Libraries/jQueryUI/jQueryUI.dnn
Fix issue in #5116 where file was renamed in one place but not another.
> Fix wrong file name for jQuery UI

- Dnn.AdminExperience/ClientSide/Extensions.Web/src/components/DeleteExtension/index.jsx
Fixes #3778
In the delete extensions PersonaBar, the version of the module is not displayed and I fixed that problem
please go to delete the extension in PersonaBar
> Fixed issue where the uninstall extension shows version 0.0.0

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.00.SqlDataProvider
> Add missing databaseOwner and objectQualifier

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
- Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
- Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/main.jsx
- yarn.lock
Fixes https://github.com/dnnsoftware/Dnn.Platform/issues/5290
The actual fix for the reported issue was done in https://github.com/DNNCommunity/dnn-elements/pull/579
This PR pulls in that new version and also updates the other dependencies on this project.
> Updated dependencies on dnn-resource-manager

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/readme.md
- yarn.lock
In earlier PRs the yarn.lock file was updated apparently in a wrong way.
I did a git bisect to find the commit that initially caused the issue and it was ee066b46c99b5304f1cd9437f225e623474cfaed which only touched the yarn.lock file. I reverted that commit and cleaned all local files (node_modules, caches, etc.) Then I rand a full build which updated the yarn.lock file properly and this build worked fine locally. Let's download the build from this CI run before merging to make sure and try to avoid one more RC :)
Fixes #5300
> Resolved an issue where the React modules would not load

- DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
Allowed creating different nested folder types
> Allowed creating different nested folder types

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components.d.ts
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list-item/dnn-rm-folder-list-item.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-cardview/dnn-rm-items-cardview.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-cardview/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-listview/dnn-rm-items-listview.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-listview/readme.md
> Allows opening resource manager folders with double-click

- package.json
- yarn.lock
See https://blog.nrwl.io/lerna-reborn-whats-new-in-v6-10aec6e9091c
>If you are an OSS maintainer and you use a Lerna workspace, let us know!
Ping the Lerna team [on Twitter](https://twitter.com/lernajs) or ping [me directly](https://twitter.com/juristr). We’d love to have a look and help with the migration, look at the repository and make sure it is configured in the best optimal way in terms of monorepo setup and features like caching.
>
>That said, as an open-source maintainer you also get unlimited free computation caching with Nx Cloud. So we’d love to set you up with that.
> Upgrade to lerna 6.x

- Build/Build.csproj
- Build/Lifetime.cs
- azure-pipelines.yml
- build.config
> Upgrade Cake dependencies

- SECURITY.md
Corrected verbiage and phrasing issues with the policy
> Updated Security Policy

- DNN Platform/Modules/ResourceManager/Components/ItemsManager.cs
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components.d.ts
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/context-menus/dnn-rm-folder-context-menu/dnn-rm-folder-context-menu.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.scss
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
> Fixed an issue where it was not possible to edit the root folder

- Build/Program.cs
Update to latest NuGet.CommandLine during build
> Update NuGet.CommandLine from 5.10.0 to 6.4.0

- Build/Program.cs
Update build to use latest Microsoft.TestPlatform package.
> Update Microsoft.TestPlatform from 16.11.0 to 17.4.1

- DNN Platform/Library/Common/Utilities/FileSystemUtils.cs
- DNN Platform/Library/Services/Installer/Writers/PackageWriterBase.cs
> Fixed an issue that prevented creating packages from UI

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-queued-file/dnn-rm-queued-file.tsx
> Resolve Resource Manager issue uploading files with uppercase extensions

- DNN Platform/Website/App_GlobalResources/GlobalResources.resx
Changed 2013 to [YEAR] in EMAIL_MESSAGING_DISPATCH_BODY.Text
Fixes #5512
> Changed 2013 to [YEAR]

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs
This was done in #5535 and merged into develop instead of `release/9.11.1` by mistake, this is the exact same commit and I am force-merging it as the commit was already approved.
> Fixed an issue where the html editor browser would fail

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.02.SqlDataProvider
These are exact copies of the sprocs from v 7.3.2 with the additional clause to ensure the deleted items are properly accounted for.  Fixes #5528
> Fix journal list sprocs

- package.json
- yarn.lock
This is an attempt to fix the current build issue with 9.11.1
> Bumped lerna to v6.5.1

- .github/ISSUE_TEMPLATE/bug-report.md
Updates issue template with v9.11.1 beeing current
> Updates issue template with v9.11.1 beeing current

- Build/Tools/NuGet/DotNetNuke.Bundle.nuspec
> Remove DotNetNuke.Web.Deprecated from DotNetNuke.Bundle

- DNN Platform/Library/Services/GeneratedImage/DnnImageHandler.cs
This PR enabled DI support for `ImageTransform`.
This PR does not contain any breaking changes but does depend on #4098, and therefore this PR is targeting DNN 10.0.0.
> Enable dependency injection for ImageTransform

- DNN Platform/Library/Modules/NavigationProvider.cs
- DNN Platform/Library/UI/Containers/ActionsMenu.cs
- DNN Platform/Library/UI/Skins/NavObjectBase.cs
- DNN Platform/Modules/DDRMenu/Actions.cs
- DNN Platform/Modules/DDRMenu/App_Start/Startup.cs
- DNN Platform/Modules/DDRMenu/DDRMenuControl.cs
- DNN Platform/Modules/DDRMenu/DDRMenuNavigationProvider.cs
- DNN Platform/Modules/DDRMenu/DotNetNuke.Modules.DDRMenu.csproj
- DNN Platform/Modules/DDRMenu/Localisation/Generic.cs
- DNN Platform/Modules/DDRMenu/Localisation/ILocaliser.cs
- DNN Platform/Modules/DDRMenu/Localisation/Localiser.cs
- DNN Platform/Modules/DDRMenu/MenuBase.cs
- DNN Platform/Modules/DDRMenu/MenuView.ascx.cs
- DNN Platform/Modules/DDRMenu/SkinObject.cs
- DNN Platform/Tests/DotNetNuke.Tests.Modules.DDRMenu/DotNetNuke.Tests.Modules.DDRMenu.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Modules.DDRMenu/app.config
- DNN Platform/Tests/DotNetNuke.Tests.Modules.DDRMenu/packages.config
- DNN Platform/Website/admin/Containers/DropDownActions.ascx.cs
This PR relies on #5616. It enables DI support for DDR menu localization and for `NavigationProvider`
> Add DI for DDR Menu and NavigationProvider

- DNN Platform/DotNetNuke.Web/Api/AuthorizeAttributeBase.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Attributes/MenuPermissionAttribute.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Containers/PersonaBarContainer.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Controllers/PersonaBarController.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Dnn.PersonaBar.Library.csproj
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Startup.cs
This PR enables dependency injection for `IMenuItemController`
> Enable DI for IMenuItemController

- DNN Platform/Modules/DnnExportImport/Components/Common/Util.cs
- DNN Platform/Modules/DnnExportImport/Components/Controllers/BaseController.cs
- DNN Platform/Modules/DnnExportImport/Components/Controllers/ExportController.cs
- DNN Platform/Modules/DnnExportImport/Components/Controllers/ImportController.cs
- DNN Platform/Modules/DnnExportImport/Components/Engines/ExportImportEngine.cs
- DNN Platform/Modules/DnnExportImport/Components/Scheduler/ExportImportScheduler.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
- DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
- DNN Platform/Modules/DnnExportImport/Services/ExportImportController.cs
- DNN Platform/Modules/DnnExportImport/Startup.cs
- DNN Platform/Modules/DnnExportImport/packages.config
This PR relies on #5616. It adds DI support in the Export/Import module (i.e. `BasePortableService` and `IPortable`).
> Add DI support for site export/import

- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.csproj
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Services/MenuExtensionsController.cs
This PR enables dependency injection for `IExtensionController`
> Enable DI for IExtensionController

- DNN Platform/Library/Common/Initialize.cs
- DNN Platform/Library/Entities/Modules/EventMessageProcessor.cs
- DNN Platform/Library/Services/EventQueue/EventQueueController.cs
This PR relies on #5616. It enables dependency injection for `EventMessageProcessorBase` (i.e. the component which runs `UpgradeModule`)
> Add DI for EventMessageProcessorBase

- DNN Platform/DotNetNuke.ModulePipeline/ModuleControlPipeline.cs
- DNN Platform/DotNetNuke.Web.Mvc/MvcModuleControlFactory.cs
- DNN Platform/DotNetNuke.Web.Mvc/Startup.cs
- DNN Platform/DotNetNuke.Web.Razor/RazorModuleControlFactory.cs
- DNN Platform/DotNetNuke.Web.Razor/Startup.cs
- DNN Platform/Library/Startup.cs
- DNN Platform/Library/UI/Modules/BaseModuleControlFactory.cs
- DNN Platform/Library/UI/Modules/Html5/Html5ModuleControlFactory.cs
- DNN Platform/Library/UI/Modules/IModuleControlFactory.cs
- DNN Platform/Library/UI/Modules/ReflectedModuleControlFactory.cs
- DNN Platform/Library/UI/Modules/WebFormsModuleControlFactory.cs
Fixes #5605
This PR implements the proposed solution in #5605.
The target branch is 10.0.0, since the `IModuleControlFactory` has been changed. If this is incorrect I can change the branch and cherry-pick the commit. 🙂
> Allow registration of custom IModuleControlFactory implementations

- DNN Platform/Library/Services/Mail/Mail.cs
- DNN Platform/Library/Services/Mail/MessageType.cs
- DNN Platform/Website/App_GlobalResources/GlobalResources.resx
- DNN Platform/Website/admin/Security/SendPassword.ascx.cs
Closes #5245
Email administrator when an unapproved user requests a password reset. Then the administrator can verify that it is a valid request, and if so, authorize the user and send a new password reset.
> Send email to administrator when an unauthorized user requests a password reset

- DNN Platform/DotNetNuke.Web/Api/SupportedModulesAttribute.cs
> Add params array constructor to SupportedModulesAttribute

- DNN Platform/Website/admin/Containers/Icon.ascx.cs
> Don't prefix icon path if it's rooted

- DNN Platform/DotNetNuke.Web/Api/SupportedModulesAttribute.cs
- DNN Platform/Website/admin/Containers/Icon.ascx.cs
Updated `release/10.0.0` with latest fixes from `9.x.x`
> Updated `release/10.0.0` with latest fixes from `9.x.x`

- DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
- DNN Platform/DotNetNuke.DependencyInjection/LazyWrapper.cs
- DNN Platform/Library/Startup.cs
Fixes #5646
Thanks @iJungleboy!
> Enable lazy DI registration

- .github/ISSUE_TEMPLATE/bug-report.yml
Update bug report issue form to require versions
> Update bug report issue form to require versions

- .github/ISSUE_TEMPLATE/bug-report.yml
Update `what-happened` field of bug issue form
> Update `what-happened` field of bug issue form

- .github/ISSUE_TEMPLATE/enhancement-request.yml
Correct checkboxes in enhancement request form
> Correct checkboxes in enhancement request form

- .github/ISSUE_TEMPLATE/enhancement-request.yml
Attempt to fix YML issue in `enhancement-request.yml`
> Attempt to fix YML issue in `enhancement-request.yml`

- .github/ISSUE_TEMPLATE/enhancement-request.yml
Correct `Yes` in `enhancement-request.yml`
> Correct `Yes` in `enhancement-request.yml`

- .github/ISSUE_TEMPLATE/bug-report.yml
Added 9.12.0-rc1 to bug report template
> Added 9.12.0-rc1 to bug report template

- .github/ISSUE_TEMPLATE/bug-report.yml
Another cleanup attempt for line spacing
> Another cleanup attempt for line spacing

- Build/Tasks/thirdparty.json
> Install CodeDOM provider by default

- .github/ISSUE_TEMPLATE/bug-report.yml
Updated bug-report.yml as per v9.12.0 release
> Updated bug-report.yml as per v9.12.0 release

- Build/Tasks/thirdparty.json
The declaration in thirdparty.json was missed in #5724
Closes #5740
> Fixed an issue where DnnPlugins package was not being produced

- DNN Platform/Providers/FolderProviders/AzureFolderProvider/Settings.ascx.cs
> Fix casing mismatch between codebehind and ascx

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Servers/App_LocalResources/Servers.resx
> Adjust help text for SMTP SSL setting

- DNN Platform/Connectors/GoogleAnalytics/App_LocalResources/SharedResources.resx
- DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
- DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Servers/App_LocalResources/Servers.resx
Updates `release/10.0.0` with latest fixes from `develop`
> Updates `release/10.0.0` with latest fixes from `develop`

- DNN Platform/Library/Common/Globals.cs
- DNN Platform/Library/Obsolete/EventLogController.cs
- DNN Platform/Library/Obsolete/SerializationController.cs
Found a couple of typos in #5754
> Fix incorrect deprecation versions

- DNN Platform/Website/admin/Menus/ModuleActions/ModuleActions.css
Support Themes using box-sizing: border-box; without adding CSS hacks.
For Module action Menu drop-down items
- Removed Fixed height for Action 
- Removed Font Family Arial
fixes #5783
> Update ModuleActions.css for #5783

- DNN Platform/Library/Common/Extensions/HttpContextDependencyInjectionExtensions.cs
> Fix infinite loop on install

- Build/Build.csproj
- DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/DotNetNuke.Tests.SourceGenerators.csproj
- azure-pipelines.yml
- global.json
This PR upgrades the build project
> Use .NET 8.x and Cake 4.0.0 for build

- azure-pipelines.yml
Ensures the yarn cache folder exists before doing yarn caching
> Fixed a CI issue that prevented yarn package caching

- .github/dependabot.yml
- .yarnrc.yml
- Build/Build.csproj
- DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/DotNetNuke.Tests.SourceGenerators.csproj
- azure-pipelines.yml
- gitversion.yml
- global.json
- package.json
Merged latest fixes on `develop` into `release/10.0.0`
> Merged latest fixes on `develop` into `release/10.0.0`

- DNN Platform/Skins/Aperture/src/scss/components/_dnn.scss
- DNN Platform/Skins/Aperture/src/scss/components/_login.scss
- DNN Platform/Skins/Aperture/src/scss/mixins/_mixins.scss
- DNN Platform/Skins/Aperture/src/scss/variables/_controls.scss
This PR resolves a few mixin issues as well as styles the login.
> DNN 10 Theme: Update styling of login 

- DNN Platform/Library/Common/Utilities/UrlUtils.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Common/UrlUtilsTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/Fakes/FakeHostController.cs
- DNN_Platform.sln.DotSettings
Clean up and document `UrlUtils` class.
> Clean up UrlUtils

- DNN Platform/Skins/Aperture/tsconfig.json
This PR makes a few minor refinements to the Aperture theme **tsconfig** `compilerOptions`.
> Refine a few TypeScript `compilerOptions`

- DNN Platform/Skins/Aperture/src/scss/utilities/_dimension.scss
This PR resolves an issue with the responsive `dimension` utility classes within the new `Aperture` theme.
> Resolve issue with responsive `dimension` utility classes

- DNN Platform/Skins/Aperture/src/scss/utilities/_image.scss
- DNN Platform/Skins/Aperture/src/scss/utilities/_utilities.scss
This PR adds `image` utilities to the new `Aperture` theme to help with responsive images.
> Add responsive `image` utilities

- DNN Platform/Skins/Aperture/src/scripts/menu.ts
- yarn.lock
This PR updates the new DNN 10 Aperture theme to have smooth scrolling for all hashed nav menu items.  The content that will be in the new `Default` template will have divs with ids for targeting those sections on the home page.
> Aperture theme - add smooth scrolling on click for hashed nav items

- DNN Platform/Skins/Aperture/menus/mobile/RazorMenu.cshtml
- DNN Platform/Skins/Aperture/src/scripts/menu.ts
- DNN Platform/Skins/Aperture/src/scss/components/_nav.scss
**NOTE: Please review/approve/merge #5918 before this one, as I had to stack commits to test these changes against the previously submitted PR.**
This PR adds multiple UI/UX refinements/fixes to the mobile menu.
> Aperture theme - mobile menu refinement

- Build/Build.csproj
This should fix the build issue.
> Re-applies #5924 onto the release branch

- .github/ISSUE_TEMPLATE/bug-report.yml
This PR updates the bug report issue template to reflect the current released and alpha versions.
> Update bug report issue template with latest version info

- .github/ISSUE_TEMPLATE/bug-report.yml
- Build/Build.csproj
- DNN Platform/Library/Common/Utilities/UrlUtils.cs
- DNN Platform/Library/Services/FileSystem/FileManager.cs
- DNN Platform/Library/Services/FileSystem/Internal/FileSecurityController.cs
- DNN Platform/Library/Services/FileSystem/Internal/IFileSecurityController.cs
- DNN Platform/Modules/ResourceManager/App_LocalResources/ResourceManager.resx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components.d.ts
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-open-file/dnn-action-open-file.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/context-menus/dnn-rm-file-context-menu/dnn-rm-file-context-menu.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/dnn-rm-actions-bar.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-files-pane/dnn-rm-files-pane.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list-item/dnn-rm-folder-list-item.scss
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list-item/dnn-rm-folder-list-item.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.scss
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-cardview/dnn-rm-items-cardview.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-listview/dnn-rm-items-listview.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/LocalizationClient.ts
- DNN Platform/Tests/DotNetNuke.Tests.Core/Common/UrlUtilsTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FileManagerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/Fakes/FakeHostController.cs
- DNN_Platform.sln.DotSettings
- yarn.lock
> Updates `release/10.0.0` with the latest fixes from `develop`

- DNN Platform/Website/Portals/_default/Blank Website.template
- DNN Platform/Website/Portals/_default/Blank Website.template.en-US.resx
> Update `Blank Website` template for DNN 10

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/Dto/UserDetailDto.cs
> Utilize _default `popUpSkin` and `popUpContainer` for IFRAME in Users module frontend

- DNN Platform/Skins/Aperture/partials/_includes-popUpSkin.ascx
- DNN Platform/Skins/Aperture/src/scss/layouts/popUpSkin.scss
> Aperture: Remove unused SCSS and CSS reference from partial

- DNN Platform/Skins/Aperture/package.json
Resolves #5964 
Resolves #5963
> Resolve issue with main entry point in package.json file

- DNN Platform/Modules/BulkInstall/Components/DataAccess/Models/APIUser.cs
- DNN Platform/Modules/BulkInstall/Components/DataAccess/Models/Obfuscated.cs
- DNN Platform/Modules/BulkInstall/Components/FeatureController.cs
- DNN Platform/Modules/BulkInstall/Components/WebAPI/RemoteController.cs
- DNN Platform/Modules/BulkInstall/Dnn.Modules.BulkInstall.csproj
- DNN Platform/Modules/BulkInstall/packages.config
- DNN Platform/Modules/BulkInstall/web.Clients.config
- DNN Platform/Modules/BulkInstall/web.Debug.config
- DNN Platform/Modules/BulkInstall/web.Release.config
- DNN Platform/Modules/BulkInstall/web.config
This PR cleans up all project references and is part of the ongoing work for #5920.
> Bulk Install: Clean up all project references

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Connectors/Connectors.html
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Connectors/scripts/Connectors.js
Fix #5900: use correct selector.
> Fixed an issue where one could not "unselect" Google Analytics (Legacy UA) connector

- Build/Build.csproj
- Build/Context.cs
- DNN Platform/JavaScript Libraries/DnnPlugins/DnnPlugins.dnn
- DNN Platform/Library/Common/Utilities/XmlExtensions.cs
- DNN Platform/Library/Entities/Modules/ModuleController.cs
- DNN Platform/Library/Entities/Tabs/TabController.cs
- DNN Platform/Website/DesktopModules/Admin/Security/EditUser.ascx.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Connectors/Connectors.html
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Connectors/scripts/Connectors.js
- yarn.lock
> Merge latest changes from release/9.13.3 branch into release/10.0.0

- Build/Build.csproj
- Build/Context.cs
> Merges build issue fix done in `release/9.13.3` back into `develop`

- DNN Platform/Library/Framework/SecurityPolicy.cs
Closes #5991: fix incorrect replacements introduced by a previous code review
> Replaced the boolean values by the corresponding permissions constants values

- Build/Tasks/thirdparty.json
Install CodeDOM provider by default
Reapply 46f92d5c7188b65c95555962c9601fedc97d76ce #5690
Fixes  #5999
> CodeDOM installed by default

- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/dnn-bulk-install.scss
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/dnn-bulk-install.tsx
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/readme.md
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/index.ts
This PR is for the initial implementation of tabs within the new Bulk Install extension.
> Bulk Install: Initial implementation of tabs

- Build/Build.csproj
- DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
> Updates `release/10.0.0` branch with latest fixes from `develop`

- Build/Build.csproj
- DNN Platform/Website/admin/Menus/ModuleActions/ModuleActions.js
- DNN Platform/Website/admin/Modules/App_LocalResources/ModuleSettings.ascx.resx
- DNN Platform/Website/admin/Modules/Modulesettings.ascx
- DNN Platform/Website/admin/Modules/Modulesettings.ascx.cs
- DNN Platform/Website/admin/Modules/Modulesettings.ascx.designer.cs
Updates `release/10.0.0` with the latest changes from `develop`
> Updates `release/10.0.0` with the latest changes from `develop`

- Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/Suggestion/index.jsx
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/Suggestion/style.less
- Dnn.AdminExperience/ClientSide/Pages.Web/package.json
- Dnn.AdminExperience/ClientSide/Roles.Web/package.json
- Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/FiltersBar/index.jsx
- Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/UsersInRole/index.jsx
- Dnn.AdminExperience/ClientSide/Users.Web/package.json
- Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
- Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/UsersRoles/index.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Roles/scripts/bundles/roles-bundle.js.LICENSE.txt
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/scripts/bundles/users-bundle.js.LICENSE.txt
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/scripts/exportables/Users/UsersCommon.js.LICENSE.txt
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/exports/export-bundle.js.LICENSE.txt
- yarn.lock
Supercedes #5597
For some reason I was not able to fix that branch to build. Doing the same work manually did end up working. I tested an install can could not find anything broken in the persona bar.
> Bump react-widgets from 4.4.6 to 5.8.4

- yarn.lock
This PR bumps caniuse-lite from 1.0.30001584 to 1.0.30001660
> Update caniuse-lite to latest

- Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/RoleEditor/index.jsx
- Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/RoleRow/index.jsx
- Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/UsersInRole/UserRow/index.jsx
- Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/Web.jsx
- Dnn.AdminExperience/ClientSide/Servers.Web/src/services/smtpServerService.js
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Servers/WebServer/ServerInfo.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SystemInfoWebController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Roles/App_LocalResources/Roles.resx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Servers/App_LocalResources/Servers.resx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteImportExport/scripts/bundles/siteimportexport-bundle.js.LICENSE.txt
Fixes #6155 
This screenshot shows what these changes will look like:
> PersonaBar, Settings, Servers, System Info, Web subtab - Adds the .NET Framework Product Version

- DNN Platform/Skins/Aperture/src/scss/variables/_colors.scss
> Aperture: Added new CSS variables for DNN 10 color system

- .github/ISSUE_TEMPLATE/bug-report.yml
This PR updates the bug report template with correct DNN Platform version information.
> Update with correct version info

- DNN Platform/Skins/Aperture/src/scss/components/_dnn.scss
> Aperture: Updated DNN tab styling to comply with new color system

- DNN Platform/Skins/Aperture/src/scss/components/_dnn.scss
> Aperture: Updated permission grid styling to resolve a layout issue

- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components.d.ts
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/api-users/api-user.model.ts
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/api-users/api-users.scss
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/api-users/api-users.tsx
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/dnn-bulk-install.scss
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/dnn-bulk-install.tsx
This PR is for the initial implementation of the `API Users` tab within the new Bulk Install extension. This is part of the ongoing effort for #5920.
> Bulk Install: Initial implementation of `API Users` tab UI

- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/api-users/readme.md
This PR updates the readme for the new `api-users` component.  It was accidentally omitted from a previous PR.  This continues the work for #5920.
> Bulk Install: Update readme for `api-users` component

- Dnn.AdminExperience/ClientSide/Pages.Web/package.json
- yarn.lock
>  Update `release/10.0.0` with latest changes from `develop`

- DNN Platform/Website/Portals/_default/Default Website.template
> Fixed a typo in default website template

- DNN Platform/Skins/Aperture/menus/desktop/RazorMenu.cshtml
- DNN Platform/Skins/Aperture/menus/footer/RazorMenu.cshtml
> Resolved issue with disabled page names and refactored logic

- DNN Platform/DotNetNuke.Abstractions/Application/IApplicationInfo.cs
- DNN Platform/Library/Application/Application.cs
- DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
- DNN Platform/Modules/Groups/SocialGroups.dnn
- DNN Platform/Modules/HTML/dnn_HTML.dnn
- DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
- DNN Platform/Modules/Journal/Journal.dnn
- DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
- DNN Platform/Website/Portals/_default/Default Website.template.en-US.resx
- Dnn.AdminExperience/ClientSide/Licensing.Web/src/components/platform/index.jsx
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/serversummary.js
- README.md
Resolves #6273 and other references to dnndocs.com.
> Updated all references from dnndocs.com to docs.dnncommunity.org

- DNN Platform/Library/Entities/Portals/PortalStyles.cs
> Added prefixes to css variables portal settings

- DNN Platform/Website/Portals/_default/Default Website.template
> Updated default template content to use proper background class from Aperture

- DNN Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs
> delete authentication cookie when the cookie expires or is invalid

- DNN Platform/DotNetNuke.Web/Api/Auth/ApiTokens/Repositories/ApiTokenRepository.cs
- DNN Platform/DotNetNuke.Web/Startup.cs
- DNN Platform/Library/Startup.cs
This PR adds DataContext to DI using AddTransient so the following pattern:
``` cs
using (IDataContext ctx = DataContext.Instance())
{
var rep = ctx.GetRepository<SqlQuery>();
rep.Insert(query);
}
```
to
``` cs
public ApiTokenRepository(IDataContext dataContext)
{
this.dataContext = dataContext;
}
....
var rep = this.dataContext.GetRepository<ApiToken>();
return rep.GetById(apiTokenId);
```
> Add DataContext to DI

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/10.00.00.SqlDataProvider
> SQL 2017 fix

- DNN Platform/Skins/Aperture/build.ts
- DNN Platform/Skins/Aperture/menus/desktop/RazorMenu.cshtml
- DNN Platform/Skins/Aperture/src/scss/components/_nav.scss
This PR:
* Resolves an issue where the chokidar `watch` was not triggering for some theme files
* Implements better styling for sub nav menu items
* Resolves #6329
> Aperture: Resolved file watch and implemented better styling support for sub menu items

- DNN Platform/Skins/Aperture/build.ts
In CI or on a brand new clone, we do not have a WebsitePath in the settings, so in this case we spit out the files to a temp directory so we can grab them from there to orchestrate our packaging.
> Refactored Aperture build to fix CI issue

- DNN Platform/Library/Security/Permissions/AdvancedPermissionProvider.cs
Fix #6349 IndexOutOfRangeException in AdvancedPermissionProvider
This PR addresses the issue reported in #6349 where an IndexOutOfRangeException occurs in the AdvancedPermissionProvider when generating and adding virtual permissions. The exception was triggered by attempting to add items to a permissions collection that was not modifiable.
- On a fresh installation of DNN 10 RC, the AdvancedPermissionProvider throws an IndexOutOfRangeException while adding virtual permissions to the permissions collection.
- The problem arises because the base method returns a collection that is not meant to be modified directly, leading to an exception when virtual permissions are appended.
- **Create a New, Modifiable Collection:**  
Instead of adding virtual permissions directly to the collection …
> Fix #6349 IndexOutOfRangeException in AdvancedPermissionProvider

- DNN Platform/Dnn.ClientSide/src/styles/default-css/10.0.0/ui/_forms.scss
> Resolved issue with login button styling on hover

- Build/PackagingPatterns.cs
- Build/Tasks/CreateUpgrade.cs
- Build/Tasks/packaging.json
- DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/TelerikUninstaller.cs
- DNN Platform/Library/Entities/Modules/DesktopModuleController.cs
- DNN Platform/Library/Services/Installer/Installers/ModuleInstaller.cs
- DNN Platform/Library/Services/Upgrade/Upgrade.cs
- DNN Platform/Modules/TelerikRemoval/TelerikRemoval.dnn
- DNN Platform/Modules/TelerikRemoval/UpgradeController.cs
> Remove TelerikRemoval module after removing Telerik

- Build/Build.csproj
- global.json
This PR merges changes from the `develop` branch into `release/10.0.0`
> Merge `develop` into `release/10.0.0`

- DNN Platform/Library/Services/Installer/Installers/ConfigInstaller.cs
> Add logs and resilience for invalid config component

- DNN Platform/Components/Log4Net/bin/DotNetNuke.Log4Net.XML
- DNN Platform/DotNetNuke.Instrumentation/DotNetNuke.Instrumentation.csproj
- DNN Platform/DotNetNuke.Log4net/DotNetNuke.Log4Net.csproj
- DNN Platform/DotNetNuke.Log4net/log4net/AssemblyInfo.cs
> Fixed a casing issue with Log4Net

- DNN Platform/Skins/Aperture/partials/_footer.ascx
- DNN Platform/Skins/Aperture/partials/_header.ascx
- DNN Platform/Skins/Aperture/src/scss/sections/_footer.scss
- DNN Platform/Skins/Aperture/src/scss/sections/_header.scss
Add a CSS class to the Theme Header and Footer (+ associated SCSS) so their styling does not influence headers and footer in the page / module content.
fixes #6399
> #6399 Theme Header and Footer class

- DNN Platform/Skins/Aperture/containers/title.ascx
- DNN Platform/Skins/Aperture/partials/_footer.ascx
- DNN Platform/Skins/Aperture/partials/_header.ascx
- DNN Platform/Skins/Aperture/src/scss/sections/_footer.scss
- DNN Platform/Skins/Aperture/src/scss/sections/_header.scss
- DNN Platform/Skins/Aperture/src/scss/sections/_sections.scss
- DNN Platform/Skins/Aperture/src/scss/utilities/_containers.scss
I added 2rem margin at the bottom of a container & renamed the aperture-container class to aperture-wrapper so I could use it for the containers
fixes #6400
> dnn10 Theme module distance bottom #6400

- DNN Platform/Skins/Aperture/src/scss/utilities/_dnn-edit.scss
- DNN Platform/Skins/Aperture/src/scss/utilities/_utilities.scss
I added a box-shadow to the PB as suggested by @valadas.
Result:
fixes #6403
> Add more distinction between PB and Theme #6403

- DNN Platform/Skins/Aperture/containers/title.ascx
- DNN Platform/Skins/Aperture/partials/_footer.ascx
- DNN Platform/Skins/Aperture/partials/_header.ascx
- DNN Platform/Skins/Aperture/src/scss/sections/_footer.scss
- DNN Platform/Skins/Aperture/src/scss/sections/_header.scss
- DNN Platform/Skins/Aperture/src/scss/sections/_sections.scss
- DNN Platform/Skins/Aperture/src/scss/utilities/_containers.scss
Reverts dnnsoftware/Dnn.Platform#6412
> Revert "dnn10 Theme module distance bottom #6400"

- DNN Platform/Website/Default.aspx.cs
Popup skin should always be used if requested no matter if it lives in an actual popup or in an iframe in the PersonaBar
Closes #6365
> Fixed an issue where auth providers config would use wrong layout

- .github/ISSUE_TEMPLATE/bug-report.yml
Updates bug report template with current versions
> Updates bug report template with current versions

- DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
Fixes #6443 
Add missing assembly file versions in `DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn`.
> fix #6443 Add missing assembly file versions in `Dnn.Jwt.dnn`.

- DNN Platform/Website/Default.aspx.cs
> Fixed an issue where popups would not work

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/10.00.00.02.SqlDataProvider
For https://github.com/dnnsoftware/Dnn.Platform/issues/6429#issuecomment-2748855512
Note that there's still an open question as to whether this fix improves the experience or not.
> Avoid SQL error for existing ContentWorkflowActions rows

- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Controllers/ContentEditorManager.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.csproj
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/AddExistingModuleMenu.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/ExitEditModeMenu.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/PageSettingsMenu.cs
> Fixed an issue where normal users could not exit edit mode

- SECURITY.md
Added more details to our security policy
> Added more details to our security policy

- DNN Platform/Website/Portals/_default/Blank Website.template
- DNN Platform/Website/Portals/_default/Default Website.template
- yarn.lock
> Fixed an issue where new portals could not be created

- DNN Platform/Library/Entities/Modules/ModuleController.cs
> Do not throw if existing value is null

- DNN Platform/Library/Services/Upgrade/Internals/InstallControllerImpl.cs
- Fixes #6499
Azure SQL Server is reported using a 12 version number, but  it is ALWAYS updated to the latest and greatest version so it meets the current 2017 and later requirement that is needed by DNN Platform.
This change adds a special secondary check if a 12 version number is returned to check for the edition.  If it is Azure SQL it sets the proper flag allowing installation
> Updated Version to handle Azure SQL

- DNN Platform/Modules/ResourceManager/Components/Common/Utils.cs
> Fix exception checking folder permissions

- Build/Tasks/packaging.json
> Exclude System.Runtime.CompilerServices.Unsafe from upgrade

- DNN Platform/Components/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dnn
> Update description of CodeDOM compiler package

- DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
> Un-register  System.IdentityModel.Tokens.Jwt DLL instead of deleting

- DNN_Platform.sln
> Remove reference to DNN_Package.build

- DNN Platform/DotNetNuke.Abstractions/Application/CacheControlHeader.cs
- DNN Platform/Library/Entities/Host/Host.cs
- DNN Platform/Library/Entities/Host/HostSettings.cs
- DNN Platform/Website/Install/DotNetNuke.install.config.resources
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/10.01.01.SqlDataProvider
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Servers/PerformanceSettings/PerformanceController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsPerformanceController.cs
The mechanism to get and update the cacheability settings had a bug which prevented them from properly getting used.
This PR should fix #6703
> Fix cacheability settings
