dnnsoftware/Dnn.Platform

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Editors/ModulePackageEditor.cs
Fixes #4081 
Changing friendly name for a module in extensions page updates it only in Packages table and doesn't update it in DesktopModules table. Included friendly name property to be updated in DesktopModules table.
> module friendly name updated as part of module extension update

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/App.jsx
Fixes #4123 
The error path was using notify method to show error instead of notifyError method which results in showing incorrect notification icon. Fixed it to use correct method.
> Error message to use correct error icon

- DNN Platform/Dnn.AuthServices.Jwt/Components/Schedule/PurgeExpiredTokensTask.cs
- DNN Platform/Dnn.AuthServices.Jwt/Data/DataService.cs
- DNN Platform/Dnn.AuthServices.Jwt/Data/Scripts/09.08.00.SqlDataProvider
- DNN Platform/Dnn.AuthServices.Jwt/Data/Scripts/Uninstall.SqlDataProvider
- DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
- DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
This PR introduces a scheduled task in DNN to remove expired JWT tokens using the existing (and until now unused) DeleteExpiredTokens SPROC.
> Purge Expired JWT tokens task

- .github/mergeable.yml
This PR updates mergeable to not allow merging of PRs that contain a `Future:` milestone.
> Update mergeable to not allow merging of PRs with Future:... milestone

- DNN Platform/DotNetNuke.Instrumentation/DnnLog.cs
- DNN Platform/DotNetNuke.Instrumentation/DnnLogger.cs
- DNN Platform/DotNetNuke.Instrumentation/DotNetNuke.Instrumentation.csproj
- DNN Platform/DotNetNuke.Instrumentation/ILog.cs
- DNN Platform/DotNetNuke.Instrumentation/ILoggerSource.cs
- DNN Platform/DotNetNuke.Instrumentation/LoggerSource.cs
- DNN Platform/DotNetNuke.Instrumentation/LoggerSourceImpl.cs
* Adds missing documentation
* Removes `internal` fields (changing to `private` or properties as appropriate)
* Remove underscores from field names
> Treat warnings as errors for DotNetNuke.Instrumentation

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpAdminController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpHostController.cs
Fixes #3813 
Simplifies and makes the logic for TEST SMTP emails used **FROM** and **TO** and utilizes newer logic for both a Host or an Administrator when sending a test email.
Somehow the previous didnt get merged.  I think this code change refines things a bit to get the job done as expected.
> Update SMTP Test Email Logic

- DNN Platform/Library/Entities/Portals/PortalAliasController.cs
- DNN Platform/Library/Entities/Portals/PortalAliasInfo.cs
Addresses [CA1708](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1708)
>Identifiers for namespaces, types, members, and parameters cannot
>differ only by case because languages that target the common language
>runtime are not required to be case-sensitive. For example, Visual
>Basic is a widely used case-insensitive language.
Fixes #4138
> Hide new members that differ only by case

- DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/Dnn.Modules.ModuleCreator.csproj
- DNN Platform/DotNetNuke.Website.Deprecated/DotNetNuke.Website.Deprecated.csproj
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddModule.ascx.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddModule.ascx.designer.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddPage.ascx.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddPage.ascx.designer.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/ControlBar.ascx.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/ControlBar.ascx.designer.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/RibbonBar.ascx.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/RibbonBar.ascx.designer.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/SwitchSite.ascx.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/SwitchSite.ascx.designer.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/UpdatePage.ascx.cs
- DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/UpdatePage.ascx.designer.cs
- DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj
- DNN Platform/Modules/HTML/EditHtml.ascx.cs
- DNN Platform/Modules/HTML/dnn_HTML.dnn
- DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
- DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
- DNN Platform/Tests/App.config
- DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
This PR removes remaining references to Telerik (primarily project references that aren't used).
> Remove Telerik references

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PagesControllerImpl.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Services/ComponentsController.cs
> enable "unauthenticated users" role in the list.

- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Entities/Modules/Settings/HostSettingAttribute.cs
- DNN Platform/Library/Entities/Modules/Settings/ISettingsRepository.cs
- DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
This PR does two things:
1. It adds the (IMO missing) HostSettingsAttribute which persists the value to the HostSettings table
2. It allows you to construct the settings repository with a simple PortalId to retrieve a settings class with only portal/host settings
Because of #2 you can also create a settings class using -1 for portal ID which allows you to use only HostSettings.
> Add host setting option and ability to use settings outside module context

- DNN Platform/HttpModules/DotNetNuke.HttpModules.csproj
- DNN Platform/HttpModules/Localization/LocalizationModule.cs
- DNN Platform/Library/Framework/PageBase.cs
- DNN Platform/Library/Services/Localization/Localization.cs
- DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
- DNN Platform/Modules/CoreMessaging/Services/SubscriptionsController.cs
- DNN Platform/Website/Default.aspx
- DNN Platform/Website/Install/Config/09.08.00.config
- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
Thanks @mitchelsellers for tracking down the answer to our `async` issues.
This turns on [`Async`](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ydy4x04a(v=vs.100)?redirectedfrom=MSDN#attributes) for `Default.aspx`.
Previously, when we attempted this in #2089, we ran into an issue with the culture not being preserved throughout the entire page lifecycle.  So, for example, the page may have been loaded in a non-English context, but the URLs were generated for en-US anyway.
The solution is to set the thread culture via an `IHttpModule` implementation, rather than via the page's `OnInit` method.  This allows the culture to persist throughout the page request.
> Support C# Async Constructs During Page Rendering

- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/UserControls/PersonaBarContainer.ascx
Fixes #3288 
Attempted to find any instances of the incorrect CSS class name `personalBarContainer` in the core and there aren't in any file other file.  
To keep with the current naming convention and make it easier for any third-party developers to correct, a new class name of `personaBarContainer` has been added for now to allow for developers to have a period of time to resolve any potential compatibility updates in their own extensions.
> Properly named CSS class & keeps the other for compatibility for now

- DNN Platform/Library/Common/Utilities/Config.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/ConfigConsole/ConfigConsoleController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/scripts/ConfigConsole.js
Closes #3103
Adds support to edit Robots.txt in the Persona Bar's Configuration Manager feature.  
This supports instances where there may be multiple robots.txt files for multi-portal instances.  An included update detects the correct mode to render in CodeMirror based on the file extension of the "configuration" file in question.
> Adds support for editing the robots.txt on a website

- DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
Closes #4157
An infinite redirect loop could occur even in situations where the portal aliasses where setup in canonical mode.
Relates to this discussion: https://github.com/dnnsoftware/Dnn.Platform/discussions/4137
> Resolves an infinite redirect loop issue

- DNN Platform/Website/Default.aspx
Resolves #2547
Meta tag names are now lower-cased to play nicely with third-party SEO tools.
> Lowercases the meta tag names

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/ConfigConsole.html
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/css/ConfigConsole.css
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/scripts/ConfigConsole.js
Resolves #4169 
Please see the linked issue for more details on why this was implemented without package management. It is a stepping-stone PR to get the editor integrated into a project that does not already have package management set up.
> Swap CodeMirror in ConfigConsole for monaco-editor

- DNN Platform/Library/Services/Log/EventLog/LogController.cs
Fixes: #4175
Fixes a bug where the event log will silently fail if the username is not provided and the `HttpContext` is not set. This will happen if the event log is being used during the Application Startup which executes prior to the initialization of the `HttpContext`.
> Fixes Event Log from Failing Silently during Application Startup

- DNN Platform/Library/Entities/Modules/ModuleInfo.cs
- DNN Platform/Modules/DnnExportImportLibrary/Dto/Pages/ExportTabModule.cs
> Mark Webslice for Removal

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/Converters.cs
Closes #3541 
The existing behavior when editing a tab would add the Portal level description and keyword fields.  If the user then clicked saved it would be saved to the page as content.
The defaulting of descriptions when rendered is correct, but this behavior resulted in improper values being set without the user knowing.
> Resolved issue with Keyword and Description Defaults

- DNN Platform/DotNetNuke.Web/Api/Internal/ServicesRoutingManager.cs
This allows types that implement `IServiceRouteMapper` to utilize constructor injection from the DI container.
@mitchelsellers unfortunately, this is the only commit from #3933 that doesn't have any potential lifetime management issues.
> Enable dependency injection for IServiceRouteMapper

- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/Mail/CoreMailProvider.cs
- DNN Platform/Library/Services/Mail/Mail.cs
- DNN Platform/Library/Services/Mail/MailAttachment.cs
- DNN Platform/Library/Services/Mail/MailInfo.cs
This PR takes the work done by @meetmandeep in #4156 and extracts the `MailAttachment` class, so that we can process the switch to MailKit separately (i.e. for a later release).
> Introduce MailAttachment class

- DNN Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs
Fixes #3661
Reset redirectURL value so that it will be empty for populating redirectURL with 'Redirect After Login' value
> Reset redirect url for redirecting to 'Redirect After Login' page

- DNN Platform/Website/Resources/Shared/components/CountriesRegions/dnn.CountriesRegions.js
Fixes #3671 
jquery-ui has a default behavior for autocomplete fields where it will use the ui.item.id to update the input field when using the arrow keys to navigate the autocomplete suggestions. 
The change that was made was to add an event handler for the focus event so that we could override the default behavior and show the ui.item.name as the user uses the arrow keys to navigate the autocomplete suggestions. 
This makes for a better experience so that users know what suggestion they will be selecting as they scroll through the suggestions with the arrow keys.
- Login to DNN
- Click the Username at the top to view your user profile 
- Click Edit Profile
- Expand the Address section
- In the country field, begin typing **uni** for United States
- You'll see a list of suggestions, use …
> Fixed issue country/region field showed Id instead of name when using arrow keys

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/FolderPicker.jsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/FolderSelector.jsx
Closes #4200
The filtering logic was applied with a null result and removing all the results, I added a check for null which makes the fileting work when the search is used.
> Fixes an issue where folder search would not work in resrouce manager

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Seo/App_LocalResources/Seo.resx
This is a pull request for Issue [#3992](https://github.com/dnnsoftware/Dnn.Platform/issues/3992)
Simple fix to Sitemap page priority tooltip
> Fix tooltip Sitemap page priority

- .github/PULL_REQUEST_PROCESS.md
@dnnsoftware/approvers I'm thinking this is a bit overkill, as I can't think of a reason why it would matter who actually clicks the merge button.  The important thing is that there are two approvals.  Do you all agree?
> Remove impractical rule

- DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.de-DE.resx
- DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.es-ES.resx
- DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.fr-FR.resx
- DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.it-IT.resx
- DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
- DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.resx
Fixes #3791 
Some of the localization files made reference to some unsupported operating systems. With this change, those unsupported systems have been removed from the messaging for the **FileAndFolderPermissionCheckFailed**. Other keys in the localization file referenced an unsupported version of SQL in the **IsValidSqlServerVersionCheck** and **IsValidSqlServerVersion** keys. The following changes have been made. 
- Updated the InstallWizard.aspx.resx files to update the .NET Framework requirements from 4.0 to 4.7.2
- Updated the minimum SQL version from 2008 to 2008 R2 to match the Docs
- Removed mentions of unsupported operating systems for the **FileAndFolderPermissionCheckFailed** message. 
- Removed **IsValidDotNetVersion.Text** as it was no longer referenced in the solution
> Updated .NET & SQL requirements in InstallWizard localization files

- DNN Platform/Admin Modules/Dnn.Modules.Console/Components/BusinessController.cs
- DNN Platform/Admin Modules/Dnn.Modules.Console/Dnn.Modules.Console.csproj
- DNN Platform/Library/Services/Exceptions/Exceptions.cs
- DNN Platform/Modules/CoreMessaging/Components/CoreMessagingBusinessController.cs
- DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
- DNN Platform/Modules/CoreMessaging/Services/CoreMessagingRouteMapper.cs
- DNN Platform/Modules/CoreMessaging/Services/FileUploadController.cs
- DNN Platform/Modules/CoreMessaging/Services/FilesStatus.cs
- DNN Platform/Modules/CoreMessaging/Services/MessagingServiceController.cs
- DNN Platform/Modules/CoreMessaging/Services/SubscriptionsController.cs
- DNN Platform/Modules/CoreMessaging/Subscriptions.ascx.cs
- DNN Platform/Modules/CoreMessaging/View.ascx.cs
- DNN Platform/Modules/CoreMessaging/ViewModels/InboxSubscriptionViewModel.cs
- DNN Platform/Modules/CoreMessaging/ViewModels/NotificationActionViewModel.cs
- DNN Platform/Modules/CoreMessaging/ViewModels/NotificationViewModel.cs
- DNN Platform/Modules/CoreMessaging/ViewModels/NotificationsViewModel.cs
- DNN Platform/Modules/CoreMessaging/ViewModels/SubscriptionViewModel.cs
- DNN Platform/Modules/CoreMessaging/ViewModels/TotalsViewModel.cs
- Resolves 101 warnings
- Prevents sending detailed errors to frontend
- Updates documentation and settings here and there to make it build and correct related documentation
- Enabled TreatBuildWarningsAsErrors on project
> Resolves 101 build warnings on CoreMessaging project

- DNN Platform/Modules/DnnExportImport/Components/Common/CompressionUtil.cs
- DNN Platform/Modules/DnnExportImport/Components/Common/Constants.cs
- DNN Platform/Modules/DnnExportImport/Components/Common/Enums.cs
- DNN Platform/Modules/DnnExportImport/Components/Common/SummaryList.cs
- DNN Platform/Modules/DnnExportImport/Components/Common/Util.cs
- DNN Platform/Modules/DnnExportImport/Components/Controllers/BaseController.cs
- DNN Platform/Modules/DnnExportImport/Components/Controllers/EntitiesController.cs
- DNN Platform/Modules/DnnExportImport/Components/Controllers/ExportController.cs
- DNN Platform/Modules/DnnExportImport/Components/Dto/SummaryItem.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
- DNN Platform/Modules/DnnExportImport/Components/Services/UsersDataExportService.cs
Resolves some (I did not count but probably around 100) build warnings in the Import Export library.
> Resolves some build warnings in the ImportExport project.

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageTypeSelector/PageTypeSelector.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
This PR is in relation to #4239 
I have made a simple addition to the Persona Bar so that you can see the Page ID without having to go the the SEO -> URL Test service to get it.
Unless there is somewhere else where people would see it fit I can re-do the change elsewhere however this is the most logical place I could think of...
> Adding Page ID to the Page Management

- DNN Platform/Library/Entities/Users/Social/RelationshipControllerImpl.cs
- DNN Platform/Library/Obsolete/EventLogController.cs
- DNN Platform/Library/Services/Log/EventLog/IEventLogController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Social/RelationshipControllerTests.cs
Resolves #4242
The PR:
- Deprecates the interface
- Deprecates the implementation
- The implementation beeing internal and the interface having a warning to not implement by 3rd parties, we can replace it's usage in other downstream classes without too much worry
- I did only one usage replacement in RelationshipController as a proof of concept and adjusted the related test on it.
- There are many many usages of this in Platform, so if thise PR is ok, we have a plan forward for the other usages, any feedback welcome.
> Deprecates IEventLogController in favor of DI

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
Fixes #4247 
The language code for SCAYT plugin is fixed to match specification. The supported code is en_US instead of en-us, for example.
> SCAYT language code configuration fixed

- DNN Platform/Tests/.editorconfig
- DNN_Platform.sln
- Dnn.AdminExperience/Tests/.editorconfig
Tests projects are not consumed by 3rd parties but where contrained to the same stylecop code style rules as the rest of the platform code (like documentation requirements and name styles and whitespace time. Since we are on a hunt to reduce our build warnings, this PR relaxes those rules on the Tests projects for now.
I would like to revisit this at a later date and actually correct some of those but for now it removes us 959 warnings quickly.
> Relaxed compile warnings on Tests projects

- DNN Platform/Website/Install/Config/09.08.00.config
This PR places the new Localization HTTP module right after URL Rewrite (which determines the culture from the URL), and then all modules after it can make use of that culture info.  The current behavior puts it at the end for upgrades, which potentially causes issues.
> Ensure new Localization HTTP module is running soon enough

- DNN Platform/HttpModules/Localization/LocalizationModule.cs
- DNN Platform/HttpModules/Membership/MembershipModule.cs
- DNN Platform/Library/Services/Localization/Localization.cs
During testing we discovered that the thread locale was not set correctly when switching languages. This PR addresses that issue.
> Fix Localization Issues

- DNN Platform/Dnn.AuthServices.Jwt/Auth/JwtAuthMessageHandler.cs
- DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/IJwtController.cs
- DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
- DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/LoginData.cs
- DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/LoginResultData.cs
- DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/PersistedToken.cs
- DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/RenewalDto.cs
- DNN Platform/Dnn.AuthServices.Jwt/Components/Schedule/PurgeExpiredTokensTask.cs
- DNN Platform/Dnn.AuthServices.Jwt/Data/DataService.cs
- DNN Platform/Dnn.AuthServices.Jwt/Data/IDataService.cs
- DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
- DNN Platform/Dnn.AuthServices.Jwt/Library.build
- DNN Platform/Dnn.AuthServices.Jwt/Services/MobileController.cs
- DNN Platform/Dnn.AuthServices.Jwt/Services/ServiceRouteMapper.cs
- DNN Platform/DotNetNuke.Web/Api/Auth/AuthMessageHandlerBase.cs
Currently JWT provider is not installed by default, this is an issue because we can't update it's code upon Dnn upgrades and are currently planning on doing some improvements in this area soonish. For the next improvements to actually run and have some sort of expected behavior on it in the next releases, it should be installed by default.
This PR makes it install be default as well as resolves almost all it's styleocop warnings.
> Installs JWT provider by default

- DNN Platform/Dnn.AuthServices.Jwt/Library.build
- DNN Platform/Library/Services/Upgrade/Upgrade.cs
DNN is distributed with a number of optional packages like Jwt Auth. If we make a fix to these packages they should be upgraded together with DNN.
This PR will install optional packages (i.e. .resources files) if they have been installed previously. It also reverts an earlier change where we made Jwt install by default to work around this issue.
> Upgrade optional packages when they've already been installed

- DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
With the recent change to make optional packages (.resources) upgrade if the package was previously installed, while upgrading the JWT authentication provider, it cause the existing web.config configuration to be reset to the default and that would happen on each upgrade.
This PR makes it ignore the node if it is already present from a previous installation.
> Prevents JWT upgrade to change existing config

- Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/index.jsx
- Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/style.less
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/SiteSettings/UpdateOtherSettingsRequest.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
This PR brings back the "EnablePopups" setting to the UI. It will appear under "More" on the Portal Settings PB module.
> Implement EnablePopups switch in portal settings PB module

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/RegisterController.cs
The user preferred locale is a required field in user profiles. Some change made it that in 9.8.0 this property is null. This PR reverts the behavior so the preferred locale is set on new users.
Basically the locale was already set but before initializing the profile and initializing the profile would reset it, this PR just moves one line
> Fixed an issue where new users would have no preferred locale.

- DNN Platform/Library/Services/Mail/CoreMailProvider.cs
While working on the Feedback module the messages where missing their body, then I tried creating new users and those emails where also missing the body. Looks like the CoreMailProvider was missing setting the body to the emails.
This PR solves that.
> Fixed an issue where all emails where missing the body

- DNN Platform/Library/Data/SqlDataProvider.cs
> Fix data reader not getting disposed

- DNN Platform/Website/Resources/Shared/scripts/dnn.PasswordStrength.js
Fixes #4300 
Self-closing span tags are bad practice and not supported by HTML actually. Spans were getting nested each other since they didn't have proper ending tags so that it's fixed now.
Demo: https://drive.google.com/file/d/1SSJ3vnkfZLOxxYJWM6MEWtU4JL0y2YNY/view?usp=sharing
> Issue-4300 - Edit Account - New Password field validation lines are not correct

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/Dto/UserBasicDto.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/Dto/UserDetailDto.cs
DTO objects should not have expression-bodied properties as .net serialization does not keep the thread locale and reverts to en-US. This caused the user profile editing to not respect the current locale.
> Ensure properties in DTO objects use backing fields

- DNN Platform/DotNetNuke.ModulePipeline/DotNetNuke.ModulePipeline.csproj
I think this missing reference is causing the build error we started seeing on Friday, though I'm not sure why it wasn't required before.
> Fix build error

- README.md
It was pointing to an old build definition.
> Fix DevOps build badge

- DNN Platform/Library/Properties/AssemblyInfo.cs
- DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Data/RepositoryBaseTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
- DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Urls/ExtensionUrlProviderControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Urls/packages.config
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
We don't automatically run the integration tests, so we weren't notified that some of them are failing because they aren't setting up the services container.  This commit fixes that for a couple projects.
> Fix some integration tests

- DNN Platform/Library/Entities/Content/ContentController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Content/ContentControllerTests.cs
Fixes #4002 
Fixes audit trail for adding new content to the DNN database. This now properly assigns the CreatedByUserID & LastModifiedByUserID if it is not explicitly set on the `ContentItem`.
When adding Content to the DNN database using the `ContentController.AddContentItem(ContentItem item)` API it would not set the `CreatedByUserId` or `LastModifiedByUserId` correctly. In this API DNN invokes a Stored Procedure and uses the same value for both fields, it then sets `LastModifiedByUserId` after the stored procedure is invoked. This is why we would get some odd behavior where `CreatedByUserId` was -1 and `LastModifiedByUserId` would be 1. 
I have outlined the new rules in this table below
| New/existing rules | ContentItem.CreatedByUserID | CurrentUser().UserID | Resulting …
> Fixes AddContentItem Audit Trail for CreatedByUserId & LastModifiedByUserId

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeview.jsx
Fixes #4324 
Removed the dragover state from destination element when dragged and hold between pages.
> remove dragover state from element when dragged BETWEEN pages

- README.md
- azure-pipelines.yml
This adds a YAML definition for the build, so that pull requests can make incremental changes to the build process, and to publicly document the build process.
This is just a copy of the existing build process, using the View YAML feature in pipelines.
> Use YAML for build pipeline

- DNN Platform/Library/Common/Utilities/Config.cs
Changed WebConfigurationManager for System.Configuration.ConfigurationManager when reading connection strings and app settings
Fixes #4227 
Changed only the WebConfigurationManager instances being used for reading app settings and connection strings. Tested on a 9.7.2 website.
> Changed WebConfigurationManager for ConfigurationManager

- .github/BUILD.md
`-Target CreateSettings` and `-Target ResetDevSite` should now be `--target=CreateSettings` and `--target=ResetDevSite`.
> Update BUILD documentation for Cake v1 changes

- DNN Platform/Library/Entities/Urls/FriendlyUrlSettings.cs
- DNN Platform/Library/Entities/Users/UserController.cs
- DNN Platform/Library/Security/Membership/UserLoginStatus.cs
- DNN Platform/Website/App_GlobalResources/SharedResources.resx
- DNN Platform/Website/Default.aspx.cs
- DNN Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs
Fixes #4346 by removing the Running Default check from default.aspx and marked enum members and validation methods as obsolete.
> Removed "Running Default" check from Default.aspx

- DNN Platform/Library/Services/Localization/Localization.cs
Fixes #4304 
As I mentioned in the issue, this does cause the duplication of some `Set-Cookie` headers.  So we'll have to decide which is more important, unless someone else wants to spend more time trying to figure out how to get ASP.NET cookies to behave.
This reverts commit 2435e149b1fd8cf484916dbdedc7d765789e8b02.
> Revert "Simplify cookie setting to avoid duplicate language cookies being set"

- Build/Cake/packaging.cs
> Allows upgrades from de-teleriked dnn instances

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Fixes #4196 
A child page given as first option in the "Add Multiple Pages" is an invalid option now. In addition to that a parent with just ">" in next line is also marked as invalid (Empty child tab name).
> child page without a parent should not be validated

- DNN Platform/Library/Services/Installer/Installers/AssemblyInstaller.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Installer/AssemblyInstallerTests.cs
> Fix AssemblyInstaller failing to UnRegister dll if missing from disk.

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.08.01.SqlDataProvider
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/4362
The rootcause of this problem is in the following line of a `GetFoldersByPermissions` stored procedure:
The subquery above is trying to get all the folders for the specific user/role for which access is denied (`allowAccess=0`). The subquery returns list of folder ID's.
Problem is that `allowAccess` flag relates to a concrete folder permission (READ, WRITE, ADD...) and not to an entire folder. This means, if at least one permission is denied so we return entire folder and consider it as denied. This is the issue. Due to that it is not getting appeared on UI.
Instead, we must return concrete denied **folder permission** for the specific user/role. 
See the changes I did highlighted in yellow below. FolderID is replaced by …
> DNN-42147 Denying the `ADD` permission for a role on an asset makes it invisible to users on CKE Editor.

- DNN Platform/Library/Collections/ReaderWriterLockStrategy.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Collections/ExclusiveLockSharedDictionaryTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Collections/ReaderWriterLockSharedDictionaryTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Collections/SharedDictionaryTests.cs
We have a unit test that started failing about 2/3 of the time, which is causing us to manually re-run builds.
This changes that test to be more explicit.
> Try to fix flaky test

- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
- DNN Platform/Website/DotNetNuke.Website.csproj
The DotNetNuke.Library project (i.e. `DotNetNuke.dll`) has many duplicate references, one to a project (e.g. DotNetNuke.Instrumentation) and another to the output of that project (e.g. `..\DotNetNuke.Instrumentation\bin\DotNetNuke.Instrumentation.dll`)
This removes all of the assembly references when a project reference exists.  It also replaces the assembly reference for DotNetNuke.Syndication with a project reference.
> Remove duplicate references

- DNN Platform/Tests/.editorconfig
- DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
- DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
- DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
- Dnn.AdminExperience/Tests/.editorconfig
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/PagesControllerUnitTests.cs
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
This turns off the documentation rules for StyleCop and turns on Warnings as Errors for all test projects
> Warnings as Errors for test projects

- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Components/FacebookClient.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Components/FacebookUserData.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/DotNetNuke.Authentication.Facebook.csproj
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Login.ascx.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Settings.ascx.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Components/GoogleClient.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Components/GoogleUserData.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/DotNetNuke.Authentication.Google.csproj
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Login.ascx.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Settings.ascx.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Components/LiveClient.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Components/LiveUserData.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/DotNetNuke.Authentication.LiveConnect.csproj
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Login.ascx.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Settings.ascx.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Components/TwitterClient.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Components/TwitterUserData.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/DotNetNuke.Authentication.Twitter.csproj
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Login.ascx.cs
- DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Settings.ascx.cs
This enabled warnings as errors for all four external auth providers (Twitter, Facebook, Google, and Live)
> Enable warnings as errors for 3rd party auth providers

- DNN Platform/Library/Services/Mail/Mail.cs
The public method `Mail.ConvertToText` was accidentally removed in #3969, this PR adds it back.
> Add back method which was removed in #3969

- DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
- DNN Platform/Library/Entities/Urls/RedirectReason.cs
Fixes #3466
While using the default Advanced URL format setting on the DNNFriendlyUrl config, redirects would always return 301 Permanent response codes even when the user had it set as a Temporary redirect from the Persona Bar.
This PR removes: 
1. the evaluation of a static setting (ForwardExternalUrlsType) that always forces both Internal Page and External URL redirects to be permanent without evaluating the user defined setting. This setting is hardcoded and not read from the DB.
This PR adds: 
1. logic to check if the user has defined the page as permanent/redirect for both Internal DNN Page redirects and External URL redirects
2. A new redirect reason so that the response reason matches the response code.
> Fix Issue #3466 - Incorrect Redirect Response Codes

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageDetails/PageUrl/PageFile/PageFile.jsx
Fixes #4386 
Validation code was not getting passed to PageFile.jsx which is fixed now. The code gets sent to the file upload control along the chain.
Demo: https://drive.google.com/file/d/1rcSV2QK1p9Yp54Zde-Cbcim44j6wPbQ5/view
> Issue-4386 - Cannot Create Pages of Type "File"

- DNN Platform/DotNetNuke.DependencyInjection/DependencyAttribute.cs
- DNN Platform/DotNetNuke.Web/Api/Internal/DnnActionFilterProvider.cs
- DNN Platform/DotNetNuke.Web/Api/Internal/ServicesRoutingManager.cs
- DNN Platform/DotNetNuke.Web/DependencyInjection/BuildUpExtensions.cs
- DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
- DNN Platform/DotNetNuke.Web/Startup.cs
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/Mocks/MockCBO.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/DnnActionFilterProviderTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/ServiceRoutingManagerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/DependencyInjection/BuildUpExtensionsTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/DependencyInjection/BuildUpExtensions_SampleFilters.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
This adds property injection for WebAPI filters using the current Dependency Injection model. It mimics similar techniques that are common in the Unity Dependency Injection library by creating a new `BuildUp()` extension method to manage the Property Injection.
Suppose you have an `ActionFilter` that decorates one of your WebAPI methods and you need to leverage dependency injection to access a specific service. In ASP.NET WebAPI you can't use constructor injection due to how the filters are generated in the pipeline. It is considered a best practice to use Property Injection instead of the standard constructor injection.
This can be dangerous for us to adopt into the platform as I can see property injection and the `BuildUp()` method being abused. I would like to take a closer look at the …
> Adds Dependency Injection to WebAPI Action Filters using Property Injection

- Dnn.AdminExperience/ClientSide/AdminLogs.Web/src/components/LogSettings/LogSettingEditor/index.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/AdminLogsController.cs
Fixes #4398
This pull request reverts 4d1f352e8ca076ab9092362d9bc2da367dadc4e6 and changes the Admin Logs panel to show error notifications when Log Settings operations fail (instead of success notifications)
> Admin Logs - Fixed Log Settings errors

- DNN Platform/Library/Entities/Modules/Settings/ParameterAttributeBase.cs
- DNN Platform/Library/Entities/Modules/Settings/PortalSettingAttribute.cs
- DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
- DNN Platform/Website/App_GlobalResources/SharedResources.resx
This affects the settings support we have for modules. With this PR you can now store a setting securely.
> Support for secure settings in settings serialization

- DNN Platform/Library/Entities/Portals/PortalInfo.cs
`PortalInfo.PortalId` was introduced in DNN 9.7.2, but should have been made private (i.e. should have been an explicit interface implementation), in order to avoid breaking case insensitive languages (e.g. VB.NET)
I'm not sure this is the right solution, since it will be breaking to anyone using the new member for the last three releases (whereas with #4139 we resolved an issue introduced in 9.7.2 in 9.7.3).
> Remove member with case-sensitive naming conflict

- DNN Platform/Library/Entities/Content/Taxonomy/TermController.cs
Resolves #4410 by clearing the cache of the content item if a new term was associated.  Additionally fixed a situation where a term was removed.
> Fixe Caching Issue in TermsController

- DNN Platform/Library/Services/GeneratedImage/DnnImageHandler.cs
return WhiteListFolderPaths.Any(normalizeFilePath.StartsWith); => 
return WhiteListFolderPaths.Any(s => normalizeFilePath.StartsWith(s, StringComparison.InvariantCultureIgnoreCase));
> Fix DnnImageHandler bug when filepath mixedcase #4420

- DNN Platform/Library/Entities/Urls/FriendlyUrlSettings.cs
Resolved #2862 by introducing a new default exclusion for lowercase URL's to prevent lowercasing the URL's that contain the verification code.
This DOES not change anything for users on upgrade that has custom values for the "prevent lowercase" setting due to risk of manipulating the value they may have.
> Resolved issue with lowercase URL's and account verifications

- azure-pipelines.yml
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml states:
>We recommend upgrading from build artifacts (`PublishBuildArtifacts@1` and `DownloadBuildArtifacts@0`) to pipeline artifacts (`PublishPipelineArtifact@1` and `DownloadPipelineArtifact@2`) for faster output storage speeds.
> Use pipeline artifacts instead of build artifacts

- Build/Cake/unit-tests.cs
- azure-pipelines.yml
Cake currently runs each test assembly in its own test process and these processes are not run in parallel.  This PR adjusts the build to pass all test assemblies to the test runner at once.
> Run unit tests in parallel

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/plugins/dnnpages/lang/fr.js
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/plugins/dnnpages/lang/nl.js
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/plugins/dnnpages/plugin.js
In the upgraded dnnpages-plugin for CKEditor, I left the full list of langues. Since only 3 (en,de,pl) language files are actually supported currently, the others result in an error.
This simple removal provides the same solution we had before.
I skipped creating an issue this time, since it's not in a RC yet, anyway. If needed, I'm happy to create one, of course.
> removed languages not provided in dnnpages plugin

- azure-pipelines.yml
Currently the YAML pipeline for Azure DevOps documents the required variables in comments, but they're actually configured separately with the pipeline.  Using [parameters](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script) instead allows us to restrict the available options and declare defaults in the YAML document, instead of having them defined separately.
> Use parameters instead of variables in pipeline

- Dnn.AdminExperience/ClientSide/Pages.Web/src/services/pageService.js
Fixes #3081 
I added the default value for sitemapPriority on the client, since several other "controls" get their ddefault values there too, and since I didn't really find a better place for it.
I concidered PagesController.GetDefaultSettings but that didn't seem right either.
This change adds the default value to the property that is being used for the value of the dropdown. When the page is saved, this value is posted to the server too and correctly saved.
> sitemappriority for new page set to 0.5

- DNN Platform/DotNetNuke.Web.Client/ClientResourceManager.cs
- DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
- DNN Platform/Tests/App.config
- DNN Platform/Website/Install/Config/09.09.00.config
- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
Resolves #4447 by removing the old system.web/httpHandlers and system.web/httpModules sections from the web.config.  Additionally removed one instance where DNN would have manually added one back in.
> Web.config Cleanup

- Dnn.AdminExperience/ClientSide/Sites.Web/package.json
- Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
- Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/Components/ListView/index.jsx
- Dnn.AdminExperience/ClientSide/Sites.Web/src/containers/Root.prod.js
This is related to #3875 and is for the `Sites.Web` project.  
* `moment` replaced with `dayjs`
* ClientSide project name changed from `boilerplate` (wtf) to `sites`
> Migrate from moment to dayjs for Sites.Web

- Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
`moment` is not used in this project, so to avoid confusion, the package has been removed.  This resolves the need identified in #3875  for migrating to `dayjs` as well.
> Remove moment package from SiteImportExport.Web

- Dnn.AdminExperience/ClientSide/Roles.Web/package.json
`moment` is not used in this project, so to avoid confusion, the package has been removed. This resolves the need identified in #3875 for migrating to `dayjs` as well.
> Remove moment package from Roles.Web

- Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
Remove `moment` package from `AdminLogs.Web` because it is not used.  This PR relates to #3875.
> Remove moment package from AdminLogs.Web

- Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
Remove `moment` package from `Prompt.Web` since it is not used.  This PR relates to #3875
> Remove moment package from Prompt.Web

- DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
- DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.cs
- DNN Platform/Connectors/GoogleTagManager/Scripts/connector.js
- DNN Platform/Library/Services/Analytics/Config/AnalyticsConfiguration.cs
Fixes #4452 
Fixes #4453 
Both issues were found in the GTM Connector I previously contributed, but I found #4453 (Null Reference exception thrown on deletion of connection) to also occur with the GA Connector (which makes sense since the GTm Connector was initially a copy of that one).
To fix that I added null-checks in a few places.
The other issue is not a bug, but it's a valid point that  it's not very friendly to make the user manually edit SiteAnalytics.config before being able to use the GTM connector.
So I added code to check siteanalytics.config for the presence of a script for it. If there is none, the default script is added. If there is any (which could be edited in the installation) it's not changed.
However, I have one issue in the code. To find SiteAnalytics.config, I …
> Fixed an issue that prevented Google Tag Manager to create scripts and delete connection

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/.storybook/utils.js
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/WebpackExternals/index.js
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/DatePicker/index.jsx
Migrate `moment` to `dayjs` for `Dnn.React.Common` - relates to #3375
> Migrate moment to dayjs for Dnn.React.Common

- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Library.build
- DNN Platform/Library/packages.config
When I was doing my PR for DependencyInjection logging the MailKit provider was logging an error saying it was missing the 1.8.8 version of BouncyCastle.Crypto. The NuGet package was referenced, however, the DLL was never being added to the bin folder on install. This PR fixes that issue.
> MailKit missing BouncyCastle.Crypto

- Dnn.AdminExperience/ClientSide/Pages.Web/package.json
- Dnn.AdminExperience/ClientSide/Pages.Web/src/utils.js
Migrate `moment` to `dayjs` for `Pages.Web` project.  This relates to #3875.
> Migrate moment to dayjs for Pages.Web

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/WebpackExternals/index.js
The common bundle goal was to put on the page stuff that most of our React modules use in order to reduce each of the bundles for individual modules at the cost of a larger common bundle. This is nice but several of the exported (Webpack Externals) packages are simply not used by any module or a single module.
This PR marks all of those deprecated for removal in v.10 except es6-promise which is a polyfill needed to support IE11 and it's used by some of the modules.
It also removes all development time only dependencies, which should not even be distributed. I was hoping for a big file reduction, but well, it will remove about 300Kb to the bundle when we do remove it, so it's better than nothing 🤷
> Deprecates dependencies in common bundle

- Build/Tools/NuGet/DotNetNuke.DependencyInjection.nuspec
- DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
- DNN Platform/DotNetNuke.DependencyInjection/Extensions/TypeExtensions.cs
- DNN Platform/DotNetNuke.Instrumentation/Properties/AssemblyInfo.cs
- DNN Platform/DotNetNuke.Web.Mvc/Extensions/StartupExtensions.cs
- DNN Platform/DotNetNuke.Web/Api/Extensions/StartupExtensions.cs
- DNN Platform/DotNetNuke.Web/DependencyInjectionInitialize.cs
Fixes #4454
Added logging to the SafeGetTypes function. The function would successfully load the types safely, without crashing, but would eat any exceptions that were thrown about missing references. I have added an `ILog` parameter to the function to print out the missing types.
> Add Logging to the Dependency Injection SafeGetTypes function

- DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
Based on http://www.mimekit.com/docs/html/Frequently-Asked-Questions.htm#SslHandshakeException
> Automatically handle TLS negotiation for MailKit

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
This addresses the build warnings:
```
D:\a\1\s\Build\BuildScripts\AEModule.build(3,3): warning MSB4011: "D:\a\1\s\packages\Yarn.MSBuild.1.16.0\build\Yarn.MSBuild.props" cannot be imported again. It was already imported at "D:\a\1\s\Dnn.AdminExperience\Dnn.PersonaBar.Extensions\Dnn.PersonaBar.Extensions.csproj (3,3)". This is most likely a build authoring error. This subsequent import will be ignored.
D:\a\1\s\Dnn.AdminExperience\Dnn.PersonaBar.Extensions\Dnn.PersonaBar.Extensions.csproj(776,3): warning MSB4011: "D:\a\1\s\packages\Yarn.MSBuild.1.16.0\build\Yarn.MSBuild.targets" cannot be imported again. It was already imported at "D:\a\1\s\Build\BuildScripts\AEModule.build (4,3)". This is most likely a build authoring error. This subsequent import will be ignored.
```
> Remove duplicate references to Yarn.MsBuild

- Build/BuildScripts/AEModule.build
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/packages.config
- yarn.lock
I'm hopeful that we can transition to Yarn 2 at some point, but for now this at least gets us to the latest version of the 1.x branch.
> Use latest Yarn 1.x

- Build/BuildScripts/AEModule.build
- azure-pipelines.yml
* Add caching of Yarn files to speed up builds
* Pass `--frozen-lockfile` to `yarn install` to avoid extra work and inconsistent build state
> Adjust Yarn configuration for CI

- DNN Platform/Library/Services/Mail/CoreMailProvider.cs
- DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
Fixes #4502 
Related to Issue #4472 and PR #4473 which add usage of CC and BCC fields to the MailProvider implementations.
This PR adds the use of ReplyTo to both the CoreMailProvider and MailKitMailProvider.
Also, the BodyEncoding property of the MailInfo object passed into the provider is now used by CoreMailProvider, the same way as it was before the implementation of the provider model.
The change was tested by using OpenForm to send a message with a custom ReplyTo address.
> Use ReplyTo Address in MailProvider implementations

- DNN Platform/DotNetNuke.Web.Client/ClientResourceManager.cs
- DNN Platform/Library/Services/FileSystem/FileContentTypeManager.cs
- DNN Platform/Website/Default.aspx.cs
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.09.01.SqlDataProvider
Fixes #4499
1. To support Page Stylesheets stored in AzureFolderProvider (and others).  Attempt to get the Page Stylesheet from the FolderProvider first.  If it exists with an external url, then include the css in a page header `link`.  If not, include through ClientResourceMananger (current way)
2. Add CSS contenttype to FileContentTypeManager.cs and Database Lists of type 'ContentTypes'.  If this doesn't exist .css will be uploaded as 'application/octet-stream' and browsers won't use it as a css file.
> Azure page css

- DNN Platform/Website/admin/Skins/UserAndLogin.ascx
I removed the hard coded spaces on line 23 and 24
fixes #4504
> Remove extra spaces from UserAndLogin Theme Object fixes #4504

- Build/Cake/build.cs
- Build/Cake/ci.cs
This is a follow up on my previous PR to automatically calculate the packages checksums during CI builds, by mistake I put the target dependencies on the wrong target, this PR should fix that and actually make the correct target run.
> Fixed an issue where checksums where not generated in CI builds

- Build/Tools/NuGet/DotNetNuke.Instrumentation.nuspec
The current state includes a circular dependency from DotNetNuke.Core
to DotNetNuke.DependencyInjection to DotNetNuke.Instrumentation to
DotNetNuke.Core.
> Remove NuGet dependency from Instrumentation

- .github/workflows/image-actions.yml
The Compress Images workflow isn't catching most of the images being
committed. This is, in part, because it doesn't run with permissions to
edit PRs on forks. This updates the configuration to open a new PR when
a commit is merged, if there are images that can be compressed. It also
adds a scheduled run, in case something gets missed.
Based on https://github.com/calibreapp/image-actions#combined-workflow
> Update Compress Images GitHub Actions workflow

- .github/workflows/image-actions.yml
There's a typo in the `image-actions.yml` GitHub Actions workflow since my PR #4478 was merged
> Fix typo in image-actions

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Provider.build
Fixes #4537 
In a previous PR I moved images and icons out of the ckeditor folder, since they really where not related to the editor, but the provider itself. In issue #4537 it was pointed out that the moved images are currently not included in the install package.
This PR fixes that by changing the build file.
Tested with a new install from the develop branch.
> Fixed an issue where CK-Editor provider did not include image files in install package

- DNN Platform/Providers/FolderProviders/AzureFolderProvider/AzureFolderProvider.cs
Fixes #4481
Override UpdateFile in the AzureFolderProvider, look to see if the original filename is different from the new one.  If it is, then delete it.
> Fixes #4481 AzureFolderProvider uploading same file with different case

- DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
Fixes #4306 
If PortalAliasMapping is set to redirect, and the request is not for the primary alias, user will be redirected
In advancedUrlRewriter.IsPortalAliasIncorrect there was a check to allow redirection to an alias when forceAlias was used in the querystring.
I added to that check that if the request is not for a primary alias, and PortalAliasMapping is set to redirect, the user will also be redirected to the primary alias
> fixed redirect to primary alias when PortalAliasMapping is set to redirect

- Build/Build.csproj
- Build/Cake/build.cs
- Build/Program.cs
Cake and its various modules have released updates, this PR applies those updates.
One fixed bug has to do with when a working directory change takes affect, so a couple of paths needed to be adjusted (in general, everything is now always automatically using the correct root directory).
> Upgrade Cake to 1.1.0

- .gitignore
- Build/Build.csproj
- Build/Program.cs
- Build/Tasks/Build.cs
See https://msbuildlog.com/ for the log viewer and other details on binary logs.
> Use binary logger instead of console logger for speedier builds

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.09.00.SqlDataProvider
Config code (09.09.00.config) only runs if we have a matching 09.09.00.SqlDataProvider present. Some time ago we added generating an empty one to prevent these kind of issues in many upgrade areas during build. But it does not commit that file so it only fixes it for that release version and we are lacking a 09.09.00.SqlDataProvider in 09.09.01.
For that reason the code that modifies the web.config file to add the MailKit provider does not fire when upgrade from <9.9.0 to 9.9.1
This PR solves this but in DNN10 it would be nice to look into the upgrade code so that it does not rely on xx.xx.xx.SqlDataProvider as the single source to know if there is any upgrade to do as we don't always have slq changes, it would be nice to look at multiple versioned files like config and IUpgradeable …
> Fixed an issue that prevented MailKit configuration upon upgrades

- .github/dependabot.yml
With [the announcement of General Availability for Dependabot version updates](https://github.blog/changelog/2021-03-31-dependabot-version-updates-are-now-generally-available/), I thought it would be good to setup a basic config. I added npm and NuGet at monthly for now. We can also disable them altogether, or set them up for a different branch.
> Add initial dependabot config

- Build/Tasks/OtherPackages.cs
- Build/Tasks/PackageMailKit.cs
- Build/Tasks/packaging.json
- Build/Tasks/unversionedManifests.txt
- DNN Platform/Components/MailKit/License.txt
- DNN Platform/Components/MailKit/MailKit.dnn
Fixes #4563 
I haven't had a chance to test that this does the right thing, waiting for the generated packages to check.
Also, I'd like to adjust how we're generating these to read the versions and update the manifest magically, but haven't gotten to that yet.
> Add package for MailKit

- DNN Platform/DotNetNuke.Web/InternalServices/ItemListServiceController.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ExistingModuleDialog.js
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ModuleDialog.js
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Styles/ContentEditor.css
Resolves #4203 
Thanks to @valadas for a great deal of help on this one!
> Add capability to add existing modules from other sites in site group

- Build/Tasks/CreateNugetPackages.cs
We're currently producing ["legacy" symbols packages](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages) for NuGet, which is causing issues with automated pushing of NuGet packages (the ordering matters of whether you push the non-symbols or symbols package first and we're getting a conflict error).
This PR tells NuGet to produce the [newer symbols package format, `*.snupkg`](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg), which should resolve that issue.
I've had unrelated issues getting my build to finish locally, so this change still needs confirmation from the PR build.
> Produce snupkg format for NuGet

- .github/dependabot.yml
This adjusts the Dependabot config to add the following labels to all dependency PRs:
* [_Type: Maintenance_](https://github.com/dnnsoftware/Dnn.Platform/labels/Type%3A%20Maintenance)
* [_Priority: Low_](https://github.com/dnnsoftware/Dnn.Platform/labels/Priority%3A%20Low)
* [_Status: Testing_](https://github.com/dnnsoftware/Dnn.Platform/labels/Status%3A%20Testing)
It also adds [_Type: Build/Release_](https://github.com/dnnsoftware/Dnn.Platform/labels/Type%3A%20Build%2FRelease) to PRs for GitHub Actions updates.
Let me know if any of those don't make sense to y'all and we can adjust or remove.  Thanks!
> Adjust labels used by dependabot

- DNN Platform/Library/Services/FileSystem/FolderManager.cs
> Use ConcurrentDictionary in FolderManager.cs

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
The feature does not create a hyperlink (which would have an href parameter), when an `<a>` tag has no href, it is called an anchor (hence the `<a>`). Also the phrasing was a bit unclear and this new way to phrase it explains the feature a little better.
> Clarified text on module anchor feature

- DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Fixes #4684 
The bug was very similar to #4143 and the code to check the order of modules is added on top of the fix provided for #4143's PR (#4144).
> Issue-4684 - Exporting a page after changing a module's order within the same pane doesn't reflect in imported site

- DNN Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs
I have changed function to get IP for Login Ip validation with last UserRequestIPAddressController function
This PR solves the issue mentioned in #4701
Basically I have changed
var clientIp = NetworkUtils.GetClientIpAddress(this.Request);
To
var clientIp = userRequestIpAddressController.GetUserRequestIPAddress(new HttpRequestWrapper(this.Request));
> Improve Validation IP Address for login

- DNN Platform/DotNetNuke.Web/InternalServices/FileUploadController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/Mocks/MockComponentProvider.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/FileUploadControllerTests.cs
Request content is compared using culture dependent string comparison
The string comparison code breaks when culture is “tr-TR”. 
The fileName parameter does not get set and UploadFile() helper method does not get called.
Fixed by changing the comparison to invariant culture.
Added unit tests covering the code changes.
Fixes #4654
> Fix for #4654: Unable to Upload File into Assets On Turkish Localization

- DNN Platform/Library/Entities/Host/Host.cs
Fixes #3526
Deprecates the Host Setting property DisplayCopyright so that it can be removed in v11
Nothing to really test here. Minimal, low-risk change
> Deprecating DisplayCopyright Host Setting

- DNN Platform/Website/admin/Security/App_LocalResources/SendPassword.ascx.resx
- DNN Platform/Website/admin/Security/SendPassword.ascx.cs
#4605
Includes the email address or username in the password reset message for better visibility into PASSWORD_SENT_FAILURE events.
> add email to password sent message for error tracing, fixes #4605

- DNN Platform/Library/Entities/Users/UserInfo.cs
When an email goes out that uses the [user:username] property, it doesn't properly fill in the username if the site is set to use email as username. This PR fixes that.
> Fixed an issue where UserInfo.UserName was wrong with "Use email as username" setting turned on

- DNN Platform/Website/Install/UnderConstruction.template.htm
Fixes #4650
Removed the logo from the UnderConstruction page
- Start with a previous version of DNN prior to the current release
- Once installed/setup, unzip the DNN upgrade package in the website root
- Before running the upgrade, update the following keys to false in the web.config, 
```
<add key="AutoUpgrade" value="false" />
<add key="UseInstallWizard" value="false" />
```
- Navigate to the homepage of your DNN Install
- This will trigger the UnderConstruction page to be displayed. 
- You should not see a logo displayed on the page.
> Removed the logo from the Under Construction page

- Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/Performance.jsx
Fixed onchange event handler for 'Cache-Settings' dropdown 
UI was not sending the request in the correct format to UpdatePerformanceSettings() API, when "No Caching" value is selected.
The root cause being in the Performance component's onChangeField(). The value selected in the 'Cache-Settings' dropdown was not validated correctly.
Fixed code in the if clause. When "No Caching" is selected, "event.value" is "0". The updated code makes sure that if function evaluates to true when caching value is "0". So API request sends correct value for "CacheSetting" parameter.
Fixes #4672
> Fix for #4672: Cache-Setting 'NoCaching' not saved

- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
This enhances the server summary section of the Persona Bar in the following ways:
* Update server styling updated to utilize new theming feature via CSS variables.
* Improved styling overall (thanks @valadas for the suggestion on using the left border).
This PR also cleans up a bunch of CSS formatting issues.
> Enhanced styling for server summary in persona bar

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PagesControllerImpl.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Resolves #3111
URL page types now support absolute and relative URLs.  Furthermore, better handling has been added for URLs that begin with `//` or have not including a leading `/` (e.g., `PageName`, `PageName#AnchorName`).
> Added support for absolute and relative URLs

- DNN Platform/Library/Services/GeneratedImage/ImageHandlerInternal.cs
Added an additional check before calling IsPicVisibleToCurrentUser(userId)
For anonymous user, userId is invalid i.e. less than or equal to zero. For invalid user, IsPicVisibleToCurrentUser() returns false and 403 code is sent to UI.
The additional check of isAnonymousUser, avoids the call to IsPicVisibleToCurrentUser() and image is returned for the anonymous user.
Fixes #4733
> Fix for #4733: Profile image for anonymous user is not displayed.

- Build/Tasks/packaging.json
- DNN Platform/Components/Microsoft.AspNetMvc/Microsoft.AspNetMvc.dnn
- DNN Platform/Components/Microsoft.AspNetWebPages/Microsoft.AspNetWebPages.dnn
- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
The original PR #4716 missed a few pieces.
1) Need to include the WebMatrix DLLs in the new AspNetWebPages package, they were also updated.
2) Need to include DotNetNuke.Web.Mvc in the AspNetMvc package, since it relies on a particular version of MVC (another option would be adjusting the version range on the binding redirect, but that would only fix subsequent upgrades).
3) Move the HTTP module for MVC into the AspNetMvc package, since the pieces it relies on aren't included until after install.
> Fix some conflicts with ASP.NET dependencies

- Dnn.AdminExperience/ClientSide/Pages.Web/src/actions/__test__/pageActions.test.js
- Dnn.AdminExperience/ClientSide/Pages.Web/src/actions/pageActions.js
Fixes #4760 
If the deleted page has any children, the page hierarchy is fetched and if the currently displayed page is in the child list of the deleted page, the page gets redirected.
> Issue-4760 - Deleting the parent page while the child page is open doesn't redirect

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.10.01.SqlDataProvider
Adds more columns to the SELECT in these two stored procedures, so that the columns that the code is expecting are there.
Fixes #3624
Thanks @prjrvp for providing the fix!
> Add missing columns to messaging stored procs

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
- Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
- Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
- Dnn.AdminExperience/ClientSide/Pages.Web/package.json
- Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
- Dnn.AdminExperience/ClientSide/Roles.Web/package.json
- Dnn.AdminExperience/ClientSide/Security.Web/package.json
- Dnn.AdminExperience/ClientSide/Seo.Web/package.json
- Dnn.AdminExperience/ClientSide/Servers.Web/package.json
- Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
- Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
- Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
- Dnn.AdminExperience/ClientSide/Sites.Web/package.json
- Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
- Dnn.AdminExperience/ClientSide/Themes.Web/package.json
- Dnn.AdminExperience/ClientSide/Users.Web/package.json
- Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
This adds a `lint` task into all projects with autofix enabled. This will make it easier to auto-fix eslint warnings if we change the configs or while updating eslint dependency in batch using lerna or yarn workspaces. Unfortunately (well fortunately) there were no autofixable warnings to resolve after this change which was my main goal with this PR, anyway, it's still good to have I believe for the future.
Also, this PR includes the commits in #4770 so if it is merged first, this becomes easier to review. If this one gets merged first than dependabot should close #4770 automatically too.
> Added lint task to all node projects 

- DNN Platform/Library/Entities/Modules/DesktopModuleInfo.cs
- DNN Platform/Library/Services/Installer/Installers/ModuleInstaller.cs
By allowing a DesktopModule to have an explicit FriendlyName and
Description set by the install manifest, instead of using the Package
FriendlyName and Description, allows multiple DesktopModules per Package
Fixes #2887
Reimplementation of #2887 and #2886
> Allow multiple DesktopModules per PackageID

- DNN Platform/Library/Framework/Reflection.cs
- DNN Platform/Library/Services/Search/Internals/LuceneControllerImpl.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/Framework/ReflectionTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Search/Internals/LuceneControllerImplTests.cs
Fixes #4823
If a parameterless constructor doesn't exist, the constructor with "Version" parameter is used instead if exists.
> Custom Analyzer types generate System.MissingMethodException

- DNN Platform/Modules/HTML/Components/HtmlTextController.cs
- DNN Platform/Modules/HTML/EditHtml.ascx.cs
- DNN Platform/Modules/HTML/HtmlModule.ascx.cs
- DNN Platform/Modules/HTML/Settings.ascx.cs
Based on [a question on the forums](https://dnncommunity.org/forums/aft/2588) I thought it might be helpful to remove some of the `internal` usages of `Globals.DependencyProvider`, since 3rd party modules can't copy that pattern.
> Avoid HTML module using Globals.DependencyProvider

- DNN Platform/Library/Services/Authentication/AuthenticationConfigBase.cs
`AuthenticationConfigBase` is marked as `Serializable` but has an `IServiceProvider` property which cannot be serialized (it's a type defined outside of DNN and is not marked as `Serializable`). This causes an issue when using a caching provider that uses serialization, e.g. https://github.com/davidjrh/dnn.rediscachingprovider
This PR ~adds the `NonSerialized` attribute to the property and~ makes it retrieve the `IServiceProvider` dynamically (so that it always has a valid value, even after going through serialization).
Fixes #3592
> Resolve serialization issue

- DNN Platform/Library/Services/Mail/CoreMailProvider.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Mail/MailTests.cs
This functionality was inexplicably removed in b3e066f #4187
Includes fixes originally from #2900 (1b44e1d)
Fixes #2899
> Add back alternate views for core mail provider

- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/css/main.css
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
Closes #4787
added IE specific styling by means of a media query
> IE11 corrections fixes #4787

- .github/BUILD.md
Our current build does not work if the developer has an old version of yarn installed globally.
I don't know why but the diff looks very strange...
> Added documentation about yarn updates

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
Fixed an issue where it was impossible to edit html on child portals.
Closes #4791
I have also cleaned up the file a bit
- Resolved all stylecop warnings
- Removed unhelpful comments on private methods
- Renamed some variables and methods for better code clarity
- Updated some comments on public methods
- Removed commented out code
For an easier review, the bug is the first commit and the other commits are cleanup.
> Fixed an issue where it was impossible to edit html on child portals

- Build/Tools/NuGet/DotNetNuke.Web.nuspec
I am not 100% if what I am doing is correct, but when upgrading a module to depend on DNN 9.10.1, the build fails saying that DotNetNuke.Web uses System.Web.Http v5.2.7 but the project references v5.2.3. I usually just update the dependency manually, but though we could declare it so it updates it automatically.
I am no nuget expert, so not sure if this is the right way to do it, looking at the nuget experts (you know who you are) :P
> Marked nuget dependency from DotNetNuke.Web on Microsoft.AspNet.WebApi.Core

- DNN Platform/Modules/CoreMessaging/module.css
Removed module specific styling for a default DNN Button in the Core Messaging module
fixes #4830
> Removed module specific styling for a default DNN Button

- DNN Platform/DotNetNuke.Web.Deprecated/UI/WebControls/TermsSelector.cs
- DNN Platform/DotNetNuke.WebUtility/js/MicrosoftAjax.js
- DNN Platform/Library/Entities/Modules/ModuleController.cs
- DNN Platform/Library/Entities/Urls/TabPathController.cs
- DNN Platform/Library/Security/Roles/RoleController.cs
- DNN Platform/Library/Services/GeneratedImage/DnnImageHandler.cs
- DNN Platform/Library/Services/Search/ModuleIndexer.cs
- DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Services/CloudServicesController.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/Utility.cs
- DNN Platform/Website/DesktopModules/Admin/Security/ProfileDefinitions.ascx.cs
- DNN Platform/Website/js/Debug/MicrosoftAjax.js
Closes #4836 by removing the word "Dummy" from all DNN Platform SOurce code.
*NOTE* References inside third-party referenced scripts were not changed.
> Removal of "Dummy" from code

- azure-pipelines.yml
This allows access to the MSBuild log for failed builds
> Always upload build artifacts

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
The settings for the current portal alias local were returned to the UI instead of the requested language picked in the Page Settings editor. This caused an issue where you would get let's say the English tabs for a french site setting if the last page you happened to visit was English instead of french. The user would then save any setting and all the RedirectAfters would save the wrong thing for that locale.
Closes #4232
Closes #4260
> Resolved an issue where the wrong RedirectAfter tabs were showing for localized sites.

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.10.03.SqlDataProvider
Fixes #4573
Retrieving folders per permissions needed to include conditionals for both grant and deny permissions; also using CTE instead of temp table for better performance.
> Fixed getting Folders by Permissions

- DNN Platform/DotNetNuke.Web.Client/ClientResourceSettings.cs
- DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
I created the necessary overloads that take the portalId as a param. 
I changed LoadPortalSettings to use that new overload.
> fix issue #4900 - created and used overloads that take the portalId as parameter

- DNN Platform/Library/Entities/Users/UserInfo.cs
> Fix #4906: cache the roles array in the user info object.

- .github/workflows/open-merged-pr-to-future-9.11.0.yml
This is a version of #4755 for the 9.11.0 release branch
> Add workflow to auto-open PRs to v9.11 branch

- .github/workflows/updateVersions.yml
After the versions in the `package.json` files are bumped, we need to have `yarn` update the corresponding versions in the lock file.
> Update version in Yarn lock file after bumping

- DNN Platform/Website/Portals/_default/Blank Website.template
- DNN Platform/Website/Portals/_default/Default Website.template
> Update website templates to set `User Registration` to `None` by default

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/Table.jsx
Fixes #4924
The S.E.O. view doesn't update correctly after changing the state because all automatic URLs are returned by the backend with the same `id` of -1. And this `id` property is used as the React component key, which needs to be unique.
This is a typical pitfall with React.
My fix consists of using the array index to generate a negative sequence so that the first automatic URL gets -1, the second -2 and so on.
> Fixed SEO tab not updating correctly after deleting a URL

- .github/workflows/open-merged-pr-to-future-9.11.0.yml
The [workflow triggered](https://github.com/dnnsoftware/Dnn.Platform/runs/4382542237) by the merge/rebase of #4925 failed, presumably because it was accessing the `merge_commit_sha` but the PR was closed via rebase. I've updated the workflow to just use `sha`, which still points to the rebased commit, and [tested on my repo](https://github.com/bdukes/Dnn.Platform/pull/4).
> Adjust release merge workflow

- .github/workflows/open-merged-pr-to-future.yml
This GitHub Actions workflow should open a PR to the `release/10.0.0` branch whenever any PR is merged into the `develop` branch.
The `release/10.0.0` branch should be created before this is merged.
I'm not sure if there's a good way to test this without truly enabling it.
This copies the labels from the original PR. Do we want that, or do we want these v10 merges to always be labelled _Type: Maintenance_?
> Add workflow to auto-open PRs to v10 branch

- DNN Platform/Modules/ResourceManager/module.css
Made sure that all HTML elements in the Resource Manager use 
box-sizing: border-box, independent of the Theme.
fixes #4928
> Updated Module.css to fix #4928

- DNN Platform/Library/UI/Skins/Skin.cs
In the framework we can push a message to the UI which appears in a colored box. This message should not be able to contain any scripts.
> No module message should be able to contain any scripts

- DNN Platform/DotNetNuke.Web.Mvc/Framework/ActionFilters/ValidateAntiForgeryTokenAttribute.cs
Fixes #4958
Properly check for RequestVerificationToken and __RequestVerificationToken in ValidateAntiForgeryTokenAttribute.
The AllKeys property is a plain string[] and Contains is the System.Linq.Enumerable.Contains<T>() which by default does a case-sensitive check.
> Make check for RequestVerificationToken case insensitive as per RFC 7230 and RFC 7540.

- DNN Platform/Website/Providers/DataProviders/09.10.03.SqlDataProvider
Fix Database OutputCache Provider: OutputCacheAddItem stored procedure dublicate primarykey check
> Fix OutputCacheAddItem stored procedure

- azure-pipelines.yml
The 2022 image is currently causing issues, presumably we need to upgrade to Cake 2.x
See https://github.com/dnnsoftware/Dnn.Platform/pull/5004#issuecomment-1030281326 for details
> Use windows-2019 image for CI build

- Build/Build.csproj
- Build/Context.cs
- Build/Program.cs
- Build/Tasks/Build.cs
- Build/Tasks/BuildAll.cs
- Build/Tasks/BuildServerSetVersion.cs
- Build/Tasks/BuildToTempFolder.cs
- Build/Tasks/BuildWithDatabase.cs
- Build/Tasks/CopyWebsite.cs
- Build/Tasks/CreateDeploy.cs
- Build/Tasks/CreateInstall.cs
- Build/Tasks/CreateNugetPackages.cs
- Build/Tasks/CreateSymbols.cs
- Build/Tasks/CreateUpgrade.cs
- Build/Tasks/Default.cs
- Build/Tasks/GeneratePackagesChecksums.cs
- Build/Tasks/GenerateSecurityAnalyzerChecksums.cs
- Build/Tasks/GenerateSqlDataProvider.cs
- Build/Tasks/OtherPackages.cs
- Build/Tasks/PreparePackaging.cs
- Build/Tasks/ResetDevSite.cs
- Build/Tasks/RunUnitTests.cs
- Build/Tasks/SetPackageVersions.cs
- Build/Tasks/UpdateDnnManifests.cs
- azure-pipelines.yml
This PR upgrades the Build project to Cake 2.0.0. In order to do this upgrade, Cake.Frosting.Issues.Recipe was replaced, since [it's not yet upgraded to support Cake 2](https://github.com/cake-contrib/Cake.Issues.Recipe/issues/253). The basic behavior of the recipe (read issues from MSBuild and report them to Azure DevOps) has been put in place.
> Upgrade Cake to 2.x

- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Security/Cookies/PurgeAuthCookiesTask.cs
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.00.SqlDataProvider
Add a scheduled task to purge AuthCookies from the DB that have expired.
Fixes #4982
> Purge expired auth cookies

- DNN Platform/DotNetNuke.Web.Mvc/DnnMvcHandler.cs
Fixes #5003
Sets up the thread culture info for partially rendered MVC views, similar to how it is done for normal page requests (WebForms and MVC) and WebAPI requests.
> Setup the localization for partial MVC view requests.

- Build/Tasks/Build.cs
Currently the CI build reports all "issues" as warnings to Azure DevOps, so the errors that caused a build to fail aren't easy to find. Previously we had been using Cake.Frosting.Issues.Recipe to automatically report these issues, which [does not distinguish between errors and warnings](https://github.com/cake-contrib/Cake.Issues.Recipe/blob/b3bca0f7ba02ba478b315365b04e2df8abed77d0/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/BuildServers/AzureDevOpsBuildServer.cs#L64-L79), and that logic was copied when we recently removed the Cake.Frosting.Issues.Recipe package reference during the upgrade to Cake 2.0. This PR adjusts that logic to report errors as errors and everything else as warnings.
> Report build errors as errors to Azure DevOps

- Build/Tasks/packaging.json
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Data.SqlDataProvider
- DNN Platform/Website/release.config
A clean install would fail due the the mismatched version in the web.config vs the file in the bin folder.
Upon upgrade the DLL file in the bin folder is not included and the package should take care of upgrading the one that is there.
> Fixed an issue where WebFormsMvp initial version mismatched with the config

- DNN Platform/Connectors/GoogleTagManager/GoogleTagManager.config
> Update GTM to follow Google best practices

- Build/Tools/NuGet/DotNetNuke.Web.Mvc.nuspec
- Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
Since version 9.10.0 DNN moved up the dependencies on Microsoft's libraries. This should be reflected in the Nuspec file or else your module will not build. This also means that 9.10.0, 9.10.1 and 9.10.2 nuget packages for DNN will not work to build MVC style modules.
> Fix versions of dependencies in Nuget spec files

- Build/Tasks/Build.cs
If the clean fails, the rebuild never happens, and reading issues from the rebuild log needs to be skipped. This is the reason the errors in #5009 aren't being shown in the build logs.
> Fix failure to report issues when clean fails

- Build/Tasks/Build.cs
Due to a bug I introduced in #5034 we stopped reporting any build errors or warnings from the build process (_only_ errors from the clean before the build were reported)
> Fix not reporting errors or warnings from build

- DNN Platform/Website/admin/Skins/Privacy.ascx.cs
- DNN Platform/Website/admin/Skins/Terms.ascx.cs
Set the rel attribute of the hyperlink only if there is either no value set in the skin or a non blank value defined in the skin. If it is set to rel="" in the skin, the hyperlink will be rendered without a rel attribute.
Fixes #5047
> Allow removal of rel for Terms and Privacy skin objects

- DNN Platform/DotNetNuke.Web.Deprecated/DotNetNuke.Web.Deprecated.csproj
- DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
- DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
- DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
- DNN Platform/Modules/Journal/DotNetNuke.Modules.Journal.csproj
- DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
- DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
- DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
- Dnn.AdminExperience/ClientSide/Sites.Web/publish.bat
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Licensing/App_LocalResources/Licensing.resx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/css/main.css
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/AppEvents/Attributes/IgnoreVersionMatchCheckAttribute.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/App_LocalResources/PersonaBar.resx
I noticed a number of places where DNN Platform still referenced Evoq, even though they are (or should be) entirely separate. I've removed all of those references
> Remove Evoq references

- DNN Platform/Library/Entities/Urls/AdvancedFriendlyUrlProvider.cs
- DNN Platform/Website/admin/Modules/Modulesettings.ascx.cs
Closes #5051
This PR fixes two related issues.
First, in module settings, when getting the alias for a page, use the host portal ID if it's a host tab.
Second, in the advanced friendly URL provider, make sure that `PortalAlias` isn't `null` before trying to read its `HttpAlias`.
> Fix error getting host tab URL

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/scripts/ConfigConsole.js
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/scripts/SqlConsole.js
This has bugged me for a while. But on some of my sites I was unable to use the SQL Console. This is because the scripts are downloaded using an absolute path from the root of the domain. For virtual roots, this will mean those scripts do not load and the module will break. This PR fixes aims to fix that.
> Fixes relative path issues in loading monaco editor

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/AuditChecks.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Checks/BaseCheck.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Checks/CheckTelerikPresence.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Checks/CheckUserProfilePage.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Checks/CheckUserProfilePageTests.cs
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
- Closes #4948
This pull request adds this new `CheckUserProfilePage` class to check the visibility of the user profile page defined in Site Settings > Site Behavior > Default Pages > User Profile Page, according to the following criteria:
* If the Activity Feed page cannot be found, or is deleted, it returns PASS.
* Otherwise, if the Activity Feed page is public, it returns ALERT.
* Otherwise, if My Profile cannot be found or is deleted, it returns PASS.
* Otherwise, if My Profile is public, it returns ALERT.
* Otherwise, it returns PASS.
* If the selected user profile page cannot be found, or is deleted, it returns PASS.
* Otherwise, if the selected user profile page is public, it returns ALERT.
* Otherwise, it returns PASS.
Also, a new base class for audit checks is introduced, and …
> Add new Security Analyzer check for permissions on "Activity Feed" and "User Profile" pages

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Checks/CheckUserProfilePage.cs
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Checks/CheckUserProfilePageTests.cs
This is a small addendum to #5080.
* The summary of `CheckUserProfilePage` was still referencing the portal registration type.
* There was a small bit of duplicate code in one of the unit tests.
> Deduplicated some code in audit check unit test

- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/scripts/util.js
These two utility methods are unused and they depended on `momentjs`.  Instead of swapping out for `dayjs` I felt it best to remove the methods instead.  
This PR relates to #3875
> Removed two unused utility methods that depended on `momentjs`

- DNN Platform/Library/Services/Installer/Installers/AssemblyInstaller.cs
Fixes #5025.
Ensures that the `FileInstaller.DeleteFiles` flag is set to `true` when UnRegister-ing an Assembly file in the AssemblyInstaller.
> Allow the underlying FileInstaller to delete the file if needed.

- DNN Platform/Library/Security/PortalSecurity.cs
Encoded content is not always correctly decoded, this addition resolves the issue.
> Correctly Encode Text Fields

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/AdminLogs.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Bundle.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Extensions.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Licensing.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Pages.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Prompt.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Roles.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Security.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Seo.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Servers.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/SiteGroups.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/SiteImportExport.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/SiteSettings.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/webpack.config.js
- Dnn.AdminExperience/ClientSide/Sites.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/TaskScheduler.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Themes.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/webpack.config.js
- Dnn.AdminExperience/ClientSide/Users.Web/webpack.config.js
- Dnn.AdminExperience/ClientSide/Vocabularies.Web/webpack.config.js
Resolves issue #5120 
What it does is to replace the following:
```
module.exports = {
```
with 
```
module.exports = (env, argv) => {
const isProduction = argv.mode === "production";
return {
```
for all the webpack configurations where we use isProduction. The command line p option (i.e. `webpack -p`) will now properly set isProduction in the configuration.
> Fix issue with undefined isProduction in Yarn scripts

- Build/BuildScripts/AEModule.build
- Build/Tasks/unversionedManifests.txt
AEModule.build had 2 globs that would return some of the same files and have them duplicated in resources.zip files, which was not a major issue but found it while troubleshooting another issue.
Also, WebFormsMVP had recently been made into a package but it was not added to the list of unversioned manifest and would get automatically versioned by the current DNN version upon build.
> Fixed 2 build issues

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpHostController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Servers/App_LocalResources/Servers.resx
SMTP entity was returning some values which should not be inside of the response. This change is removing some unnecessary values from SMTP entity. And sending this field as blank from UI page will not change the value.
> Removing some unnecessary values from SMTP entity

- DNN Platform/Tests/App.config
- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/Dnn.PersonaBar.ConfigConsole.Tests.csproj
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/app.config
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/packages.config
This PR consolidates some dependencies only used in tests to their latest versions.  This affects _DotNetNuke.Tests.Integration_ and _Dnn.PersonaBar.ConfigConsole.Tests_, by upgrading _System.Threading.Tasks.Extensions_ to 4.5.4 and _System.Runtime.CompilerServices.Unsafe_ to 6.0.0
> Update a couple of test dependencies

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
Fixes #4709 
CKE Editor disappears on postback. Returning false will stop the postback from happening.
> Fix bug - postback issue with the cke editor

- DNN Platform/Modules/HTML/Components/HtmlTextController.cs
- DNN Platform/Tests/DotNetNuke.Tests.Modules/AssemblyInfo.cs
- DNN Platform/Tests/DotNetNuke.Tests.Modules/DotNetNuke.Tests.Modules.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Modules/Html/HtmlTextControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Modules/TestSetup.cs
- DNN Platform/Tests/DotNetNuke.Tests.Modules/packages.config
- DNN_Platform.sln
Fixes #5187
This PR adds a new DotNetNuke.Tests.Modules project with tests for `HtmlTextController.ManageRelativePaths`. It resolves the linked issue and also refactors that function to clean up and clarify its implementation.
> Resolve HTML module bug with invalid HTML

- azure-pipelines.yml
This will allow us to rerun a build without getting an error that the artifact was already published
> Add unique suffix to artifact name

- DNN Platform/Library/Common/Utilities/DataCache.cs
- DNN Platform/Library/Data/DataProvider.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Entities/Portals/PortalInfo.cs
- DNN Platform/Library/Obsolete/EventLogController.cs
- DNN Platform/Library/Security/Permissions/ComparePortalPermissions.cs
- DNN Platform/Library/Security/Permissions/PermissionProvider.cs
- DNN Platform/Library/Security/Permissions/PortalPermissionCollection.cs
- DNN Platform/Library/Security/Permissions/PortalPermissionController.cs
- DNN Platform/Library/Security/Permissions/PortalPermissionInfo.cs
- DNN Platform/Library/Security/Permissions/TabPermissionController.cs
- DNN Platform/Library/Security/PortalSecurity.cs
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.00.SqlDataProvider
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/UnInstall.SqlDataProvider
- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/App.jsx
- Dnn.AdminExperience/ClientSide/Pages.Web/src/services/securityService.js
- Dnn.AdminExperience/ClientSide/Pages.Web/src/utils.js
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PagesControllerImpl.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/Security/SecurityService.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/MenuControllers/PagesMenuController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
Replays #5118 on `release/9.11.0` (it was originally incorrectly merged into `develop`).
> Reapply "Top level pages" on release/9.11.0

- .github/workflows/open-merged-pr-to-future.yml
Until we have a `release/10.0.0` this will fail every time
> Disable PR merge for 10.0.0 branch

- DNN Platform/Library/Entities/Users/Profile/UserProfile.cs
> Resolve null reference when data types are missing

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsLogsController.cs
Added validation routines to ensure that the requests for log file display are file names only.
> Restrict log viewing to files only

- DNN Platform/DotNetNuke.Web.Client/ClientResourceManager.cs
- DNN Platform/Library/Services/Tokens/PropertyAccess/JavaScriptDto.cs
- DNN Platform/Library/Services/Tokens/PropertyAccess/JavaScriptPropertyAccess.cs
- DNN Platform/Modules/ResourceManager/View.html
This PR improves on #5242. 
- Use dictionaries of attributes directly instead of requiring them to be serialized and deserialized as strings
- Add HTML attributes overloads for CSS
- Clean up some comments, typos, and other code
> Improve HTML attribute support in client resource manager

- DNN Platform/Modules/ResourceManager/Module.build
Fixes #5251
The MSBuild script copies files from `ResourceManager.Web\dist\dnn-resource-manager` to `Scripts\dnn-resource-manager` and then expects those files to be includes in the resources zip, but the timing of operations means that the files for the resources zip get calculated because the copy.
This PR adjusts the timing of the copying (which I don't think actually does anything, but I don't want to spend more time trying to understand MSBuild). The second change is to explicitly include those new files into the `Resources` variable in MSBuild during the `UpdateFiles` target, so that they get included in the later `Package` target.
> Ensure Resource Manager script files are included in package

- DNN Platform/Library/UI/Modules/Html5/RequestPropertyAccess.cs
- DNN Platform/Modules/ResourceManager/View.html
Closes #5262
It was a bit of a rabbit hole to go down to figure this one out. Initially I thought the CDF had an error serving javascript with a css mime type. But the underlying issue is that with Stencil.js there is a main script that registers individual components scripts in a different way depending on browser support and loads or not some polyfills accordingly (very efficient). This means that that "entry" file was served by the CDF but the file attempts to load it's "component details" files relative to that path. Unfortunatelly thanks to CDF, that relative path was the CDF handler itselft instead of the path to the other js files. And the CDF defaults to css mime type if it can't figure out the right one.
The Client Dependency Framework does not support javascript modules (because …
> Fixed an issue that prevent using resource-manager with CDF

- DNN Platform/Library/UI/Modules/Html5/RequestPropertyAccess.cs
- DNN Platform/Modules/ResourceManager/View.html
Closes #5265
The .Net Request.ApplicationPath behaves this way:
- For a normal install it returns `/`
- For a virtual directory install it retursn `/dnn` (or whatever virtual directory name)
Notice here that in one case the string ends with a / and in the other case not.
This behaviour makes it diffucult to use it in a multi-purpose token made for relative urls as in:
```
<script src="[Request.ApplicationPath]/DesktopModules" />
```
Would render:
- `/dnn/DesktopModules` for a virtual directory (OK)
- `//DesktopModules` for a normal hosting scenario (NOT OK)
This PR adds `RelativeAppPath` which is a variation of `ApplicationPath` that will always end with `/`.
Usage as follows makes it usable in both scenarios and consumers can expect to always have the ending `/` provided:
```
<script …
```
> Added support for RelativeAppPath in Request token

- DNN Platform/DotNetNuke.Maintenance/Telerik/TelerikUtils.cs
Closes #5260
Some dlls may be native code and fail when attemping to check if they have dependencies on Telerik.
This PR basically skips those files, if we can't detect if they depend on Telerik, then they can't possibly depend on Telerik.
> Fixed an issue where Telerik analysis would fail

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/dnn-rm-folder-mappings.scss
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/dnn-rm-folder-mappings.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
- DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
Closes #5274
The new logic is as follows:
1. If we don't have any folder mapping info, we show the standard folder svg
2. If we have in the resource manager an svg for the provider, we use that one (usually nicer and we have one for our own Azure profider connector)
3. If the provider has one, we use the one the provider dictates If all else fails, we use the standard svg one.
In addition to this, I also added a button so users can create new folder mappings (totally forgot about that part when implementing the feature).
> Fixed an issue where folder provider icons would not show

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-queued-file/dnn-rm-queued-file.tsx
Closes #5271
The url used to upload files did not support DNN being hosted on non-root folder in IIS hosting.
> Fixed an issue that prevent upload when using application folder

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/dnn-rm-actions-bar.scss
Closes #5284
In gridview some dropdowns would display under the file/folder icons making them unusable.
> Fixed an issue where resource manager menus would show under icons

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/readme.md
- yarn.lock
#5305 Accidently targetted the `develop` branch instead of release/9.11.0
This PR simply redoes it on the release branch.
In earlier PRs the yarn.lock file was updated apparently in a wrong way.
I did a git bisect to find the commit that initially caused the issue and it was https://github.com/dnnsoftware/Dnn.Platform/commit/ee066b46c99b5304f1cd9437f225e623474cfaed which only touched the yarn.lock file. I reverted that commit and cleaned all local files (node_modules, caches, etc.) Then I rand a full build which updated the yarn.lock file properly and this build worked fine locally. Let's download the build from this CI run before merging to make sure and try to avoid one more RC :)
Fixes …
> Resolved an issue where the React modules would not load

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
- yarn.lock
This PR removes the unused and unmaintained package `react-test-utils` from the project. This package has a dependency on a GitHub repo that has been removed, so if you don't have that package cached (e.g. run `yarn cache clean --all` in the repo) you will get a build failure.
> Remove react-test-utils

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/MenuControllers/PagesMenuController.cs
Fixes #5312 
Pass the TabId of the current page instead of PortalId.
> Pass TabId instead of PortalId

- Build/Tasks/CopyWebConfigToDevSite.cs
- Build/Tasks/ResetDatabase.cs
This PR resolves two issues we ran into while using ResetDevSite to setup a new DNN dev site (plus a third issue that I thought about while in the code).
The first issue is that you get an obscure SQL error if the `DatabasePath` in your local settings uses `/` instead of `\` (or, really `\\` since it's a JSON file). 
>     ========================================
>     ResetDatabase
>     ========================================
>     System.Data.SqlClient.SqlException (0x80131904): A file activation error occurred. The physical file name 'C:/dbs/dnn.local\dnn.local.mdf' may be incorrect. Diagnose and correct additional errors, and retry the operation.
>     CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
The extra issue is that if `DatabasePath` …
> Smooth out potential issues using ResetDevSite

- Build/Tasks/OtherPackages.cs
Resolves issue mentioned at https://github.com/dnnsoftware/Dnn.Platform/pull/5185#issuecomment-1254967053
In #5185 SharpZipLib was removed as a dependency of DNN (except where required by deprecated APIs). A library package was introduced to manage upgrading the dependency, but that package was mistakenly left out of the distribution. This PR resolves that oversight.
> Include SharpZipLib package

- Build/Build.csproj
- Build/Program.cs
- Build/Tasks/Build.cs
Updates build to Cake.Issues.MsBuild 2.0 Beta 1 which comes with support for binary log version 9. This allows to remove certain workarounds which are currently required in the build.
> Update to Cake.Issues.MsBuild 2.0 Beta 1

- DNN Platform/Library/Entities/Portals/PortalController.cs
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.01.SqlDataProvider
Fixes #2874
Checks IsSecure. If true, encrypt the value before checking if it has changed.  Update stored procedure UpdatePortalSetting to properly save IsSecure in PortalSettings.
I'm the developer that was @yog-it which is now my organization account.
> Save IsSecure property of Portal Setting 

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/scripts/ConfigConsole.js
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/scripts/SqlConsole.js
Fixes #5322
This PR updates the SQL Console and Config Manager to load the Monaco editor script using `personaBarSettings.applicationPath` instead of `dnn.getVar("sf_siteRoot")`.
This still needs to be tested on a site hosted in a virtual directory.
> Fix MonacoEditor not loading for child aliases

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
In #5351 a change was implemented to get the root folders according to the settings. Because of this a user is now always on some sort of root folder instead of the root folders not being part of any and having a virtual "root" ListItem. So before that change we were auto-expending that root item but now all direct children are open by default and it does not look right. This PR solves that by not expanding automatically the first level in the tree.
Before:
After:
> Fixed an issue where first level folders were auto-expanded.

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
- yarn.lock
Closes #5349
This was fixed on the dnn-modal itself in https://github.com/DNNCommunity/dnn-elements/pull/633 and this PR simply bumps our dependency on dnn-elements to bring in that fix.
> Fixed an issue where resource manager modal could not contain long lists

- Dnn.AdminExperience/ClientSide/Extensions.Web/src/components/InstallExtensionModal/index.jsx
Modification of the next button in the get package information step, whose name could not be called from language resource files and could not be translated in multilingual portals.
> Modify Next Button on install wizard

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/FileUploader.ashx.cs
Fixes #5339 
The code checked wether resize on upload dimensions are configured, then checked wether the image needs resizing, but fails to actually upload if the image doesn't need resising.
This PR fixes that.
> 5339 Handle upload for image smaller than configured resize dimensions

- DNN Platform/Library/Services/Scheduling/ScheduleItem.cs
The NextStart property was setting itself instead of the privete nextStart value which made it go into an infinite loop and caused the instance to crash.
I also added docs to public methods while I was there.
> Fixed an infinite loop in schedule item.

- DNN Platform/Library/Services/Installer/Installer.cs
If a package manifest would have a comment on the level of the first node, the installer would try to parse the comment instead of the real non-comment node.
0f60ce3a8ba7985e8fb835a9570cbd6855cc6b65 Fixes the actual issue and
50bb9e9328fc4af567e4e1125c41140e2d7c6712 just cleans-ups the file a bit and adds some documentation
> Fixed an issue where comments in manifest would make install fail

- DNN Platform/Website/admin/Skins/Language.ascx.cs
In a previous PR the backing field has been changed and inadvertently the code in this property was set to the property name which creates an infinite loop.
> Fix casing issue on SelectedItemTemplate property

- DNN Platform/Website/DesktopModules/Admin/EditExtension/AuthenticationEditor.ascx.cs
- DNN Platform/Website/DesktopModules/Admin/Security/SecurityRoles.ascx.cs
- DNN Platform/Website/admin/Skins/tags.ascx.cs
PR #5337 implemented auto-fixes for style issues, but the renaming of backing fields sometimes caused a conflict which resulted in the property becoming recursive
> Resolve properties made incorrectly recursive

- DNN Platform/Library/Entities/Tabs/TabController.cs
Fix localizing parent tabs breaking existing localized child tabs by updating the child->parent tab links when localizing parent tabs.
Closes #5383
> Fix localizing parent tabs breaking existing localized child tabs

- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Library.build
Since the addition of library.build to the Library project, the old build logic with a copy to the debug folder is bypassed. This PR fixes that.
> Fix the library debug build to debug folder

- DNN Platform/Library/Services/UserRequest/UserRequestIPAddressController.cs
Fixes issue #5371.
Added code to correctly parse the request IP Address when original IP Address comes in the request header "X-Forwarded-For" (i.e. when using an ARR like in an Azure App Service) by removing the port.
> Fix issue #5371 to correctly handle Request IP Addresses

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/SiteSettings/LanguagesControllerTasks.cs
When creating localized pages a progress bar is shown which uses a text file to store the progress. This file gets a locked error which this PR hopes to solve.
> Fix loading of progress file in content localizer

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/Table.jsx
Fix issues that can cause duplicate rows to show in page->advanced->SEO.
The 'extra duplicate rows appearing after adding new SEO URL' issue is fixed by keying by: `url_${url.id}_${url.path}_${url.statusCode.Key}`. This will be unique for non-automatic URLs because of the {url.id}, and is unique for automatic URLs because of the path and statusCode. It means that the human generated ones will be detected as new rows if the path is edited, but I don't think that's a big deal and this keeps the code simple.
The 'duplicated looking rows show in SEO dialog with multiple languages' issues is fixed by only including unique rows in the dialog. I could have changed it to show the language that's causing the duplicate row in the dialog, but I the extra rows aren't particularly relevant anyway so …
> Fix issues that can cause duplicate rows to show in page->advanced->SEO

- DNN Platform/Library/Data/DataProvider.cs
- DNN Platform/Library/Entities/IPFilter/IIPFilterController.cs
- DNN Platform/Library/Entities/IPFilter/IPFilterController.cs
- DNN Platform/Library/Entities/IPFilter/IPFilterInfo.cs
- Dnn.AdminExperience/ClientSide/Security.Web/src/components/ipFilters/index.jsx
- Dnn.AdminExperience/ClientSide/Security.Web/src/components/ipFilters/ipFilterEditor/index.jsx
- Dnn.AdminExperience/ClientSide/Security.Web/src/components/ipFilters/ipFilterRow/index.jsx
- Dnn.AdminExperience/ClientSide/Security.Web/src/components/ipFilters/ipFilterRow/style.less
- Dnn.AdminExperience/ClientSide/Security.Web/src/components/ipFilters/style.less
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/UpdateIpFilterRequest.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SecurityController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/SqlDataProvider/09.11.01.SqlDataProvider
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
Closes #4140
Hosts can now set a note with each IP Filter rule to remind them about the purpose of each rule.
> Added support for a Notes field in IP Filters

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
Fixes #5406 
In Browser.FileUpload in CKEditorProvider, there is a check for images, that handles the uploading of images, but the branch for non-images is missing.
> 5406 Fix uploading documents through link popup

- DNN Platform/Library/Entities/Users/IUserController.cs
I updated the `IUserController` docs in #5400, but my `GetUsersBasicSearch` details were a little off.
> Correct GetUsersBasicSearch docs

- DNN Platform/Library/Security/Permissions/Controls/FolderPermissionsGrid.cs
- DNN Platform/Library/Services/Authentication/OAuth/OAuthSettingsBase.cs
- DNN Platform/Library/Services/Journal/JournalTypeInfo.cs
- DNN Platform/Library/Services/OutputCache/Providers/MemoryProvider.cs
- DNN Platform/Library/UI/Skins/Controls/LanguageTokenReplace.cs
- DNN Platform/Library/UI/Skins/SkinControl.cs
- DNN Platform/Library/UI/Skins/SkinThumbNailControl.cs
- DNN Platform/Library/UI/UserControls/DualListControl.cs
- DNN Platform/Library/UI/UserControls/Help.cs
- DNN Platform/Library/UI/UserControls/HelpButtonControl.cs
- DNN Platform/Library/UI/UserControls/SectionHeadControl.cs
- DNN Platform/Library/UI/UserControls/TextEditor.cs
- DNN Platform/Library/UI/UserControls/URLControl.cs
- DNN Platform/Library/UI/UserControls/URLTrackingControl.cs
- DNN Platform/Library/UI/UserControls/User.cs
- DNN Platform/Library/UI/WebControls/PagingControl.cs
PR #5337 changed the casing of some `public` and `protected` field and property names. These are breaking changes, as pointed out by @skamphuis. This PR resolves these renames.
> Fix renamed public/protected properties and fields

- DNN Platform/Library/Entities/Tabs/ITabController.cs
- DNN Platform/Library/Entities/Tabs/TabController.cs
- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageLocalization/PageLocalization.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
The previous code was throwing a null ref exception in CreateLocalizedCopyInternal when trying to copy languages that didn't exist in the parent page.  Instead we should skip them.
Also added a warning to the UI to make it clear to users why all their languages weren't added for partially localized parent pages.
Fixes https://github.com/dnnsoftware/Dnn.Platform/issues/5403
> Fix 'Add Missing Languages' when parent page only has some languages enabled

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
I was consistently experiencing locally the build issues we sometimes (well oftentimes) get on azure (can't resolved Dnn.Platform\Dnn.AdminExperience\Dnn.PersonaBar.Extensions\Dnn.PersonaBar.Extensions.csproj)...
So I was trying to pinpoint the possible cause of that issues and when I removed the Project GUIDS from this project file, the build started working. Many of the other .csproj files don't have any ProjectType defined at all and they work fine.
I have confirmed that the install files are still being produced.
One of the GUIDs defines this as an MVC project but it is clearly not, the other defines it as a C# project but the .csproj extension already defines that.
Is anyone is opposed to remove both, then I can bring back the one starting with FAE04....
I am absolutelly not sure …
> Possibly fixed intermittent build issues

- DNN Platform/Modules/ResourceManager/Components/SettingsManager.cs
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-queued-file/dnn-rm-queued-file.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
I haven't had a chance to test this, but I believe this should pass through to the API whether the module is in Global Assets mode or for the current portal.
> Keep track of whether in global assets mode

- DNN Platform/DotNetNuke.Abstractions/DotNetNuke.Abstractions.csproj
- DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
- DNN Platform/DotNetNuke.Maintenance/DotNetNuke.Maintenance.csproj
- DNN Platform/DotNetNuke.ModulePipeline/DotNetNuke.ModulePipeline.csproj
The last couple of builds have errored with the following error:
```
Does D:\a\1\s\DNN Platform\DotNetNuke.Abstractions\..\..\Website\bin specify a file name
or directory name on the target
(F = file, D = directory)?
```
`D:\a\1\s\DNN Platform\DotNetNuke.Abstractions\DotNetNuke.Abstractions.csproj(37,5): error MSB3073: The command "XCOPY "D:\a\1\s\DNN Platform\DotNetNuke.Abstractions\bin\Release\netstandard2.0\DotNetNuke.Abstractions*" "D:\a\1\s\DNN Platform\DotNetNuke.Abstractions\..\..\Website\bin" /S /Y" exited with code 2. [D:\a\1\s\DNN Platform\DotNetNuke.Abstractions\DotNetNuke.Abstractions.csproj]`
> Resolve XCOPY error during build

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/SearchPage/SearchPageInput.jsx
Modification of pages search place holder that can be read from language resource files.
> Modify search placeholder

- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
- DNN Platform/Tests/DotNetNuke.Tests.Modules/DotNetNuke.Tests.Modules.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Modules/packages.config
DotNetNuke.Test.Integration references version 1.0.2 of Microsoft.NETFramework.ReferenceAssemblies and Microsoft.NETFramework.ReferenceAssemblies.net472, whereas all other projects reference 1.0.3.
Likewise, DotNetNuke.Tests.Modules references version 3.13.2 of NUnit, whereas all other projects reference 3.13.3.
This PR resolves the inconsistency.
> Fix out-of-sync package versions in test projects

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/app.config
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/packages.config
All references to Newtonsoft.Json are for version 13.0.2 except Dnn.PersonaBar.Extensions which references 13.0.1. This PR resolves the issue
> Fix PersonaBar project referencing wrong version of Newtonsoft.Json

- Build/Tasks/BuildNpmPackages.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/packages.config
As a follow-up to #5433, this PR removes the Yarn.MsBuild package that is no longer used.
> Remove now-unused Yarn.MsBuild package

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/dnn-resource-manager.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/store/store.ts
- DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
Resolves #5437 
This PR addresses multiple issues related to the referenced issue:
* A new `CanManageFolderTypes` endpoint was added.
* The front end was updated to leverage the new `CanManageFolderTypes` endpoint
* Gear icon for managing folder types in the bottom left of Resource Manager is now hiding for users that are not SuperUsers or Admins.
* The modal is also hidden now for users that aren't SuperUsers or Admins, and thus resolving the `401` from the other API call.
> Remove `Settings` from Resource Manager display for users without permission

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpAdminController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpHostController.cs
Fixed an issue that prevented sending smtp test emails Due to the UI changes in #5152 the frontend now posts an obfuscated password unless the user is currently changing the password. That scenario got handled correctly for UpdateSmtpSettings but the same logic needed to be implements in SendTestEmail for that button to work fine.
Closes #5391
> Fixed an issue that prevented sending smtp test emails

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/Options.aspx.resx
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx.designer.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Constants/SettingConstants.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Objects/EditorProviderSettings.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/Utility.cs
Closes #5408 
Backgroup of the changes can be found in #5408 
In summary I added 4 settings for host level, and implmented their usage on opening the file browser, and on uploading files.
> Added host level setting for browser and upload folders of html editor

- DNN Platform/Library/UI/UserControls/URLControl.cs
Fixes #5423
The URLControl tries for "ADD" permission on the selected folder, but that doesn't exist (anymore?). It changed it to "WRITE" instead, which seems logical because that's actually the permission you're controlling by giving a user or role Edit permissions on a folder. This seems to fix the issues mentioned in #5423 and in [Links](https://github.com/DNNCommunity/DNN.Links/issues/65) and [Documents](https://github.com/DNNCommunity/DNN.Documents/issues/21).
However, I did find other references to the "ADD" permission in several other places:
- ResourceManager.PermissionsManager
- InternalServices.FileUploadController (but that checks for both ADD and WRITE)
- Modules.Export.ascx.cs
These might need changing too. Happy to do so, by the way. Just let me know.
> Fixes an issue where URLControl checks upload permissions wrong

- DNN Platform/Library/Common/Utilities/Config.cs
Fixes #4839
When saving the security settings, an error could occur if the web.config file has not had the attribute maxAllowedContentLength for node security//requestFiltering//requestLimits.  On some occasions users may have added the node but not the attribute.  This fix checks for the attribute, if it does not exist it adds it to the node before setting the value.
> Correctly save the attribute maxAllowedContentLength

- Build/Program.cs
- azure-pipelines.yml
The build has been failing sometimes due to GitVersion.Tool requiring the .NET 5 SDK, this updates to a version that supports .NET 6 and removes the .NET 5 SDK reference from the build.
> Update GitVersion.Tool and remove .NET 5 SDK

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/css/SqlConsole.css
A class name was renamed in #5453 but that class name was used in css and that was missed.
Closes #5466
> Fixed an issue where the SQL editor would not have height

- DNN Platform/Controls/CountryListBox/CountryLookup.cs
- DNN Platform/Library/UI/WebControls/PropertyEditor/Edit Controls/DNN Edit Controls/DNNCountryAutocompleteControl.cs
Fixes #2140
DNNCountryAutocompleteControl.cs LoadControls() method expects Country code in StringValue but receives Country Name
So in the CountryLookup.cs I made a CodeByName static method that will convert a Country Name to Country Code (based on a list already on the file as an array of strings.
Then now DNNRegionEditControl will receive the countryCode and will load the child items
> Fixes #2140 issue

- DNN Platform/Library/UI/WebControls/PropertyEditor/FieldEditorControl.cs
An automated stylecop fix caused a casing issue on a variable (IsValid vs isValid) that was a private field and a public property. The property calling a method and the method using the field (but in this case it was using the property by mistake and causing the endless loop).
I also fixed all other stylecop issues on the file and tested the build to confirm it fixes the issue.
> Fixed an issue that caused an infinite loop when saving pofiles

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-move-items/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/context-menus/dnn-rm-file-context-menu/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/context-menus/dnn-rm-folder-context-menu/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-files-pane/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-cardview/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-listview/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-left-pane/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-move-items/readme.md
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-right-pane/readme.md
As part of stencil pojects, documentation about teach component is auto-generated upon build. In a previous PR I forgot to run a full production build before doing the PR so those docs were not commited.
This PR commits them.
> Commited docs for dnn-resource-manager

- DNN Platform/Library/Common/Utilities/Config.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/BusinessController.cs
Since `Globals.glbConfigFolder` starts with a slash (`"\\Config\\"`), using it in `Path.Combine` causes that section of the path to become the path root, instead of being appended to the previous path, as it was with plain string concatenation
Fixes #5522
> Fix Path.Combine with glbConfigFolder

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs
Fix #5533 - Error happen due filteredSettings is null.
> Fix #5533 - Null checker on EditorHostSetting

- Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/DetailRow/index.jsx
- Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/UserSettings/index.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/App_LocalResources/Users.resx
Added UserID to the information shown in the Users module
Closes #4412
This displays in the settings details but also if you hover the username in the list...
> Added UserID to the information shown in the Users module

- Build/Tasks/BuildNpmPackages.cs
Azure pipelines has updated windows-latest to run on node v18.x.x on Febuary 17th.
Node 18 has bumped some requirements about open-ssl and Webpack 4 will not be updated to support this use case.
The correct solution is to upgrade to webpack 5 but this has the potential to be a massive task. In the meantime one can pass openssl-legacy-provider for node v18 to support the legacy ssl methods. This PR is a workaround to make our current build work and be able to release DNN v9.11.1 I'll create an issue to do this in a more proper manner after I can confirm this PR fixes our issue in CI.
> Implemented a workaround to support node v18

- azure-pipelines.yml
Enforces using node >= v18.x.x
> Update azure-pipelines.yml for Azure Pipelines to use node v18

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/dnn-resource-manager.scss
Temporary CSS-only fix for next DNN patch release to give the Resource Manager a better default height.
In brief, the default height is currently hard-coded to 400px. This fix instead bases the height on the browser's height using "100vh - 25rem" which basically means the resource manager's height will be (dynamically) about 400px less than the browser's height (to account for the theme's header and footer at least). We've also set a min-height of 30rem (appx 480px) so scroll bars appear, but everything functions as expected.
Temp fix, but does not close Issue https://github.com/dnnsoftware/Dnn.Platform/issues/5361
> Temp fix Resource Manager default height

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/AdminLogs/AdminLogsController.cs
Fixes #5573
Fixes an exception when attempting to email logs - needed to select the document element rather than the XmlDocument object.
> Fix exception when emailing admin logs

- DNN Platform/Library/UI/UserControls/HelpButtonControl.cs
- DNN Platform/Library/UI/UserControls/SectionHeadControl.cs
- DNN Platform/Library/UI/UserControls/TextEditor.cs
- DNN Platform/Library/UI/UserControls/URLTrackingControl.cs
The `ModuleID` property of `URLTrackingControl` references itself and so always loops forever whenever it's read.
Fixes #5577
Fixes https://github.com/DNNCommunity/DNN.Documents/issues/22
> Fix unintentional recursion (i.e. stack overflow)

- DNN Platform/Library/Services/Syndication/RssHandler.cs
- DNN Platform/Library/Services/Syndication/SyndicationHandlerBase.cs
- DNN Platform/Syndication/DotNetNuke.Syndication.csproj
- DNN Platform/Syndication/OPML/Opml.cs
- DNN Platform/Syndication/OPML/OpmlDownloadManager.cs
- DNN Platform/Syndication/OPML/OpmlOutline.cs
- DNN Platform/Syndication/OPML/OpmlOutlines.cs
- DNN Platform/Syndication/RSS/GenericRssChannel.cs
- DNN Platform/Syndication/RSS/GenericRssElement.cs
- DNN Platform/Syndication/RSS/RssChannelBase.cs
- DNN Platform/Syndication/RSS/RssChannelDom.cs
- DNN Platform/Syndication/RSS/RssDataSource.cs
- DNN Platform/Syndication/RSS/RssDataSourceView.cs
- DNN Platform/Syndication/RSS/RssDownloadManager.cs
- DNN Platform/Syndication/RSS/RssElementBase.cs
- DNN Platform/Syndication/RSS/RssElementCustomTypeDescriptor.cs
- DNN Platform/Syndication/RSS/RssHttpHandlerBase.cs
- DNN Platform/Syndication/RSS/RssHttpHandlerHelper.cs
- DNN Platform/Syndication/RSS/RssHyperLink.cs
- DNN Platform/Syndication/RSS/RssXmlHelper.cs
- DNN Platform/Syndication/Settings.cs
Resolve documentation warnings in DotNetNuke.Syndication project, turn on `TreatWarningsAsErrors`
> Resolve warnings in DotNetNuke.Syndication

- DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
- DNN Platform/Modules/DnnExportImportLibrary/DnnExportImportLibrary.csproj
- yarn.lock
In #5555 and #5556 LIteDB version was bumped by dependabot but the reference in the .csproj files were not updated. This PR fixes that so we have a working build. It also updates our yarn.lock after running a build following other dependencies updates.
> Fixed an issue resolving LiteDB

- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/theme.css
Fixes #5591
Adding the ability for themers or admins to adjust the size of the PersonaBar Logo while keeping the existing size (default).
> Enhance PersonaBarTheme.css to Resize the PersonaBar Logo

- DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandRepository.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Prompt/CommandRepository.cs
- DNN Platform/Library/Startup.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Repositories/CommandRepository.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/CommandController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Startup.cs
This PR updates creation of Prompt commands to use the dependency injection container.
This includes a breaking change in `ICommandRepository.GetCommand` to take an `IServiceProvider` (in addition to the command name).
> Enable Dependency Injection for Prompt commands

- DNN Platform/DotNetNuke.Web.Mvc/Routing/MvcRoutingManager.cs
- DNN Platform/DotNetNuke.Web.Mvc/Startup.cs
- DNN Platform/DotNetNuke.Web/Api/Internal/ServicesRoutingManager.cs
- DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
- DNN Platform/DotNetNuke.Web/Startup.cs
- DNN Platform/Library/Common/Internal/IRoutingManager.cs
- DNN Platform/Library/Common/Internal/ServicesRoutingManager.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/ServiceRoutingManagerTests.cs
This PR enables dependency injection for `AuthMessageHandlerBase` (basic, digest, and JWT are built-in).
This also replaces the use of reflection to register routes for Web API and MVC.
> Use DI for auth message handlers & routing

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/Dto/UserBasicDto.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/UsersController.cs
> Fix avatar url not being populated when calling UserController.GetUsers

- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FileManagerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FolderManagerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/StandardFolderProviderTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/CryptographyProviders/CoreCryptographyProviderTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/CryptographyProviders/FipsCompilanceCryptographyProviderTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Installer/AssemblyInstallerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Mobile/PreviewProfileControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Mobile/RedirectionControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Search/Internals/LuceneControllerImplTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Tokens/TokenReplaceTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Services/UserRequest/UserRequestIPAddressControllerTest.cs
- DNN Platform/Tests/DotNetNuke.Tests.Data/RepositoryBaseTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Urls/ExtensionUrlProviderControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Utilities/HttpContextHelper.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/Framework/ModuleDelegatingViewEngineTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/Framework/Modules/ModuleApplicationTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/Internals/DnnDependencyResolverTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/Internals/WebFormsServiceProviderTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/PortalAliasRouteManagerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/Api/ServiceRoutingManagerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/FileUploadControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/SearchServiceControllerTests.cs
- DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/TabVersionControllerTests.cs
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/ConfigConsoleControllerTests.cs
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/Dnn.PersonaBar.ConfigConsole.Tests.csproj
#5627 introduced `FakeServiceProvider` and applied it to about half of the scenarios where `Globals.DependencyProvider` is being mocked in a test. This PR applies it in all other scenarios (except for the couple where we're directly testing dependency injection and need more control over the container setup).
> Use FakeServiceProvider for the rest of the tests

- Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
- Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/editLanguagePanel/index.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
> Change site localization mode to be "Site" instead of `Site Title`

- DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/Startup.cs
- DNN Platform/Library/Startup.cs
#5652 introduced an issue because [the Telerik Removal component registers `LocalizationProvider` with the DI container using a lambda pointing to `LocalizationProvider.Instance`](https://github.com/dnnsoftware/Dnn.Platform/blob/a716272d41a864b263cc4db413caa0ae33f02ce9/DNN%20Platform/DotNetNuke.Maintenance/Telerik/Removal/Startup.cs#L32-L37), which is [`ComponentBase.Instance`](https://github.com/dnnsoftware/Dnn.Platform/blob/a716272d41a864b263cc4db413caa0ae33f02ce9/DNN%20Platform/Library/ComponentModel/ComponentBase.cs#L18-L37). Since `LocalizationProvider` is not registered with `ComponentFactory`, this means that, due to #5652, it falls back to the DI container, which then asks the `ComponentFactory` _again_, creating an infinite loop, and ultimately a `StackOverflowException`.
This PR …
> Resolve StackOverflowException

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs
Fixes #5657 
Method `SettingsUtil.LoadEditorSettingsByKey` gets a portalRoles parameter which it uses to determine which role-related default/host settings are overwritten on portal/page/module level. However, those host-level settings do not have role related settings, because roles are only available on a portal level.
This way, the settings for `ToolbarRoles` and `UploadSizeRoles` where emptied and reverted to their defaults in the UI. On save, those "new" settings would then be stored.
This PR fixes that by passing in `null` as portalRoles for loading settings on host/default level, and by not changing the role related settings in `SettingsUtil.LoadEditorSettingsByKey` when no portalRoles are available.
> Fixes #5657 issue with CKE loading previously set toolbar options

- .github/BUILD.md
Under the Building Dnn section, the link How to Contribute is broken.
> Fixes #5660 - Broken link on BUILD.md

- .github/PULL_REQUEST_PROCESS.md
This corrects a broken link to the `Contribute Page` within the PULL_REQUEST_PROCESS documentation
> Correct broken link to `Contribute Page` within PR process documentation

- DNN Platform/Connectors/GoogleAnalytics/Scripts/connector.js
- DNN Platform/Connectors/GoogleAnalytics/connector.htm
- DNN Platform/Connectors/GoogleAnalytics4/Scripts/connector.js
- DNN Platform/Connectors/GoogleAnalytics4/connector.htm
- DNN Platform/Connectors/GoogleTagManager/Scripts/connector.js
- DNN Platform/Connectors/GoogleTagManager/connector.htm
Fixes #5667
It appears [the `checked` binding](https://knockoutjs.com/documentation/checked-binding.html) started returning `undefined` when unchecked (probably only alongside using the `checkedValue` binding) when [we upgraded Knockout from 3.3.0 to 3.5.1](https://github.com/dnnsoftware/Dnn.Platform/commit/a0d5273d372fc9db3a2b85860bde839884e5b944).
I'm now using `checkedValue: 'true'` to set the value to a string when checked, and then falling back to the string `'false'` if it's not `'true'`.
Thanks @david-poindexter and @valadas for pointing in the right direction.
> Resolve connector checkbox saving

- .github/ISSUE_TEMPLATE/enhancement-request.yml
> Correct YML formatting

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
This PR contains a fix for #5645.
The previous fix for drag/drop of images (#5415 ) broke the upload via the dialog. This fix makes sure both uploads are working as expected.
The upload-request coming from Drag/drop contains a querystring variable "responseType" which I'm using here to determine which response to send.
> Fixes #5645 image upload problem

- .github/ISSUE_TEMPLATE/bug-report.yml
Attempt to use multi-line markdown in `affected-versions` dropdown description.
> Cleaned up format of affected-versions dropdown

- DNN Platform/Tests/DotNetNuke.Tests.Modules.DDRMenu/DotNetNuke.Tests.Modules.DDRMenu.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Modules.DDRMenu/packages.config
#5671 bumped NUnit3TestAdapter references from 4.4.2 to 4.5.0, on `develop`. A reference was added to DotNetNuke.Tests.Modules.DDRMenu in the meantime on `release/10.0.0`. This PR updates that reference on `release/10.0.0`.
> Bump NUnit3TestAdapter for DotNetNuke.Tests.Modules.DDRMenu

- Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
I noticed that we'd [updated Newtonsoft to 13.0.1 in DNN 9.11](https://github.com/dnnsoftware/Dnn.Platform/pull/5168) (and [subsequently to 13.0.2](https://github.com/dnnsoftware/Dnn.Platform/pull/5417) in 9.11.1), but we hadn't updated [the dependency for the DotNetNuke.WebApi NuGet package](https://www.nuget.org/packages/DotNetNuke.WebApi/9.11.2#dependencies-body-tab).
> Match Newtonsoft dependency version for NuGet pkg

- DNN Platform/DotNetNuke.DependencyInjection/Extensions/TypeExtensions.cs
- DNN Platform/DotNetNuke.DependencyInjection/Extensions/TypesResult.cs
- DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
- DNN Platform/DotNetNuke.Web.Mvc/Extensions/StartupExtensions.cs
- DNN Platform/DotNetNuke.Web/Api/Extensions/StartupExtensions.cs
- DNN Platform/DotNetNuke.Web/DependencyInjectionInitialize.cs
- DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
Fixes #5711.
This PR introduces `DotNetNuke.DependencyInjection.Extensions.TypesResult` into `DotNetNuke.DependencyInjection`, using it as the return value for new methods on `TypeExtensions`. This new type has three properties:
- `IReadOnlyCollection<Type> Types`
- `IReadOnlyDictionary<Assembly, ReflectionTypeLoadException> LoadExceptions`
- `IReadOnlyDictionary<Assembly, Exception> OtherExceptions`
As of DNN 9.12.0, `TypeExtensions` contains one non-obsolete method, `static Type[] SafeGetTypes(this Assembly assembly, ILog logger)`. This PR adds four new public methods:
- `TypesResult SafeGetTypes()`
- `TypesResult SafeGetTypes(this IEnumerable<Assembly> assemblies)`
- `void LogOtherExceptions(this TypesResult result, ILog logger)`
- `StringBuilder BuildLoaderExceptionsMessage(this …
> Log all loader errors at once, at warning level

- DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
One may have a settings class that includes a mix of HostSettings, PortalSettings, ModuleSettings and TabModuleSettings.
The previous mechanism had different cache keys for PortalId or TabModuleId, but that brought 2 problems:
1. It is possible to have the same number for a portalId and TabModuleId which would invalidate the wrong cache.
2. When reading settings using the GetSettings method overload that takes moduleInfo, it would get stale settings for all PortalSettings if it was saved also using moduleInfo overload.
I am on the fence about this PR, but it caches now using always portalId.
PROS: It fixed the issue at hand.
CONS: It clears the portal settings cache to be clear, not the whole portal settings cache but only the specified settings class type being requested. This is maybe a …
> Fixed an issue with settings caching using SettingsRepository

- DNN Platform/Connectors/GoogleAnalytics/App_LocalResources/SharedResources.resx
- DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
- DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
- Fixes #5700 
Updated the name to consistently reference (Legacy UA) to help identify it as universal analytics.
This allows 9.12.x to be properly named, with a new ticket to be created to remove the legacy package in 10.x
> Updated the name of the connector for #5700

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.01.SqlDataProvider
This is a partial fix for #5552 
A stored procedure that should have been remove a long time ago, back in 7.2.2, was still in the DNN Data model.  This change removes it.
> Partial solution for #5552 to remove a stored procedure 

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.01.SqlDataProvider
- Fixes #5634 
Given the nature of the default configurations, this change looks for a default configuration still existing; if found, it updates the configuration to be proper.  If the settings do not match the defaults no changes are made.
> Fixed the retry fequency if un-changed for the WebServerMonitor

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/Options.aspx.resx
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx.designer.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Constants/SettingConstants.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Objects/EditorProviderSettings.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Objects/SettingBase.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/Utility.cs
Closes #5761 
This PR implements an extra option in the File Browser settings tab, and uses the setting to determine wether the file browser button is allowed for the user.
Supports Host, Site, Page and Module level setting.
> CKE Adds option to allow browser by permissions

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.01.SqlDataProvider
Fixes #5552 by introducing the final set of needed changes.
Three additional elements that should have been remove by prior upgrade scripts were updated to be removed `ImportDocumentLibraryCategories`, `ImportDocumentLibraryCategoryAssoc`, and `FitsExtendedPropertyPermission`.
Changes were also made to the `ExportImport_AddUpdateUsersBulk` stored procedure to correct a table reference.
There are two changes requested in #5552 that I do not believe we should fix at this time, given the nature of where those came from.
[dbo].[aspnet_AnyDataInTables] Invalid object name 'dbo.aspnet_WebEvent_Events' P
[dbo].[aspnet_Users_DeleteUser] Invalid object name 'dbo.aspnet_UsersInRoles' P
They were not included.
> Updated to remove additional elements

- DNN Platform/Library/Common/Extensions/HttpContextDependencyInjectionExtensions.cs
- DNN Platform/Library/DotNetNuke.Library.csproj
- DNN Platform/Library/Services/DependencyInjection/IScopeAccessor.cs
- DNN Platform/Library/Services/DependencyInjection/ScopeAccessor.cs
> Add a request scope if it wasn't created

- DNN Platform/Library/Security/PortalSecurity.cs
> Add documentation for `PortalSecurity.cs`

- DNN Platform/Library/Services/Localization/LocalizationProvider.cs
This fixes an issue in GetCompiledResources where Host files were not merged into the resulting dictionary.
> Incorporate host resources in compiled resources

- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/serversummary.js
Closes #5771
Some browser change (affecting most Chromium based browsers) made it so that the Server Summary panel would no longer hide after showing. This simplifies the css and improves the javascript to circumvent the issue.
> Fixed an issue where ServerSummary would not hide

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-download-item/dnn-action-download-item.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
Closes #5551
The string is in quotes when there are spaces in the filename and Chrome replaced those with underscores. Filenames with special characters are encoded in the response. This adds a function to convert all those special cases back into a plain string that matches the actual filename in the front end.
> Fixed an issue where filenames of downloads would get mangled

- DNN Platform/Library/Common/Utilities/Config.cs
- DNN Platform/Tests/App.config
- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SecurityController.cs
Resolves #5778 
The following was done in this PR:
* Updated default values for `maxRequestLength` in `development.config` and `release.config`.
* Added section for IIS7 support of `maxAllowedContentLength`
```xml
<system.webServer>
<security>
<requestFiltering>
<requestLimits maxAllowedContentLength="28672000" />
</requestFiltering>
</security>
</system.webServer>
```
* Resolved backend calculation issues resulting in confusing values (by default and when saving)
* Resolved validation issue that was preventing an admin from increasing the Max Upload Size in the UI.  Now it validates against the max supported value of 4GB (minus one byte) for IIS.
Lastly, we decided it best to not add a new field in the UI to control `requestLengthDiskThreshold`.  Since this is not something DNN admins …
> Update `web.config` max upload size defaults, correct backend calcs, and fix validation issue preventing increasing

- .github/ISSUE_TEMPLATE/bug-report.yml
Update bug-report.yml to include v9.13-rc
> Update bug-report.yml to include v9.13-rc

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-copy-url/dnn-action-copy-url.tsx
Closes https://github.com/dnnsoftware/Dnn.Platform/issues/5797
Summary
Add check before copying the url of a file because if the file is in an azure storage account you will get the url of the page and the storage together
> resourceManager bad url using Azure

- .github/ISSUE_TEMPLATE/bug-report.yml
Updates issue template as per having released `v9.13.0`
> Updates issue template as per having released `v9.13.0`

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/FileUploader.ashx.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Constants/SettingConstants.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.dnn
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Module/EditorConfigManager.ascx.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
This PR closes 2 issues:
Closes #5811 
Closes #5812 
for #5811 :
Since I have not been able to find any site with a settingname starting with the host level prefix of DNNCKH#, I changed the host level prefix to be the one that's actually being used: DNNCKP#-1#
For obvious reasons I also changed the occurences of strings DNNCHP# to use SettingConstants.
for #5812 :
I had to move the part that reads the setting value outside of an if-block, and stop it from overriding the host level setting with the site level setting, when set on host level.
> CKE Provider fixes

- DNN Platform/Library/Security/PortalSecurity.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/Security/PortalSecurity/PortalSecurityTest.cs
- DNN Platform/Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
Fixes #5834
Prevents control characters to be inserted in the username field.
Before (http://localhost/Login?username=User%00name):
After (http://localhost/Login?username=User%00name):
Noteworthy, this blocks _all_ control characters, including `\n` or `\r`. Instead of removing `\t` I've added a replacement of a space, but I don't think anyone uses a tab (since this switches the input field in the browser) or new lines (since this isn't a textarea) in their username.
> Prevent control characters in username

- DNN Platform/JavaScript Libraries/DnnPlugins/dnn.jquery.js
Fixes #5818
Fixes #5839
I'm not sure what caused this issue, maybe this is introduced in #5724. 
The problem is that "dnn.jquery.js" was loaded before "ScriptResource.axd" that includes the WebForms classes (with `Sys.WebForms.PageRequestManager`). To resolve this issue the events are now being registered after the DOM has been loaded. In this case the classes are loaded.
> Fixed JavaScript error

- DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
Fixes #5844
Currently the module cache is being retrieved from the portal cache because we're only using the portal ID as key. Now we're using both the portal and module ID to generate a key.
If there is no module, then we use -1 as module ID; which is the null-value.
> Fixed module cache

- DNN Platform/Library/Security/Permissions/FolderPermissionInfo.cs
- DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Core/Security/Permissions/PermissionProviderTests.cs
> Fix exception saving folder permissions

- gitversion.yml
Closes #5871
Also further limits how far back GitVersion looks at commits for versioning purposes which makes it way quicker to run.
> Fixed an issue where develop was publishing wrong version

- .github/dependabot.yml
This PR updates the Dependabot config so that it will open on PR for multiple related dependencies. I've added a handful of NuGet dependencies that appeared to be directly connected, though others can be added in the future.
> Add Dependabot groups for NuGet

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-left-pane/dnn-rm-left-pane.tsx
- azure-pipelines.yml
This could cause confusion and users to accidently perform batch operations (like deletions) by accident on items they were not expecting to be selected.
Closes #5758
> Fixed an issue that kept rm items selected after changing folders

- DNN Platform/Modules/ResourceManager/App_LocalResources/ResourceManager.resx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components.d.ts
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-open-file/dnn-action-open-file.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/context-menus/dnn-rm-file-context-menu/dnn-rm-file-context-menu.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/dnn-rm-actions-bar.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-files-pane/dnn-rm-files-pane.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-cardview/dnn-rm-items-cardview.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-listview/dnn-rm-items-listview.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/LocalizationClient.ts
Closes #5885
Open commands added for files: double click handler, new button in the action bar and a new context menu for the files.
> Resources manager module: added file open commands

- DNN Platform/Skins/Aperture/src/scss/components/_backgrounds.scss
- DNN Platform/Skins/Aperture/src/scss/components/_borders.scss
- DNN Platform/Skins/Aperture/src/scss/components/_buttons.scss
- DNN Platform/Skins/Aperture/src/scss/components/_components.scss
- DNN Platform/Skins/Aperture/src/scss/components/_dnn.scss
- DNN Platform/Skins/Aperture/src/scss/components/_helpers.scss
- DNN Platform/Skins/Aperture/src/scss/components/_text.scss
This PR adjusts component style helpers to follow a unique naming system for the Aperture theme.  These styles will be utilized for content within the `Default`/`Blank` templates.
Example Background Classes
* aperture-bg-primary
* aperture-bg-secondary
* aperture-bg-tertiary
* aperture-bg-info
* _aperture-bg-****_
Example Border Classes
* aperture-border-primary
* aperture-border-secondary
* aperture-border-tertiary
* aperture-border-info
* _aperture-border-****_
Example Button Classes
* aperture-btn-primary
* aperture-btn-secondary
* aperture-btn-tertiary
* aperture-btn-info
* _aperture-btn-****_
Example Text Classes
* aperture-text-primary
* aperture-text-secondary
* aperture-text-tertiary
* aperture-text-info
* _aperture-text-****_
> Update component style helpers to set the stage for template content dev

- DNN Platform/Skins/Aperture/containers/title.ascx
- DNN Platform/Skins/Aperture/default.ascx
- DNN Platform/Skins/Aperture/src/scss/components/_components.scss
- DNN Platform/Skins/Aperture/src/scss/components/_containers.scss
- DNN Platform/Skins/Aperture/src/scss/components/_panes.scss
This PR adds a `title` container to the `Aperture` theme.  It also makes an adjustment to styles for the `ContentPane` to ensure `display: block` instead of `display: flex`.
> DNN 10 Theme: Add title container (mainly for Resource Manager module use in templates)

- DNN Platform/Skins/Aperture/src/scss/_base.scss
- DNN Platform/Skins/Aperture/src/scss/utilities/_dividers.scss
- DNN Platform/Skins/Aperture/src/scss/utilities/_flex.scss
- DNN Platform/Skins/Aperture/src/scss/utilities/_margin.scss
- DNN Platform/Skins/Aperture/src/scss/utilities/_utilities.scss
- DNN Platform/Skins/Aperture/themeReleaseNotes.txt
This PR:
* Updates margins on base styles.
* Adds a utility class for `aperture-divider`.
* Resolves an issue with the `flex` utility class naming convention to bring it more in line with what people coming from Bootstrap would expect.
* Add support to `margin` utility classes for `auto`.
* Update release notes to remove version to avoid an ongoing maintenance nightmare.
> Aperture theme - refine various styles and utility classes

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list-item/dnn-rm-folder-list-item.scss
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list-item/dnn-rm-folder-list-item.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.scss
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
Calculate the menu's position based on the parent element.
> Fix #5912: Resource Manger Context Menu Doesn't reposition after scroll.

- DNN Platform/Skins/Aperture/src/scss/utilities/_borders.scss
This PR adds responsive border-radius utilities.  Examples:
* `aperture-border-radius-1`
* `aperture-border-radius-2`
* `aperture-border-radius-3`
* `aperture-border-radius-4`
* `aperture-border-radius-5`
> Aperture theme - add responsive border radius utility

- DNN Platform/DotNetNuke.Web/Api/Auth/ApiTokens/ApiTokenController.cs
- Dnn.AdminExperience/ClientSide/Security.Web/src/components/apiTokenSettings/index.jsx
- Dnn.AdminExperience/ClientSide/Security.Web/src/components/apiTokens/CreateApiToken/index.jsx
During a Demo of the new DNN 10 API Tokens feature, a few things struck me that needed improvement:
- Fallback for when a resourcefile cannot be found so that API keys will show up with some text
- Do not show or allow users to create things when it's switched off
This PR addresses these issues
> Improve API tokens

- DNN Platform/Website/Portals/_default/Default Website.template
Resolves #5935 
The PNG/JPG file paths were changed previously in the HTML module content, but I missed it in the `files` section of the template.
This PR also resolves dimensions information on one of the two JPGs.
> Default template photos fix

- DNN Platform/Skins/Aperture/partials/_footer.ascx
Resolves #5941 
These values were hard-coded before and not localized.  These should use the default localized values within DNN:
Using this `appSetting` in the `web.config` you can now see the values are localized.  Thanks again @valadas for showing me this!
```xml
<appSettings>
<add key="ShowMissingKeys" value="true" />
</appSettings>
```
> Removed hard-coded text for Terms and Privacy theme objects

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/tsconfig.json
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Roles/scripts/bundles/roles-bundle.js.LICENSE.txt
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/scripts/bundles/users-bundle.js.LICENSE.txt
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/scripts/exportables/Users/UsersCommon.js.LICENSE.txt
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/exports/export-bundle.js.LICENSE.txt
- yarn.lock
Fixed a node typing issue in resource manager
This add `@types/node` to the `dev-dependencies` so we hopefully have better typings and also adds `skipLibCheck` to the typescript configuration so that basically only "our" code is checked.
@bdukes this may be the fix for the current build issue with https://github.com/dnnsoftware/Dnn.Platform/pull/5960 if you want to rebase it after this fix.
> Fixed a node typing issue in resource manager

- DNN Platform/Website/DesktopModules/Admin/Security/EditUser.ascx.cs
The EditUser control used to be used to edit users in a (now defunct) module in DNN pre PersonaBar. Currently it is only used to edit one's details when you click on Edit on your profile page. It no longer needs the ability to edit another user and this should be disabled.
> Completely remove the ability to edit another user from control.

- DNN Platform/JavaScript Libraries/DnnPlugins/DnnPlugins.dnn
Fix #5883: register the dnn.jquery.js in html body
> Fixed an issue re-sending the verification email

- DNN Platform/Library/Services/FileSystem/FolderManager.cs
When navigating folders using a Folder Provider, this code would refresh the whole provider even though we are not making changes.
This PR avoids doing so if EnableFileAutoSync is off, thus improving navigation performance. Users can use the Refresh button to do so manually as needed instead.
This is related to #5969 but does not solve it completely, it improves the navigation of folders experience but there is still the performance issue uploading.
> Fixed a performance issue while navigating folders for providers

- Build/Build.csproj
Updates build to make use of addins optimized to be used with Cake Frosting. Compared to the previously used addins, these addins contain NuGet dependencies instead of shipping them as part of the package. 
In case of Cake.Git this fixes some issues with native LibGit2Sharp DLLs. Beside that it gives you control about the version of dependencies which should be used in your build, which can be useful for example for Cake.Issues.MsBuild and MsBuild.StructuredLogger if a newer binlog version should be supported and Cake.Issues.MsBuild is not available yet.
Also updates addins to latest version. For Cake.Git to a version which support Cake Frosting 4.x, and for Cake Issues addins to the latest versions, which also brings support for binlog format version 20.
> Use Cake Frosting optimized addins

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RolesController.cs
Fix #5994: Sorting (A-Z) members of roles in PersonaBar
> Fix #5994: Sorting (A-Z) members of roles in PersonaBar

- DNN Platform/Library/UI/FavIcon.cs
Fix #6011: Non conforming favicon meta tags
> Fix #6011: Non conforming favicon meta tags

- DNN Platform/DotNetNuke.Web.Mvc/MvcHttpModule.cs
- DNN Platform/HttpModules/MobileRedirect/MobileRedirectModule.cs
> Make MvcServicePath regex matching ignore case.

- DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
Fixes #6059 
Added a new static object that will be used to lock execution across threads.
Both ComputeHash calls were wrapped inside a lock statement so no concurrent executions can be done from different threads. Because of this, the result of the hash function had to be assigned to a new variable that is then used outside of the lock code block.
> Adds lock on calls to ComputeHash to handle concurrency

- DNN Platform/Website/admin/Menus/ModuleActions/ModuleActions.js
- DNN Platform/Website/admin/Modules/App_LocalResources/ModuleSettings.ascx.resx
- DNN Platform/Website/admin/Modules/Modulesettings.ascx
- DNN Platform/Website/admin/Modules/Modulesettings.ascx.cs
- DNN Platform/Website/admin/Modules/Modulesettings.ascx.designer.cs
This PR add module id information to module settings and module label.
Sometimes, module id information is needed to add an as an anchor link, or simply to locate this module.
This code add a new row in module settings to show a label and a text with module id.
Additionally module id was added in module actions script, to show it next to de module label.
I hope this code can be helpful for the platform.
Sorry if im skipping something for the PR, but is my first time pushing code for the solution.
> Add module id information.

- DNN Platform/Website/DotNetNuke.Website.csproj
- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.13.04.SqlDataProvider
This PR Fixes #6074
Actually when you go to recycle bin section, on modules tab, date showed is supposed to be deletion date for each modules, but is not the correct date, because is taking LastModifiedDate for module besides LastModifiedDate for TabModule.
PR takes dates from tabmodules table in vw_view
> Fixed an issue where the wrong deletion date was shown in recycle bin

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Recyclebin/IRecyclebinController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Recyclebin/RecyclebinController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RecyclebinController.cs
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Recyclebin/App_LocalResources/Recyclebin.resx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Recyclebin/Recyclebin.html
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Recyclebin/css/RecycleBin.css
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Recyclebin/scripts/RecycleBin.ViewModel.js
This PR Closes #6075
Recycle bin section, for now is ordering items according ids (TabId, ModuleId, UserId), but when you have a lot of deleted information, is a little bit hard to locate information.
I added an option to sort pages, modules or users according to main fields as name, alias or deletion date. Additionally i have changed Date column name to Deletion Date, to be more specific about what that field means.
> Add sorting functionality to recycle bin items

- build.ps1
- build.sh
Fix
MSBUILD : error MSB1009: Project file does not exist.
Switch: ./build/Build.csproj
> Fix build Project file does not exist.

- .github/dependabot.yml
Dependabot opened #6064 and #6065, which are both updates to Cake Issues packages, and should be grouped together. This PR updates the Cake-Issues Dependabot group to include the Cake.Frosting.Issues packages.
> Update Cake-Issues Dependabot group

- Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
- yarn.lock
This was not used, this PR removes that unused dependency and replaces #5598
> Removed optimize-css-assets-webpack-plugin dependency

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Models/HostModel.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Services/ServerSummaryController.cs
Change the string format of the NETFramework version from ToString(2) to ToString(3) to show the full 3 part .NET Framework version number in the PersonaBar.
Fixes #6143. 
Changed `.ToString(2)` to `.ToString(3)` and we now get the improve output showing the full 3 part .NET Framework version.
> Change the string format of the NETFramework ToString(3) in PersonaBar

- Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/RoleEditor/index.jsx
- Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/RoleRow/index.jsx
- Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/UsersInRole/UserRow/index.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Roles/App_LocalResources/Roles.resx
Fixes Issue #6153
This screenshot shows the result of these changes.
> Update PersonaBar Manage/Roles to show Role ID

- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/Table.jsx
Fixes #6116 - Huge Add (+) Icon in Pages SEO tab
Details in the issue's comments.
```
styles.addItemRow
^^
```
> Fixed an issue that cause wrong size of + icon in SEO module

- Build/ContextExtensions.cs
- Build/Tasks/PackageAspNetMvc.cs
- Build/Tasks/PackageAspNetWebApi.cs
- Build/Tasks/PackageAspNetWebPages.cs
- Build/Tasks/PackageComponentTask.cs
- Build/Tasks/PackageMailKit.cs
- Build/Tasks/PackageMicrosoftGlobbing.cs
- Build/Tasks/PackageNewtonsoft.cs
- Build/Tasks/PackageSharpZipLib.cs
- Build/Tasks/PackageWebFormsMvp.cs
- Build/Tasks/thirdparty.json
- DNN Platform/Components/Newtonsoft/DotNetNuke.Newtonsoft.Json.dnn
Fixes #6173
Updates the version of Newtonsoft.Json to reflect the actual version of the package 13.0.3.
Not sure what could be done for 13.0.2 release.
> Update DotNetNuke.Newtonsoft.Json.dnn to reference version 13.0.3

- Build/Tools/NuGet/DotNetNuke.Web.Mvc.nuspec
- Build/Tools/NuGet/DotNetNuke.Web.nuspec
- Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
The AspNet NuGet packages were bumped in #6146, but the dependency versions weren't bumped in the `nuspec` files
> Fix nuspec dependencies

- gitversion.yml
Some of our builds have failed due to Cake being unable to parse the GitVersion output. Running locally with Diagnostic verbosity, I receive the following error message at the top of the output:
```
Multiple branch configurations match the current branch branchName of 'bdukes/merge-develop-to-release-10.0.0'. Using the first matching configuration, 'develop'. Matching configurations include:'
- develop
- release'
```
I've deleted any branches that I can see with both `develop` and `release` in the name for the short-term.
This PR updates the `regex` field for the branches to include `^` (starts with) and `$` (ends with) tokens, so that the match is exact (i.e. the `develop` rule only matches the `develop` branch, not other branches that have `develop` in the name).
> Make GitVersion config less ambiguous

- DNN Platform/Modules/BulkInstall/Dnn.Modules.BulkInstall.csproj
- DNN Platform/Modules/BulkInstall/packages.config
- DNN Platform/Modules/BulkInstall/web.config
Updated `Microsoft.AspNet.WebApi.Core` dependency to `5.3.0` to resolve build issue.
> Updated Microsoft.AspNet.WebApi.Core dependency to 5.3.0

- DNN Platform/Website/admin/Menus/ModuleActions/ModuleActions.ascx.cs
- Fixes #6241
Given the reported issue in #6239, each time a module setting is updated the cache is cleared.  The current code, was always updating the first load to be false, even if the first load value was already set to false.
This change utilizes the retreived setting value to ensure that we are ONLY updateing the module to flip the quick settings flag to false if it is currently set to true.  This has a substantial impact to performance for modules using Quick Settings.
> Updated Quick Settings Performance

- .github/dependabot.yml
See https://devblogs.microsoft.com/dotnet/using-dependabot-to-manage-dotnet-sdk-updates/
> Add .NET SDK to dependabot

- Build/Tasks/packaging.json
- DNN Platform/Components/Microsoft.AspNetWebApi/Microsoft.AspNetWebApi.dnn
This may fix #6222 but I ran out of time to test, a clean install did work fine and that's all I had time to test for now.
I think there are a couple other dlls in the issue we could handle here or elsewhere and we need to test upgrade scenarios from 9.13.4,5,6 to be sure.
> Added sub-dependencies of AspNetWebApi to package

- DNN Platform/DotNetNuke.Instrumentation/DnnLog.cs
- DNN Platform/DotNetNuke.Instrumentation/DnnLogger.cs
- DNN Platform/DotNetNuke.Instrumentation/LoggerSourceImpl.cs
- DNN Platform/Library/Entities/Tabs/TabWorkflowTracker.cs
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Components/BusinessController.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Controllers/PersonaBarController.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Permissions/MenuPermissionController.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Services/MenuExtensionsController.cs
If we wish to move away from Log4net in the future we must begin to eliminate any exposure of its classes through our API.
The DnnLogger class inherits from and exposes log4net classes. We have an alternative in LoggerSource. Deprecating this now means we can remove log4net if needed by DNN 11.
> Deprecate DnnLogger

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Themes/ThemesController.cs
Fixes an issue where sites on non-standard paths would not display their thumbnail properly.
Fixes #6263
> Fixed a thumbnail issue for sites not in standard path

- .github/workflows/browserslist-update-db.yml
- package.json
- yarn.lock
This PR adds a GitHub Action using [browserslist-update-action](https://github.com/c2corg/browserslist-update-action), which opens a PR to bump the database used by [browserslist](https://browsersl.ist/) on a regular basis.
This PR also:
- updates `caniuse-lite` (the package with the database used by browserslist)
- bumps Yarn from 4.5.0 to 4.5.3
- runs `yarn dedupe` to reduce duplicate versions of dependencies
> Add GitHub Action to keep caniuse-lite updated

- DNN Platform/Modules/BulkInstall/BulkInstall.Web/package.json
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/api-users/api-users.scss
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/api-users/api-users.tsx
- yarn.lock
This PR upgrades `dnn-elements` to the latest version and swaps out all relevant native HTML components within the `API Users` tab.
This is part of the ongoing work for #5920.
> Bulk Install: Swapped out native components for dnn-elements in the API Users UI

- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Containers/PersonaBarContainer.cs
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/theme.css
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/bootstrap.js
This replaces hardcoded values in the PersonaBar main styles to use the dnn css-variables which allows matching branding.
- The previous way to provide a PersonaBar theme still works, so if implementors want their own style to stay unchanged no matter what portal the admin UI is accessed from, that can still work by using actual values instead of the css variables.
- This does not yet include the common components and the modules themselves, I'll do that in other PRs.
Out of box style (very similar to original)
With a different color theme (to match the site under it):
> Imports css-variables into Persona Bar main styles

- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
This PR repairs the fact that new DNN 10 installations do not have the necessary entry in the web.config to enable API tokens.
> Update release and development configs to reflect API Tokens auth addition

- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components.d.ts
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/dnn-bulk-install.tsx
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/readme.md
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/api-users/readme.md
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/event-log/event-log.model.ts
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/event-log/event-log.scss
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/event-log/event-log.tsx
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/event-log/readme.md
- DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/ip-safelist/readme.md
This PR adds the initial UI for the `Event Logs` tab of Bulk Install.  It is part of ongoing work for #5920.
> Bulk Install: Implemented initial UI for Event Logs

- DNN Platform/Library/Entities/Portals/PortalStyles.cs
This css variable was missing it's dnn- prefix that all others have.
Closes #6274
> Fixed a typo (missing prefix) for variation-opacity

- DNN Platform/Dnn.ClientSide/Dnn.ClientSide.esproj
Since the addition of the Dnn.ClientSide project in #6316, when building the project, `package-lock.json` files are created. This is because the JSPS/esproj build system runs `npm install` automatically during build. This PR disables that and runs `yarn install` instead.
I also ran into the following build error:
>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\NuGet\17.0\Microsoft.NuGet.targets(198,5): Your project does not reference ".NETCoreApp,Version=v6.0" framework. Add a reference to ".NETCoreApp,Version=v6.0" in the "TargetFrameworks" property of your project file and then re-run NuGet restore. [D:\code\Dnn.Platform\DNN Platform\Dnn.ClientSide\Dnn.ClientSide.esproj]
I'm not sure what the underlying issue is, but it does appear to be coming from a NuGet …
> Improvements for Dnn.ClientSide project

- DNN Platform/Dnn.ClientSide/src/styles/install/install.scss
I did something in our default `ul` styles that messed up the tabs in install/upgrade wizards.
> Fixed a tab position issue in install/upgrade wizard

- Build/Build.csproj
- DNN Platform/DotNetNuke.Maintenance/Constants.cs
- DNN Platform/DotNetNuke.Maintenance/DotNetNuke.Maintenance.csproj
- DNN Platform/DotNetNuke.Maintenance/Telerik/ITelerikUtils.cs
- DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/TelerikUninstaller.cs
- DNN Platform/DotNetNuke.Maintenance/Telerik/TelerikUtils.cs
- DNN Platform/DotNetNuke.ModulePipeline/DotNetNuke.ModulePipeline.csproj
- DNN Platform/Modules/TelerikRemoval/Dnn.Modules.TelerikRemoval.csproj
- DNN Platform/Modules/TelerikRemoval/TelerikRemoval.dnn
- DNN Platform/Modules/TelerikRemoval/UpgradeController.cs
- DNN Platform/Skins/Aperture/Dnn.Skins.Aperture.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Modules.DDRMenu/DotNetNuke.Tests.Modules.DDRMenu.csproj
- DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.resx
- DNN Platform/Website/Install/Install.aspx.cs
- DNN Platform/Website/Install/UpgradeWizard.aspx.cs
This PR updates the upgrade wizard and auto-upgrade pages to trigger an uninstall of Telerik, if installed, unless the version that is present is newer than the known-vulnerable version previously distributed.
This PR has not been tested yet b/c of build issues related to #6326.
> Force Telerik uninstall

- DNN Platform/Skins/Aperture/build.ts
The destination path for Aperture could not exist on a clean clone (or in this case in CI). This PR ensures the directory exists before the copy.
> Fixed an issue with distribution path of Aperture

- DNN Platform/Dnn.ClientSide/src/styles/default-css/10.0.0/base/_type.scss
- DNN Platform/Library/Entities/Portals/PortalStyles.cs
default.css was too opiniated on the color of heading, we should just use the ambiant foreground color at that level and leave it to theme developers to override if they want and how they want.
We did not have the DNN dark brown in the color system, this is now our foreground color which makes foreground text the DNN brown color and looks almost black on smaller text and keeps a soft not 100% contrast that feels nice to me.
> Changed some default styles

- DNN Platform/Dnn.ClientSide/src/styles/default-css/10.0.0/modules/modules.scss
default.css and Aperture were having a bit of a fight for a font weight that made the theme not look as designed initially. default.css should not try to be too opiniated, so I removed the font weight from it to let the theme win that fight.
> Fixed a font weight issue

- DNN Platform/Dnn.ClientSide/src/styles/default-css/10.0.0/ui/dnn-jquery/_dnn-progressbar.scss
- DNN Platform/Dnn.ClientSide/src/styles/default-css/10.0.0/ui/jquery-ui/_spinner.scss
- DNN Platform/Modules/CoreMessaging/module.css
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.18.0/plugins/balloonpanel/skins/moono/balloonpanel.css
- DNN Platform/Website/DesktopModules/Admin/SearchResults/module.css
- DNN Platform/Website/Portals/_default/Skins/_default/WebControlSkin/Default/ComboBox.Default.css
- DNN Platform/Website/Portals/_default/Skins/_default/WebControlSkin/Default/DatePicker.Default.css
- DNN Platform/Website/Portals/_default/Skins/_default/WebControlSkin/Default/Grid.Default.css
- DNN Platform/Website/Portals/_default/Skins/_default/WebControlSkin/Default/GridView.Default.css
- DNN Platform/Website/Resources/Shared/components/DropDownList/dnn.DropDownList.css
- DNN Platform/Website/Resources/Shared/stylesheets/dnndefault/7.0.0/default.css
- DNN Platform/Website/Resources/Shared/stylesheets/dnndefault/8.0.0/default.css
Many of the CSS gradients defined in the platform used the outdated syntax which specified the direction the gradient comes _from_, whereas the final approved syntax uses the keyword `to` along with the direction that the gradient _goes to_. This PR adjusts those usages.
> Use valid syntax for CSS gradients

- Build/Program.cs
- Build/Tasks/SetVersion.cs
- gitversion.yml
This PR bumps GitVersion from 5.x to 6.x. This involves adjusting the configuration and removing usage of legacy variables.
With the most straightforward conversion from the 5.x config to 6.x, the output from the tool is a bit different. As an example, here's output for this PR branch:
<details>
<summary>5.x output</summary>
<pre><code>
{
"Major": 10,
"Minor": 0,
"Patch": 0,
"PreReleaseTag": "gitversion-6.993",
"PreReleaseTagWithDash": "-gitversion-6.993",
"PreReleaseLabel": "gitversion-6",
"PreReleaseLabelWithDash": "-gitversion-6",
"PreReleaseNumber": 993,
"WeightedPreReleaseNumber": 993,
"BuildMetaData": null,
"BuildMetaDataPadded": "",
"FullBuildMetaData": "Branch.gitversion-6.Sha.2719998965ea595ecd1c9a6bda0fb6d57ce41a0d",
"MajorMinorPatch": "10.0.0",
"SemVer": …
> Bump GitVersion from 5.12.0 to 6.1.0

- DNN Platform/Dnn.AuthServices.Jwt/Library.build
I believe the @dnnsoftware/approvers had decided at some point that the JWT auth package should be included by default starting in DNN 10.
> Include JWT Auth by default

- Dnn.AdminExperience/ClientSide/Styles.Web/package.json
- Dnn.AdminExperience/ClientSide/Styles.Web/src/components/dnn-styles-module/dnn-styles-module.scss
- Dnn.AdminExperience/ClientSide/Styles.Web/src/components/dnn-styles-module/dnn-styles-module.tsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Styles/css/Styles.css
- yarn.lock
Closes #6352
The persona bar loads up a css file by convention even though we don't need one for this module.
While I had my hands in there I notice another issues, the dnn-input controls have a floating label that assumes the field has the same background as the field. This was not the case, there was also an issue with dnn-elements with passing down colors to the child elements, so this both updates to the latest dnn-elements and adds a style to make the fields use the same background color as the surrounding area.
Here is a before/after
> Added missing Styles.css file

- DNN Platform/Website/js/Debug/dnn.cookieconsent.js
- DNN Platform/Website/js/dnn.cookieconsent.js
Our new default theme does not have dependencies on jQuery and the cookie consent feature just assumed jQuery was loaded which is not the case. This makes it no longer depend on jQuery.
Closes #6353
> Made dnn.cookieconsent not require jQuery

- DNN Platform/DotNetNuke.Web.Client/ClientResourceSettings.cs
- DNN Platform/DotNetNuke.Web.Client/DotNetNuke.Web.Client.csproj
- DNN Platform/DotNetNuke.Web.Client/app.config
- DNN Platform/DotNetNuke.Web.Client/packages.config
DotNetNuke.Web.Client calls DNN methods via reflection. However, the methods it calls were removed in DNN 10, so those calls are failing. This means that configuring client resources by portal does not work in DNN 10 anymore b/c it can't find which portal the request is for.
I've fixed the worst offending method, but I think there are more.
> Fix reflection calls in Client Resources

- DNN Platform/Dnn.ClientSide/src/styles/default-css/10.0.0/ui/jquery-ui/jquery-ui.scss
The dialog css was not included in the sass compilation. Closes #6374
> Fixed missing css for dialogs

- DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
- DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
- DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
- DNN Platform/Dnn.AuthServices.Jwt/Library.build
- DNN Platform/Dnn.AuthServices.Jwt/packages.config
This PR builds on top of #6350, which upgrades the System.IdentityModel.Tokens.Jwt NuGet package. That package is now [marked as "legacy"](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/e5272528a608b903e321223dd05f132d1d31a5dd/src/System.IdentityModel.Tokens.Jwt/System.IdentityModel.Tokens.Jwt.csproj#L7), so this follow-on PR replaces its usage with the recommended Microsoft.IdentityModel.JsonWebTokens package (which was already referenced). This was mostly straightforward, other than the header validation check that needed to be moved around a bit.
> Replace legacy System.IdentityModel.Tokens.Jwt

- DNN Platform/Library/Services/Upgrade/Upgrade.cs
- DNN Platform/Website/Portals/_default/Blank Website.template
- DNN Platform/Website/Portals/_default/Default Website.template
In #6038 a rollup script was put in place to revamp our clean installation logic, get rid of some upgrade logic and potentially speed up installs, etc.
In RC1 issue #6364 was reported. I spent quite a lot of time trying to figure it out. Had to do a `git bisect` and it identified the commit of the rollup script as being the first commit to cause that issue. After a lot of head scratching I realized that the code in upgrade.cs was the one creating the virtual host page that should hold the module that allows editing user profiles from the Persona Bar. This solved the issue for HOST users but not for admins. For admins, this lives in the portal templates, it was cleaned up from modules we don't want, but this one needed to be brought back as the Persona Bar needs it for admins.
As I was in …
> Refactored upgrade code after rollup of sql scripts

- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/Grid.jsx
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/GridCaption.jsx
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/GridHeader.jsx
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/GridRow.jsx
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/index.jsx
- Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/style.less
- Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PermissionGrid/PermissionGrid.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
- Turns the label to have more room
- Should there be more permissions than the width allows, the table gets a slider for the overflow instead of cutting into the text
- Adds localized label names and descriptions (tooltips) to better explain what each permission does.
> Improved permissions grid (React one)

- DNN Platform/Skins/Aperture/default.ascx
- DNN Platform/Skins/Aperture/src/scss/sections/_sections.scss
This PR makes sure the content has a minimum height of 20vh even when there are no module son the page.
This is only the case when the PersonaBar is visible.
I did wonder if we should add a _dnn-edit.scss file for this?
What do you think @valadas / @david-poindexter ?
fixes #6402
> Min height of Page Content #6402

- Dnn.AdminExperience/ClientSide/Security.Web/src/components/apiTokenSettings/index.jsx
- Dnn.AdminExperience/ClientSide/Security.Web/src/components/apiTokenSettings/style.less
Due to an error the styling of this personabar page was absent. This PR fixes that.
> Fix styling issue with API Tokens Settings page on the PersonaBar

- DNN Platform/Skins/Aperture/menus/mobile/RazorMenu.cshtml
The page description should not show in the mobile menu.  This PR removes it.  
Resolves #6425
> Aperture: Resolve page description issue in mobile menu

- DNN Platform/Library/Common/Utilities/DataCache.cs
`CoreCacheType` is never used within DNN. Ideally, we could mark the type as deprecated in 9.x so it can be removed in 11.0.0.
> Mark unused CoreCacheType enum as obsolete

- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-edit-folder/dnn-rm-edit-folder.tsx
- yarn.lock
Solve permission problems as reported in
Closes #6391
Closes #6318
this.lastPermissions?.rolePermissions?.**find**(p => p.roleId === rolePermission.roleId).permissions
the **find** returns an undefined for newly added roles (and users) to the permission grid, therefore the .permissions crashes and subsequent failures follow.
> Fixed an issue managing folder permissions

- DNN Platform/Website/Install/Config/10.00.00.config
Fixes #6448
Prevents Roslyn from running to avoid potential compilation errors when a newer version of Roslyn is installed in the next steps with `Microsoft.CodeDom.Providers.DotNetCompilerPlatform_04.01.00_Install.zip`.
> Prevents Roslyn Compilation Errors During DNN v10 Upgrade

- .github/FUNDING.yml
This adds the top 4 contributors (GitHub has a limit of 4 for `GitHub Sponsors` from the past 24 months that have setup for GitHub Sponsorships.
This should show up in a sponsor list on the right bar of the repo.
> Create FUNDING.yml with top contributors

- DNN Platform/Components/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dnn
- DNN Platform/Website/Install/Config/10.00.00.config
Fixes #6448
This fix is now self-contained in the most logical place—`Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dnn`—and no longer modifies `10.00.00.config`.  
This fix effectively uninstalls Roslyn by:  
- Making necessary changes in `web.config`.  
- Unregistering the assembly.  
- Removing all files from `bin\roslyn`.  
I verified the fix across multiple test scenarios, all of which executed successfully without issues:
1. Clean install of `DNN_Platform_10.0.0-rc.15_Install.zip`.  
2. Clean install of DNN `9.13.8`, followed by an upgrade using `DNN_Platform_10.0.0-rc.15_Upgrade.zip`.  
3. Clean install of DNN `9.13.8`, then installation of `Microsoft.CodeDom.Providers.DotNetCompilerPlatform (v3.6)`, followed by an upgrade using `DNN_Platform_10.0.0-rc.15_Upgrade.zip`.  
4. …
> Fix #6448 enhance Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dnn to avoid potential compilation errors

- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Styles/App_LocalResources/Styles.resx
Replace "varialbes" with "variables"
Also remove `\n` from confirmation text that was rendering literally. Since this is just HTML content, adding a line break does not render anything (without adding a `white-space` style).
> Fix typo in styles text

- DNN Platform/Library/Entities/Tabs/TabController.cs
This PR fixes two bugs with deleting tabs. The first is described in #6438. The second comes when calling `DeleteTab` on a tab that has already been deleted (perhaps related to a workaround for the first issue 😉).
Fixes #6438
> Fix two tab deletion issues

- DNN Platform/Modules/HTML/Providers/DataProviders/SqlDataProvider/10.00.00.SqlDataProvider
- Fixes #6480
This fix involves two small changes to the processing within the file to meet consistency standards and pass SQL validations.
* Removal of the `{objectQualifier]` from the object name check as that process results in invalid SQL syntax
* Re-ordering of the table removals given the issues that arise with those removals
> Fix HTML Module Install Script #6480

- DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.13.09.SqlDataProvider
Fixes #6434 
Add cascade delete to PortalPermissions table
> Add cascade delete to PortalPermissions table

- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
I did a `git bisect` which pointed me to the commits in #6038 to rollup the sql scripts for v10. This made no sense to me since it's not really related to web.config and @uzmannazari pointed out in #6503 that a similar issue was caused by the LocalizationModule missing from the web.config. Also I could not reproduce the issue on upgrades. Then I thought since we have that v10 rollup, it uses the 10.00.00.config for the web.config xml merge scripts and up. Investigating the commit history of that file and comparing with 9.8.0 one I found that in #4251, a bugfix was done to ensure that the LocalizationModule is right after the UrlRewriteModule.
This means that upon upgrades it would be in the right place but with clean installs, that would never run and it was also missing from the base …
> Fixed an issue with wrong localization detection

- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
This was only done in 10.00.00.config but xml-merge scripts only run upon upgrades of that version, hence this would be missing from clean installs and needs to exist in the base web.config for a clean install.
I have also verified the rest of 10.00.00.config and everything else appears to be pre-exising in the base web.config files.
Completes an extra detail from https://github.com/dnnsoftware/Dnn.Platform/issues/6503
> Fixed an issue where ServiceRequestScopeModule was missing from web.config

- DNN Platform/Modules/ResourceManager/App_LocalResources/ResourceManager.resx
- DNN Platform/Modules/ResourceManager/Components/IItemsManager.cs
- DNN Platform/Modules/ResourceManager/Components/ItemsManager.cs
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/dnn-rm-actions-bar.scss
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/dnn-rm-actions-bar.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-files-pane/dnn-rm-files-pane.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-left-pane/dnn-rm-left-pane.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-top-bar/dnn-rm-top-bar.tsx
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/enums/SortOrder.ts
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
- DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/store/store.ts
- DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
Implements #5430 on 9.13.x
While allowing the user to sort files by name, date and size, the current implementation of the Resource Manager core module does not allow choosing the sort order (ascending/descending). This implementation adds this functionality.
**Current:** The logic for sorting files in ascending/descending order is already implemented in `AssetManager.Instance.GetFolderContent(...)`, but the chain of calls from the endpoint `GetFolderContent` to the class `ItemsManager` has no option to change the default *ascending* order.
**Change:** Logic for forwarding and taking into consideration the optional HTTP GET argument "sortingOrder" is implemented. *Ascending* order is used by default (i.e., when argument is not provided).
**Current:** There is no toggle button for …
> Feature: Adds ascending/descending sort toggle to Resource Manager

- Build/Tools/NuGet/DotNetNuke.DependencyInjection.nuspec
- DNN Platform/Connectors/Azure/Dnn.AzureConnector.csproj
- DNN Platform/Connectors/GoogleAnalytics/Dnn.GoogleAnalyticsConnector.csproj
- DNN Platform/Connectors/GoogleAnalytics4/Dnn.GoogleAnalytics4Connector.csproj
- DNN Platform/Connectors/GoogleTagManager/Dnn.GoogleTagManagerConnector.csproj
- DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
- DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
- DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
- DNN Platform/Modules/Groups/DotNetNuke.Modules.Groups.csproj
- DNN Platform/Modules/Journal/DotNetNuke.Modules.Journal.csproj
- DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
- DNN Platform/Modules/ResourceManager/Dnn.Modules.ResourceManager.csproj
- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
- DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
- DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
- DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
- DNN Platform/Website/DotNetNuke.Website.csproj
- Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.csproj
- Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Dnn.PersonaBar.Library.csproj
- Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.csproj
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
- Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
Fixes #6541
I also noticed duplicate `<HintPath>` elements for Newtonsoft.Json and `<Reference>` elements for Moq (presumably from bad merges) that didn't appear to be breaking anything but were still wrong, so I also fixed those.
> Fix nuget references

- DNN Platform/Admin Modules/Dnn.Modules.Console/Settings.ascx.cs
- DNN Platform/Library/Common/Utilities/HtmlUtils.cs
- DNN Platform/Library/Entities/Modules/PortalModuleBase.cs
- DNN Platform/Library/Framework/PageBase.cs
- DNN Platform/Library/Framework/UserControlBase.cs
- DNN Platform/Website/DesktopModules/Admin/Security/DataConsent.ascx
- DNN Platform/Website/DesktopModules/Admin/Security/DataConsent.ascx.cs
- DNN Platform/Website/DesktopModules/Admin/Security/Membership.ascx.cs
- DNN Platform/Website/DesktopModules/Admin/Security/ProfileDefinitions.ascx
- DNN Platform/Website/DesktopModules/Admin/Security/ProfileDefinitions.ascx.cs
- DNN Platform/Website/DesktopModules/Admin/Security/Register.ascx.cs
- DNN Platform/Website/DesktopModules/Admin/Security/User.ascx.cs
- DNN Platform/Website/DesktopModules/AuthenticationServices/DNN/Login.ascx
- DNN Platform/Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
- DNN Platform/Website/admin/Security/PasswordReset.ascx.cs
`PortalModuleBase` exposes two helpers, `LocalizeString` and `LocalizeSafeJsString`. I propose that these are deprecated and replaced with three helpers, `LocalizeText`, `LocalizeHtml`, and `LocalizeJsString`, which use the `IHtmlString` abstraction to provide proper encoding. This will allow markup to more easily transition to using the safer `<%: something %>` code placeholders (colloquially, bee-stings) instead of `<%= something %>`.
Fixes #6571 
This PR also adds the following static helper methods:
- `IHtmlString HtmlUtils.JavaScriptStringEncode(string)`
- `IHtmlString PageBase.JavaScriptStringEncode(string)`
- `IHtmlString UserControlBase.JavaScriptStringEncode(string)`
- `IHtmlString HtmlUtils.JavaScriptStringEncode(string, bool)`
- `IHtmlString …
> Adjust Localize helpers

- DNN Platform/DotNetNuke.Web/UI/WebControls/Internal/DnnDatePicker.cs
The internal `DnnDatePicker` and `DnnDateTimePicker` controls are not working since 9.13.9 (cf. 34c72c988f47ab08128f4084c820703451b835a0) because of quotes being double-encoded (because the control is JSON encoding strings which are not really strings, but intended to be arbitrary JS expressions, in this case `new Date('…')`).
This PR adjusts that encoding so that it works as it did previously.
> Fix double-encoding in DnnDatePicker internal control

- package.json
This PR bumps Yarn from 4.9.1 to [4.9.2](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.9.2).
> Bump Yarn from 4.9.1 to 4.9.2

- Build/Program.cs
This PR bumps the version of the following NuGet tools used by the Cake build:
- Microsoft.TestPlatform from 17.12.0 to 17.14.1
> Bump Microsoft.TestPlatform from 17.12.0 to 17.14.1

- DNN Platform/DotNetNuke.Web.Client/ClientResourceManager.cs
This PR deprecates `ClientResourceManager.RegisterIEStylesheet` since Internet Explorer is no longer supported.
> Deprecate `ClientResourceManager.RegisterIEStylesheet`

- Dnn.AdminExperience/ClientSide/AdminLogs.Web/src/components/AdminLog/index.jsx
- Dnn.AdminExperience/ClientSide/AdminLogs.Web/src/reducerHelpers/index.js
- Dnn.AdminExperience/ClientSide/Security.Web/src/components/apiTokens/index.jsx
- Dnn.AdminExperience/ClientSide/SiteImportExport.Web/src/components/Dashboard/index.jsx
- Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.CssEditor/scripts/CssEditor.js
Closes #6601
The global personaBarSettings javascript objet is merged from the backend with some portal settings, I guess in some place, stuff was changed from PortalSettings to IPortalSettings which means we now have `PortalId` instead of `PortalID`.
Luckily, it appears that value was only used in a few places, so this PR changes the casing in those places fixing the CSS module and some more areas affected by the same issue.
> Fixed an issue where CustomCss module would not load

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/Utility.cs
Closes #5696
This pull request addresses the issue of file uploads failing when filenames contain Unicode characters, such as Farsi or Arabic.
The previous implementation used `Utility.ConvertUnicodeChars`, which incorrectly removed these characters from the filename, leading to upload failures.
This change replaces that flawed logic with a safer and more robust method:
* It gets the original filename, including all Unicode characters.
* It then sanitizes the filename by removing or replacing invalid characters using `Path.GetInvalidFileNameChars()` from the .NET framework.
This approach ensures that filenames with non-English characters are properly preserved while maintaining security against potential path traversal attacks. The fix is a direct and efficient solution that doesn't …
> Fix: #5696, Do not convert unicode chars in filenames

- DNN Platform/Website/development.config
- DNN Platform/Website/release.config
This PR updates the default hash algorithm to SHA256. It does _not_ add any logic for migrating users from SHA1 hashes, it only affects new installations.
I have tested that password history works as expected.
Fixes #6614
> Update password hash algorithm to SHA256

- DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.dnn
As a defense-in-depth strategy, we realized that only in very exceptional circumstances does there need to be anonymous access to upload files via the CKEditor. This PR adds a `web.config` level denial of access to the CKEditor upload endpoints for anonymous users.
Thanks @r90727 for calling this out and the initial implementation.
> Deny anonymous users access to CKE endpoints
